gText_ApprenticeChallenge0::
    .string "Um, aku adalah murid ke-{STR_VAR_2} dari {STR_VAR_1}.\n"
    .string "Sengsara... Ketegangan ini membuatku kewalahan…$"

gText_ApprenticeChallenge1::
    .string "Aku adalah murid ke-{STR_VAR_2} dari {STR_VAR_1}!\n"
    .string "Kami datang!$"

gText_ApprenticeChallenge2::
    .string "Aku adalah murid ke-{STR_VAR_2} dari {STR_VAR_1}!\n"
    .string "Terima tantanganku!$"

gText_ApprenticeChallenge3::
    .string "Um… Aku adalah murid ke-{STR_VAR_2} dari {STR_VAR_1}…\n"
    .string "Apa kamu pikir seseorang sepertiku bisa menang?$"

gText_ApprenticeChallenge4::
    .string "Aku adalah murid ke-{STR_VAR_2} dari {STR_VAR_1}!\n"
    .string "Aku akan membiarkanmu menantangku!$"

gText_ApprenticeChallenge5::
    .string "Aku sangat sibuk, tapi aku juga\n"
    .string "murid ke-{STR_VAR_2} dari {STR_VAR_1}.$"

gText_ApprenticeChallenge6::
    .string "Aku adalah murid ke-{STR_VAR_2} dari {STR_VAR_1}.\n"
    .string "Senang bertemu denganmu!$"

gText_ApprenticeChallenge7::
    .string "Aku adalah murid ke-{STR_VAR_2} dari {STR_VAR_1}.\n"
    .string "Bolehkah aku mulai?$"

gText_ApprenticeChallenge8::
    .string "Aduh! Aku adalah murid ke-{STR_VAR_2} dari {STR_VAR_1}!\n"
    .string "Aku akan melakukan yang terbaik!$"

gText_ApprenticeChallenge9::
    .string "Yeehaw! Aku adalah murid ke-{STR_VAR_2} dari {STR_VAR_1}!\n"
    .string "Ayo bertarung!$"

gText_ApprenticeChallenge10::
    .string "Aku adalah murid ke-1.000 dari {STR_VAR_1}!\n"
    .string "Sebenarnya, aku yang ke-{STR_VAR_2}! Ini dia!$"

gText_ApprenticeChallenge11::
    .string "Ya, aku adalah murid ke-{STR_VAR_2} dari {STR_VAR_1}!\n"
    .string "Ayo kita mulai!$"

gText_ApprenticeChallenge12::
    .string "Yippee-yahoo! Aku adalah apa yang kamu sebut\n"
    .string "murid ke-{STR_VAR_2} dari {STR_VAR_1}!$"

gText_ApprenticeChallenge13::
    .string "Uhuk! Aku adalah murid ke-{STR_VAR_2} dari {STR_VAR_1}.\n"
    .string "Senang bertemu denganmu! Uhuk!$"

gText_ApprenticeChallenge14::
    .string "Ini menegangkan…\n"
    .string "Aku adalah murid ke-{STR_VAR_2} dari {STR_VAR_1}.$"

gText_ApprenticeChallenge15::
    .string "Aku adalah murid ke-{STR_VAR_2} dari {STR_VAR_1},\n"
    .string "dan itu bukan bohong.$"

gText_ApprenticePleaseTeach0::
    .string "Apakah kamu… {PLAYER}?\n"
    .string "Oh! Tersedu…\p"
    .string "Oh! M-maaf…\n"
    .string "Aku sangat gugup, tak bisa menahan tangis…\p"
    .string "Aku {STR_VAR_1}, dan aku sangat mengagumimu,\n"
    .string "{PLAYER}.\p"
    .string "Aku… Aku bermimpi suatu hari nanti bisa bertemu\n"
    .string "denganmu dan bertanya tentang POKéMON.\p"
    .string "Kumohon, kumohon, {PLAYER}!\n"
    .string "Ajari aku tentang POKéMON!$"

gText_ApprenticeRejectTeaching0::
    .string "Oh… T-tapi…\n"
    .string "Tersedu… Waaaaaaah!\p"
    .string "Kumohon!\n"
    .string "Aku mohon padamu, kumohon!$"

gText_ApprenticeWhichLevelMode0::
    .string "Oh, benarkah? Kamu mau?\n"
    .string "Luar biasa! Hebat! Awoooh!\p"
    .string "Oh… Maafkan aku…\n"
    .string "Aku sangat senang, sampai menangis…\p"
    .string "Um… Kalau begitu tolong beritahu aku!\n"
    .string "Ini tentang BATTLE TOWER.\p"
    .string "Mana yang lebih baik untukku: Level 50\n"
    .string "atau Open Level?$"

gText_ApprenticeLevelModeThanks0::
    .string "{STR_VAR_1}?\n"
    .string "Waaaaah!\p"
    .string "Oh! Aku minta maaf!\n"
    .string "Kamu membuatku senang dengan memilih\l"
    .string "level untukku, dan itu membuatku menangis…\p"
    .string "Tersedu…\n"
    .string "Terima kasih banyak!\l"
    .string "Tolong ajak Aku bicara lagi!$"

gText_ApprenticePleaseTeach1::
    .string "Wow! Kamu {PLAYER}, kan?\n"
    .string "Kamu sangat kuat, kan?\p"
    .string "Aku {STR_VAR_1}!\n"
    .string "Aku baru saja menjadi TRAINER!\p"
    .string "Kumohon, {PLAYER}!\n"
    .string "Bisakah kamu menjadi guruku dan ceritakan\l"
    .string "banyak hal tentang menjadi TRAINER?$"

gText_ApprenticeRejectTeaching1::
    .string "Ah, kenapa?\n"
    .string "Oh, kumohon? Kumohon sekali?\l"
    .string "Tolong jadilah guruku, kumohon!$"

gText_ApprenticeWhichLevelMode1::
    .string "Yay! Keren!\p"
    .string "Hal pertama yang ingin aku tanyakan\n"
    .string "adalah tentang BATTLE TOWER!\p"
    .string "Ruangan Level 50 dan Open Level…\n"
    .string "Mana yang paling cocok untukku?$"

gText_ApprenticeLevelModeThanks1::
    .string "{STR_VAR_1}, ya? Benar juga!\n"
    .string "Aku akan berusaha semampuku di sana!\p"
    .string "Kalau kita bertemu lagi di sini, tolong ajari\n"
    .string "aku hal lain ya, guru!$"

gText_ApprenticePleaseTeach2::
    .string "Um… Apakah kamu {PLAYER}?\n"
    .string "Namaku {STR_VAR_1}.\p"
    .string "Aku ingin menjadi POKéMON TRAINER,\n"
    .string "tapi aku tidak tahu harus berbuat apa…\p"
    .string "Jadi aku pikir mungkin aku bisa meminta\n"
    .string "nasihat darimu karena kamu sangat terkenal.\p"
    .string "{PLAYER}, bisakah kamu memberiku nasihat?$"

gText_ApprenticeRejectTeaching2::
    .string "Oh, tapi…\p"
    .string "Aku sungguh ingin menjadi POKéMON\n"
    .string "TRAINER!\p"
    .string "Kumohon, bisakah kamu menjawab pertanyaan-pertanyaanku?$"

gText_ApprenticeWhichLevelMode2::
    .string "Terima kasih!\n"
    .string "Ini pertanyaan pertamaku!\p"
    .string "BATTLE TOWER punya dua level,\n"
    .string "Level 50 dan Open Level, kan?\p"
    .string "Menurutmu, level mana yang lebih\n"
    .string "cocok untukku?$"

gText_ApprenticeLevelModeThanks2::
    .string "Oh, tantangan {STR_VAR_1}?\n"
    .string "Mengerti!\p"
    .string "Kalau aku punya pertanyaan lain, aku akan kembali\n"
    .string "ke sini untuk meminta nasihatmu!$"

gText_ApprenticePleaseTeach3::
    .string "Oh? Hah? Kamu…\n"
    .string "Tidak, itu tidak mungkin.\p"
    .string "Tidak mungkin seseorang sepertiku\n"
    .string "bisa bertemu {PLAYER}.\p"
    .string "…Kamu sungguh {PLAYER}?\n"
    .string "Aku tidak percaya aku berbicara denganmu!\p"
    .string "Ketika hal baik seperti ini terjadi,\n"
    .string "hanya hal buruk yang akan menimpaku\l"
    .string "sekarang, aku tahu itu…\p"
    .string "…Maafkan aku…\n"
    .string "Aku… {STR_VAR_1}…\p"
    .string "Tidak ada yang istimewa tentang diriku\n"
    .string "yang bisa kubanggakan…\p"
    .string "Aku bahkan tidak seharusnya mengatakan apa-apa tentang\n"
    .string "diriku karena kamu akan melupakannya…\p"
    .string "Aku bermimpi bahwa jika aku bertemu\n"
    .string "denganmu, {PLAYER}, mungkin aku bisa meminta\l"
    .string "nasihat darimu sebagai TRAINER.\p"
    .string "Tapi aku tidak berpikir kamu akan setuju\n"
    .string "dengan itu.\p"
    .string "…Atau apakah kamu akan berbaik hati\n"
    .string "memberiku nasihat?$"

gText_ApprenticeRejectTeaching3::
    .string "Aku tahu itu…\p"
    .string "Itu pasti terjadi karena aku ini\n"
    .string "orang yang sangat membosankan…\p"
    .string "Tapi aku pikir mungkin saja…\n"
    .string "Kamu tidak akan mempertimbangkannya, kan?\p"
    .string "Tapi aku tidak bisa menyerah begitu saja.\n"
    .string "Aku akan bertanya padamu selagi aku beruntung!\p"
    .string "Kumohon, maukah kamu berbaik hati memberiku\n"
    .string "nasihat?$"

gText_ApprenticeWhichLevelMode3::
    .string "Benarkah? Aku tidak percaya!\n"
    .string "Aku tidak percaya kamu mau menasihatiku!\l"
    .string "Aku… Aku senang sekali…\p"
    .string "Yang ingin kutanyakan ini sangat sepele,\n"
    .string "tapi aku tidak bisa memutuskan…\p"
    .string "Di BATTLE TOWER, kita bisa memilih\n"
    .string "Level 50 atau Open Level.\p"
    .string "Menurutmu, di jalur mana aku mungkin\n"
    .string "punya kesempatan?$"

gText_ApprenticeLevelModeThanks3::
    .string "{STR_VAR_1}? Oke!\n"
    .string "Tapi apa kamu yakin orang sepertiku\l"
    .string "akan punya kesempatan?\p"
    .string "Aku akan berusaha, meskipun kurasa\n"
    .string "tidak akan berhasil.\p"
    .string "Terima kasih banyak sudah meluangkan\n"
    .string "waktu untuk orang sepertiku.$"

gText_ApprenticePleaseTeach4::
    .string "Oh! Kamu {PLAYER}{KUN}, kan?\p"
    .string "Aku dengar kamu tangguh dalam\n"
    .string "POKéMON!\p"
    .string "Aku {STR_VAR_1}!\n"
    .string "Aku akan jadi temanmu!\p"
    .string "Tahukah kamu?\p"
    .string "Kamu tidak bisa menang di BATTLE FRONTIER\n"
    .string "jika yang kamu tahu hanyalah apa yang diajarkan\l"
    .string "di SEKOLAH TRAINER.\p"
    .string "Aku bersedia mendengarkan nasihatmu.\n"
    .string "Kamu akan setuju, kan?$"

gText_ApprenticeRejectTeaching4::
    .string "Hah? Kenapa kamu menolakku?\n"
    .string "Aku yang memintamu!\l"
    .string "Kamu harus mempertimbangkannya!$"

gText_ApprenticeWhichLevelMode4::
    .string "Oke, jadi begini.\n"
    .string "Aku ingin kamu yang memutuskannya untukku.\p"
    .string "Kamu tahu kan BATTLE TOWER punya\n"
    .string "Ruangan Level 50 dan Open Level?\p"
    .string "Menurutmu mana yang bagus\n"
    .string "untukku, {PLAYER}{KUN}?$"

gText_ApprenticeLevelModeThanks4::
    .string "Oke, {STR_VAR_1} cocok untukku?\n"
    .string "Terima kasih!\p"
    .string "Karena kamu yang memutuskan,\n"
    .string "{PLAYER}{KUN}, aku tidak akan terlalu kesal kalau\l"
    .string "aku kalah.\p"
    .string "Oke, aku akan minta nasihatmu lagi nanti.\n"
    .string "Dah!$"

gText_ApprenticePleaseTeach5::
    .string "Oh, hai! {PLAYER}{KUN}!\n"
    .string "Aku mengenalmu karena kamu terkenal!\l"
    .string "Panggil aku {STR_VAR_1}! Senang bertemu denganmu!\p"
    .string "Aku seorang TRIATHLETE, jadi aku menjaga diriku\n"
    .string "tetap bugar bahkan saat aku membesarkan POKéMON.\p"
    .string "Aku juga terlibat dalam hal lain\n"
    .string "seperti pekerjaan, tidur siang, dansa ballroom…\p"
    .string "Menjadi sesibuk ini, tidak mudah bagiku\n"
    .string "untuk menjadi TRAINER yang baik.\p"
    .string "Jadi, aku punya tawaran!\p"
    .string "Pasti ada alasan mengapa kita bertemu.\n"
    .string "Jadi, {PLAYER}{KUN}, bagaimana kalau kamu berbagi\l"
    .string "kebijaksanaanmu denganku sesekali?$"

gText_ApprenticeRejectTeaching5::
    .string "Oh, tapi, kumohon?\n"
    .string "Pria sepertiku membutuhkan seseorang sepertimu,\l"
    .string "{PLAYER}{KUN}!\p"
    .string "Jujur, aku butuh nasihatmu!$"

gText_ApprenticeWhichLevelMode5::
    .string "Terima kasih! Nah, begitu dong!\n"
    .string "Kalau begitu, kita mulai dari yang mudah!\p"
    .string "Kamu tahu kan dua jalur BATTLE TOWER?\l"
    .string "Level 50 dan Open Level itu.\p"
    .string "Aku kan orang sibuk, mana yang sebaiknya\n"
    .string "aku persiapkan?$"

gText_ApprenticeLevelModeThanks5::
    .string "{STR_VAR_1}, ya? Oke, mengerti.\n"
    .string "Aku akan coba cari waktu dan mencobanya!\p"
    .string "…Ups, aku harus kerja!\n"
    .string "Makasih! Sampai jumpa!$"

gText_ApprenticePleaseTeach6::
    .string "Tidak mungkin! Uh-uh!\n"
    .string "Mungkinkah kamu {PLAYER} yang asli?\p"
    .string "A-hah! Luar biasa! Aku {STR_VAR_1},\n"
    .string "sangat senang bertemu denganmu!\p"
    .string "{PLAYER}, kamu sangat kuat,\n"
    .string "bukan?\p"
    .string "Semua orang membicarakanmu!\p"
    .string "Oh! Aku punya ide bagus!\n"
    .string "Aku akan meminta nasihat darimu, {PLAYER}!\l"
    .string "Aku yakin itu akan membuatku lebih tangguh!\p"
    .string "Bukankah itu ide bagus?\n"
    .string "Tolong, aku ingin nasihatmu!$"

gText_ApprenticeRejectTeaching6::
    .string "Ahahaha, kamu bisa berpura-pura jahat,\n"
    .string "tapi kamu tidak bisa membodohiku!\l"
    .string "Kamu sebenarnya setuju, kan?$"

gText_ApprenticeWhichLevelMode6::
    .string "Yay! Aku tahu kamu baik hati,\n"
    .string "{PLAYER}!\p"
    .string "Apa yang harus aku tanyakan dulu ya?\n"
    .string "…Oh, aku kepikiran sesuatu!\p"
    .string "Jeng jeng jeng!\n"
    .string "Pertanyaanku adalah…\p"
    .string "Kalau aku mau ikut tantangan BATTLE TOWER,\n"
    .string "sebaiknya aku pilih jalur yang mana?\p"
    .string "Level 50 atau Open Level?\n"
    .string "Mana yang lebih cocok untukku?$"

gText_ApprenticeLevelModeThanks6::
    .string "Oh-oh-oh!\n"
    .string "{STR_VAR_1}, katamu!\l"
    .string "Terima kasih atas jawaban yang sangat keren!\p"
    .string "Sepertinya hanya itu yang ingin\n"
    .string "aku tanyakan hari ini.\p"
    .string "Kita ketemu lagi di sini ya, oke?\n"
    .string "Makasih!$"

gText_ApprenticePleaseTeach7::
    .string "Maafkan aku, tapi…\n"
    .string "Apakah kamu {PLAYER}?\p"
    .string "Aku {STR_VAR_1}, dan aku senang sekali\n"
    .string "bertemu denganmu.\p"
    .string "Aku sudah lama mengagumimu…\p"
    .string "… … … … … …\p"
    .string "Um… Aku harap kamu tidak menganggap\n"
    .string "permintaan ini terlalu memberatkan, tapi…\p"
    .string "Bolehkah aku menjadi muridmu,\n"
    .string "{PLAYER}?$"

gText_ApprenticeRejectTeaching7::
    .string "Oh…!\p"
    .string "… … … … … …\n"
    .string "… … … … … …\p"
    .string "…Aku pasti pingsan karena kaget.\n"
    .string "Maaf, aku pasti salah dengar.\p"
    .string "Kumohon! Kumohon katakan bahwa kamu akan\n"
    .string "menerima aku sebagai muridmu!$"

gText_ApprenticeWhichLevelMode7::
    .string "Oh… Aku senang sekali!\p"
    .string "Aku tidak ingin membuang waktumu,\n"
    .string "jadi tolong nasihati aku tentang ini.\p"
    .string "Aku berencana mengikuti tantangan BATTLE TOWER\n"
    .string "dalam waktu dekat.\p"
    .string "Tapi, ada dua level…\p"
    .string "Mana yang paling cocok untukku?\n"
    .string "Level 50 atau Open Level?$"

gText_ApprenticeLevelModeThanks7::
    .string "Pilihanmu {STR_VAR_1}!\n"
    .string "Aku mengerti. Aku akan berusaha sebaik mungkin!\p"
    .string "Terima kasih, {PLAYER}.\n"
    .string "Kuharap aku bisa mengandalkanmu lagi.\l"
    .string "Hati-hati ya!$"

gText_ApprenticePleaseTeach8::
    .string "Aduh! Aduh! {PLAYER}!\n"
    .string "Kamu berbicara kepadaku!\l"
    .string "Aku… Aku sangat gembira!\p"
    .string "Aku! Namaku {STR_VAR_1}!\n"
    .string "Aku baru saja menjadi TRAINER!\p"
    .string "Aku senang bertemu denganmu, {PLAYER},\n"
    .string "nama besar di dunia POKéMON!\p"
    .string "Oh-oh-oh, aku tahu!\n"
    .string "Bolehkah aku meminta bantuan besar, {PLAYER}?\p"
    .string "Tolong jadikan aku muridmu!\n"
    .string "Aku ingin belajar darimu!$"

gText_ApprenticeRejectTeaching8::
    .string "Waaaaah!\n"
    .string "{PLAYER} menolakku…\l"
    .string "Ini… Ini pengalaman yang tak ternilai!\p"
    .string "{PLAYER}, kumohon! Aku ingin mendengar\n"
    .string "jawaban yang setuju kali ini!\p"
    .string "Aku memohon bimbinganmu!$"

gText_ApprenticeWhichLevelMode8::
    .string "Hiaaa! {PLAYER} bilang ya!\n"
    .string "{PLAYER} bilang ya!\p"
    .string "Aku tidak akan bisa tidur malam ini…\n"
    .string "Terima kasih banyak!\p"
    .string "Kalau begitu, ini pertanyaanku!\p"
    .string "Di BATTLE TOWER, mana yang cocok\n"
    .string "untukku, Level 50 atau Open Level?$"

gText_ApprenticeLevelModeThanks8::
    .string "{STR_VAR_1}! Sangat dimengerti!\n"
    .string "Aku sangat mengerti!\l"
    .string "Aku senang sekali!\p"
    .string "Kuharap kamu mau mengajariku\n"
    .string "lagi lain kali.$"

gText_ApprenticePleaseTeach9::
    .string "Wah! Mungkinkah kamu…\n"
    .string "Mungkinkah kamu… {PLAYER}{KUN}?!\l"
    .string "TRAINER yang kuat dan terkenal itu?\l"
    .string "Wah, halo, bukankah aku yang paling beruntung!\p"
    .string "Halo, namaku {STR_VAR_1}!\p"
    .string "Aku sedang mencari\n"
    .string "guru POKéMON.\p"
    .string "Dan dengan waktu yang sangat tepat,\n"
    .string "datanglah kamu, {PLAYER}{KUN}!\p"
    .string "Jadi, begitulah, {PLAYER}{KUN}!\n"
    .string "Biarkan aku menjadi muridmu!$"

gText_ApprenticeRejectTeaching9::
    .string "Gwaaaah!\n"
    .string "Kamu cukup keren dan tangguh…\p"
    .string "Jangan seperti itu, kumohon.\n"
    .string "Aku memintamu!$"

gText_ApprenticeWhichLevelMode9::
    .string "Oh, yeah! Jawaban yang mantap!\n"
    .string "Keren, kalau boleh kutambahkan!\p"
    .string "Jadi bagaimana kalau nasihat pertama\n"
    .string "tentang BATTLE TOWER?\p"
    .string "Kalau aku ikut, mana yang lebih baik?\n"
    .string "Level 50 atau Open Level?$"

gText_ApprenticeLevelModeThanks9::
    .string "Uh-huh, {STR_VAR_1} ya!\n"
    .string "Oke, siplah!\l"
    .string "Aku akan tunjukkan kemampuanku, gas!\p"
    .string "Baiklah, aku akan menganggapmu sebagai mentorku!\n"
    .string "Adios!$"

gText_ApprenticePleaseTeach10::
    .string "Oh, hei, {PLAYER}{KUN}, kan?\n"
    .string "Polisi mencarimu!\p"
    .string "… … …\n"
    .string "Tentu saja aku berbohong!\p"
    .string "Aku, aku {STR_VAR_1}. Meskipun penampilanku\n"
    .string "seperti ini, aku adalah JUARA POKéMON!\l"
    .string "…Itu juga bohong!\p"
    .string "Tapi ini bukan bohong.\n"
    .string "Aku tidak terlalu pandai bertarung.\p"
    .string "Jadi, bagaimana kalau kamu menjadi guruku\n"
    .string "tentang semua hal POKéMON?$"

gText_ApprenticeRejectTeaching10::
    .string "Jika kamu akan bersikap dingin seperti itu,\n"
    .string "Aku akan menunjukkan apa yang akan kulakukan!\p"
    .string "Waaah! Waaah! Waaah!\n"
    .string "Tersedak!\p"
    .string "Hahaha, itu adalah AIR MATA PALSUku!\p"
    .string "Ayolah, maukah kamu menjadi\n"
    .string "guruku POKéMON?$"

gText_ApprenticeWhichLevelMode10::
    .string "Hore!\n"
    .string "Akan kubelikan perahu untukmu!\p"
    .string "Tentu saja aku bohong lagi!\n"
    .string "Tapi… Terima kasih, guru!\p"
    .string "Kamu tahu kan ada Level 50 dan\n"
    .string "Open Level di BATTLE TOWER?\p"
    .string "Aku bingung memutuskan level mana\n"
    .string "yang harus kutantang…\p"
    .string "Bisa kamu putuskan untukku, guru?$"

gText_ApprenticeLevelModeThanks10::
    .string "Oke, jadi {STR_VAR_1} lebih baik ya!\n"
    .string "Kalau begitu, aku akan ke level yang lain!\p"
    .string "Cuma bercanda!\n"
    .string "Aku akan menuruti ajaranmu, guru!\p"
    .string "Makasih, guru!\n"
    .string "Kuharap kamu akan terus mengajariku!$"

gText_ApprenticePleaseTeach11::
    .string "A-H-O-Y!\n"
    .string "Dan itu berarti ahoy, dan itu berarti hai!\p"
    .string "Aku {STR_VAR_1}, PELAUT rapper\n"
    .string "aku!\p"
    .string "Giliranmu sekarang, ceritakan sedikit tentang\n"
    .string "dirimu, coba saja!\p"
    .string "Uh-huh, uh-huh!\n"
    .string "Namamu {PLAYER}{KUN},\l"
    .string "dan POKéMON adalah permainanmu!\p"
    .string "Dan kamu berada di usia yang rentan\n"
    .string "ketika seluruh dunia adalah panggungmu!\p"
    .string "Bagaimanapun, aku hanya ingin mengatakan,\n"
    .string "bahwa kamu adalah TRAINER kesepuluh\l"
    .string "yang aku ajak bicara hari ini.\p"
    .string "Mari kita jadikan itu perayaan!\n"
    .string "Jadilah mentorku untuk peringatan ini!$"

gText_ApprenticeRejectTeaching11::
    .string "Tapi!\n"
    .string "Kamu harus bekerja denganku!\p"
    .string "Jangan menggoda seperti itu!\n"
    .string "Jadilah mentorku, kumohon!$"

gText_ApprenticeWhichLevelMode11::
    .string "Itu dia!\n"
    .string "{PLAYER}, kamu punya semangat!\p"
    .string "Jadi ini pertanyaan pertamaku\n"
    .string "yang butuh saranmu!\p"
    .string "Ini tentang BATTLE TOWER,\n"
    .string "dan ini bergantung pada kekuatanku!\p"
    .string "Ada Level 50 dan Open Level,\n"
    .string "mana yang cocok untukku?$"

gText_ApprenticeLevelModeThanks11::
    .string "Oke, {STR_VAR_1} ya, katamu!\n"
    .string "Aku akan pergi dan mencobanya!\p"
    .string "Kalau aku butuh nasihat,\n"
    .string "{PLAYER}, perkataanmu akan selalu kudengar!$"

gText_ApprenticePleaseTeach12::
    .string "Hei, bukankah kamu {PLAYER}?\n"
    .string "Apa yang harus aku lakukan? Berbicara denganmu?\l"
    .string "Kenapa tidak? Aku sudah berbicara denganmu!\p"
    .string "{PLAYER}, apakah kamu terkejut padaku?\n"
    .string "Sebaiknya aku memberitahumu siapa aku!\p"
    .string "{STR_VAR_1} adalah nama panggilanku.\n"
    .string "Bintang paling terang di dunia gitar,\l"
    .string "itulah aku!\p"
    .string "Apakah kamu mendengarku?\n"
    .string "Kamu mendengarku!\p"
    .string "Keberuntunganku sedang bagus,\n"
    .string "aku akan memberimu permintaan!\p"
    .string "{PLAYER}, biarkan aku menjadi bawahanmu!\n"
    .string "Aku ingin kamu mengajariku segalanya!$"

gText_ApprenticeRejectTeaching12::
    .string "Kamu menolakku, begitu?\n"
    .string "Aku harus bertanya lagi padamu!\p"
    .string "{PLAYER}, aku memohon untuk menjadi bawahanmu!\n"
    .string "Aku butuh kamu mengajariku segalanya!$"

gText_ApprenticeWhichLevelMode12::
    .string "Beruntung, ya, wuhuu!\n"
    .string "Haruskah aku ajukan pertanyaan padamu?\p"
    .string "Karena kita dekat BATTLE TOWER,\n"
    .string "bagaimana kalau pertanyaan tentang kekuatannya?\p"
    .string "Dari pilihan yang kamu lihat,\n"
    .string "mana yang tepat untukku?$"

gText_ApprenticeLevelModeThanks12::
    .string "Jika {STR_VAR_1} yang kamu sarankan,\n"
    .string "itu pasti yang terbaik!\p"
    .string "Yah, {PLAYER}, aku harus berkelana,\n"
    .string "tapi jangan lupakan aku.\p"
    .string "Sampai jumpa lagi, teman pintarku!$"

gText_ApprenticePleaseTeach13::
    .string "Oh, hai! Kamu di sana!\n"
    .string "Bisakah kamu memijat bahuku?\p"
    .string "…Ya, di sana! Itu dia!\n"
    .string "Aduh, aduh! Oooh, rasanya enak sekali!\p"
    .string "Namaku {STR_VAR_1}.\n"
    .string "Aku berlatih karate, tapi tubuhku\l"
    .string "tidak dibuat untuk menerima kekerasan…\p"
    .string "Aku memutuskan akan bertarung POKéMON dan\n"
    .string "menguatkan diriku.\p"
    .string "Kamu {PLAYER}{KUN}, kan?\n"
    .string "JUARA LIGA POKéMON?\p"
    .string "Dengar, bisakah kamu memberiku\n"
    .string "nasihat?$"

gText_ApprenticeRejectTeaching13::
    .string "Oh, kenapa?\p"
    .string "Aku tidak akan merepotkan, aku janji!\n"
    .string "Kumohon?$"

gText_ApprenticeWhichLevelMode13::
    .string "Terima kasih. Baik sekali kamu!\n"
    .string "…Uhuk! Uhuk!\p"
    .string "Oogh, aku harus cepat menguatkan diri…\p"
    .string "Aku akan segera ke BATTLE TOWER,\n"
    .string "tapi mana yang lebih baik\l"
    .string "untukku? Level 50 atau Open Level?$"

gText_ApprenticeLevelModeThanks13::
    .string "Hm, baiklah. {STR_VAR_1} ya.\n"
    .string "Aku akan segera ke sana.\p"
    .string "Kuharap aku bisa terus meminta\n"
    .string "bantuanmu--lagipula, kamu mentorku!$"

gText_ApprenticePleaseTeach14::
    .string "Er… Um…\n"
    .string "{PLAYER}{KUN}…?\p"
    .string "Tolong, jangan menatapku seperti itu.\n"
    .string "Kamu membuatku merasa tidak nyaman.\p"
    .string "Aku… Aku {STR_VAR_1}.\p"
    .string "Aku sangat malu mengatakan ini,\n"
    .string "tapi aku menjelajahi reruntuhan kuno dan semacamnya.\p"
    .string "Aku bahkan lebih malu mengakui\n"
    .string "aku tertarik pada BATTLE FRONTIER.\p"
    .string "{PLAYER}{KUN}, kamu memiliki reputasi sebagai\n"
    .string "TRAINER yang tangguh…\p"
    .string "Sulit bagiku mengatakan ini,\n"
    .string "tapi aku ingin bertanya sesuatu.\p"
    .string "Bisakah kamu menjadi guruku dan\n"
    .string "memberiku nasihat?$"

gText_ApprenticeRejectTeaching14::
    .string "Tolong jangan mengabaikanku seperti ini!\n"
    .string "Aku tidak bisa hidup dengan penghinaan ini.\p"
    .string "Tolong jadilah guruku!\n"
    .string "Aku butuh nasihatmu!$"

gText_ApprenticeWhichLevelMode14::
    .string "Te-terima kasih…\p"
    .string "Tapi tolong jangan menatapku seperti itu.\n"
    .string "Itu membuatku jadi bingung.\p"
    .string "Tolong, jawab aku tanpa menatap\n"
    .string "mataku.\p"
    .string "Di BATTLE TOWER…\n"
    .string "Level mana yang harus kucoba?$"

gText_ApprenticeLevelModeThanks14::
    .string "Oh… Oke!\n"
    .string "Aku akan mencobanya.\p"
    .string "Kuharap aku bisa membuat tantangan yang berani\n"
    .string "tanpa menjadi bingung…\p"
    .string "Terima kasih, {PLAYER}{KUN}.\n"
    .string "Jika kita bertemu lagi, kuharap kamu akan\l"
    .string "sama membantunya.$"

gText_ApprenticePleaseTeach15::
    .string "Hm? Kamu tampak seperti {PLAYER}{KUN}…\n"
    .string "Tapi apakah kamu benar-benar nyata?\p"
    .string "Kamu bisa memanggilku {STR_VAR_1}.\p"
    .string "Aku sudah lama mempertimbangkan ide untuk\n"
    .string "belajar di bawah TRAINER yang kuat.\p"
    .string "Jadi, aku harus katakan aku beruntung kamu datang!\n"
    .string "…Kamu benar-benar {PLAYER}{KUN}, ya?\p"
    .string "Tidak, tidak, jika kamu nyata, tidak apa-apa.\n"
    .string "Aku hanya ingin kamu mengakui aku\l"
    .string "sebagai muridmu.$"

gText_ApprenticeRejectTeaching15::
    .string "Oh?\n"
    .string "Tapi apa yang akan memaksamu menolak?\p"
    .string "Aku minta maaf karena skeptis tentang\n"
    .string "identitasmu.\p"
    .string "Tolong terima permintaan maafku dan\n"
    .string "terima aku sebagai muridmu.$"

gText_ApprenticeWhichLevelMode15::
    .string "Kamu benar-benar menerimaku?\n"
    .string "Aku tidak ingin merayakannya terlalu dini.\p"
    .string "Jika itu benar, aku minta maaf.\n"
    .string "Tapi sekarang, aku butuh nasihatmu.\p"
    .string "Jika aku masuk BATTLE TOWER,\n"
    .string "apa yang layak untukku?\l"
    .string "Level 50 atau Open Level?$"

gText_ApprenticeLevelModeThanks15::
    .string "{STR_VAR_1}?\n"
    .string "Apa kamu yakin?\p"
    .string "Begitu. Jika begitu, tidak apa-apa.\n"
    .string "Aku berterima kasih atas waktumu.\p"
    .string "Aku sadar aku bisa mengganggu, tapi aku senang\n"
    .string "karena kamu telah menerimaku.\p"
    .string "Mari bertemu lagi!$"

gText_ApprenticeWhatHeldItem0::
    .string "Hiks… Sob…\n"
    .string "Oh, {PLAYER}!\p"
    .string "Aku terjebak dalam dilema\n"
    .string "yang tidak bisa aku putuskan.\p"
    .string "Aku tidak bisa memutuskan apa yang harus\n"
    .string "{STR_VAR_1}-ku pegang.\p"
    .string "Tolong beritahu aku, {PLAYER}.\n"
    .string "Item apa yang harus dipegangnya?$"

gText_ApprenticeHoldNothing0::
    .string "Oh, benarkah? Sebaiknya aku tidak membuat\n"
    .string "{STR_VAR_1}-ku memegang apa pun?$"

gText_ApprenticeThanksNoHeldItem0::
    .string "Oh, oke! Aku senang ini sudah diputuskan!\n"
    .string "Luar biasa! Keren! Awoooh!\p"
    .string "Terima kasih banyak!$"

gText_ApprenticeThanksHeldItem0::
    .string "Oh, aku senang sekali…\n"
    .string "Sepertinya aku juga punya {STR_VAR_1} itu.\p"
    .string "Aku senang ini sudah diputuskan!\n"
    .string "Luar biasa! Keren! Awoooh!\p"
    .string "Terima kasih banyak!$"

gText_ApprenticeItemAlreadyRecommended0::
    .string "Waaaah! Tolong jangan jahat!\p"
    .string "Item {STR_VAR_1} itu sudah\n"
    .string "direkomendasikan padaku sebelumnya, hiks…\p"
    .string "Atau maksudmu aku tidak boleh membuat\n"
    .string "{STR_VAR_2}-ku memegang apa pun?$"

gText_ApprenticeWhatHeldItem1::
    .string "Yay! Itu {PLAYER}!\n"
    .string "Keren! Aku ingin menanyakan sesuatu!\p"
    .string "Apa kamu membuat POKéMON-mu memegang item?\n"
    .string "Aku ingin membuat milikku memegang item, tapi…\p"
    .string "Item apa yang bagus untuk\n"
    .string "dipegang {STR_VAR_1}?\p"
    .string "Bagaimana menurutmu?$"

gText_ApprenticeHoldNothing1::
    .string "Hah? Maksudmu {STR_VAR_1}-ku tidak\n"
    .string "perlu memegang apa pun?$"

gText_ApprenticeThanksNoHeldItem1::
    .string "Oh, begitu! Aku akan lakukan itu!\n"
    .string "Terima kasih sudah mengajariku!$"

gText_ApprenticeThanksHeldItem1::
    .string "Oh, wow! Satu {STR_VAR_1}, ya?\n"
    .string "Oke, aku akan lakukan itu!\p"
    .string "Terima kasih sudah mengajariku!$"

gText_ApprenticeItemAlreadyRecommended1::
    .string "Oh, uh, bukan, bukan itu maksudku.\n"
    .string "Aku ingin tahu tentang item yang berbeda\l"
    .string "dari yang sudah aku tahu.\p"
    .string "Atau maksudmu POKéMON-ku tidak\n"
    .string "perlu memegang apa pun kali ini?$"

gText_ApprenticeWhatHeldItem2::
    .string "{PLAYER}, halo!\n"
    .string "Ini tentang {STR_VAR_1}-ku…\p"
    .string "Aku ingin membuatnya memegang item yang bagus.\n"
    .string "Apa yang bagus untuknya?$"

gText_ApprenticeHoldNothing2::
    .string "Oh, jadi {STR_VAR_1}-ku tidak perlu\n"
    .string "memegang apa pun?$"

gText_ApprenticeThanksNoHeldItem2::
    .string "Oke, aku mengerti!\n"
    .string "Sampai jumpa lagi!$"

gText_ApprenticeThanksHeldItem2::
    .string "Oh, item {STR_VAR_1}?\n"
    .string "Mengerti!\p"
    .string "Aku akan berusaha sebaik mungkin untuk menemukannya!\n"
    .string "Sampai jumpa lagi!$"

gText_ApprenticeItemAlreadyRecommended2::
    .string "Seseorang sudah memberitahuku tentang\n"
    .string "{STR_VAR_1} sebelumnya.\p"
    .string "Aku ingin POKéMON-ku memegang item\n"
    .string "jenis lain.\p"
    .string "Atau menurutmu {STR_VAR_2} tidak\n"
    .string "perlu memegang apa pun?$"

gText_ApprenticeWhatHeldItem3::
    .string "Halo, {PLAYER}…\n"
    .string "Maaf mengganggumu, tapi aku punya\l"
    .string "sesuatu yang lain yang ingin aku tanyakan.\p"
    .string "Aku rasa aku tidak cukup baik untuk menang\n"
    .string "sendiri, jadi aku berpikir untuk\l"
    .string "membuat {STR_VAR_1}-ku memegang item.\p"
    .string "Tapi aku tidak tahu apa yang bagus.\p"
    .string "{PLAYER}, tolong, bisakah kamu memutuskan\n"
    .string "untukku?$"

gText_ApprenticeHoldNothing3::
    .string "POKéMON milik orang sepertiku\n"
    .string "lebih baik tanpa item?$"

gText_ApprenticeThanksNoHeldItem3::
    .string "Aku mengerti…\n"
    .string "Maksudmu aku tidak boleh bergantung pada item.\l"
    .string "Aku akan berusaha untuk tidak melakukannya!\p"
    .string "Terima kasih banyak!$"

gText_ApprenticeThanksHeldItem3::
    .string "Item {STR_VAR_1}, oke.\n"
    .string "Aku tidak yakin bisa mendapatkannya…\l"
    .string "Tidak! Aku akan berusaha mendapatkannya.\p"
    .string "Terima kasih banyak!$"

gText_ApprenticeItemAlreadyRecommended3::
    .string "Oh, tapi…\n"
    .string "Sepertinya aku pernah dengar tentang itu sebelumnya…\p"
    .string "Mungkin karena aku belum menangani\n"
    .string "item {STR_VAR_1} dengan baik?\p"
    .string "Atau maksudmu aku tidak boleh membuat\n"
    .string "{STR_VAR_2}-ku memegang apa pun?$"

gText_ApprenticeWhatHeldItem4::
    .string "Oh, {PLAYER}{KUN}.\n"
    .string "Ada sesuatu yang ingin aku tanyakan padamu.\p"
    .string "Kamu tahu kan kamu yang memutuskan POKéMON\n"
    .string "mana yang harus aku miliki?\p"
    .string "Tapi aku belum pernah bertanya item apa\n"
    .string "yang harus dipegangnya.\p"
    .string "Karena kamu sudah memberiku nasihat,\n"
    .string "bagaimana kalau selesaikan ini sampai tuntas?\p"
    .string "Apa yang bagus? Aku ingin membuat\n"
    .string "{STR_VAR_1}-ku memegang sesuatu.$"

gText_ApprenticeHoldNothing4::
    .string "Oh! Jadi {STR_VAR_1}-ku harus\n"
    .string "berusaha sekuat tenaga dengan tangan kosong?$"

gText_ApprenticeThanksNoHeldItem4::
    .string "Jika menurutmu itu yang terbaik, aku akan lakukan itu.\p"
    .string "Karena kamu yang memutuskan,\n"
    .string "{PLAYER}{KUN}, aku tidak akan terlalu kesal jika\l"
    .string "aku kalah.\p"
    .string "Oke, aku akan minta nasihatmu lagi nanti.\n"
    .string "Dah!$"

gText_ApprenticeThanksHeldItem4::
    .string "Item {STR_VAR_1}, ya?\n"
    .string "Tidak buruk. Aku akan menggunakannya!\p"
    .string "Karena kamu yang memutuskan,\n"
    .string "{PLAYER}{KUN}, aku tidak akan terlalu kesal jika\l"
    .string "aku kalah.\p"
    .string "Oke, aku akan minta nasihatmu lagi nanti.\n"
    .string "Dah!$"

gText_ApprenticeItemAlreadyRecommended4::
    .string "Hah? Apa yang kamu katakan?\n"
    .string "Kamu sudah memberitahuku tentang {STR_VAR_1}\l"
    .string "sebelumnya.\p"
    .string "Atau maksudmu {STR_VAR_2}-ku harus\n"
    .string "berusaha sekuat tenaga dengan tangan kosong?$"

gText_ApprenticeWhatHeldItem5::
    .string "Yo, {PLAYER}{KUN}!\p"
    .string "Kita berdua sibuk, tapi sepertinya kita\n"
    .string "sering bertemu ya!\p"
    .string "Hari ini aku harus berjalan,\n"
    .string "membersihkan, dan menyikat.\p"
    .string "Aku bahkan belum sempat membelikan\n"
    .string "{STR_VAR_1}-ku yang berharga apa pun.\p"
    .string "Aku tidak punya waktu, jadi bagaimana kalau\n"
    .string "kamu memberiku nasihat tentang apa yang harus\l"
    .string "dipegang {STR_VAR_1}-ku?$"

gText_ApprenticeHoldNothing5::
    .string "Oh, jadi karena aku orang sibuk, katamu\n"
    .string "{STR_VAR_1}-ku tidak butuh apa-apa?$"

gText_ApprenticeThanksNoHeldItem5::
    .string "Oke, mengerti.\n"
    .string "Aku tidak perlu waktu untuk itu.\p"
    .string "Terima kasih untuk hari ini!\n"
    .string "Sampai jumpa!$"

gText_ApprenticeThanksHeldItem5::
    .string "Oke, mengerti.\n"
    .string "Aku akan cari waktu dan menemukan\l"
    .string "{STR_VAR_1} yang kamu rekomendasikan.\p"
    .string "Aku senang bertemu mentor yang baik sepertimu.\n"
    .string "Makasih! Sampai jumpa!$"

gText_ApprenticeItemAlreadyRecommended5::
    .string "Hah? Aku sudah tahu tentang\n"
    .string "{STR_VAR_1} itu.\p"
    .string "Oh, benar, aku mengerti.\n"
    .string "Jadi karena aku orang sibuk, katamu\l"
    .string "{STR_VAR_2}-ku tidak butuh apa-apa?$"

gText_ApprenticeWhatHeldItem6::
    .string "Hai, {PLAYER}! Ini aku!\n"
    .string "Aku butuh pemikiranmu lagi hari ini.\l"
    .string "Tolong, aku butuh nasihatmu!\p"
    .string "Jeng jeng jeng!\n"
    .string "Pertanyaanku adalah…\p"
    .string "Jika aku ingin membuat {STR_VAR_1}-ku memegang\n"
    .string "sebuah item, apa itu?$"

gText_ApprenticeHoldNothing6::
    .string "Begitukah? {STR_VAR_1}-ku tidak\n"
    .string "perlu memegang item, katamu.$"

gText_ApprenticeThanksNoHeldItem6::
    .string "Oke, itu yang akan aku lakukan!\p"
    .string "Sepertinya hanya itu yang ingin\n"
    .string "aku tanyakan hari ini.\p"
    .string "Kita ketemu lagi di sini ya, oke?\n"
    .string "Makasih!$"

gText_ApprenticeThanksHeldItem6::
    .string "Uh-huh! Satu {STR_VAR_1}.\n"
    .string "Pilihan yang keren!\l"
    .string "Aku pasti akan mencobanya!\p"
    .string "Sepertinya hanya itu yang ingin\n"
    .string "aku tanyakan hari ini.\p"
    .string "Kita ketemu lagi di sini ya, oke?\n"
    .string "Makasih!$"

gText_ApprenticeItemAlreadyRecommended6::
    .string "Ahahah! Konyol sekali!\n"
    .string "Kamu sudah memberitahuku tentang\l"
    .string "{STR_VAR_1} itu sebelumnya!\p"
    .string "Kamu baik-baik saja, {PLAYER}?\p"
    .string "Oh, tunggu! {STR_VAR_2}-ku tidak\n"
    .string "perlu memegang item, katamu.$"

gText_ApprenticeWhatHeldItem7::
    .string "Halo, {PLAYER}. Kuharap kamu baik-baik\n"
    .string "saja.\p"
    .string "Bolehkah aku meminta nasihatmu?\p"
    .string "Dalam pertarungan baru-baru ini, lawanku\n"
    .string "sepertinya telah memberikan POKéMON-nya\l"
    .string "sebuah item untuk dipegang.\p"
    .string "Akibatnya, aku dikalahkan…\p"
    .string "Aku tidak ingin tertinggal.\n"
    .string "Aku ingin membuat {STR_VAR_1}-ku\l"
    .string "memegang item juga.\p"
    .string "Aku akan senang jika kamu bisa memutuskan\n"
    .string "apa yang tepat untuk POKéMON-ku…$"

gText_ApprenticeHoldNothing7::
    .string "Dengan kata lain… POKéMON-ku tidak\n"
    .string "perlu memegang item?$"

gText_ApprenticeThanksNoHeldItem7::
    .string "Aku mengerti sekarang!\n"
    .string "Aku akan terus mencoba seperti ini.\p"
    .string "Terima kasih, {PLAYER}.\n"
    .string "Kuharap aku bisa mengandalkanmu lagi.\l"
    .string "Hati-hati ya!$"

gText_ApprenticeThanksHeldItem7::
    .string "Satu {STR_VAR_1} ya!\n"
    .string "Aku akan segera memesannya.\p"
    .string "Terima kasih, {PLAYER}.\n"
    .string "Kuharap aku bisa mengandalkanmu lagi.\l"
    .string "Hati-hati ya!$"

gText_ApprenticeItemAlreadyRecommended7::
    .string "Kamu sudah memberitahuku tentang itu,\n"
    .string "dan aku sudah memilikinya.\p"
    .string "Atau maksudmu… POKéMON-ku tidak\n"
    .string "perlu memegang item?$"

gText_ApprenticeWhatHeldItem8::
    .string "Iih! {PLAYER}!\n"
    .string "A… Aku senang sekali bertemu denganmu lagi!\p"
    .string "Oh-oh-oh! Ada sesuatu yang harus\n"
    .string "aku tanyakan padamu, {PLAYER}!\p"
    .string "Tolong putuskan apa yang harus dipegang\n"
    .string "oleh {STR_VAR_1}-ku!$"

gText_ApprenticeHoldNothing8::
    .string "Oh, wow! Aku tidak menyangka jawaban itu!\n"
    .string "Jadi, item pegangan tidak perlu?$"

gText_ApprenticeThanksNoHeldItem8::
    .string "Sangat dimengerti!\n"
    .string "Aku akan terus seperti ini tanpa item!\p"
    .string "Kuharap kamu mau mengajariku\n"
    .string "lagi lain kali.$"

gText_ApprenticeThanksHeldItem8::
    .string "{STR_VAR_1}! Aku akan menggunakan itu!\p"
    .string "Um… Mungkinkah, {PLAYER}, kamu juga\n"
    .string "membuat POKéMON-mu memegang item itu?\p"
    .string "Aku pasti akan mendapatkannya!\n"
    .string "Kuharap kamu mau mengajariku\l"
    .string "lagi lain kali.$"

gText_ApprenticeItemAlreadyRecommended8::
    .string "Oh? Kamu merekomendasikan\n"
    .string "{STR_VAR_1} itu sebelumnya juga.\p"
    .string "Atau apakah itu hal terbaik untuk dipegang?\n"
    .string "Atau maksudmu {STR_VAR_2}-ku\l"
    .string "tidak perlu memegang apa-apa?$"

gText_ApprenticeWhatHeldItem9::
    .string "Hola!\n"
    .string "Maestro-ku, {PLAYER}{KUN}!\p"
    .string "Aku ingin meminta nasihatmu tentang\n"
    .string "peralatan POKéMON.\p"
    .string "Menurutmu apa yang bagus untuk\n"
    .string "dipegang {STR_VAR_1}-ku?\p"
    .string "Jangan malu-malu.\n"
    .string "Katakan saja!$"

gText_ApprenticeHoldNothing9::
    .string "Oh? Jadi, maksudmu {STR_VAR_1}-ku\n"
    .string "bisa menang tanpa memegang item apa pun?$"

gText_ApprenticeThanksNoHeldItem9::
    .string "Si, bueno!\n"
    .string "Aku akan berusaha sekuat tenaga, gas!\p"
    .string "Baiklah, terima kasih, seperti biasa!\n"
    .string "Adios!$"

gText_ApprenticeThanksHeldItem9::
    .string "Uh-huh, itu satu {STR_VAR_1}?\n"
    .string "Si, bueno!\l"
    .string "Aku akan mencarinya, sikat!\p"
    .string "Baiklah, terima kasih, seperti biasa!\n"
    .string "Adios!$"

gText_ApprenticeItemAlreadyRecommended9::
    .string "Tidak, tidak! Kamu sudah memberitahuku tentang\n"
    .string "item {STR_VAR_1} itu sebelumnya.\p"
    .string "Oh, tunggu sebentar di sini…\n"
    .string "Jadi, maksudmu {STR_VAR_2}-ku\l"
    .string "bisa menang tanpa memegang item apa pun?$"

gText_ApprenticeWhatHeldItem10::
    .string "{PLAYER}{KUN}, sesuatu yang luar biasa\n"
    .string "telah terjadi!\p"
    .string "Aku bangun pagi ini, dan POKéMON-ku\n"
    .string "punya 10 NUGGET!\p"
    .string "Tentu saja aku bohong!\n"
    .string "Wahahaha!\p"
    .string "Tapi ini bukan bohong.\n"
    .string "Aku tidak pandai memikirkan\l"
    .string "item apa yang harus dipegang POKéMON.\p"
    .string "Jadi, bagaimana kalau kamu putuskan untukku apa\n"
    .string "yang harus dipegang {STR_VAR_1}-ku, guru?$"

gText_ApprenticeHoldNothing10::
    .string "Apa artinya itu?\n"
    .string "Jangan membuatnya memegang apa-apa?$"

gText_ApprenticeThanksNoHeldItem10::
    .string "Oke, jadi seharusnya tidak memegang apa-apa.\n"
    .string "Kalau begitu, aku harus mendapatkan sesuatu untuknya!\p"
    .string "Cuma bercanda!\n"
    .string "Aku akan menuruti ajaranmu, guru!\p"
    .string "Makasih, guru!\n"
    .string "Kuharap kamu akan terus mengajariku!$"

gText_ApprenticeThanksHeldItem10::
    .string "Oke, jadi itu satu {STR_VAR_1}!\n"
    .string "Aku akan membuatnya memegang apa pun kecuali itu!\p"
    .string "Cuma bercanda!\n"
    .string "Aku akan menuruti ajaranmu, guru!\p"
    .string "Makasih, guru!\n"
    .string "Kuharap kamu akan terus mengajariku!$"

gText_ApprenticeItemAlreadyRecommended10::
    .string "Um, kamu memberitahuku tentang itu sebelumnya,\n"
    .string "kan?\p"
    .string "Apakah ada yang lain?\p"
    .string "Atau maksudmu, jangan membuat\n"
    .string "{STR_VAR_2}-ku memegang apa pun?$"

gText_ApprenticeWhatHeldItem11::
    .string "A-H-O-Y!\n"
    .string "Dan itu dibaca ahoy!\p"
    .string "Akulah si PELAUT rapper!\n"
    .string "Kupersembahkan sebuah pertanyaan\l"
    .string "yang cukup keren!\p"
    .string "Ini pertanyaan item\n"
    .string "yang butuh saranmu!\p"
    .string "{STR_VAR_1}-ku butuh item untuk dipegang,\n"
    .string "Apa itu, jika boleh aku bertanya?$"

gText_ApprenticeHoldNothing11::
    .string "Begitukah?\n"
    .string "{STR_VAR_1}-ku tidak perlu\l"
    .string "memegang apa pun dengan erat?$"

gText_ApprenticeThanksNoHeldItem11::
    .string "Oke, aku mengerti, tentu saja!\n"
    .string "POKéMON-ku akan pergi dengan tangan kosong juga!\p"
    .string "Kalau aku butuh nasihat,\n"
    .string "{PLAYER}, perkataanmu akan selalu kudengar!$"

gText_ApprenticeThanksHeldItem11::
    .string "Oke, satu {STR_VAR_1},\n"
    .string "itu yang akan aku gunakan.\l"
    .string "Aku benar telah membuatmu memilih!\p"
    .string "Kalau aku butuh nasihat,\n"
    .string "{PLAYER}, perkataanmu akan selalu kudengar!$"

gText_ApprenticeItemAlreadyRecommended11::
    .string "Oke, satu {STR_VAR_1}, katamu?\n"
    .string "Kamu sudah bilang itu kemarin.\l"
    .string "Aku butuh ide baru, cara baru.\p"
    .string "Atau, apa, benarkah?\n"
    .string "POKéMON-ku tidak perlu memegang\l"
    .string "apa pun dengan erat?$"

gText_ApprenticeWhatHeldItem12::
    .string "Hey, {PLAYER}!\n"
    .string "Aku menemukanmu lagi hari ini!\p"
    .string "Apa yang harus aku lakukan? Minta nasihatmu?\n"
    .string "Kenapa tidak? Aku sudah berbicara denganmu!\p"
    .string "{PLAYER}, apa kamu bosan denganku?\n"
    .string "Nggak, nggak mungkin.\p"
    .string "Maukah kamu mendengarkanku?\n"
    .string "Aku mencari nasihat--itulah yang\l"
    .string "aku bicarakan.\p"
    .string "Ini tentang item pegangan untuk\n"
    .string "{STR_VAR_1}-ku yang bagus.\l"
    .string "Kebimbanganku membuatku merenung.$"

gText_ApprenticeHoldNothing12::
    .string "{STR_VAR_1}-ku tidak butuh apa-apa?\n"
    .string "Tidak perlu memegang apa pun?$"

gText_ApprenticeThanksNoHeldItem12::
    .string "Jika tidak memegang apa-apa adalah yang terbaik,\n"
    .string "Aku akan lakukan seperti saranmu!\p"
    .string "Yah, {PLAYER}, aku harus berkelana,\n"
    .string "tapi jangan lupakan aku.\p"
    .string "Sampai jumpa lagi, teman pintarku!$"

gText_ApprenticeThanksHeldItem12::
    .string "Jika memegang {STR_VAR_1} itu\n"
    .string "adalah yang terbaik, aku akan lakukan seperti saranmu!\p"
    .string "Yah, {PLAYER}, aku harus berkelana,\n"
    .string "tapi jangan lupakan aku.\p"
    .string "Sampai jumpa lagi, teman pintarku!$"

gText_ApprenticeItemAlreadyRecommended12::
    .string "Bukankah aku pernah dengar tentang\n"
    .string "{STR_VAR_1} itu sebelumnya?\l"
    .string "Aku yakin, itu pasti!\p"
    .string "Aku butuh sesuatu yang baru!\n"
    .string "Atau, {STR_VAR_2}-ku tidak butuh apa-apa?\l"
    .string "Tidak perlu memegang apa pun?$"

gText_ApprenticeWhatHeldItem13::
    .string "Gwah! Aduh! {PLAYER}{KUN}, lenganku patah!\n"
    .string "Jangan sentuh, kumohon!\p"
    .string "Pasti patah saat aku mencoba\n"
    .string "berbagai item pegangan dengan rombongan\l"
    .string "POKéMON-ku.\p"
    .string "Jadi, karena keadaannya seperti ini,\n"
    .string "Aku butuh kamu untuk memutuskannya untukku.\p"
    .string "{PLAYER}{KUN}, menurutmu apa yang bagus\n"
    .string "untuk dipegang {STR_VAR_1}-ku?$"

gText_ApprenticeHoldNothing13::
    .string "Aduh…\p"
    .string "Jadi saranmu adalah {STR_VAR_1}-ku\n"
    .string "tidak perlu memegang apa pun?$"

gText_ApprenticeThanksNoHeldItem13::
    .string "Hm, baiklah. Itu akan lebih mudah\n"
    .string "bagiku, dengan keadaan sekarang.\p"
    .string "Kuharap aku bisa terus meminta\n"
    .string "bantuanmu seperti ini.$"

gText_ApprenticeThanksHeldItem13::
    .string "Hm, baiklah. Itu satu {STR_VAR_1}.\n"
    .string "Lengan POKéMON-ku baik-baik saja, jadi aku akan membuatnya\l"
    .string "memegang item itu segera.\p"
    .string "Kuharap aku bisa terus meminta\n"
    .string "bantuanmu seperti ini.$"

gText_ApprenticeItemAlreadyRecommended13::
    .string "Tidak, tidak, kamu sudah memberitahuku tentang\n"
    .string "{STR_VAR_1} itu sebelumnya, ingat?\p"
    .string "Bagaimana kalau memberitahuku sesuatu\n"
    .string "yang lebih baik?\p"
    .string "Oh, tunggu sebentar.\n"
    .string "Jadi saranmu adalah {STR_VAR_2}-ku\l"
    .string "tidak perlu memegang apa pun?$"

gText_ApprenticeWhatHeldItem14::
    .string "Er… Um…\n"
    .string "{PLAYER}{KUN}…\p"
    .string "Tolong, jangan menatapku seperti itu.\n"
    .string "POKéMON-ku tidak punya apa-apa.\p"
    .string "A… Aku sangat malu tentang ini,\n"
    .string "tapi aku sangat butuh nasihatmu.\p"
    .string "Aku tidak bisa memutuskan item pegangan apa yang akan\n"
    .string "membuat {STR_VAR_1}-ku kuat.\p"
    .string "{PLAYER}{KUN}, menurutmu apa yang\n"
    .string "bagus?$"

gText_ApprenticeHoldNothing14::
    .string "Oh… Jadi, menurutmu lebih baik\n"
    .string "jika {STR_VAR_1}-ku tidak punya item?$"

gText_ApprenticeThanksNoHeldItem14::
    .string "Oh… Oke!\n"
    .string "Aku akan pergi tanpa item.\p"
    .string "Tapi ini menegangkan.\n"
    .string "Bukankah itu terlalu keren?\p"
    .string "Terima kasih, {PLAYER}{KUN}.\n"
    .string "Jika kita bertemu lagi, kuharap kamu akan\l"
    .string "sama membantunya.$"

gText_ApprenticeThanksHeldItem14::
    .string "Oh… Oke!\n"
    .string "Aku akan menggunakan {STR_VAR_1} itu.\p"
    .string "Tapi ini menegangkan.\n"
    .string "Bukankah itu terlalu keren?\p"
    .string "Terima kasih, {PLAYER}{KUN}.\n"
    .string "Jika kita bertemu lagi, kuharap kamu akan\l"
    .string "sama membantunya.$"

gText_ApprenticeItemAlreadyRecommended14::
    .string "T-tapi aku sudah dengar tentang itu.\p"
    .string "Tolong jangan abaikan aku seperti ini!\n"
    .string "Aku tidak bisa hidup dengan penghinaan ini.\p"
    .string "Oh… Apa aku terlalu cepat mengambil kesimpulan?\n"
    .string "Apa menurutmu lebih baik jika\l"
    .string "{STR_VAR_2}-ku tidak punya item?$"

gText_ApprenticeWhatHeldItem15::
    .string "Hm? Kamu tampak seperti {PLAYER}{KUN}…\n"
    .string "Tapi apakah kamu benar-benar?\l"
    .string "Mungkin kamu kembarannya?\p"
    .string "Oh, tidak, tidak, tidak, jangan khawatir!\n"
    .string "Jika kamu benar-benar {PLAYER}, tolong\l"
    .string "lupakan kekasaranku.\p"
    .string "Yang aku inginkan adalah lebih banyak\n"
    .string "nasihat baikmu.\p"
    .string "Aku punya {STR_VAR_1} di sini yang ingin\n"
    .string "aku buat memegang item yang berguna.\p"
    .string "Apa yang pantas untuknya?$"

gText_ApprenticeHoldNothing15::
    .string "Lebih baik tidak memegang apa-apa?\n"
    .string "Apa kamu yakin?$"

gText_ApprenticeThanksNoHeldItem15::
    .string "Begitu. Jika begitu, tidak apa-apa.\n"
    .string "Aku berterima kasih atas waktumu.\p"
    .string "Mari bertemu lagi!$"

gText_ApprenticeThanksHeldItem15::
    .string "Satu {STR_VAR_1}?\n"
    .string "Apa kamu yakin?\p"
    .string "Begitu. Jika begitu, tidak apa-apa.\n"
    .string "Aku berterima kasih atas waktumu.\p"
    .string "Aku harap POKéMON-ku bisa\n"
    .string "memanfaatkannya dengan baik.\p"
    .string "Mari bertemu lagi!$"

gText_ApprenticeItemAlreadyRecommended15::
    .string "Tidak, tidak, tunggu sebentar.\n"
    .string "Aku yakin kamu sudah mengajarkanku itu sebelumnya.\p"
    .string "Aku ingin kamu merekomendasikan\n"
    .string "sesuatu yang berbeda kali ini.\p"
    .string "Mungkin kamu menyarankan agar\n"
    .string "{STR_VAR_2}-ku tidak memegang apa pun?\l"
    .string "Apa kamu yakin?$"

gText_ApprenticeWhichMonFirst0::
    .string "Waah, {PLAYER}!\n"
    .string "Aku punya dilema, hiks…\p"
    .string "Aku ingin mulai bertarung dengan orang lain,\n"
    .string "tapi aku tidak tahu harus berbuat apa.\p"
    .string "Bagaimana aku harus menyusun POKéMON-ku\n"
    .string "agar mereka menjadi yang terkuat?\p"
    .string "Tolong beritahu aku, {PLAYER}.\n"
    .string "Jika kamu jadi aku, POKéMON mana di antara ini\l"
    .string "yang akan kamu keluarkan pertama kali?$"

gText_ApprenticeMonFirstThanks0::
    .string "{STR_VAR_1}-ku harus maju pertama?\n"
    .string "Waaaaah!\p"
    .string "Oh! Maafkan aku!\n"
    .string "Kamu membuatku senang dengan memilih\l"
    .string "POKéMON pertamaku, dan itu membuatku menangis…\p"
    .string "Terima kasih banyak!$"

gText_ApprenticeWhichMonFirst1::
    .string "Yay! Itu {PLAYER}!\n"
    .string "Keren! Aku ingin menanyakan sesuatu!\p"
    .string "Um, dari POKéMON-ku, menurutmu\n"
    .string "mana yang harus keluar pertama?$"

gText_ApprenticeMonFirstThanks1::
    .string "{STR_VAR_1}-ku? Benar juga.\n"
    .string "Oke, aku akan lakukan itu!\p"
    .string "Terima kasih sudah mengajariku!$"

gText_ApprenticeWhichMonFirst2::
    .string "{PLAYER}, halo!\p"
    .string "Menurutku, dalam pertarungan, sangat penting\n"
    .string "POKéMON mana yang keluar pertama.\p"
    .string "Dari POKéMON yang aku punya,\n"
    .string "mana yang bagus untuk dikeluarkan pertama?$"

gText_ApprenticeMonFirstThanks2::
    .string "{STR_VAR_1}-ku maju pertama?\n"
    .string "Oke, aku mengerti!\p"
    .string "Sampai jumpa lagi!$"

gText_ApprenticeWhichMonFirst3::
    .string "Halo, {PLAYER}…\n"
    .string "Maaf mengganggumu lagi dengan\l"
    .string "pertanyaan lain.\p"
    .string "Aku sangat tidak percaya diri, aku tidak\n"
    .string "tahu apa yang akan aku lakukan tanpamu, {PLAYER}.\p"
    .string "Mungkin sia-sia bagiku untuk\n"
    .string "mengkhawatirkannya, tapi aku tidak bisa\l"
    .string "memutuskan sesuatu…\p"
    .string "POKéMON mana yang harus aku keluarkan\n"
    .string "pertama dalam pertarungan?$"

gText_ApprenticeMonFirstThanks3::
    .string "{STR_VAR_1}-ku?\n"
    .string "Mengerti!\p"
    .string "Aku tidak percaya kamu mau repot-repot\n"
    .string "menjawab pertanyaanku sesering ini!\p"
    .string "Aku sangat berterima kasih kamu bahkan mau\n"
    .string "berbicara denganku… Terima kasih!$"

gText_ApprenticeWhichMonFirst4::
    .string "Oh, {PLAYER}{KUN}! Ini aku!\n"
    .string "Aku senang melihatmu karena aku punya\l"
    .string "masalah kecil ini.\p"
    .string "Aku tidak bisa memutuskan bagaimana POKéMON-ku harus\n"
    .string "disusun. Bisakah kamu memutuskannya untukku?\p"
    .string "Oh, kamu tidak perlu memutuskan seluruh\n"
    .string "tim sekarang.\p"
    .string "Bagaimana kalau putuskan POKéMON\n"
    .string "pertama saja untukku?$"

gText_ApprenticeMonFirstThanks4::
    .string "{STR_VAR_1}-ku? Keren!\p"
    .string "Karena kamu yang memutuskan,\n"
    .string "{PLAYER}{KUN}, aku tidak akan terlalu kesal jika\l"
    .string "aku kalah.\p"
    .string "Oke, aku akan minta nasihatmu lagi nanti.\n"
    .string "Dah!$"

gText_ApprenticeWhichMonFirst5::
    .string "Hai, guruku {PLAYER}{KUN}!\n"
    .string "Aku sibuk lagi hari ini!\p"
    .string "Aku harus bersepeda, berbelanja,\n"
    .string "dan bersenandung.\p"
    .string "Aku bahkan belum sempat memutuskan\n"
    .string "bagaimana menyusun tim POKéMON-ku.\p"
    .string "Jadi, bagaimana kalau kamu periksa timku?\n"
    .string "Mana yang harus maju pertama?$"

gText_ApprenticeMonFirstThanks5::
    .string "Oke, mengerti.\n"
    .string "Setidaknya aku punya cukup waktu untuk menempatkan\l"
    .string "{STR_VAR_1}-ku di barisan depan!\p"
    .string "Ups, pacarku menunggu!\n"
    .string "Makasih! Sampai jumpa!$"

gText_ApprenticeWhichMonFirst6::
    .string "Yuhuu! Hai, {PLAYER}!\n"
    .string "Kamu selalu berjalan-jalan dengan gagah!\p"
    .string "Dengar, aku butuh sesuatu darimu\n"
    .string "lagi! Ini hal yang biasa!\p"
    .string "Jeng jeng jeng!\n"
    .string "Pertanyaanku adalah tentang timku.\p"
    .string "POKéMON-ku yang mana yang harus pertama\n"
    .string "maju dalam pertarungan?$"

gText_ApprenticeMonFirstThanks6::
    .string "Hmhm!\n"
    .string "{STR_VAR_1}-ku, katamu!\l"
    .string "Terima kasih atas jawaban yang paling keren!\p"
    .string "Sepertinya hanya itu yang ingin\n"
    .string "aku tanyakan hari ini.\p"
    .string "Kita ketemu lagi di sini ya, oke?\n"
    .string "Makasih!$"

gText_ApprenticeWhichMonFirst7::
    .string "Terima kasih banyak sudah berhenti untuk\n"
    .string "berbicara denganku, {PLAYER}.\p"
    .string "Aku tahu aku memanfaatkan\n"
    .string "kebaikanmu, tapi bolehkah aku meminta nasihat?\p"
    .string "Aku ingin kamu memutuskan urutan\n"
    .string "tim POKéMON-ku.\p"
    .string "Aku akan senang jika kamu bisa memutuskan\n"
    .string "POKéMON mana yang harus maju pertama.$"

gText_ApprenticeMonFirstThanks7::
    .string "{STR_VAR_1}-ku ya!\n"
    .string "Aku akan menempatkannya di depan segera!\p"
    .string "Terima kasih, {PLAYER}.\n"
    .string "Kuharap aku bisa mengandalkanmu lagi.\l"
    .string "Hati-hati ya!$"

gText_ApprenticeWhichMonFirst8::
    .string "Iih! {PLAYER}!\n"
    .string "A… Aku senang sekali bertemu denganmu lagi!\p"
    .string "POKéMON-ku telah menjadi jauh\n"
    .string "lebih kuat!\p"
    .string "Tapi aku tidak selalu menang. Sepertinya\n"
    .string "tergantung pada POKéMON mana yang maju pertama.\p"
    .string "{PLAYER}, tolong, aku butuh bantuanmu!\p"
    .string "Tolong putuskan POKéMON-ku yang mana\n"
    .string "yang harus maju pertama!$"

gText_ApprenticeMonFirstThanks8::
    .string "Hiks… Aku diliputi kebahagiaan…\p"
    .string "Seperti mimpi kamu memutuskannya\n"
    .string "untukku, {PLAYER}.\p"
    .string "Tapi sangat dimengerti!\n"
    .string "Aku akan maju dengan {STR_VAR_1}-ku dulu!\p"
    .string "Kuharap kamu mau mengajariku\n"
    .string "lagi lain kali.$"

gText_ApprenticeWhichMonFirst9::
    .string "Halo, halo!\n"
    .string "Mentorku, {PLAYER}{KUN}!\l"
    .string "Berikan aku nasihat bijakmu hari ini!\p"
    .string "Begini, aku sudah mengumpulkan tim\n"
    .string "tiga POKéMON. Sejauh ini bagus.\p"
    .string "Tapi urutan bertarung tim belum\n"
    .string "diputuskan.\p"
    .string "Di sinilah kamu masuk, {PLAYER}{KUN}!\n"
    .string "Kamu yang putuskan POKéMON mana yang memimpin!\p"
    .string "Jangan malu-malu.\n"
    .string "Katakan saja!$"

gText_ApprenticeMonFirstThanks9::
    .string "Uh-huh, {STR_VAR_1}-ku yang memimpin!\n"
    .string "Oke, siplah!\l"
    .string "Aku akan atur ulang formasinya, sikat!\p"
    .string "Baiklah, terima kasih, seperti biasa!\n"
    .string "Adios!$"

gText_ApprenticeWhichMonFirst10::
    .string "{PLAYER}{KUN}, dengar!\n"
    .string "Ini krisis!\p"
    .string "POKéMON-ku, ketiganya, masuk ke\n"
    .string "pertarungan sekaligus!\p"
    .string "Tentu saja itu tidak mungkin!\n"
    .string "Wahahaha!\p"
    .string "Tapi ini bukan bohong.\n"
    .string "Aku tidak pandai memikirkan\l"
    .string "bagaimana aku harus menyusun POKéMON-ku.\p"
    .string "Jadi, bagaimana kalau kamu putuskan untukku POKéMON\n"
    .string "mana yang harus maju pertama, guru?$"

gText_ApprenticeMonFirstThanks10::
    .string "Oke, jadi {STR_VAR_1}-ku yang kamu pilih?\n"
    .string "Kalau begitu, aku akan biarkan yang lain maju pertama!\p"
    .string "Cuma bercanda!\n"
    .string "Aku akan menuruti ajaranmu, guru!\p"
    .string "Makasih, guru!\n"
    .string "Kuharap kamu akan terus mengajariku!$"

gText_ApprenticeWhichMonFirst11::
    .string "A-H-O-Y!\n"
    .string "Dan itu dibaca ahoy!\p"
    .string "Akulah si PELAUT rapper!\n"
    .string "Kupersembahkan sebuah pertanyaan\l"
    .string "yang cukup keren!\p"
    .string "Ini pertanyaan susunan tim\n"
    .string "yang butuh saranmu!\p"
    .string "Dari semua ini, mana yang harus maju pertama\n"
    .string "sebagai yang pertama di tempat?$"

gText_ApprenticeMonFirstThanks11::
    .string "Oke, aku mengerti, tentu saja!\n"
    .string "Aku akan menukarnya, itu yang akan kulakukan!\p"
    .string "Kalau aku butuh nasihat,\n"
    .string "{PLAYER}, perkataanmu akan selalu kudengar!$"

gText_ApprenticeWhichMonFirst12::
    .string "Yahoo, {PLAYER}!\n"
    .string "Apa kabarmu?\p"
    .string "Apa yang harus aku lakukan? Langsung bertanya?\n"
    .string "Uh-huh, aku punya sesuatu untuk ditanyakan!\l"
    .string "Apa kamu mendengarku?\l"
    .string "Kamu mendengarku!\p"
    .string "Kamu harus memutuskan, POKéMON-ku\n"
    .string "yang mana yang pertama beraksi!\l"
    .string "Ke dalam pertarungan, maksudku.$"

gText_ApprenticeMonFirstThanks12::
    .string "{STR_VAR_1}-ku? Ya!\n"
    .string "Itu cukup, tidak ada masalah!\p"
    .string "Yah, {PLAYER}, aku harus berkelana,\n"
    .string "tapi jangan lupakan aku.\p"
    .string "Sampai jumpa lagi, teman pintarku!$"

gText_ApprenticeWhichMonFirst13::
    .string "…Aduh… aduh… {PLAYER}{KUN}…\n"
    .string "Perutku tiba-tiba sakit…\p"
    .string "…Sekarang sudah membaik…\p"
    .string "Pasti aku terlalu khawatir memikirkan\n"
    .string "bagaimana aku harus menyusun\l"
    .string "rombongan POKéMON-ku.\p"
    .string "Jadi, karena keadaannya seperti ini,\n"
    .string "Aku butuh kamu untuk memutuskannya untukku.\p"
    .string "{PLAYER}{KUN}, POKéMON-ku yang mana yang harus\n"
    .string "maju pertama? Agar aku menang, maksudku.$"

gText_ApprenticeMonFirstThanks13::
    .string "Hm, baiklah.\n"
    .string "{STR_VAR_1}-ku maju pertama.\p"
    .string "Aku akan atur susunannya seperti itu setelah\n"
    .string "aku makan malam.\p"
    .string "Kuharap aku bisa terus meminta\n"
    .string "bantuanmu seperti ini.$"

gText_ApprenticeWhichMonFirst14::
    .string "Er… Um…\n"
    .string "{PLAYER}{KUN}?\p"
    .string "Tolong, jangan menatapku seperti itu.\n"
    .string "Kamu membuatku jadi bingung.\p"
    .string "Um…\n"
    .string "Aku sangat butuh nasihatmu.\p"
    .string "Aku malu mengatakannya,\n"
    .string "tapi aku sudah memilih tim 3-POKéMON-ku.\l"
    .string "Tapi aku tidak bisa memutuskan urutannya.\p"
    .string "POKéMON mana yang harus aku keluarkan pertama\n"
    .string "agar setidaknya aku terlihat mampu?$"

gText_ApprenticeMonFirstThanks14::
    .string "Oh… Oke!\n"
    .string "Aku akan mulai dengan {STR_VAR_1}-ku.\p"
    .string "Kuharap aku bisa melakukan yang terbaik tanpa\n"
    .string "menjadi bingung.\p"
    .string "Terima kasih, {PLAYER}{KUN}.\n"
    .string "Jika kita bertemu lagi, kuharap kamu akan\l"
    .string "sama membantunya.$"

gText_ApprenticeWhichMonFirst15::
    .string "Hm? Kamu tampak seperti {PLAYER}{KUN}…\n"
    .string "Tapi apakah kamu benar-benar?\l"
    .string "Mungkin kamu peniru yang pintar?\p"
    .string "Oh, tidak, tidak, tidak, jangan khawatir!\n"
    .string "Jika kamu benar-benar {PLAYER}, tolong\l"
    .string "lupakan kekasaranku.\p"
    .string "Yang aku inginkan adalah nasihat baikmu.\p"
    .string "Aku punya tim POKéMON di sini.\n"
    .string "Aku ingin kamu memberitahuku mana yang\l"
    .string "harus maju pertama dalam pertarungan.$"

gText_ApprenticeMonFirstThanks15::
    .string "{STR_VAR_1}-ku…\n"
    .string "Kamu tidak sedang mengerjaiku kan?\p"
    .string "Begitu. Jika begitu, tidak apa-apa.\n"
    .string "Aku berterima kasih atas waktumu.\p"
    .string "Aku seperti yang kamu lihat, tapi aku akan\n"
    .string "melakukan yang terbaik.\p"
    .string "Mari bertemu lagi!$"

gText_ApprenticeWhichMon0::
    .string "Hiks…\n"
    .string "Oh, {PLAYER}!\p"
    .string "Waktu yang tepat!\n"
    .string "Ada sesuatu yang tidak bisa aku putuskan…\p"
    .string "Aku tidak bisa memutuskan POKéMON mana yang harus\n"
    .string "aku gunakan.\p"
    .string "Aku tidak bisa memutuskan antara POKéMON\n"
    .string "{STR_VAR_1} dan {STR_VAR_2}…\p"
    .string "{PLAYER}, menurutmu mana yang akan memberi\n"
    .string "bahkan aku kesempatan untuk menang?$"

gText_ApprenticeMonThanks0::
    .string "Hiks… A… Aku mengerti!\n"
    .string "Oh! Maafkan aku!\l"
    .string "Kamu membuatku sangat bahagia, aku menangis…\p"
    .string "Aku akan berusaha menangkap satu\n"
    .string "{STR_VAR_1}!\p"
    .string "Terima kasih banyak!$"

gText_ApprenticeWhichMon1::
    .string "Yay! Itu {PLAYER}!\n"
    .string "Yay, kamu datang di waktu yang tepat juga!\l"
    .string "Aku butuh nasihatmu lagi!\p"
    .string "Um, aku bingung--haruskah aku menggunakan\n"
    .string "{STR_VAR_1} atau {STR_VAR_2}-ku…\p"
    .string "Menurutmu mana yang harus aku besarkan,\n"
    .string "{PLAYER}?$"

gText_ApprenticeMonThanks1::
    .string "Oh, jadi {STR_VAR_1}-ku lebih baik!\n"
    .string "Oke, aku akan lakukan itu!\p"
    .string "Terima kasih sudah mengajariku!$"

gText_ApprenticeWhichMon2::
    .string "{PLAYER}, halo!\n"
    .string "Aku punya pertanyaan yang ingin aku tanyakan.\p"
    .string "Aku dalam dilema apakah aku harus\n"
    .string "membesarkan satu {STR_VAR_1} atau {STR_VAR_2}.\p"
    .string "POKéMON mana yang menurutmu akan\n"
    .string "lebih kuat?$"

gText_ApprenticeMonThanks2::
    .string "{STR_VAR_1} pilihanmu?\n"
    .string "Oke, aku mengerti!\p"
    .string "Aku akan pergi menangkap {STR_VAR_1} yang kuat\n"
    .string "segera!\p"
    .string "Sampai jumpa lagi!$"

gText_ApprenticeWhichMon3::
    .string "Halo, {PLAYER}…\p"
    .string "Um, kamu mungkin sudah lupa\n"
    .string "tentang orang sepertiku…\p"
    .string "…Tapi itu tidak masalah jika kamu\n"
    .string "bisa memberiku nasihat…\p"
    .string "Aku tidak bisa memutuskan jenis POKéMON\n"
    .string "apa yang harus aku besarkan…\p"
    .string "Aku sudah mempersempit pilihan ke POKéMON\n"
    .string "{STR_VAR_1} dan {STR_VAR_2}, tapi di situlah\l"
    .string "aku terjebak…\p"
    .string "{PLAYER}, kamu mungkin tidak mau\n"
    .string "repot, tapi tolong putuskan untukku.$"

gText_ApprenticeMonThanks3::
    .string "Tapi akankah {STR_VAR_1} liar bahkan\n"
    .string "memperhatikanku?\p"
    .string "Aku akan mencoba!\p"
    .string "Tapi akankah aku bisa menangkapnya…\n"
    .string "Tidak! Aku akan berusaha!\p"
    .string "Terima kasih!$"

gText_ApprenticeWhichMon4::
    .string "Oh, {PLAYER}{KUN}! Aku senang melihatmu!\n"
    .string "Aku baru saja akan mencarimu!\p"
    .string "Bisakah kamu memutuskan jenis POKéMON apa\n"
    .string "yang harus aku gunakan?\p"
    .string "Misalnya…\n"
    .string "Bagaimana dengan POKéMON {STR_VAR_1}\l"
    .string "dan {STR_VAR_2}?\p"
    .string "Menurutmu mana yang lebih\n"
    .string "baik?$"

gText_ApprenticeMonThanks4::
    .string "{STR_VAR_1}? Keren!\p"
    .string "Karena kamu yang memutuskan,\n"
    .string "{PLAYER}{KUN}, aku tidak akan terlalu kesal jika\l"
    .string "aku kalah.\p"
    .string "Oke, aku akan minta nasihatmu lagi nanti.\n"
    .string "Dah!$"

gText_ApprenticeWhichMon5::
    .string "Kalau bukan {PLAYER}{KUN}! Apa kabar?\n"
    .string "Aku sibuk lagi seperti biasa!\p"
    .string "Aku juga ingin pandai dengan POKéMON,\n"
    .string "tapi aku belum bisa memutuskan\l"
    .string "POKéMON mana yang harus aku gunakan.\p"
    .string "Kamu tahu kan {STR_VAR_1} terlihat kuat?\n"
    .string "Tapi {STR_VAR_2} sulit untuk diabaikan.\p"
    .string "{PLAYER}{KUN}, berikan aku nasihat baikmu!\n"
    .string "Mana yang bagus untukku?$"

gText_ApprenticeMonThanks5::
    .string "Oke, mengerti.\n"
    .string "Aku akan cari waktu dan menangkap\l"
    .string "{STR_VAR_1} yang kamu rekomendasikan.\p"
    .string "Aku senang bertemu mentor yang baik sepertimu.\n"
    .string "Makasih! Sampai jumpa!$"

gText_ApprenticeWhichMon6::
    .string "Oh!\n"
    .string "Yay, itu {PLAYER}!\p"
    .string "Aku tidak membuang waktu menyombongkan diri ke\n"
    .string "teman-temanku tentang bertemu denganmu!\p"
    .string "Aku butuh pemikiranmu lagi hari ini.\n"
    .string "Ini mudah bagimu!\p"
    .string "Jeng jeng jeng!\n"
    .string "Pertanyaanku adalah…\p"
    .string "Jika aku membesarkan POKéMON,\n"
    .string "dan pilihannya adalah satu {STR_VAR_1}\l"
    .string "atau {STR_VAR_2}, mana yang seharusnya?$"

gText_ApprenticeMonThanks6::
    .string "Ahhh!\n"
    .string "{STR_VAR_1}, katamu!\l"
    .string "Terima kasih atas jawaban yang paling keren!\p"
    .string "Sepertinya hanya itu yang ingin\n"
    .string "aku tanyakan hari ini.\p"
    .string "Kita ketemu lagi di sini ya, oke?\n"
    .string "Makasih!$"

gText_ApprenticeWhichMon7::
    .string "Oh, apakah itu kamu, {PLAYER}?\n"
    .string "Aku senang melihatmu lagi!\p"
    .string "Sejak aku menjadi muridmu,\n"
    .string "kepercayaandiriku mulai tumbuh.\p"
    .string "Aku rasa aku siap membesarkan POKéMON\n"
    .string "milikku sendiri!\p"
    .string "{PLAYER}, bolehkah aku memintamu untuk memilih\n"
    .string "POKéMON mana yang harus aku besarkan?\p"
    .string "Pilihannya adalah POKéMON\n"
    .string "{STR_VAR_1} atau {STR_VAR_2}…\l"
    .string "POKéMON mana yang tepat untukku?$"

gText_ApprenticeMonThanks7::
    .string "Satu {STR_VAR_1} ya!\n"
    .string "Aku akan segera menemukannya!\p"
    .string "Terima kasih, {PLAYER}.\n"
    .string "Kuharap aku bisa mengandalkanmu lagi.\l"
    .string "Hati-hati ya!$"

gText_ApprenticeWhichMon8::
    .string "Iih! {PLAYER}! Aku bertemu denganmu lagi!\n"
    .string "A… Aku senang sekali!\p"
    .string "Oh-oh-oh, aku tahu!\n"
    .string "Aku tidak boleh melewatkan kesempatan ini!\p"
    .string "Bolehkah aku meminta bantuan besar, {PLAYER}?\n"
    .string "Tolong pilihkan POKéMON untukku!\p"
    .string "Tolong putuskan mana yang lebih baik,\n"
    .string "{STR_VAR_1} atau {STR_VAR_2}!$"

gText_ApprenticeMonThanks8::
    .string "Wow! Kamu memutuskannya untukku!\n"
    .string "Satu {STR_VAR_1} akan aku besarkan dengan\l"
    .string "kemampuan terbaikku.\p"
    .string "Kuharap kamu mau mengajariku\n"
    .string "lagi lain kali.$"

gText_ApprenticeWhichMon9::
    .string "Hei, hei!\n"
    .string "Mentorku, {PLAYER}{KUN}!\p"
    .string "Halo, aku sudah mencarimu\n"
    .string "untuk nasihat bijakmu lagi!\p"
    .string "Jenis POKéMON mana yang tepat\n"
    .string "untukku, satu {STR_VAR_1} atau {STR_VAR_2}?\p"
    .string "Jangan malu-malu.\n"
    .string "Katakan saja!$"

gText_ApprenticeMonThanks9::
    .string "Uh-huh, satu {STR_VAR_1} ya!\n"
    .string "Oke, siplah!\l"
    .string "Aku akan mendapatkannya di BOLA, sikat!\p"
    .string "Baiklah, terima kasih, seperti biasa!\n"
    .string "Adios!$"

gText_ApprenticeWhichMon10::
    .string "{PLAYER}{KUN}, dengar! Berita besar!\n"
    .string "Aku menangkap POKéMON fatamorgana!\p"
    .string "Tentu saja aku bohong!\n"
    .string "Wahahaha!\p"
    .string "Tapi ini bukan bohong.\n"
    .string "Aku tidak pandai menangkap\l"
    .string "POKéMON.\p"
    .string "Jadi, bagaimana kalau kamu putuskan untukku jenis\n"
    .string "POKéMON apa yang harus aku tangkap,\l"
    .string "guru?\p"
    .string "Mana yang lebih baik?\n"
    .string "{STR_VAR_1} atau {STR_VAR_2}?$"

gText_ApprenticeMonThanks10::
    .string "Oke, jadi {STR_VAR_1} yang kamu pilih?\n"
    .string "Kalau begitu, aku akan ambil jenis yang lain!\p"
    .string "Cuma bercanda!\n"
    .string "Aku akan menuruti ajaranmu, guru!\p"
    .string "Makasih, guru!\n"
    .string "Kuharap kamu akan terus mengajariku!$"

gText_ApprenticeWhichMon11::
    .string "A-H-O-Y!\n"
    .string "Dan itu dibaca ahoy!\p"
    .string "Akulah si PELAUT rapper!\n"
    .string "Pasti kamu ingat siapa aku kan?\p"
    .string "Hari ini, aku punya pertanyaan POKéMON\n"
    .string "yang butuh saranmu!\p"
    .string "Aku punya pilihan antara\n"
    .string "{STR_VAR_1} dan {STR_VAR_2} ini, kamu lihat.\l"
    .string "Mana yang harus aku tangkap?$"

gText_ApprenticeMonThanks11::
    .string "{STR_VAR_1}, katamu, hei, hei!\n"
    .string "Aku akan segera menangkapnya!\p"
    .string "Kalau aku butuh nasihat,\n"
    .string "{PLAYER}, perkataanmu akan selalu kudengar!$"

gText_ApprenticeWhichMon12::
    .string "Oh, wow, kalau bukan {PLAYER}!\p"
    .string "Apa yang harus aku lakukan? Minta nasihatmu?\n"
    .string "Kenapa tidak? Aku sudah berbicara denganmu!\p"
    .string "Sudah lama. Biarkan aku mencairkan\n"
    .string "suasana. Aku juga mencari nasihat!\l"
    .string "Apa kamu mendengarku?\l"
    .string "Kamu mendengarku!\p"
    .string "POKéMON-ku--mana yang harus aku gunakan?\n"
    .string "Antara {STR_VAR_1} atau {STR_VAR_2}.\l"
    .string "Mana yang kamu pilih?$"

gText_ApprenticeMonThanks12::
    .string "Jika {STR_VAR_1} itu yang terbaik,\n"
    .string "Aku akan lakukan seperti saranmu!\p"
    .string "Yah, {PLAYER}, aku harus berkelana,\n"
    .string "tapi jangan lupakan aku.\p"
    .string "Sampai jumpa lagi, teman pintarku!$"

gText_ApprenticeWhichMon13::
    .string "Oh, hai, {PLAYER}{KUN}…\n"
    .string "Kepalaku sakit sekali…\p"
    .string "Pasti aku terlalu khawatir tentang\n"
    .string "jenis POKéMON yang harus aku besarkan.\p"
    .string "Jadi, karena keadaannya seperti ini,\n"
    .string "Aku butuh kamu untuk memutuskannya untukku.\p"
    .string "{PLAYER}{KUN}, jika aku harus memilih antara\n"
    .string "POKéMON {STR_VAR_1} dan\l"
    .string "{STR_VAR_2}, mana yang seharusnya?$"

gText_ApprenticeMonThanks13::
    .string "Hm, satu {STR_VAR_1}, baiklah.\n"
    .string "Aku akan mencarinya saat aku sembuh.\p"
    .string "Kuharap aku bisa terus meminta\n"
    .string "bantuanmu seperti ini.$"

gText_ApprenticeWhichMon14::
    .string "Er… Um…\n"
    .string "{PLAYER}{KUN}…?\p"
    .string "Tolong, jangan menatapku seperti itu.\n"
    .string "Aku jadi bingung…\l"
    .string "A… Aku butuh nasihatmu.\p"
    .string "A… Aku sangat malu, tapi aku tidak bisa\n"
    .string "memutuskan POKéMON mana yang akan digunakan.\p"
    .string "Jika pilihannya {STR_VAR_1} atau\n"
    .string "{STR_VAR_2}, mana yang lebih baik?$"

gText_ApprenticeMonThanks14::
    .string "Oh… Oke!\n"
    .string "Aku akan berusaha dengan satu {STR_VAR_1}.\p"
    .string "Kuharap aku bisa melakukan yang terbaik tanpa\n"
    .string "menjadi bingung.\p"
    .string "Terima kasih, {PLAYER}{KUN}.\n"
    .string "Jika kita bertemu lagi, kuharap kamu akan\l"
    .string "sama membantunya.$"

gText_ApprenticeWhichMon15::
    .string "Hm? Kamu tampak seperti {PLAYER}{KUN}…\n"
    .string "Tapi apakah kamu benar-benar nyata?\p"
    .string "Tidak, tidak, jika kamu nyata, tidak apa-apa.\n"
    .string "Kebetulan, aku ingin mendapatkan\l"
    .string "nasihatmu.\p"
    .string "Ini tentang POKéMON yang akan aku gunakan.\p"
    .string "Jika pilihannya POKéMON\n"
    .string "{STR_VAR_1} dan {STR_VAR_2}, mana yang\l"
    .string "lebih pantas untukku?$"

gText_ApprenticeMonThanks15::
    .string "{STR_VAR_1}?\n"
    .string "Apa kamu yakin?\p"
    .string "Begitu. Jika begitu, tidak apa-apa.\n"
    .string "Aku berterima kasih atas waktumu.\p"
    .string "Aku harap itu sesuatu yang bahkan aku bisa\n"
    .string "tangani dengan baik.\p"
    .string "Mari bertemu lagi!$"

gText_ApprenticeWhichMove0::
    .string "Waaah! Oh, {PLAYER}!\n"
    .string "Hiks… Isak…\p"
    .string "Aku punya dilema!\n"
    .string "Aku tidak bisa memutuskan jurus untuk\l"
    .string "{STR_VAR_1}-ku…\p"
    .string "Tolong, tolong, {PLAYER}.\n"
    .string "Bisakah kamu memutuskannya untukku?\p"
    .string "Untuk {STR_VAR_1}-ku, jurus mana yang\n"
    .string "akan menjadi pilihan yang lebih baik: {STR_VAR_2}\l"
    .string "atau {STR_VAR_3}?$"

gText_ApprenticeMoveThanks0::
    .string "{STR_VAR_1}?\n"
    .string "Waaaaah!\p"
    .string "Oh! Maafkan aku, {PLAYER}!\n"
    .string "Kamu membuatku sangat bahagia dengan memutuskan\l"
    .string "jurusnya, aku menangis…\p"
    .string "Hiks…\n"
    .string "Terima kasih banyak!$"

gText_ApprenticeWhichMove1::
    .string "Yay! Hai, {PLAYER}!\n"
    .string "Aku butuh nasihatmu lagi!\p"
    .string "Aku ingin mengajari {STR_VAR_1}-ku\n"
    .string "jurus yang keren.\p"
    .string "Aku suka salah satu dari jurus\n"
    .string "{STR_VAR_2} atau {STR_VAR_3}.\l"
    .string "Apa rekomendasimu?$"

gText_ApprenticeMoveThanks1::
    .string "{STR_VAR_1} lebih baik? Kurasa begitu!\n"
    .string "Oke, aku akan pilih itu!\p"
    .string "Kalau kita bertemu lagi di sini, tolong ajari\n"
    .string "aku hal lain ya, guru!$"

gText_ApprenticeWhichMove2::
    .string "{PLAYER}, halo!\n"
    .string "Ini tentang {STR_VAR_1}-ku, tapi aku\l"
    .string "khawatir tentang jurus-jurusnya.\p"
    .string "Begini, jurus-jurusnya adalah {STR_VAR_2}\n"
    .string "dan {STR_VAR_3}.\p"
    .string "Mana yang lebih kuat dan lebih baik untuk\n"
    .string "{STR_VAR_1}-ku?$"

gText_ApprenticeMoveThanks2::
    .string "{STR_VAR_1} pilihanmu?\n"
    .string "Oke, aku mengerti!\p"
    .string "Aku akan segera mengajarkan {STR_VAR_1} ke\n"
    .string "POKéMON-ku!\p"
    .string "Sampai jumpa lagi!$"

gText_ApprenticeWhichMove3::
    .string "Ohhh, {PLAYER}…\n"
    .string "Aku putus asa, sungguh!\p"
    .string "Aku sudah memutuskan untuk membesarkan POKéMON,\n"
    .string "tapi sekarang aku bahkan tidak bisa memutuskan\l"
    .string "jurus apa yang harus kupelajari…\p"
    .string "Aku tahu itu tidak berarti apa-apa\n"
    .string "bagimu, {PLAYER}.\p"
    .string "Tapi itu sangat berarti bagiku…\p"
    .string "Tolong, {PLAYER}, bisakah kamu memilihkan\n"
    .string "jurus untuk {STR_VAR_1}-ku?\p"
    .string "Jika kamu bisa memilih antara\n"
    .string "{STR_VAR_2} dan {STR_VAR_3}…$"

gText_ApprenticeMoveThanks3::
    .string "Aku mengerti!\p"
    .string "Tapi akankah ia mau belajar\n"
    .string "{STR_VAR_1} untukku…\l"
    .string "Tidak! Aku akan berusaha!\p"
    .string "Terima kasih!$"

gText_ApprenticeWhichMove4::
    .string "Oh, {PLAYER}{KUN}!\n"
    .string "Aku juga berharap bertemu denganmu!\p"
    .string "Aku bertanya-tanya jurus apa yang\n"
    .string "cocok untuk {STR_VAR_1}-ku.\p"
    .string "Aku tidak bisa memutuskan, jadi bisakah kamu\n"
    .string "memutuskannya untukku?\p"
    .string "Misalnya… Bagaimana dengan jurus\n"
    .string "{STR_VAR_2} dan {STR_VAR_3}?\l"
    .string "Mana yang lebih baik?$"

gText_ApprenticeMoveThanks4::
    .string "{STR_VAR_1}? Keren!\p"
    .string "Karena kamu yang memutuskan,\n"
    .string "{PLAYER}{KUN}, aku tidak akan terlalu kesal jika\l"
    .string "aku kalah.\p"
    .string "Oke, aku akan minta nasihatmu lagi nanti.\n"
    .string "Dah!$"

gText_ApprenticeWhichMove5::
    .string "Kenapa bisa sesibuk ini?\n"
    .string "Hei, kalau bukan {PLAYER}{KUN}!\l"
    .string "Apa kabar?\p"
    .string "Sejak bangun pagi ini, aku sudah\n"
    .string "jogging, berenang, dan memasak!\p"
    .string "Kamu tidak akan percaya betapa sibuknya aku!\p"
    .string "Aku bahkan tidak bisa memutuskan jurus\n"
    .string "apa yang harus dipelajari {STR_VAR_1}-ku!\p"
    .string "{STR_VAR_2} kelihatannya bagus, kan?\n"
    .string "Tapi {STR_VAR_3} juga lumayan.\p"
    .string "{PLAYER}{KUN}, berikan aku nasihat baikmu!\n"
    .string "Jurus mana yang bagus untukku?$"

gText_ApprenticeMoveThanks5::
    .string "Oke, mengerti.\n"
    .string "Aku akan luangkan waktu dalam jadwalku dan\l"
    .string "mengajarkan jurus itu.\p"
    .string "Aku senang bertemu mentor yang baik sepertimu.\n"
    .string "Makasih! Sampai jumpa!$"

gText_ApprenticeWhichMove6::
    .string "Oh! Beruntung!\n"
    .string "Aku bertemu denganmu lagi, {PLAYER}!\l"
    .string "Aku butuh pemikiranmu lagi hari ini.\p"
    .string "Jeng jeng jeng!\n"
    .string "Pertanyaanku adalah…\p"
    .string "Untuk {STR_VAR_1}-ku, jurus mana yang\n"
    .string "paling cocok, {STR_VAR_2} atau\l"
    .string "{STR_VAR_3}?$"

gText_ApprenticeMoveThanks6::
    .string "Ahhh!\n"
    .string "{STR_VAR_1}, katamu!\l"
    .string "Terima kasih atas jawaban yang paling keren!\p"
    .string "Sepertinya hanya itu yang ingin\n"
    .string "aku tanyakan hari ini.\p"
    .string "Kita ketemu lagi di sini ya, oke?\n"
    .string "Makasih!$"

gText_ApprenticeWhichMove7::
    .string "Oh, halo, {PLAYER}.\n"
    .string "Kuharap kamu baik-baik saja?\p"
    .string "Aku harus meminta nasihatmu lagi.\n"
    .string "Ini tentang {STR_VAR_1}-ku tersayang.\p"
    .string "Apa jurus yang ideal untuk\n"
    .string "{STR_VAR_1}-ku yang menggemaskan?\l"
    .string "{STR_VAR_2} atau {STR_VAR_3}?$"

gText_ApprenticeMoveThanks7::
    .string "{STR_VAR_1} ya!\n"
    .string "Aku akan segera mengajarkannya!\p"
    .string "Terima kasih, {PLAYER}.\n"
    .string "Kuharap aku bisa mengandalkanmu lagi.\l"
    .string "Hati-hati ya!$"

gText_ApprenticeWhichMove8::
    .string "Iih! {PLAYER}! Aku bertemu denganmu lagi!\n"
    .string "A… Aku senang sekali!\p"
    .string "Setiap kali aku butuh, kamu selalu\n"
    .string "ada untukku, {PLAYER}!\p"
    .string "Hari ini, aku ingin kamu merekomendasikan\n"
    .string "sebuah jurus untukku!\p"
    .string "Tolong pilihkan jurus untuk\n"
    .string "{STR_VAR_1}-ku!\p"
    .string "Jurus mana yang lebih baik,\n"
    .string "{STR_VAR_2} atau {STR_VAR_3}?$"

gText_ApprenticeMoveThanks8::
    .string "Oh-oh-oh! Terima kasih!\n"
    .string "{STR_VAR_1} ya!\l"
    .string "Sangat dimengerti!\p"
    .string "Kuharap kamu mau mengajariku\n"
    .string "lagi lain kali.$"

gText_ApprenticeWhichMove9::
    .string "Hola, {PLAYER}{KUN}, bueno!\n"
    .string "Aku berharap lebih banyak lagi\l"
    .string "nasihat bijakmu hari ini!\p"
    .string "Apa jurus terbaik untuk\n"
    .string "{STR_VAR_1}-ku?\p"
    .string "Harus sesuatu yang akan\n"
    .string "membuatku menang begitu saja!\p"
    .string "Apakah itu {STR_VAR_2}?\n"
    .string "Atau {STR_VAR_3}?$"

gText_ApprenticeMoveThanks9::
    .string "Uh-huh, {STR_VAR_1} ya!\n"
    .string "Si, bueno!\l"
    .string "Aku akan mengajarkannya, sikat!\p"
    .string "Baiklah, terima kasih, seperti biasa!\n"
    .string "Adios!$"

gText_ApprenticeWhichMove10::
    .string "{PLAYER}{KUN}, ini benar-benar gila!\p"
    .string "POKéMON-ku!\n"
    .string "Ia mempelajari enam jurus!\p"
    .string "Tentu saja aku bohong!\n"
    .string "Wahahaha!\p"
    .string "Tapi ini bukan bohong.\n"
    .string "Aku tidak pandai memilih jurus\l"
    .string "untuk POKéMON-ku.\p"
    .string "Jadi, bagaimana kalau kamu putuskan untukku jenis\n"
    .string "jurus apa yang harus aku ajarkan?\p"
    .string "{STR_VAR_2} atau {STR_VAR_3}--mana yang\n"
    .string "paling cocok dengan {STR_VAR_1}-ku?$"

gText_ApprenticeMoveThanks10::
    .string "Oke, jadi {STR_VAR_1} yang kamu pilih?\n"
    .string "Kalau begitu, aku akan memilih jurus lain!\p"
    .string "Cuma bercanda!\n"
    .string "Aku akan menuruti ajaranmu, guru!\p"
    .string "Makasih, guru!\n"
    .string "Kuharap kamu akan terus mengajariku!$"

gText_ApprenticeWhichMove11::
    .string "A-H-O-Y!\n"
    .string "Dan itu dibaca ahoy!\p"
    .string "Akulah si PELAUT rapper!\n"
    .string "Aku selalu siap, jangan tanya kenapa.\p"
    .string "Hari ini, aku punya pertanyaan jurus\n"
    .string "yang butuh saranmu!\p"
    .string "{STR_VAR_2} dan {STR_VAR_3} adalah\n"
    .string "jurusnya. Apa yang terbaik\l"
    .string "untuk {STR_VAR_1}-ku agar ia hebat?$"

gText_ApprenticeMoveThanks11::
    .string "{STR_VAR_1}, katamu, hei, hei!\n"
    .string "Aku akan segera mengajarkannya!\p"
    .string "Kalau aku butuh nasihat,\n"
    .string "{PLAYER}, perkataanmu akan selalu kudengar!$"

gText_ApprenticeWhichMove12::
    .string "Oh, ya, kalau bukan {PLAYER}!\p"
    .string "Apa yang harus aku lakukan? Minta nasihatmu?\n"
    .string "Kenapa tidak? Aku sudah berbicara denganmu!\p"
    .string "{PLAYER}, apa kamu terkejut denganku?\n"
    .string "Aku ingin nasihatmu, tidak bisakah kamu lihat?\p"
    .string "Apa kamu mendengarku?\n"
    .string "Kamu mendengarku!\p"
    .string "{STR_VAR_1}-ku--apa yang harus ia gunakan?\n"
    .string "Antara {STR_VAR_2} atau {STR_VAR_3},\l"
    .string "apa yang kamu pilih?$"

gText_ApprenticeMoveThanks12::
    .string "Jika {STR_VAR_1} itu yang terbaik,\n"
    .string "Aku akan lakukan seperti saranmu!\p"
    .string "Yah, {PLAYER}, aku harus berkelana,\n"
    .string "tapi jangan lupakan aku.\p"
    .string "Sampai jumpa lagi, teman pintarku!$"

gText_ApprenticeWhichMove13::
    .string "Gahack! Gaah! Oh, {PLAYER}{KUN}…\n"
    .string "Aku sedang flu berat…\p"
    .string "Aku ingin memilih jurus untuk POKéMON-ku,\n"
    .string "tapi aku tidak sanggup…\p"
    .string "Jadi, karena keadaannya seperti ini,\n"
    .string "Aku butuh kamu untuk memutuskannya untukku.\p"
    .string "{PLAYER}{KUN}, jika aku harus memilih antara\n"
    .string "{STR_VAR_2} dan {STR_VAR_3} untuk\l"
    .string "{STR_VAR_1}-ku, mana yang seharusnya?$"

gText_ApprenticeMoveThanks13::
    .string "Hm, {STR_VAR_1}, baiklah. Uhuk!\n"
    .string "Aku akan mengajarkannya saat aku sembuh.\p"
    .string "Kuharap aku bisa terus meminta\n"
    .string "bantuanmu seperti ini.$"

gText_ApprenticeWhichMove14::
    .string "Er… Um…\n"
    .string "{PLAYER}{KUN}…?\p"
    .string "Tolong, jangan menatapku seperti itu.\n"
    .string "Aku jadi bingung…\l"
    .string "A… Aku butuh nasihatmu.\p"
    .string "A… Aku sangat malu, tapi aku tidak bisa\n"
    .string "memutuskan jurus apa yang harus aku ajarkan\l"
    .string "ke POKéMON-ku.\p"
    .string "Ini untuk {STR_VAR_1}-ku.\n"
    .string "Jika pilihannya {STR_VAR_2} atau\l"
    .string "{STR_VAR_3}, mana yang lebih baik?$"

gText_ApprenticeMoveThanks14::
    .string "Oh… Oke!\n"
    .string "Aku akan mencoba {STR_VAR_1} itu.\p"
    .string "Kuharap aku bisa mengajarkan jurus itu…\n"
    .string "Ini sangat menegangkan…\p"
    .string "Terima kasih, {PLAYER}{KUN}.\n"
    .string "Jika kita bertemu lagi, kuharap kamu akan\l"
    .string "sama membantunya.$"

gText_ApprenticeWhichMove15::
    .string "Hm? Kamu tampak seperti {PLAYER}{KUN}…\n"
    .string "Tapi apakah kamu benar-benar nyata?\p"
    .string "Mungkin kamu salah satu peniru\n"
    .string "yang populer?\p"
    .string "Tidak, tidak, jika kamu nyata, tidak apa-apa.\n"
    .string "Tidak perlu marah, aku jamin!\p"
    .string "Kebetulan, aku ingin mendapatkan\n"
    .string "nasihatmu.\p"
    .string "Ini tentang {STR_VAR_1}-ku.\p"
    .string "Jurus mana yang lebih baik untuk digunakannya,\n"
    .string "{STR_VAR_2} atau {STR_VAR_3}?$"

gText_ApprenticeMoveThanks15::
    .string "{STR_VAR_1}?\n"
    .string "Tidak ada keraguan tentang itu?\p"
    .string "Begitu. Jika begitu, tidak apa-apa.\n"
    .string "Aku berterima kasih atas waktumu.\p"
    .string "Aku harap itu sesuatu yang bahkan\n"
    .string "POKéMON-ku bisa pelajari.\p"
    .string "Mari bertemu lagi!$"

gText_ApprenticePickWinSpeech0::
    .string "Oh… {PLAYER}?\n"
    .string "Itu {PLAYER}!\l"
    .string "Oh! Hiks…sob… Tolong, dengarkan!\p"
    .string "Aku… Saat aku bertarung, aku sangat gugup,\n"
    .string "Aku tidak bisa menahan tangis bahkan jika aku menang…\p"
    .string "Aku berharap bisa mengatakan sesuatu yang keren\n"
    .string "saat aku menang…\p"
    .string "Tolong, tolong, {PLAYER}!\n"
    .string "Bisakah kamu mengajarkanku sesuatu\l"
    .string "yang keren untuk dikatakan saat aku menang agar aku tidak menangis?$"

gText_ApprenticeWinSpeechThanks0::
    .string "{STR_VAR_1}\p"
    .string "Luar biasa! Keren! Awoooh!\n"
    .string "Itu sangat keren!\p"
    .string "Oh… Maafkan aku…\n"
    .string "Aku sangat senang, aku menangis…\p"
    .string "Hiks… {PLAYER}!\n"
    .string "Terima kasih banyak untuk semuanya!\p"
    .string "Aku akan bertarung sebaik mungkin untuk\n"
    .string "demimu, {PLAYER}!\p"
    .string "{PLAYER}…\n"
    .string "Lain kali… Kita harus bertarung!$"

gText_ApprenticePickWinSpeech1::
    .string "Yay! Itu {PLAYER}! Halo!\n"
    .string "Aku ingin menanyakan sesuatu!\p"
    .string "Aku ingin mengatakan sesuatu yang keren saat\n"
    .string "aku memenangkan pertandingan.\p"
    .string "Apa kamu punya ucapan keren yang\n"
    .string "bisa kamu rekomendasikan?$"

gText_ApprenticeWinSpeechThanks1::
    .string "{STR_VAR_1}\p"
    .string "Oh, wow! Itu sangat keren!\n"
    .string "Oke, aku akan mengatakan itu!\p"
    .string "Terima kasih sudah mengajariku selama ini!\n"
    .string "Aku akan melakukan yang terbaik\l"
    .string "ke mana pun aku pergi mulai sekarang!\p"
    .string "Saat kita bertemu lagi, itu akan menjadi\n"
    .string "sebuah pertarungan!$"

gText_ApprenticePickWinSpeech2::
    .string "{PLAYER}, halo!\p"
    .string "POKéMON-ku dan aku siap untuk\n"
    .string "apa pun, kecuali satu hal.\p"
    .string "Menurutku akan bagus jika aku punya\n"
    .string "sesuatu untuk diteriakkan saat aku menang.\p"
    .string "Bisakah kamu memikirkan sesuatu yang bagus\n"
    .string "untuk dikatakan?$"

gText_ApprenticeWinSpeechThanks2::
    .string "{STR_VAR_1}\p"
    .string "…Keren!\n"
    .string "Aku akan menggunakan itu!\p"
    .string "Aku akan pergi bertarung di mana-mana.\p"
    .string "Siapa tahu, aku bahkan bisa bertarung\n"
    .string "denganmu suatu hari nanti, {PLAYER}.\p"
    .string "Lain kali, mari bertemu di tempat\n"
    .string "pertarungan!$"

gText_ApprenticePickWinSpeech3::
    .string "Halo, {PLAYER}…\n"
    .string "Maaf mengganggumu, tapi aku putus asa…\p"
    .string "Bahkan saat…\n"
    .string "Bahkan saat aku menang, aku tidak punya sesuatu\l"
    .string "yang spesial untuk dikatakan…\p"
    .string "Aku tahu itu tidak berarti apa-apa\n"
    .string "bagimu, {PLAYER}.\p"
    .string "Tapi itu sangat berarti bagiku…\p"
    .string "Tolong, {PLAYER}, apa yang harus aku katakan\n"
    .string "jika aku memenangkan pertarungan?$"

gText_ApprenticeWinSpeechThanks3::
    .string "{STR_VAR_1}\p"
    .string "Itu menginspirasi…\p"
    .string "Uh… Apakah boleh orang sepertiku\n"
    .string "bahkan mengatakan itu?\p"
    .string "Tidak! Aku akan berusaha!\p"
    .string "{PLAYER}, terima kasih banyak telah\n"
    .string "bersabar denganku begitu lama…\p"
    .string "Aku berjanji akan melakukan yang terbaik mulai sekarang.\p"
    .string "Aku yakin kamu akan cepat lupa tentang\n"
    .string "orang sepertiku, tapi mari kita bertemu\l"
    .string "di suatu tempat lagi!$"

gText_ApprenticePickWinSpeech4::
    .string "Oh, {PLAYER}{KUN}.\n"
    .string "Ada sesuatu yang ingin aku sampaikan.\p"
    .string "Aku tahu aku tidak selalu terdengar\n"
    .string "baik atau sopan…\p"
    .string "Saat aku memenangkan pertarungan, kurasa aku terlihat\n"
    .string "sombong.\p"
    .string "Aku tidak ingin orang tidak menyukaiku,\n"
    .string "jadi aku ingin mengatakan sesuatu yang baik kepada\l"
    .string "seseorang yang aku kalahkan.\p"
    .string "Tapi aku tidak bisa memikirkan apa pun yang bagus!\n"
    .string "Bisakah kamu memikirkannya untukku?$"

gText_ApprenticeWinSpeechThanks4::
    .string "{STR_VAR_1}\p"
    .string "Tidak buruk!\n"
    .string "Ya, itu yang akan aku gunakan!\p"
    .string "Aku akan pergi dan melakukan apa\n"
    .string "yang aku bisa dengan apa yang kamu ajarkan di\l"
    .string "kepala dan hatiku.\p"
    .string "Maaf aku sudah terlalu memaksa\n"
    .string "padamu!\p"
    .string "Lain kali, kita bertarung, oke?\n"
    .string "Sampai jumpa!$"

gText_ApprenticePickWinSpeech5::
    .string "Oh, aku tidak tahan betapa sibuknya aku!\n"
    .string "Oh, hei, aku sedang mencarimu, {PLAYER}{KUN}.\p"
    .string "Apa kamu baik-baik saja seperti biasa?\n"
    .string "Tidak ada yang berubah bagiku sama sekali.\p"
    .string "Aku harus berlari, bertarung, dan memetakan\n"
    .string "sesuatu. Kenapa aku begitu sibuk?\p"
    .string "Tapi meskipun aku sibuk, tidak sopan\n"
    .string "jika aku langsung pergi setelah\l"
    .string "menang tanpa mengatakan sepatah kata pun.\p"
    .string "Jadi, apa ucapan keren untuk\n"
    .string "menegaskan kekerenanku saat aku selesai\l"
    .string "dan pergi? {PLAYER}{KUN}, bantu aku!$"

gText_ApprenticeWinSpeechThanks5::
    .string "{STR_VAR_1}\p"
    .string "Oke, mengerti.\n"
    .string "Aku bisa meluangkan waktu untuk mengatakan itu!\p"
    .string "Jujur, aku senang bertemu mentor yang baik\n"
    .string "sepertimu.\p"
    .string "Aku akan meluangkan waktu agar\n"
    .string "aku bisa mulai bertarung.\p"
    .string "Terima kasih untuk semuanya, {PLAYER}{KUN}!\n"
    .string "Kita harus bertarung, kamu dan aku, suatu hari nanti!$"

gText_ApprenticePickWinSpeech6::
    .string "Aku beruntung lagi!\n"
    .string "{PLAYER}! Aku senang melihatmu!\l"
    .string "Seperti biasa, aku butuh nasihatmu!\p"
    .string "Jeng jeng jeng!\n"
    .string "Pertanyaan terakhirku adalah…\p"
    .string "Jika aku memenangkan pertarungan dan ingin mengakhirinya\n"
    .string "dengan gaya keren, apa yang\l"
    .string "harus aku katakan?$"

gText_ApprenticeWinSpeechThanks6::
    .string "{STR_VAR_1}\p"
    .string "Itu… Itu luar biasa!\n"
    .string "Itu berwibawa dan keren! Aku akan memakainya!\p"
    .string "…Dengar, kurasa aku mulai mahir\n"
    .string "dalam hal ini, ya?\p"
    .string "Jadi, aku berpikir untuk menantang\n"
    .string "TRAINER lain mulai sekarang.\p"
    .string "{PLAYER}, nasihatmu sangat membantuku.\p"
    .string "Mungkin suatu hari nanti, akan ada saatnya\n"
    .string "kita bertarung!\p"
    .string "Terima kasih untuk semuanya!$"

gText_ApprenticePickWinSpeech7::
    .string "Oh, {PLAYER}.\n"
    .string "Aku sangat senang bertemu denganmu!\p"
    .string "Aku tidak lagi punya kekhawatiran\n"
    .string "mengenai POKéMON-ku.\p"
    .string "Diriku sendirilah yang mengkhawatirkanku…\p"
    .string "Apa kamu tahu bagaimana seorang TRAINER mengatakan\n"
    .string "beberapa hal setelah memenangkan pertarungan?\p"
    .string "Tentu saja, aku berharap bisa melakukannya\n"
    .string "juga!\p"
    .string "Tolong, apa yang harus aku katakan saat\n"
    .string "aku memenangkan pertarungan?$"

gText_ApprenticeWinSpeechThanks7::
    .string "{STR_VAR_1}\p"
    .string "Ah! Ucapan itu! Itu menyegarkanku\n"
    .string "dan membuatku merasa terlahir kembali!\p"
    .string "Aku harus segera menggunakannya!\p"
    .string "Dan sekarang, aku harus pergi,\n"
    .string "{PLAYER}…\p"
    .string "Aku akan pergi bertarung dengan banyak orang,\n"
    .string "tapi aku tidak akan pernah melupakan ajaranmu.\p"
    .string "Mungkin suatu hari nanti…\n"
    .string "Selamat tinggal!$"

gText_ApprenticePickWinSpeech8::
    .string "Iih! Aku melihat {PLAYER}!\n"
    .string "A… Aku senang sekali melihatmu!\p"
    .string "Oh-oh-oh! Ada sesuatu yang harus\n"
    .string "aku tanyakan padamu!\p"
    .string "Beberapa waktu lalu, aku memenangkan pertarungan.\n"
    .string "Bagian itu membuatku pusing!\p"
    .string "Tapi itu membuatku sangat senang sampai\n"
    .string "aku tercekat dan tidak bisa berkata apa-apa!\p"
    .string "Jadi sekarang, {PLAYER}, tolong, aku ingin kamu\n"
    .string "memikirkan kalimat penutup saat aku menang!$"

gText_ApprenticeWinSpeechThanks8::
    .string "{STR_VAR_1}\p"
    .string "Waaaaah!\n"
    .string "Aku akan mengatakan itu?!\l"
    .string "A… Aku sangat gembira!\p"
    .string "Te-te-terima kasih!\n"
    .string "Aku tidak punya penyesalan lagi sekarang!\p"
    .string "Aku akan bepergian sekarang dan bertarung\n"
    .string "dengan berbagai macam orang.\p"
    .string "Semuanya, aku berutang padamu, {PLAYER}.\n"
    .string "Sungguh, sungguh, terima kasih!\p"
    .string "Aku harus pergi sekarang, tapi mari kita bertemu\n"
    .string "dalam pertarungan suatu hari nanti!$"

gText_ApprenticePickWinSpeech9::
    .string "Hola, bueno!\n"
    .string "{PLAYER}{KUN}!\p"
    .string "Kamu tahu, aku mulai ingin berkelana\n"
    .string "dan bertarung di mana pun aku bisa.\p"
    .string "Tapi sebelum itu, aku ingin nasihatmu\n"
    .string "sekali lagi, tolong!\p"
    .string "Jika aku memenangkan pertarungan, apa sesumbar\n"
    .string "yang bagus yang bisa aku katakan kepada\l"
    .string "lawan TRAINER-ku yang kalah?$"

gText_ApprenticeWinSpeechThanks9::
    .string "{STR_VAR_1}\p"
    .string "Uh-huh, itu manis!\n"
    .string "Si, bueno!\l"
    .string "Aku akan coba mengatakannya, sikat!\p"
    .string "Dan sekarang, saatnya mengucapkan selamat tinggal!\n"
    .string "Terima kasih untuk berbagai hal!\p"
    .string "Lawan aku suatu hari nanti, oke?\n"
    .string "Adios!$"

gText_ApprenticePickWinSpeech10::
    .string "{PLAYER}{KUN}, ada masalah besar!\p"
    .string "Saat aku memenangkan pertarungan, aku menyombongkannya\n"
    .string "setidaknya selama satu jam!\p"
    .string "Tentu saja aku bohong!\n"
    .string "Wahahaha!\p"
    .string "Tapi ini bukan bohong.\n"
    .string "Aku tidak pandai mengobrol.\p"
    .string "Jadi, bagaimana kalau kamu putuskan untukku apa\n"
    .string "yang harus aku katakan setelah memenangkan pertarungan,\l"
    .string "guru?$"

gText_ApprenticeWinSpeechThanks10::
    .string "{STR_VAR_1}\p"
    .string "Itu yang harus aku katakan, ya?\n"
    .string "Kalau begitu, aku akan menghindarinya!\p"
    .string "Cuma bercanda!\n"
    .string "Aku akan menuruti ajaranmu, guru!\p"
    .string "Terima kasih sudah mengajariku selama ini,\n"
    .string "guru!\p"
    .string "Aku akhirnya mengerti tentang menjadi\n"
    .string "seorang TRAINER.\p"
    .string "Aku akan pergi dan memenangkan pertarungan\n"
    .string "melawan TRAINER mana pun.\p"
    .string "Mungkin itu kamu suatu hari nanti, guru!\p"
    .string "Itu saja!\n"
    .string "Selamat tinggal, guruku!$"

gText_ApprenticePickWinSpeech11::
    .string "A-H-O-Y!\n"
    .string "Dan itu dibaca ahoy!\p"
    .string "Akulah si PELAUT rapper!\n"
    .string "Ini akan menjadi pertanyaan terakhirku,\l"
    .string "jangan kamu menangis!\p"
    .string "Ini pertanyaan ucapan\n"
    .string "yang butuh saranmu!\p"
    .string "Jika aku memenangkan pertandingan, apa yang bisa aku katakan\n"
    .string "dengan cara yang sangat keren?$"

gText_ApprenticeWinSpeechThanks11::
    .string "{STR_VAR_1}\p"
    .string "Sempurna! Itu yang akan aku gunakan.\n"
    .string "Aku benar telah membuatmu memilih!\p"
    .string "Dan sekarang, kurasa yang terbaik,\n"
    .string "adalah jika aku terbang dari sarang!\p"
    .string "Terima kasih atas semua yang kamu ajarkan.\n"
    .string "Aku akan pergi bertarung!\p"
    .string "S-E-L-A-M-A-T J-A-L-A-N!\n"
    .string "Dan itu dibaca selamat jalan,\l"
    .string "untukmu ini penghormatanku!$"

gText_ApprenticePickWinSpeech12::
    .string "Oh, ya, {PLAYER}!\n"
    .string "Aku menemukanmu lagi hari ini!\p"
    .string "Apa yang harus aku lakukan? Bertanya lagi padamu?\n"
    .string "Kenapa tidak? Aku sudah bertanya padamu!\p"
    .string "Ngomong-ngomong, {PLAYER}…\n"
    .string "Apa kamu mendengarku?\l"
    .string "Kamu mendengarku!\l"
    .string "Aku butuh lebih banyak nasihat untukku!\p"
    .string "Ini tentang apa yang harus aku teriakkan.\n"
    .string "Sesuatu yang keren untuk diteriakkan saat\l"
    .string "pertarungan berakhir dengan baik.\p"
    .string "Ayolah, aku ingin mendengarmu mengatakannya!$"

gText_ApprenticeWinSpeechThanks12::
    .string "{STR_VAR_1}\p"
    .string "Baiklah, baiklah!\n"
    .string "Aku akan menggunakan itu karena sangat keren!\p"
    .string "Aku kehabisan hal untuk ditanyakan padamu.\n"
    .string "Melambaikan tangan adalah satu-satunya yang tersisa.\p"
    .string "Tapi mungkin suatu hari kita akan bertemu, dengan satu\n"
    .string "takdir untuk dikalahkan.\p"
    .string "Tapi, ini benar-benar waktunya untuk mengucapkan selamat tinggal.\p"
    .string "Yah, {PLAYER}, aku harus berkelana,\n"
    .string "tapi jangan lupakan aku!\p"
    .string "Hati-hati, {PLAYER}!\n"
    .string "Sayang kamu!$"

gText_ApprenticePickWinSpeech13::
    .string "{PLAYER}{KUN}, aku selesai…\n"
    .string "Hidungku tidak berhenti meler…\p"
    .string "Aku sedang mencoba memikirkan sesuatu\n"
    .string "yang keren untuk dikatakan saat aku memenangkan pertarungan.\p"
    .string "Itu sangat menginspirasiku, membuatku menangis,\n"
    .string "dan sekarang hidungku tidak berhenti meler…\p"
    .string "Jadi, karena keadaannya seperti ini,\n"
    .string "Aku butuh kamu untuk memutuskannya untukku, {PLAYER}{KUN}.\p"
    .string "Saat aku memenangkan pertarungan,\n"
    .string "apa yang harus aku katakan?$"

gText_ApprenticeWinSpeechThanks13::
    .string "{STR_VAR_1}\p"
    .string "… … …Itu bagus.\n"
    .string "Tidak, itu sangat menginspirasi!\l"
    .string "Itu membuat air mata baru di mataku!\p"
    .string "Tapi meskipun air mata dan hidungku\n"
    .string "meler, aku akan menggunakan ucapan itu!\p"
    .string "Aku kehabisan hal untuk ditanyakan padamu,\n"
    .string "{PLAYER}{KUN}.\p"
    .string "Mulai sekarang, kita saingan!\n"
    .string "Terima kasih untuk semuanya!$"

gText_ApprenticePickWinSpeech14::
    .string "Er… Um…\n"
    .string "{PLAYER}{KUN}…\p"
    .string "Tolong, jangan menatapku seperti itu.\n"
    .string "Kamu membuatku jadi gugup.\p"
    .string "A… Aku butuh nasihatmu lagi.\n"
    .string "Tapi ini akan menjadi yang terakhir…\p"
    .string "Sangat memalukan untuk bertanya,\n"
    .string "tapi bagaimana jika aku memenangkan pertarungan?\l"
    .string "Apa yang harus aku katakan?$"

gText_ApprenticeWinSpeechThanks14::
    .string "{STR_VAR_1}\p"
    .string "Oh… Oke!\n"
    .string "Aku akan mencoba mengatakan itu!\l"
    .string "Aku mungkin terlalu gugup untuk mengatakannya…\p"
    .string "Terima kasih, {PLAYER}{KUN}.\n"
    .string "Aku harus mengucapkan selamat tinggal sekarang.\p"
    .string "Aku akan menuruti semua yang telah kamu ajarkan,\n"
    .string "{PLAYER}{KUN}, dan melakukan yang terbaik.$"

gText_ApprenticePickWinSpeech15::
    .string "Hm? Kamu tampak seperti {PLAYER}{KUN}…\n"
    .string "Tapi apakah kamu benar-benar?\l"
    .string "Mungkin BONEKA {PLAYER} yang pintar?\p"
    .string "Oh, tidak, tidak, tidak, jangan khawatir!\n"
    .string "Jika kamu benar-benar nyata, tolong\l"
    .string "lupakan kekasaranku.\p"
    .string "Tidak perlu begitu marah. Yang aku inginkan hanyalah\n"
    .string "lebih banyak nasihat baikmu.\p"
    .string "Ini menyangkut sebuah ucapan.\p"
    .string "Lebih tepatnya, apa yang harus aku katakan\n"
    .string "jika aku memenangkan pertarungan?$"

gText_ApprenticeWinSpeechThanks15::
    .string "{STR_VAR_1}\p"
    .string "… … … … … …\n"
    .string "Saat aku memenangkan pertandingan…\p"
    .string "{STR_VAR_1}\p"
    .string "…Apa kamu serius?\p"
    .string "Begitu. Jika kamu serius, tidak apa-apa.\n"
    .string "Aku berterima kasih atas waktumu.\p"
    .string "Aku harap bahkan aku akan bisa\n"
    .string "menggunakan ucapan itu dengan baik.\p"
    .string "Sepertinya aku sudah kehabisan nasihat\n"
    .string "yang aku butuhkan.\p"
    .string "Aku percaya ini saatnya aku mengucapkan\n"
    .string "selamat tinggal dan memulai sendiri.\p"
    .string "Terima kasih, mentorku!\n"
    .string "Aku minta maaf atas skeptisismeku!$"
