FallarborTown_BattleTentLobby_Text_WelcomeToBattleTent:
.string "Selamat datang di TENDA PERTARUNGAN\n"
.string "SITUS FALLARBOR!\p"
.string "Akulah pemandumu untuk Turnamen Set KO!$"

FallarborTown_BattleTentLobby_Text_TakeChallenge:
.string "Nah, apa kamu ingin menerima tantangan\n"
.string "Turnamen Set KO?$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge:
.string "Kami menantikan tantanganmu di\n"
.string "kesempatan lain!$"

FallarborTown_BattleTentLobby_Text_ExplainFallarborTent:
.string "Di TENDA PERTARUNGAN FALLARBOR,\n"
.string "kita akan mengikuti Turnamen Set KO.\p"
.string "Semua peserta masuk dengan tim berisi\n"
.string "tiga POKéMON.\p"
.string "Ketiga POKéMON harus diatur sesuai\n"
.string "urutan kemunculannya.\p"
.string "Selama pertarungan, POKéMON akan muncul\n"
.string "satu per satu sesuai urutan yang ditentukan.\p"
.string "Sekali POKéMON masuk ke pertarungan, ia harus\n"
.string "tetap di sana sampai pertandingan selesai.\p"
.string "Jika pertandingan belum selesai dalam\n"
.string "tiga giliran, akan ada penilaian.\p"
.string "Jika kamu ingin menghentikan tantanganmu,\n"
.string "silakan simpan permainan.\p"
.string "Jika tidak disimpan, kamu tidak akan bisa\n"
.string "melanjutkan tantanganmu.\p"
.string "Jika kamu berhasil mengalahkan\n"
.string "tiga TRAINER berturut-turut,\l"
.string "kami akan memberimu hadiah menarik.$"

FallarborTown_BattleTentLobby_Text_SaveBeforeChallenge:
.string "Sebelum membawamu ke TENDA PERTARUNGAN,\n"
.string "aku harus menyimpan. Boleh?$"

@ Unused
FallarborTown_BattleTentLobby_Text_WhichLevelMode:
.string "Kami menawarkan dua level tantangan,\n"
.string "Level 50 dan Open Level.\l"
.string "Mana pilihanmu?$"

FallarborTown_BattleTentLobby_Text_SelectThreeMons:
.string "Baiklah, sekarang pilih\n"
.string "tiga POKéMON-mu, silakan.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
.string "Wahai penantang!\p"
.string "Kamu tidak punya tiga POKéMON\n"
.string "yang diperlukan untuk masuk.\p"
.string "Mereka juga tidak boleh memegang\n"
.string "item yang sama.\p"
.string "EGG{STR_VAR_1} tidak memenuhi syarat.\p"
.string "Jika sudah siap,\n"
.string "silakan kembali.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
.string "Wahai penantang!\p"
.string "Kamu tidak punya tiga POKéMON\n"
.string "yang diperlukan untuk masuk.\p"
.string "Untuk lolos, kamu harus membawa tiga\n"
.string "jenis POKéMON yang berbeda.\p"
.string "Mereka juga tidak boleh memegang\n"
.string "item yang sama.\p"
.string "EGG{STR_VAR_1} tidak memenuhi syarat.\p"
.string "Jika sudah siap,\n"
.string "silakan kembali.$"

FallarborTown_BattleTentLobby_Text_GuideYouToBattleTent:
.string "Sekarang akan kubimbing kamu ke\n"
.string "TENDA PERTARUNGAN.$"

FallarborTown_BattleTentLobby_Text_DidntSaveBeforeQuitting:
.string "Wahai penantang!\p"
.string "Kamu tidak menyimpan permainan sebelum\n"
.string "mematikannya, kan?\p"
.string "Sayang sekali, tapi itu membuatmu\n"
.string "didiskualifikasi dari tantanganmu.\p"
.string "Tentu saja, kamu boleh memulai\n"
.string "tantangan baru.$"

FallarborTown_BattleTentLobby_Text_BeatThreeTrainers:
.string "Luar biasa! Kamu telah mengalahkan\n"
.string "tiga TRAINER berturut-turut!$"

FallarborTown_BattleTentLobby_Text_WaitWhileSaveGame:
.string "Tunggu sebentar selagi aku menyimpan permainan.$"

FallarborTown_BattleTentLobby_Text_PresentYouWithPrize:
.string "Untuk merayakan 3 kemenangan beruntunmu,\n"
.string "kami berikan hadiah ini.$"

FallarborTown_BattleTentLobby_Text_ReceivedPrize:
.string "Hadiah {STR_VAR_1} didapatkan.$"

FallarborTown_BattleTentLobby_Text_BagFullReturnForPrize:
.string "Oh?\n"
.string "BAG-mu sepertinya penuh.\p"
.string "Tolong kosongkan ruang dan\n"
.string "kembali lagi untuk mengambil hadiahmu.$"

FallarborTown_BattleTentLobby_Text_ThankYouWaitWhileSaving:
.string "Terima kasih banyak telah berpartisipasi!\p"
.string "Tunggu sebentar selagi aku menyimpan permainan.$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge2:
.string "Kami menantikan tantanganmu di\n"
.string "kesempatan lain!$"

FallarborTown_BattleTentLobby_Text_LookingForwardToArrival:
.string "Kami sudah menantikan\n"
.string "kedatanganmu.\p"
.string "Sebelum aku membawamu ke TENDA PERTARUNGAN,\n"
.string "aku harus menyimpan permainan. Mohon tunggu.$"

VerdanturfTown_BattleTentLobby_Text_WelcomeToBattleTent:
.string "Selamat datang di TENDA PERTARUNGAN\n"
.string "SITUS VERDANTURF!\p"
.string "Di sini, kepercayaan TRAINER terhadap\n"
.string "POKéMON diuji.$"

VerdanturfTown_BattleTentLobby_Text_TakeChallenge:
.string "Apa kamu ingin menerima tantangan\n"
.string "TENDA PERTARUNGAN VERDANTURF?$"

VerdanturfTown_BattleTentLobby_Text_ExplainVerdanturfTent:
.string "Di TENDA PERTARUNGAN VERDANTURF,\n"
.string "ada satu aturan penting yang harus\l"
.string "ditaati.\p"
.string "TRAINER hanya diizinkan untuk menukar\n"
.string "POKéMON mereka masuk dan keluar.\p"
.string "Selain itu, TRAINER dilarang\n"
.string "memerintah POKéMON mereka.\p"
.string "POKéMON harus bertindak sesuai\n"
.string "sifatnya dan bertarung sendiri.\p"
.string "Kamu harus percaya pada POKéMON-mu\n"
.string "dan mengawasi mereka.\p"
.string "Jika kamu berhasil mengalahkan\n"
.string "tiga TRAINER berturut-turut,\l"
.string "kami akan memberimu hadiah.\p"
.string "Jika kamu ingin menghentikan\n"
.string "tantanganmu, silakan simpan permainan.\p"
.string "Jika tidak disimpan sebelum berhenti,\n"
.string "kamu akan didiskualifikasi.$"

VerdanturfTown_BattleTentLobby_Text_ReturnFortified:
.string "Saat hatimu dan POKéMON-mu sudah\n"
.string "lebih kuat, kamu harus kembali.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_WhichLevelMode:
.string "Ada dua tingkat kesulitan,\n"
.string "Level 50 dan Open Level.\l"
.string "Tantangan mana yang kamu pilih?$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
.string "Hhh…\p"
.string "Kamu tidak punya tiga POKéMON\n"
.string "yang dibutuhkan untuk tantangan ini.\p"
.string "Untuk masuk, kamu harus menyediakan tiga\n"
.string "jenis POKéMON yang berbeda.\p"
.string "Mereka juga tidak boleh memegang\n"
.string "item yang sama.\p"
.string "EGG{STR_VAR_1} tidak memenuhi syarat.\p"
.string "Kembalilah setelah kamu\n"
.string "bersiap-siap.$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
.string "Hhh…\p"
.string "Kamu tidak punya tiga POKéMON\n"
.string "yang dibutuhkan untuk tantangan ini.\p"
.string "Untuk masuk, kamu harus menyediakan tiga\n"
.string "jenis POKéMON yang berbeda.\p"
.string "Mereka juga tidak boleh memegang\n"
.string "item yang sama.\p"
.string "EGG{STR_VAR_1} tidak memenuhi syarat.\p"
.string "Kembalilah setelah kamu\n"
.string "bersiap-siap.$"

VerdanturfTown_BattleTentLobby_Text_SelectThreeMons:
.string "Bagus. Sekarang, kamu harus memilih\n"
.string "tiga POKéMON-mu.$"

VerdanturfTown_BattleTentLobby_Text_SaveBeforeChallenge:
.string "Aku harus menyimpan sebelum membawamu ke\n"
.string "TENDA PERTARUNGAN. Boleh?$"

VerdanturfTown_BattleTentLobby_Text_NowFollowMe:
.string "Bagus.\n"
.string "Sekarang, ikuti aku.$"

VerdanturfTown_BattleTentLobby_Text_ResultsWillBeRecorded:
.string "Aku merasa terhormat telah melihat\n"
.string "kehebatan POKéMON-mu.\p"
.string "Hasilnya akan dicatat.\n"
.string "Aku minta kamu menunggu sebentar.$"

VerdanturfTown_BattleTentLobby_Text_AchievedThreeWinStreak:
.string "Mencapai 3 kemenangan beruntun…\p"
.string "Ikatan yang mengikat hatimu dengan\n"
.string "POKéMON-mu tampaknya kuat dan sejati.$"

VerdanturfTown_BattleTentLobby_Text_FeatWillBeRecorded:
.string "Prestasimu akan dicatat.\n"
.string "Aku minta kamu menunggu sebentar.$"

VerdanturfTown_BattleTentLobby_Text_PresentYouWithPrize:
.string "Atas prestasi 3 kemenangan beruntunmu,\n"
.string "kami berikan hadiah ini.$"

SlateportCity_BattleTentLobby_Text_WelcomeToBattleTent:
.string "Selamat datang di TENDA PERTARUNGAN\n"
.string "SITUS SLATEPORT!\p"
.string "Akulah pemandumu untuk Turnamen\n"
.string "Battle Swap.$"

SlateportCity_BattleTentLobby_Text_TakeChallenge:
.string "Apa kamu mau menerima tantangan\n"
.string "Battle Swap?$"

SlateportCity_BattleTentLobby_Text_ExplainSlateportTent:
.string "Di TENDA PERTARUNGAN SLATEPORT,\n"
.string "kami mengadakan acara Battle Swap\l"
.string "menggunakan POKéMON sewaan.\p"
.string "Pertama, kamu akan dipinjami tiga\n"
.string "POKéMON khusus untuk acara ini.\p"
.string "Dengan POKéMON sewaan yang diberikan,\n"
.string "kamu harus melakukan SINGLE BATTLE.\p"
.string "Jika menang, kamu diizinkan menukar\n"
.string "satu POKéMON sewaanmu.\p"
.string "Ulangi siklus bertarung dan\n"
.string "bertukar ini--jika kamu menang tiga kali\l"
.string "berturut-turut, kamu akan mendapatkan hadiah menarik.\p"
.string "Jika kamu ingin menghentikan\n"
.string "tantanganmu, silakan simpan permainan.\p"
.string "Jika tidak disimpan sebelum berhenti,\n"
.string "kamu akan didiskualifikasi.$"

SlateportCity_BattleTentLobby_Text_LookForwardToNextVisit:
.string "Kami menantikan kunjunganmu berikutnya.$"

@ Unused
SlateportCity_BattleTentLobby_Text_WhichLevelMode:
.string "Level mana yang ingin kamu tantang?\n"
.string "Level 50 atau Level 100?$"

SlateportCity_BattleTentLobby_Text_SaveBeforeChallenge:
.string "Sebelum kamu memulai tantanganmu,\n"
.string "aku perlu menyimpan data. Boleh?$"

@ Unused
SlateportCity_BattleTentLobby_Text_HoldMonsForSafekeeping:
.string "Oke, aku akan menyimpan POKéMON-mu\n"
.string "selama kamu bertanding.$"

SlateportCity_BattleTentLobby_Text_StepThisWay:
.string "Silakan lewat sini.$"

SlateportCity_BattleTentLobby_Text_ReturnRentalMonsSaveResults:
.string "Terima kasih telah berpartisipasi!\p"
.string "Akan kukembalikan POKéMON-mu sebagai ganti\n"
.string "POKéMON sewaan kami.\p"
.string "Aku juga harus menyimpan hasil acaramu.\n"
.string "Mohon tunggu.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnMonsExchangeRentals:
.string "Akan kukembalikan POKéMON-mu sebagai ganti\n"
.string "POKéMON sewaan kami.$"

SlateportCity_BattleTentLobby_Text_WonThreeMatchesReturnMons:
.string "Selamat!\n"
.string "Kamu telah memenangkan tiga pertandingan beruntun!\p"
.string "Akan kukembalikan POKéMON-mu sebagai ganti\n"
.string "POKéMON sewaan kami.\p"
.string "Aku juga harus menyimpan hasil acaramu.\n"
.string "Mohon tunggu.$"

SlateportCity_BattleTentLobby_Text_AwardYouThisPrize:
.string "Sebagai pengakuan atas 3 kemenangan beruntunmu,\n"
.string "kami berikan hadiah ini.$"

SlateportCity_BattleTentLobby_Text_NoRoomInBagMakeRoom:
.string "Oh?\n"
.string "Sepertinya tidak ada ruang untuk ini.\p"
.string "Tolong kosongkan ruang di BAG-mu dan\n"
.string "beri tahu aku.$"

SlateportCity_BattleTentLobby_Text_BeenWaitingForYou:
.string "Kami sudah menunggumu!\p"
.string "Sebelum kita melanjutkan tantanganmu,\n"
.string "aku harus menyimpan permainan.$"

SlateportCity_BattleTentLobby_Text_DidntSaveBeforeQuitting:
.string "Maaf harus mengatakan ini, tapi kamu tidak\n"
.string "menyimpan sebelum berhenti bermain terakhir kali.\p"
.string "Akibatnya, kamu telah didiskualifikasi\n"
.string "dari tantanganmu.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnPersonalMons:
.string "Kami akan kembalikan POKéMON pribadimu.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReceivedPrize:
.string "Hadiah {STR_VAR_1} didapatkan.$"

@ Unused
SlateportCity_BattleTentLobby_Text_RulesAreListed:
.string "Aturan Battle Swap tercantum.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReadWhichHeading:
.string "Judul mana yang ingin kamu baca?$"

SlateportCity_BattleTentLobby_Text_ExplainBasicRules:
.string "Dalam acara Battle Swap, kamu hanya boleh menggunakan\n"
.string "tiga POKéMON.\p"
.string "Baik saat menyewa atau bertukar,\n"
.string "timmu tidak boleh memiliki dua atau lebih\l"
.string "POKéMON yang sama.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapPartnerRules:
.string "Kamu hanya boleh bertukar POKéMON dengan\n"
.string "TRAINER yang baru saja kamu kalahkan.\p"
.string "Kamu hanya boleh bertukar dengan POKéMON\n"
.string "yang digunakan oleh TRAINER yang kalah itu.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNumberRules:
.string "Setelah setiap pertarungan yang kamu menangkan, kamu boleh\n"
.string "bertukar dengan satu POKéMON lawanmu\l"
.string "yang kalah.\p"
.string "Kamu tidak akan bisa bertukar POKéMON\n"
.string "dengan TRAINER ketiga di acara ini.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNotes:
.string "Ada dua poin penting yang harus diperhatikan\n"
.string "saat bertukar POKéMON.\p"
.string "Pertama, saat bertukar, kamu tidak bisa memeriksa\n"
.string "statistik POKéMON yang akan kamu\l"
.string "terima.\p"
.string "Kedua, POKéMON di timmu\n"
.string "diurutkan secara berurutan, tergantung pada\l"
.string "urutan saat kamu menyewanya.\p"
.string "Urutan ini tidak berubah\n"
.string "meskipun pertukaran dilakukan.$"

SlateportCity_BattleTentLobby_Text_ExplainMonRules:
.string "POKéMON di TENDA PERTARUNGAN\n"
.string "SLATEPORT semuanya adalah sewaan.\p"
.string "Semua POKéMON sewaan berada di\n"
.string "Level 30.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_RulesAreListed2:
.string "Aturan TENDA PERTARUNGAN VERDANTURF\n"
.string "tercantum.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ReadWhichHeading:
.string "Judul mana yang ingin kamu baca?$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainBasicRules:
.string "Di TENDA PERTARUNGAN VERDANTURF,\n"
.string "POKéMON diharuskan berpikir dan\l"
.string "bertarung sendiri.\p"
.string "Tidak seperti di alam liar, POKéMON yang hidup\n"
.string "dengan manusia berperilaku berbeda\l"
.string "tergantung pada sifatnya.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainNatureRules:
.string "Tergantung pada sifatnya, POKéMON\n"
.string "mungkin lebih suka menyerang apa pun yang terjadi.\p"
.string "POKéMON lain mungkin lebih suka melindungi\n"
.string "dirinya dari segala bahaya.\p"
.string "Ada lagi yang mungkin suka mengganggu atau\n"
.string "membuat bingung lawannya.\p"
.string "Tergantung pada sifatnya, POKéMON\n"
.string "akan memiliki jurus favorit yang pandai\l"
.string "digunakannya.\p"
.string "Ia mungkin juga tidak menyukai jurus tertentu yang\n"
.string "sulit digunakannya.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainMoveRules:
.string "Ada jurus ofensif yang memberikan\n"
.string "kerusakan langsung pada lawan.\p"
.string "Ada jurus defensif yang\n"
.string "digunakan untuk bersiap menghadapi serangan musuh atau\l"
.string "digunakan untuk menyembuhkan HP dan sebagainya.\p"
.string "Ada juga jurus lain yang agak aneh\n"
.string "yang mungkin melemahkan lawan dengan\l"
.string "masalah status termasuk racun dan\l"
.string "kelumpuhan.\p"
.string "POKéMON akan mempertimbangkan untuk menggunakan jurus dalam\n"
.string "ketiga kategori ini.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainUnderpoweredRules:
.string "Saat tidak diperintah oleh TRAINER-nya,\n"
.string "POKéMON mungkin tidak dapat secara efektif\l"
.string "menggunakan jurus tertentu.\p"
.string "POKéMON tidak pandai menggunakan jurus\n"
.string "apa pun yang tidak disukainya.\p"
.string "Jika POKéMON hanya mengetahui jurus yang\n"
.string "tidak sesuai dengan sifatnya, ia akan sering\l"
.string "tidak dapat mencapai potensinya.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainWhenInDangerRules:
.string "Tergantung pada sifatnya, POKéMON mungkin\n"
.string "mulai menggunakan jurus yang tidak cocok dengan\l"
.string "sifatnya saat dalam kesulitan.\p"
.string "Jika POKéMON mulai berperilaku aneh\n"
.string "saat terdesak, perhatikan baik-baik.$"

BattleTentLobby_Text_ExplainLevelRules:
.string "Di TENDA PERTARUNGAN ini, level\n"
.string "lawanmu akan disesuaikan untuk\l"
.string "mencocokkan level POKéMON-mu.\p"
.string "Namun, tidak ada TRAINER yang kamu hadapi\n"
.string "akan memiliki POKéMON di bawah Level 30.$"

VerdanturfTown_BattleTentLobby_Text_RulesAreListed:
.string "Aturan TENDA PERTARUNGAN VERDANTURF\n"
.string "tercantum.$"