PetalburgCity_Gym_Text_GiveEnigmaBerry:
	.string "AYAH: Hai, {PLAYER}!\p"
	.string "Aku baru dapat BERRY\n"
	.string "sangat langka.\n"
	.string "Ini untukmu.$"

Route104_Text_PlantBerriesInSoilTakeThis:
	.string "Jika lihat BERRY tumbuh\n"
	.string "di tanah subur, ambil saja.\p"
	.string "Tapi tanam BERRY lagi\n"
	.string "di tempat yang sama.\n"
	.string "Itu sopan santun.\p"
	.string "Ini, ambil ini.$"

Route104_Text_TrainersOftenMakeMonHoldBerries:
	.string "Dari penampilanmu,\n"
	.string "kau pasti TRAINER, kan?\p"
	.string "TRAINER sering membuat\n"
	.string "POKÉMON memegang BERRY.\p"
	.string "Tanam atau pakai BERRY,\n"
	.string "terserah padamu.$"

Route111_Text_WateredPlantsEveryDayTakeBerry:
	.string "Aku sirami tanaman\n"
	.string "setiap hari.\n"
	.string "Banyak bunga bermekaran.\p"
	.string "Dan juga banyak BERRY!\p"
	.string "Ini untukmu!\n"
	.string "Ambil saja!$"

Route111_Text_GoingToTryToMakeDifferentColorBerries:
	.string "Aku akan coba keras\n"
	.string "menanam BERRY warna-warni.\p"
	.string "Kau juga harus berusaha!$"

Route111_Text_WhatColorBerriesToLookForToday:
	.string "Hari ini, BERRY warna apa\n"
	.string "yang akan kucari?$"

Route114_Text_LoveUsingBerryCrushShareBerry:
	.string "Aku suka mesin BERRY\n"
	.string "CRUSH, jadi kumpulkan BERRY.\p"
	.string "Boleh kubagikan satu.$"

Route114_Text_TryBerryCrushWithFriends:
	.string "Coba mesin BERRY CRUSH\n"
	.string "bersama teman-temanmu.$"

Route114_Text_FunToThinkAboutBerries:
	.string "BERRY mana yang ditanam?\n"
	.string "Pakai atau simpan BERRY?\p"
	.string "Asyik dipikirkan.$"

Route120_Text_BerriesExpressionOfLoveIsntIt:
	.string "BERRY tumbuh dengan\n"
	.string "menyerap sinar matahari.\p"
	.string "Kita bantu tumbuh dengan\n"
	.string "menyiramnya rutin.\p"
	.string "Itu bentuk kasih sayang,\n"
	.string "bukan?$"

Route120_Text_YesYouUnderstand:
	.string "Ya, ya.\n"
	.string "Kau mengerti maksudku.\p"
	.string "Ambil ini.$"

Route120_Text_MakeYourOwnImpressions:
	.string "Tapi penting juga punya\n"
	.string "pandangan sendiri…\p"
	.string "Ini untukmu.$"

Route120_Text_BerryIsRareRaiseItWithCare:
	.string "BERRY ini langka.\n"
	.string "Rawatlah dengan penuh kasih.$"

Route120_Text_IllGetMoreBerriesFromBerryMaster:
	.string "Aku akan ambil BERRY lagi\n"
	.string "dari MASTER BERRY.$"

LilycoveCity_Text_BerrySuitsYou:
	.string "Begini saja…\p"
	.string "Seperti jas cocok untukku,\n"
	.string "angin sepoi cocok untuk laut.\p"
	.string "Dan kau? BERRY sangat\n"
	.string "cocok untukmu…\p"
	.string "Mengapa begitu?$"

LilycoveCity_Text_BecauseYoureTrainer:
	.string "Begini saja…\p"
	.string "Karena kau seorang TRAINER!$"

LilycoveCity_Text_PokeblocksSuitPokemon:
	.string "Begini saja…\p"
	.string "Seperti kesederhanaan\n"
	.string "cocok untukku,\n"
	.string "{POKEBLOCK}S sangat cocok\n"
	.string "untuk POKÉMON.$"

Route123_BerryMastersHouse_Text_YoureDeservingOfBerry:
	.string "Panggil aku MASTER BERRY.\p"
	.string "Impianku: dunia penuh\n"
	.string "bunga indah. Jadi aku tanam\n"
	.string "BERRY dan bagikan ke semua.\p"
	.string "Kau layak dapat satu!$"

Route123_BerryMastersHouse_Text_WhyBeStingyTakeAnother:
	.string "Jangan pelit!\n"
	.string "Ambil lagi!$"

Route123_BerryMastersHouse_Text_VisitPrettyPetalFlowerShop:
	.string "Kunjungi TOKO BUNGA\n"
	.string "MAWAR CANTIK dekat RUSTBORO.\p"
	.string "Sebarkan bunga ke dunia!$"

Route123_BerryMastersHouse_Text_DoneForToday:
	.string "Sudah cukup hari ini.\n"
	.string "Datang lagi lain kali.\p"
	.string "Sebarkan bunga ke dunia!$"

Route123_BerryMastersHouse_Text_HeardAGoodSayingLately:
	.string "Suamiku penanam BERRY\n"
	.string "terbaik di dunia.\p"
	.string "Aku bangga padanya.\p"
	.string "Ngomong-ngomong, anakku,\n"
	.string "pernah dengar pepatah bagus\n"
	.string "belakangan ini?$"

Route123_BerryMastersHouse_Text_InspirationalTakeThis:
	.string "Wah! Pepatah luar biasa!\n"
	.string "Menginspirasi sekali!\p"
	.string "Ini untukmu.$"

Route123_BerryMastersHouse_Text_GoodSayingTakeThis:
	.string "Wah! Pepatah bagus sekali.\n"
	.string "Kau hebat.\p"
	.string "Ini untukmu.$"

Route123_BerryMastersHouse_Text_JoyNeverGoesOutOfMyLife:
	.string "Keempat cucuku harus\n"
	.string "lebih hebat dari suamiku.\p"
	.string "Kebahagiaan tak pernah\n"
	.string "pergi dari hidupku!$"

Route123_BerryMastersHouse_Text_Ah:
	.string "Ah…$"

Route104_PrettyPetalFlowerShop_Text_ThisIsPrettyPetalFlowerShop:
	.string "Halo!\p"
	.string "Ini TOKO BUNGA\n"
	.string "MAWAR CANTIK.\p"
	.string "Menyebarkan bunga ke dunia!$"

Route104_PrettyPetalFlowerShop_Text_LearnAboutBerries:
	.string "{PLAYER}{KUN}, mau belajar\n"
	.string "tentang BERRY?$"

Route104_PrettyPetalFlowerShop_Text_IntroLearnAboutBerries:
	.string "Namamu?\p"
	.string "{PLAYER}{KUN}.\n"
	.string "Nama bagus.\p"
	.string "{PLAYER}{KUN}, mau belajar\n"
	.string "tentang BERRY?$"

Route104_PrettyPetalFlowerShop_Text_BerriesExplanation:
	.string "BERRY tumbuh di pohon\n"
	.string "yang hanya hidup di tanah\n"
	.string "subur.\p"
	.string "Jika ambil BERRY, tanam\n"
	.string "lagi di tanah itu.\p"
	.string "BERRY yang ditanam akan\n"
	.string "tumbuh, berbunga indah,\l"
	.string "lalu berbuah BERRY lagi.\p"
	.string "Impianku: dunia penuh\n"
	.string "bunga indah.\l"
	.string "Itu mimpiku.\p"
	.string "Bantu aku, {PLAYER}{KUN}.\n"
	.string "Tanam BERRY, sebarkan bunga.$"

Route104_PrettyPetalFlowerShop_Text_FlowersBringHappiness:
	.string "Bunga membuat orang\n"
	.string "bahagia, ya?$"

Route104_PrettyPetalFlowerShop_Text_YouCanHaveThis:
	.string "Halo!\p"
	.string "Semakin kau rawat bunga,\n"
	.string "semakin indah mekarnya.\p"
	.string "Kau pasti suka merawat\n"
	.string "bunga. Ini untukmu.$"

Route104_PrettyPetalFlowerShop_Text_WailmerPailExplanation:
	.string "Saat BERRY tumbuh,\n"
	.string "siram dengan WAILMER PAIL.\p"
	.string "Oh, satu hal lagi.\p"
	.string "Jika BERRY tak dipetik,\n"
	.string "ia jatuh ke tanah.\l"
	.string "Tapi akan tumbuh lagi.\p"
	.string "Keren, kan?\n"
	.string "Seperti punya semangat hidup.$"

Route104_PrettyPetalFlowerShop_Text_ImGrowingFlowers:
	.string "Aku ingin seperti kakakku.\n"
	.string "Aku juga tanam bunga!\p"
	.string "Ini untukmu!\n"
	.string "Hadiah!$"

Route104_PrettyPetalFlowerShop_Text_MachineMixesBerries:
	.string "BERRY bisa ditanam,\n"
	.string "dipegang POKÉMON,\n"
	.string "atau dicampur di mesin\n"
	.string "jadi permen untuk POKÉMON.\p"
	.string "Aku juga mau permen itu.$"

SootopolisCity_Text_NameIsKiriHaveOneOfThese:
	.string "Hai, siapa namamu?\p"
	.string "… … …  … … …  … … …\n"
	.string "Oke. Nama bagus!\p"
	.string "Namaku KIRI.\p"
	.string "Orang tuaku memberi nama\n"
	.string "agar aku sehat dan hangat.\l"
	.string "Itu harapan mereka.\p"
	.string "Ambil ini.$"

SootopolisCity_Text_GiveYouThisBerryToo:
	.string "KIRI beri kau BERRY ini!\n"
	.string "Aku sangat suka!$"

SootopolisCity_Text_WhatKindOfWishInYourName:
	.string "Apa harapan yang tersemat\n"
	.string "dalam namamu?$"

SootopolisCity_Text_LikeSeasonBornIn:
	.string "Musim semi, panas,\n"
	.string "gugur, dan dingin.\p"
	.string "Jika lahir di musim semi,\n"
	.string "apakah kau suka musim semi?\l"
	.string "Jika lahir di musim panas,\n"
	.string "suka musim panas?$"

SootopolisCity_Text_ThenILoveAutumn:
	.string "KIRI lahir di musim gugur,\n"
	.string "jadi aku suka musim gugur!\p"
	.string "Musim apa yang kau suka?$"

SootopolisCity_Text_OhDoesntMatter:
	.string "Oh…\n"
	.string "Tak apa-apa…\p"
	.string "Masih banyak yang ingin\n"
	.string "kuketahui…$"