gText_Birch_Welcome::
.string "Hai! Maaf membuatmu menunggu!\p"
.string "Selamat datang di dunia POKéMON!\p"
.string "Namaku BIRCH.\p"
.string "Tapi semua orang memanggilku PROFESSOR\n"
.string "POKéMON.\p"
.string "$"

gText_Birch_Pokemon::
.string "Inilah yang kita sebut “POKéMON.”\p"
.string "\n"
.string "$"

gText_Birch_MainSpeech::
.string "Dunia ini dihuni oleh makhluk\n"
.string "yang dikenal sebagai POKéMON.\p"
.string "Kita manusia hidup berdampingan \ndengan POKéMON,\l"
.string "kadang sebagai teman bermain, dan\l"
.string "kadang sebagai rekan kerja.\p"
.string "Dan terkadang, kita berkelompok\n"
.string "dan bertarung dengan sesama kita.\p"
.string "Tapi meski dekat, kita tidak\n"
.string "tahu segalanya tentang POKéMON.\p"
.string "Faktanya, ada banyak sekali\n"
.string "rahasia seputar POKéMON.\p"
.string "Untuk mengungkap misteri POKéMON,\n"
.string "aku telah melakukan penelitian.\l"
.string "Itulah yang kulakukan.\p"
.string "$"

gText_Birch_AndYouAre::
.string "Dan kamu?$"

gText_Birch_BoyOrGirl::
.string "Apa kamu Pria?\n"
.string "Atau Wanita?$"

gText_Birch_WhatsYourName::
.string "Baiklah.\n"
.string "Siapa namamu?$"

gText_Birch_SoItsPlayer::
.string "Jadi, {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
.string "Ah, oke!\p"
.string "Kamu {PLAYER}{KUN} yang pindah ke\n"
.string "kampung halamanku, LITTLEROOT.\l"
.string "Aku mengerti sekarang!\p"
.string "$"

gText_Birch_AreYouReady::
.string "Baiklah, apa kamu siap?\p"
.string "Petualanganmu sendiri akan\n"
.string "segera dimulai.\p"
.string "Beranikan dirimu, dan lompatlah ke\n"
.string "dunia POKéMON tempat impian,\l"
.string "petualangan, dan persahabatan menanti!\p"
.string "Baiklah, aku akan menunggumu nanti.\n"
.string "Temui aku di LAB POKéMON-ku.\p"
.string "$"