BerryBlender_Text_BlendWithTheBlendMaster:
.string "BLEND MASTER: Tentu saja!\n"
.string "Akulah sang BLEND MASTER!\p"
.string "Campur bersamaku, dan kamu akan menyaksikan\n"
.string "keahlianku dalam mencampur!$"

BerryBlender_Text_SeeMyMasteryInAction:
.string "BLEND MASTER: Hmmm! Jadi, kamu ingin\n"
.string "melihat keahlianku beraksi?$"

BerryBlender_Text_TooBusyNowIsee:
.string "Hmmm!\p"
.string "Jadi, kamu terlalu sibuk sekarang, ya!\p"
.string "Tapi jangan khawatir!\n"
.string "Aku akan di sini seharian!\l"
.string "Cepat kembali dari urusanmu!$"

BerryBlender_Text_BlendMasterNoBerries:
.string "Hmmm!\p"
.string "Kamu tidak punya satu BERRY pun!\p"
.string "Aku akan di sini seharian!\n"
.string "Cepat kembali dengan beberapa BERRY!$"

BerryBlender_Text_BlendMasterKnowHowToMakePokeblocks:
.string "Tentu saja!\n"
.string "Tentu saja!\p"
.string "Ngomong-ngomong…\n"
.string "Kamu tahu cara mencampur {POKEBLOCK}\l"
.string "dari BERRY?$"

BerryBlender_Text_BlendMasterExplainBerryBlending:
.string "Hmmm!\p"
.string "Ah, tapi ini proses yang sederhana!\p"
.string "Saat panah BLENDER sampai di\n"
.string "penandamu, tekan saja Tombol A.\p"
.string "Hanya itu yang perlu kamu lakukan.\p"
.string "Saat kamu lihat betapa presisinya aku menekan\n"
.string "Tombol A, kamu akan mengerti.$"

BerryBlender_Text_BlendMasterLetsBerryBlender:
.string "Baiklah!\p"
.string "Kalau begitu, ayo kita mulai!\p"
.string "Bersama-sama dengan BLEND MASTER,\n"
.string "ayo BERRY BLENDER!$"

BerryBlender_Text_BlendMasterNoPokeblockCase:
.string "Hmmm!\p"
.string "Sepertinya kamu belum mendapatkan\n"
.string "{POKEBLOCK} CASE!\p"
.string "Aku akan di sini seharian!\n"
.string "Dapatkan {POKEBLOCK} CASE dan cepat kembali!$"

BerryBlender_Text_BlendMasterPokeblockCaseFull:
.string "Hmmm!\p"
.string "{POKEBLOCK} CASE-mu sepertinya penuh!\p"
.string "Aku akan di sini seharian!\n"
.string "Gunakan beberapa {POKEBLOCK} dan cepat kembali!$"

BerryBlender_Text_WhoaAwesome:
.string "Whoa!\n"
.string "Luar biasa!$"

BerryBlender_Text_WickedlyFast:
.string "Cepat sekali!$"

BerryBlender_Text_WhatAnExpert:
.string "Benar-benar ahli!$"

BerryBlender_Text_MadeAmazingPokeblocksWithMaster:
.string "Saat aku mencampur dengan sang MASTER,\n"
.string "kami membuat {POKEBLOCK} yang luar biasa!$"

BerryBlender_Text_QualitiesOfBlendMaster:
.string "Mata yang mengikuti panah dengan\n"
.string "intensitas seperti mesin…\p"
.string "Tangan yang menekan Tombol A\n"
.string "dengan presisi seperti jam…\p"
.string "Memiliki kualitas-kualitas ini membuat\n"
.string "BLEND MASTER benar-benar hebat.$"

BerryBlender_Text_MasterWorksOnSkillsInMountains:
.string "BLEND MASTER seharusnya melatih\n"
.string "keahliannya jauh di dalam gunung.\p"
.string "Terkadang, dia datang ke LILYCOVE\n"
.string "untuk mencampur BERRY seharian.$"