CableClub_Text_WelcomeWhichCableClubService:
	.string "Selamat datang di POKéMON CABLE\n"
	.string "CLUB.\p"
	.string "Layanan mana yang kamu inginkan\n"
	.string "untuk digunakan?$"

CableClub_Text_WhichService:
	.string "Layanan mana yang kamu inginkan\n"
	.string "untuk digunakan?$"

CableClub_Text_TradeUsingLinkCable::
	.string "Tukar POKéMON dengan pemain lain\n"
	.string "menggunakan kabel GBA Game Link.$"

CableClub_Text_BattleUsingLinkCable::
	.string "Kamu bisa melawan TRAINER lain\n"
	.string "menggunakan kabel GBA Game Link.$"

CableClub_Text_RecordCornerUsingLinkCable::
	.string "Kamu dapat menggunakan RECORD CORNER\n"
	.string "dengan orang lain memakai kabel GBA Game Link.$"

@ Unused
CableClub_Text_CloseThisMenu:
	.string "Tutup menu ini.$"

CableClub_Text_NeedTwoMonsForDoubleBattle:
	.string "Untuk DOUBLE BATTLE, kamu harus\n"
	.string "memiliki setidaknya dua POKéMON.$"

CableClub_Text_NeedTwoMonsToTrade:
	.string "Untuk menukar, kamu harus memiliki\n"
	.string "setidaknya dua POKéMON bersamamu.$"

CableClub_Text_CantTradeEnigmaBerry:
	.string "POKéMON yang memegang {STR_VAR_1}\n"
	.string "BERRY tidak dapat ditukar.$"

gText_PleaseWaitForLink::
	.string "Mohon tunggu.\n"
	.string "… … Tombol B: Batalkan$"

gText_ConfirmLinkWhenPlayersReady::
	.string "Saat semua pemain siap…\n"
	.string "Tombol A: Konfirmasi\l"
	.string "Tombol B: Batalkan$"

gText_ConfirmStartLinkWithXPlayers::
	.string "Mulai tautan dengan {STR_VAR_1} pemain.\n"
	.string "Tombol A: Konfirmasi\l"
	.string "Tombol B: Batalkan$"

gText_AwaitingLinkup::
	.string "Menunggu tautan…\n"
	.string "… … Tombol B: Batalkan$"

@ Unused
CableClub_Text_OkayToSaveProgress::
	.string "Progresmu harus disimpan sebelum\n"
	.string "menghubungkan. Boleh disimpan?$"

CableClub_Text_PleaseEnter:
	.string "Silakan masuk.$"

CableClub_Text_DirectYouToYourRoom:
	.string "Aku akan mengarahkanmu ke kamarmu sekarang.$"

Text_SomeoneIsNotReadyToLink:
	.string "Seseorang belum siap untuk terhubung.\p"
	.string "Silakan kembali setelah semua orang\n"
	.string "telah membuat persiapan.$"

Text_LinkErrorPleaseReset:
	.string "Maaf, ada kesalahan tautan…\n"
	.string "Silakan setel ulang dan coba lagi.$"

Text_PlayersMadeDifferentSelections:
	.string "Mitra tautan tampaknya telah\n"
	.string "membuat pilihan yang berbeda.$"

CableClub_Text_PleaseVisitAgain:
	.string "Silakan kunjungi lagi.$"

CableClub_Text_IncorrectNumberOfParticipants:
	.string "Jumlah peserta\n"
	.string "tidak benar.$"

CableClub_Text_CantSingleBattleWithXPlayers:
	.string "Mode SINGLE BATTLE tidak dapat\n"
	.string "dimainkan oleh {STR_VAR_1} pemain.$"

CableClub_Text_CantDoubleBattleWithXPlayers:
	.string "Mode DOUBLE BATTLE tidak dapat\n"
	.string "dimainkan oleh {STR_VAR_1} pemain.$"

CableClub_Text_NeedFourPlayers:
	.string "Harus ada empat pemain untuk\n"
	.string "memainkan Mode Pertarungan ini.$"

CableClub_Text_PleaseConfirmNumberAndRestart:
	.string "Mohon konfirmasi jumlah\n"
	.string "pemain dan mulai lagi.$"

Text_TerminateLinkConfirmation:
	.string "Tautan akan diakhiri jika kamu\n"
	.string "meninggalkan ruangan. Apakah tidak apa-apa?$"

Text_TerminateLinkPleaseWait:
	.string "Mengakhiri tautan…\n"
	.string "Kamu akan diantar keluar\l"
	.string "dari ruangan. Mohon tunggu.$"

CableClub_Text_TooBusyToNotice:
	.string "TRAINER ini terlalu sibuk untuk\n"
	.string "memperhatikan…$"

CableClub_Text_GotToLookAtTrainerCard:
	.string "Skor! Aku melihat\n"
	.string "KARTU TRAINER {STR_VAR_1}!$"

CableClub_Text_GotToLookAtColoredTrainerCard:
	.string "Skor! Aku melihat\n"
	.string "KARTU TRAINER {STR_VAR_1}!\p"
	.string "Itu kartu {STR_VAR_2}!$"

BattleColosseum_2P_Text_TakePlaceStartBattle:
	.string "Silakan ambil tempatmu dan mulai\n"
	.string "pertarunganmu.$"

TradeCenter_Text_TakeSeatStartTrade:
	.string "Silakan duduk dan mulai\n"
	.string "pertukaranmu.$"

RecordCorner_Text_ThanksForComing:
	.string "Terima kasih sudah datang.$"

CableClub_Text_TrainerCardDataOverwritten:
	.string "Data KARTU TRAINER akan\n"
	.string "ditimpa.$"

CableClub_Text_HopeToSeeYouAgain:
	.string "Aku harap bisa bertemu kamu lagi!$"

CableClub_Text_NotSetUpForFarAwayRegion:
	.string "Aku sangat menyesal.\p"
	.string "Kami belum siap untuk melakukan pertukaran\n"
	.string "dengan TRAINER yang jauh di wilayah\l"
	.string "lain…$"

CableClub_Text_OtherTrainerNotReady:
	.string "TRAINER lain belum siap.$"

CableClub_Text_YouHaveAMonThatCantBeTaken:
	.string "Kamu memiliki setidaknya satu POKéMON\n"
	.string "yang tidak bisa diambil.$"

RecordCorner_Text_TakeSeatAndWait:
	.string "Silakan duduk dan tunggu.$"

RecordCorner_Text_PlayerSentOverOneX:
	.string "{STR_VAR_1} mengirimkan satu\n"
	.string "{STR_VAR_2}.$"

CableClub_Text_CantMixWithJapaneseGame:
	.string "Maaf, ada kesalahan transmisi.\p"
	.string "Kamu tidak dapat mencampur catatan dengan\n"
	.string "game Ruby atau Sapphire Jepang.\p"
	.string "Juga, kamu tidak dapat mencampur catatan dengan\n"
	.string "game Emerald Jepang dan Ruby atau\l"
	.string "Sapphire luar negeri pada saat bersamaan.$"

CableClub_Text_AdapterNotConnected:
	.string "Adaptor Nirkabel tidak\n"
	.string "terhubung dengan benar.$"

CableClub_Text_ParticipantsStepUpToCounter:
	.string "Peserta diminta untuk melangkah\n"
	.string "ke meja resepsionis.$"

@ Unused
CableClub_Text_Hello:
	.string "Halo!$"

@ Unused
CableClub_Text_PleaseWait:
	.string "Mohon tunggu.$"

CableClub_Text_YouMayTradeHere::
	.string "Kamu bisa menukar POKéMON-mu di sini\n"
	.string "dengan TRAINER lain.$"

CableClub_Text_YouMayBattleHere::
	.string "Kamu bisa bertarung dengan teman-temanmu\n"
	.string "di sini.$"

CableClub_Text_CanMakeBerryPowder::
	.string "Dua hingga lima TRAINER bisa membuat\n"
	.string "BERRY POWDER bersama.$"

CableClub_Text_CanMixRecords::
	.string "Catatan dua hingga empat pemain\n"
	.string "bisa digabungkan.$"

@ Unused
CableClub_Text_GuideToVariousServices:
	.string "Panduan layanan\n"
	.string "WIRELESS CLUB.$"

CableClub_Text_CancelSelectedItem::
	.string "Membatalkan item MENU yang dipilih.$"

@ Unused
CableClub_Text_WhichBattleMode:
	.string "Mode pertarungan mana yang kamu inginkan?$"

@ Unused
CableClub_Text_ReturnsToPreviousStep:
	.string "Kembali ke langkah sebelumnya.$"

CableClub_Text_NeedBerryForBerryCrush:
	.string "Untuk menggunakan layanan BERRY CRUSH,\n"
	.string "kamu harus memiliki setidaknya satu BERRY.$"

CableClub_Text_NeedTwoMonsForUnionRoom:
	.string "Untuk memasuki UNION ROOM, kamu harus\n"
	.string "memiliki setidaknya dua POKéMON.$"

CableClub_Text_NoEnigmaBerryInUnionRoom:
	.string "Tidak ada POKéMON yang memegang {STR_VAR_1}\n"
	.string "BERRY yang boleh memasuki UNION ROOM.$"

CableClub_Text_UnionRoomAdapterNotConnected:
	.string "Ini adalah POKéMON WIRELESS CLUB\n"
	.string "UNION ROOM.\p"
	.string "Sayangnya, Adaptor Nirkabelmu\n"
	.string "tidak terhubung dengan benar.\p"
	.string "Silakan datang lagi.$"

@ Unused
CableClub_Text_OhExcuseMe:
	.string "Oh…\n"
	.string "Maafkan aku!$"

CableClub_Text_PlayerIsWaiting:
	.string "Tampaknya {STR_VAR_1} sedang bermain\n"
	.string "sekarang.\l"
	.string "Ayo!$"

MossdeepCity_GameCorner_1F_Text_DescribeWhichGame:
	.string "Aku bisa menjelaskan aturan game kepadamu,\n"
	.string "jika kamu mau.\p"
	.string "Game mana yang harus aku jelaskan?$"

MossdeepCity_GameCorner_1F_Text_PokemonJumpInfo:
	.string "“POKéMON JUMP”\p"
	.string "Buat POKéMON-mu melompati tali\n"
	.string "VINE WHIP dengan Tombol A.\p"
	.string "Hanya POKéMON mini sekitar 28 inci\n"
	.string "atau kurang yang boleh berpartisipasi.\p"
	.string "POKéMON yang hanya berenang, menggali,\n"
	.string "atau terbang tidak pandai melompat.\p"
	.string "Akibatnya, POKéMON tersebut tidak\n"
	.string "boleh berpartisipasi.\p"
	.string "Hal-hal baik terjadi jika semua orang\n"
	.string "melompat tepat waktu.$"

MossdeepCity_GameCorner_1F_Text_DodrioBerryPickingInfo:
	.string "“MEMETIK BERRY DODRIO”\p"
	.string "Perintahkan tiga kepala DODRIO untuk\n"
	.string "menangkap BERRY yang jatuh.\p"
	.string "Tekan kanan, atas, atau kiri pada\n"
	.string "{PLUS} Control Pad untuk menggerakkan kepala.\p"
	.string "Untuk memainkan game ini, kamu harus\n"
	.string "memiliki DODRIO.$"

MossdeepCity_GameCorner_1F_Text_TalkToOldManToPlay:
	.string "Jika kamu ingin bermain game,\n"
	.string "tolong beritahu orang tua di sampingku.$"

MossdeepCity_GameCorner_1F_Text_WelcomeCanYouWait:
	.string "Hai, selamat datang!\n"
	.string "Apakah kamu di sini untuk bermain game menggunakan\l"
	.string "Komunikasi Nirkabel?\p"
	.string "Bisakah kamu menunggu sebentar?$"

MossdeepCity_GameCorner_1F_Text_ComeAgain:
	.string "Baiklah, datang lagi!$"

MossdeepCity_GameCorner_1F_Text_AdapterNotConnected:
	.string "Adaptor Nirkabel tidak terhubung.\n"
	.string "Kembali lagi setelah terhubung!$"

MossdeepCity_GameCorner_1F_Text_PlayWhichGame:
	.string "Baiklah, game mana yang ingin kamu\n"
	.string "mainkan?$"

MossdeepCity_GameCorner_1F_Text_EnterWhichPokemon:
	.string "POKéMON mana yang ingin kamu\n"
	.string "masukkan?$"

MossdeepCity_GameCorner_1F_Text_AllGoodToGo:
	.string "Oke, kamu siap.\n"
	.string "Jangan biarkan yang lain mengalahkanmu!$"

@ Unused
MossdeepCity_GameCorner_1F_Text_LeavingDoComeAgain:
	.string "Apakah kamu pergi sekarang?\n"
	.string "Datang lagi ya!$"

MossdeepCity_GameCorner_1F_Text_ExplainRequiredMon:
	.string "Sepertinya kamu tidak punya POKéMON\n"
	.string "yang bisa dimasukkan…\p"
	.string "Apakah kamu ingin aku menjelaskan jenis\n"
	.string "POKéMON apa yang bisa masuk?$"

MossdeepCity_GameCorner_1F_Text_ShortJumpingPokemonAllowed:
	.string "“POKéMON JUMP” terbuka untuk POKéMON\n"
	.string "sekitar 28 inci atau kurang.\p"
	.string "Yang tidak bisa kamu masukkan adalah\n"
	.string "POKéMON yang tidak bisa melompat.\p"
	.string "Kamu tahu, seperti POKéMON yang hanya\n"
	.string "berenang, menggali, atau terbang.\p"
	.string "Itu saja yang perlu kamu ketahui.$"

MossdeepCity_GameCorner_1F_Text_OnlyDodrioAllowed:
	.string "DODRIO BERRY-PICKING adalah game yang\n"
	.string "hanya DODRIO yang boleh masuk.$"

@ Unused
MossdeepCity_GameCorner_1F_Text_RetryPlease:
	.string "Bisakah kamu mencoba ini dari awal\n"
	.string "lagi, tolong?$"

CableClub_Text_WelcomeWhichDirectCornerRoom:
	.string "Selamat datang di POKéMON WIRELESS\n"
	.string "CLUB DIRECT CORNER.\p"
	.string "Kamu bisa berinteraksi langsung\n"
	.string "dengan teman-temanmu di sini.\p"
	.string "Kamar mana yang ingin kamu\n"
	.string "masuki?$"

CableClub_Text_TradePokemon:
	.string "Apakah kamu ingin menukar POKéMON?$"

CableClub_Text_PlayWhichBattleMode:
	.string "Mode Pertarungan mana yang ingin kamu\n"
	.string "mainkan?$"

CableClub_Text_AccessRecordCorner:
	.string "Apakah kamu ingin mengakses\n"
	.string "RECORD CORNER?$"

CableClub_Text_UseBerryCrush:
	.string "Apakah kamu ingin menggunakan\n"
	.string "Sistem BERRY CRUSH?$"

CableClub_Text_ExplainBattleModes:
	.string "Ada tiga Mode Pertarungan.\p"
	.string "SINGLE BATTLE adalah untuk dua TRAINER\n"
	.string "dengan satu atau lebih POKéMON masing-masing.\p"
	.string "Setiap TRAINER dapat memiliki satu POKéMON\n"
	.string "dalam pertarungan pada satu waktu.\p"
	.string "DOUBLE BATTLE adalah untuk dua TRAINER\n"
	.string "dengan dua atau lebih POKéMON masing-masing.\p"
	.string "Setiap TRAINER akan mengeluarkan dua\n"
	.string "POKéMON dalam pertarungan pada satu waktu.\p"
	.string "MULTI BATTLE adalah untuk empat TRAINER\n"
	.string "dengan satu atau lebih POKéMON masing-masing.\p"
	.string "Setiap TRAINER dapat memiliki satu POKéMON\n"
	.string "dalam pertarungan pada satu waktu.$"

CableClub_Text_ChooseGroupLeaderOfTwo:
	.string "Tolong tentukan siapa di antara kalian berdua\n"
	.string "yang akan menjadi PEMIMPIN.\p"
	.string "Pemain lain harus memilih\n"
	.string "“GABUNG GRUP.”$"

CableClub_Text_ChooseGroupLeaderOfFour:
	.string "Tolong tentukan siapa di antara kalian berempat\n"
	.string "yang akan menjadi PEMIMPIN GRUP.\p"
	.string "Pemain lain harus memilih\n"
	.string "“GABUNG GRUP.”$"

CableClub_Text_ChooseGroupLeader:
	.string "Tolong tentukan siapa di antara kalian\n"
	.string "yang akan menjadi PEMIMPIN GRUP.\p"
	.string "Pemain lain harus memilih\n"
	.string "“GABUNG GRUP.”$"

CableClub_Text_WelcomeUnionRoomEnter:
	.string "Selamat datang di POKéMON WIRELESS\n"
	.string "CLUB UNION ROOM.\p"
	.string "Kamu bisa berinteraksi langsung dengan\n"
	.string "TRAINER lain di sini, beberapa di antaranya\l"
	.string "mungkin tidak kamu kenal.\p"
	.string "Apakah kamu ingin memasuki RUANGAN?$"

CableClub_Text_UnionRoomInfo:
	.string "Para TRAINER di UNION ROOM\n"
	.string "adalah pemain di sekitarmu\l"
	.string "yang juga telah memasuki RUANGAN.\p"
	.string "Kamu bisa melakukan berbagai hal\n"
	.string "di sini, seperti bertukar salam.\p"
	.string "Kamu bisa memasukkan dua POKéMON hingga\n"
	.string "Lv. 30 untuk pertarungan satu lawan satu.\p"
	.string "Kamu bisa ikut serta dalam obrolan dengan\n"
	.string "dua hingga lima orang.\p"
	.string "Atau, kamu bisa mendaftarkan POKéMON untuk\n"
	.string "ditukar.\p"
	.string "Apakah kamu ingin memasuki RUANGAN?$"

CableClub_Text_EnjoyUnionRoom:
	.string "Aku harap kamu menikmati waktumu di\n"
	.string "UNION ROOM.$"

CableClub_Text_FirstTimeRightThisWay:
	.string "Halo!\n"
	.string "Namaku TEALA.\p"
	.string "Ini pasti pertama kalimu\n"
	.string "di sini.\p"
	.string "Aku akan menunjukkan cara kerja\n"
	.string "Sistem Komunikasi Nirkabel.\p"
	.string "Pertama, aku perlu menunjukkan\n"
	.string "lantai ini di POKéMON CENTER kami.\p"
	.string "Lewat sini, silakan.$"

CableClub_Text_ExplainWirelessClubFirstTime:
	.string "Di lantai atas, ada dua ruangan.\p"
	.string "Pertama, ruang kiri: UNION ROOM.\p"
	.string "Kamu bisa terhubung dengan TRAINER\n"
	.string "di sekitarmu yang juga masuk\l"
	.string "ke UNION ROOM.\p"
	.string "Di sini, kalian bisa mengobrol,\n"
	.string "bertarung, atau bertukar POKéMON.\p"
	.string "Kedua, ruang kanan: DIRECT CORNER.\p"
	.string "Kamu bisa bertukar atau bertarung\n"
	.string "POKéMON dengan teman di sini.\p"
	.string "Jika Wireless Adapter tidak terpasang,\n"
	.string "kamu tetap bisa terhubung lewat\l"
	.string "kabel GBA Game Link.\p"
	.string "Jika demikian, kamu harus pergi ke\n"
	.string "DIRECT CORNER.\p"
	.string "Semoga kamu menikmati Sistem\n"
	.string "Komunikasi Nirkabel!$"

CableClub_Text_AskAboutLinking:
	.string "Halo, {PLAYER}!\p"
	.string "Ini aku, TEALA, petugas POKéMON\n"
	.string "CENTER lantai 2.\p"
	.string "Apakah ada sesuatu yang ingin kamu\n"
	.string "tanyakan padaku tentang tautan?$"

CableClub_Text_ExplainWirelessClub:
	.string "Izinkan aku menjelaskan cara kerja\n"
	.string "POKéMON WIRELESS CLUB.\p"
	.string "Di lantai atas ini, ada\n"
	.string "dua ruangan.\p"
	.string "Pertama, ruangan di sebelah kiri.\n"
	.string "Itu adalah UNION ROOM.\p"
	.string "Kamu bisa terhubung dengan TRAINER\n"
	.string "di sekitarmu yang juga telah memasuki\l"
	.string "UNION ROOM.\p"
	.string "Dengan mereka, kamu bisa melakukan hal-hal seperti\n"
	.string "mengobrol, bertarung, dan bertukar.\p"
	.string "Kedua, ruangan di sebelah kanan adalah\n"
	.string "DIRECT CORNER.\p"
	.string "Kamu bisa bertukar atau bertarung POKéMON\n"
	.string "dengan teman-temanmu di ruangan ini.\p"
	.string "Terkadang, kamu mungkin tidak dapat\n"
	.string "menemukan teman-temanmu di UNION ROOM\l"
	.string "atau DIRECT CORNER.\p"
	.string "Dalam kasus itu, tolong dekati\n"
	.string "teman-temanmu.\p"
	.string "Jika Adaptor Nirkabel tidak\n"
	.string "terhubung, kamu masih bisa terhubung\l"
	.string "menggunakan kabel GBA Game Link.\p"
	.string "Jika demikian, kamu harus pergi\n"
	.string "ke DIRECT CORNER.\p"
	.string "Aku harap kamu menikmati\n"
	.string "Sistem Komunikasi Nirkabel.$"

CableClub_Text_HopeYouEnjoyWirelessSystem:
	.string "Aku harap kamu menikmati Sistem\n"
	.string "Komunikasi Nirkabel.$"
