Text_PictureBookShelf:
	.string "Ada satu set buku bergambar POKéMON.$"

Text_BookShelf:
	.string "Rak ini penuh dengan berbagai macam buku.$"

Text_PokemonCenterBookShelf:
	.string "Majalah POKéMON!\n"
	.string "POKéMON PAL…\p"
	.string "POKéMON HANDBOOK…\n"
	.string "POKéMON LUCU…$"

Text_Vase:
	.string "Vas ini terlihat mahal…\n"
	.string "Mengintip ke dalam…\p"
	.string "Tapi, kosong.$"

Text_EmptyTrashCan:
	.string "Kosong.$"

Text_ShopShelf:
	.string "Rak-rak penuh dengan berbagai macam\n"
	.string "barang dagangan POKéMON.$"

Text_Blueprint:
	.string "Semacam cetak biru?\n"
	.string "Terlalu rumit!$"
