gContestHallPaintingCaption::
	.string "{STR_VAR_1}\n"
	.string "{STR_VAR_3} milik {STR_VAR_2}$"

@ Unused
gContestPaintingContest::
	.string "KONTES$"

gContestRankNormal::
	.string "PERINGKAT NORMAL$"

gContestRankSuper::
	.string "PERINGKAT SUPER$"

gContestRankHyper::
	.string "PERINGKAT HYPER$"

gContestRankMaster::
	.string "PERINGKAT MASTER$"

gContestLink::
	.string "TAUTAN$"

gContestCoolness::
	.string "KEREN$"

gContestBeauty::
	.string "CANTIK$"

gContestCuteness::
	.string "IMUT$"

gContestSmartness::
	.string "PINTAR$"

gContestToughness::
	.string "KUAT$"

gContestPaintingCool1::
	.string "Sangat keren tanpa henti--\n"
	.string "{STR_VAR_1} yang tak ternilai$"

gContestPaintingCool2::
	.string "Hei!\n"
	.string "POKéMON tampan {STR_VAR_1}$"

gContestPaintingCool3::
	.string "Yang luar biasa, menakjubkan, dan\n"
	.string "sangat hebat {STR_VAR_1}$"

gContestPaintingBeauty1::
	.string "Venus terakhir abad ini--\n"
	.string "{STR_VAR_1} yang cantik$"

gContestPaintingBeauty2::
	.string "Senyum {STR_VAR_1} yang mempesona,\n"
	.string "berkilauan$"

gContestPaintingBeauty3::
	.string "Idola super POKéMON CENTER--\n"
	.string "{STR_VAR_1} yang tak tertandingi$"

gContestPaintingCute1::
	.string "{STR_VAR_1} yang cantik dan manis$"

gContestPaintingCute2::
	.string "Potret kemenangan\n"
	.string "{STR_VAR_1} yang cantik$"

gContestPaintingCute3::
	.string "Beri kami kedipan mata!\n"
	.string "POKéMON imut {STR_VAR_1}$"

gContestPaintingSmart1::
	.string "Maestro kecerdasan--\n"
	.string "POKéMON bijak {STR_VAR_1}$"

gContestPaintingSmart2::
	.string "{STR_VAR_1}--yang terpilih\n"
	.string "di antara semua POKéMON$"

gContestPaintingSmart3::
	.string "Momen elegan {STR_VAR_1}\n"
	.string "yang luar biasa$"

gContestPaintingTough1::
	.string "Si cepat {STR_VAR_1}\n"
	.string "yang berotot kuat$"

gContestPaintingTough2::
	.string "Yang kuat, lebih kuat, dan\n"
	.string "terkuat {STR_VAR_1}$"

gContestPaintingTough3::
	.string "POKéMON hiper {STR_VAR_1}\n"
	.string "yang sangat tangguh$"
