gText_AppealNumWhichMoveWillBePlayed::
	.string "Bandingkan no. {STR_VAR_1}!\n"
	.string "Jurus mana yang akan dimainkan?$"

gText_AppealNumButItCantParticipate::
	.string "Bandingkan no. {STR_VAR_1}!\n"
	.string "Tapi tidak bisa berpartisipasi!$"

gText_MonAppealedWithMove::
	.string "{STR_VAR_1} menarik perhatian dengan\n"
	.string "{STR_VAR_2}!$"

gText_MonWasWatchingOthers::
	.string "{STR_VAR_1} sedang mengamati\n"
	.string "yang lain.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AllOutOfAppealTime::
	.string "Waktu banding kita\n"
	.string "sudah habis!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

@ Appeal result texts

gText_BecameMoreConsciousOfOtherMons::
	.string "Itu menjadi lebih sadar\n"
	.string "akan POKéMON lain.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCantMakeAnAppealAfterThis::
	.string "{STR_VAR_1} tidak bisa membuat\n"
	.string "banding setelah ini.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SettledDownJustLittleBit::
	.string "Itu sedikit\n"
	.string "tenang.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameObliviousToOtherMons::
	.string "Itu menjadi tidak peduli\n"
	.string "terhadap POKéMON lain.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameLessAwareOfOtherMons::
	.string "Itu menjadi kurang sadar\n"
	.string "akan POKéMON lain.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoppedCaringAboutOtherMons::
	.string "Itu berhenti peduli dengan\n"
	.string "POKéMON lain.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToStartleOtherMons::
	.string "Itu mencoba mengejutkan\n"
	.string "POKéMON lain.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToDazzleOthers::
	.string "Itu mencoba menyilaukan\n"
	.string "yang lain.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAwayFromMon::
	.string "HAKIM memalingkan muka\n"
	.string "dari {STR_VAR_1}.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToUnnerveNextMon::
	.string "Itu mencoba membuat gugup\n"
	.string "POKéMON berikutnya.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonBecameNervous::
	.string "{STR_VAR_1} menjadi\n"
	.string "gugup.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealTriedToUnnerveWaitingMons::
	.string "Banding itu mencoba membuat\n"
	.string "POKéMON yang menunggu gugup.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TauntedMonsDoingWell::
	.string "Itu mengejek POKéMON\n"
	.string "yang tampil baik.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonRegainedItsForm::
	.string "{STR_VAR_1} mendapatkan kembali\n"
	.string "bentuknya.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToJamMonDoingWell::
	.string "Itu mencoba mengganggu POKéMON\n"
	.string "yang tampil baik.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StandoutMonHustledEvenMore::
	.string "{STR_VAR_1} yang menonjol\n"
	.string "berjuang lebih keras.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_LargelyUnnoticedMonWorkedHard::
	.string "{STR_VAR_1} yang sebagian besar\n"
	.string "tidak diperhatikan bekerja keras.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsMonBefore::
	.string "Itu bekerja sebanyak\n"
	.string "POKéMON sebelumnya.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell::
	.string "Banding {STR_VAR_1}\n"
	.string "tidak berjalan baik.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsPrecedingMon::
	.string "Itu bekerja sebanyak POKéMON\n"
	.string "sebelumnya.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell2::
	.string "Banding {STR_VAR_1}\n"
	.string "tidak berjalan baik.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell3::
	.string "Banding {STR_VAR_1}\n"
	.string "tidak berjalan baik.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell::
	.string "Banding {STR_VAR_1}\n"
	.string "sedikit berhasil.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell::
	.string "Banding {STR_VAR_1}\n"
	.string "cukup berhasil.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently::
	.string "Banding {STR_VAR_1}\n"
	.string "berhasil dengan sangat baik.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWasDud::
	.string "Banding {STR_VAR_1}\n"
	.string "gagal.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotWorkVeryWell::
	.string "Banding {STR_VAR_1}\n"
	.string "tidak berhasil dengan baik.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell2::
	.string "Banding {STR_VAR_1}\n"
	.string "sedikit berhasil.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell2::
	.string "Banding {STR_VAR_1}\n"
	.string "cukup berhasil.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentVeryWell::
	.string "Banding {STR_VAR_1}\n"
	.string "berhasil dengan sangat baik.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently2::
	.string "Banding {STR_VAR_1}\n"
	.string "berhasil dengan sangat baik.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SameTypeAsOneBeforeGood::
	.string "Itu tipe yang sama dengan\n"
	.string "POKéMON sebelumnya--bagus!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_NotSameTypeAsOneBeforeGood::
	.string "Itu bukan tipe yang sama dengan\n"
	.string "yang sebelumnya--bagus!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoodOutMuchMoreThanMonBefore::
	.string "Itu jauh lebih menonjol\n"
	.string "daripada POKéMON sebelumnya.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_DidntDoAsWellAsMonBefore::
	.string "Itu tidak tampil sebaik\n"
	.string "POKéMON sebelumnya.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsConditionRoseAboveUsual::
	.string "Kondisi {STR_VAR_1}\n"
	.string "meningkat di atas normal.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsHotStatusMadeGreatAppeal::
	.string "Status panas {STR_VAR_1}\n"
	.string "membuatnya menjadi daya tarik yang hebat!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedUpInLineForNextAppeal::
	.string "Itu naik dalam antrean untuk\n"
	.string "banding berikutnya.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedBackInLineForNextAppeal::
	.string "Itu mundur satu baris\n"
	.string "untuk banding berikutnya.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ScrambledUpOrderForNextTurn::
	.string "Itu mengacaukan\n"
	.string "urutan untuk giliran berikutnya.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAtMonExpectantly::
	.string "HAKIM memandang\n"
	.string "{STR_VAR_1} dengan penuh harap.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverWell::
	.string "Kombo banding berjalan\n"
	.string "dengan baik.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverVeryWell::
	.string "Kombo banding berjalan\n"
	.string "dengan sangat baik.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverExcellently::
	.string "Kombo banding berjalan\n"
	.string "dengan luar biasa.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonManagedToAvertGaze::
	.string "{STR_VAR_1} berhasil\n"
	.string "mengalihkan pandangannya.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonManagedToAvoidSeeingIt::
	.string "{STR_VAR_1} berhasil\n"
	.string "menghindari melihatnya.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonIsntFazedByThatSortOfThing::
	.string "{STR_VAR_1} tidak terpengaruh\n"
	.string "oleh hal semacam itu.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonBecameALittleDistracted::
	.string "{STR_VAR_1} sedikit\n"
	.string "terganggu.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_TriedToStartleOtherPokemon::
	.string "Itu mencoba mengejutkan\n"
	.string "POKéMON lain.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonLookedDownOutOfDistraction::
	.string "{STR_VAR_1} menunduk\n"
	.string "karena terganggu.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonTurnedBackOutOfDistraction::
	.string "{STR_VAR_1} berbalik\n"
	.string "karena terganggu.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCouldntHelpUtteringCry::
	.string "{STR_VAR_1} tidak bisa menahan\n"
	.string "teriakan.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCouldntHelpLeapingUp::
	.string "{STR_VAR_1} tidak bisa menahan\n"
	.string "melompat.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonTrippedOutOfDistraction::
	.string "{STR_VAR_1} tersandung\n"
	.string "karena terganggu.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonWasTooNervousToMove::
	.string "{STR_VAR_1} terlalu\n"
	.string "gugup untuk bergerak.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItMessedUp2::
	.string "Tapi itu mengacau.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItFailedToMakeTargetNervous::
	.string "Tapi itu gagal membuat\n"
	.string "target gugup.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItFailedToMakeAnyoneNervous::
	.string "Tapi itu gagal membuat\n"
	.string "siapa pun gugup.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItWasIgnored::
	.string "Tapi itu diabaikan…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_CouldntImproveItsCondition::
	.string "Tapi itu tidak bisa memperbaiki\n"
	.string "kondisinya…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_BadConditionResultedInWeakAppeal::
	.string "Kondisi buruknya\n"
	.string "menghasilkan banding yang lemah.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonWasUnaffected::
	.string "{STR_VAR_1}\n"
	.string "tidak terpengaruh.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_RepeatedAppeal::
	.string "{STR_VAR_1} mengecewakan\n"
	.string "dengan mengulang banding.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXWentOverGreat::
	.string "{STR_VAR_3} milik {STR_VAR_1}\n"
	.string "berhasil dengan baik.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXDidntGoOverWell::
	.string "{STR_VAR_3} milik {STR_VAR_1}\n"
	.string "tidak berjalan baik di sini…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXGotTheCrowdGoing::
	.string "{STR_VAR_3} milik {STR_VAR_1}\n"
	.string "membuat penonton antusias.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCantAppealNextTurn::
	.string "{STR_VAR_1} tidak bisa menarik\n"
	.string "perhatian di giliran berikutnya…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AttractedCrowdsAttention::
	.string "Itu menarik perhatian\n"
	.string "penonton.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_CrowdContinuesToWatchMon::
	.string "Penonton terus\n"
	.string "menonton {STR_VAR_3}.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsMoveIsIgnored::
	.string "{STR_VAR_2} milik {STR_VAR_1}\n"
	.string "diabaikan.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_Contest_Shyness::
	.string "malu$"

gText_Contest_Anxiety::
	.string "kecemasan$"

gText_Contest_Laziness::
	.string "kemalasan$"

gText_Contest_Hesitancy::
	.string "keraguan$"

gText_Contest_Fear::
	.string "ketakutan$"
