@ With the exception of Link standby, none of the below texts are used

gTest_MissedTurn::
	.string "Melewatkan giliran$"

gText_LinkStandby4::
	.string "Tautan siaga!$"

gText_WinnerIsPlayersMonCongrats::
	.string "Pemenangnya adalah {STR_VAR_2} milik {STR_VAR_1}!\n"
	.string "Selamat!$"

gText_WinnerIsPlayersMon::
	.string "Pemenangnya adalah {STR_VAR_2} milik {STR_VAR_1}!{PAUSE_UNTIL_PRESS}$"

gText_PrimaryJudgingNumX::
	.string "Penilaian utama: No. {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_SecondaryJudgingNumX::
	.string "Penilaian sekunder: No. {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_SetEventNumX::
	.string "Atur acara: No. {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_MoveUsedMostOften::
	.string "Jurus yang paling sering digunakan:\n"
	.string "{STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_MostImpressiveMon::
	.string "POKéMON yang paling mengesankan:\n"
	.string "{STR_VAR_2} milik {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_SetEventNumX2::
	.string "Atur acara: No. {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_LinkTVProgramWillNotBeMadeTrainerLost::
	.string "Program TV tautan tidak akan dibuat\n"
	.string "karena TRAINER kalah.{PAUSE_UNTIL_PRESS}$"
