EventTicket_Text_OldSeaMapTooFar:
	.string "Ada apa, anak muda?\p"
	.string "Apa, kamulah yang seharusnya memiliki\n"
	.string "peta tua yang compang-camping?\p"
	.string "Mari kita lihat.\n"
	.string "… … … … … …\p"
	.string "Wah, ini cukup jauh.\n"
	.string "Aku takut tidak bisa membantumu…$"

EventTicket_Text_BrineyHoldOnASecond:
	.string "BRINEY: Tunggu sebentar!\p"
	.string "Apa maksudnya menolak\n"
	.string "seseorang yang sangat kubantu?$"

EventTicket_Text_BrineyLetsSail:
	.string "{PLAYER}{KUN}, Aku sangat menyesal.\p"
	.string "Kamu datang kepadaku mencari bantuanku,\n"
	.string "dan kami hampir menolakmu.\p"
	.string "Baiklah, biarkan aku memperbaikinya.\p"
	.string "Kita akan berlayar segera, tentu saja!\p"
	.string "Mari kita temukan pulau ini di\n"
	.string "PETA LAUT LAMA ini!$"

EventTicket_Text_OddTicketGetOnBoard:
	.string "Apakah kamu yang membawa tiket aneh\n"
	.string "itu?\p"
	.string "Tempat yang kamu coba tuju adalah pulau\n"
	.string "yang sangat, sangat jauh.\p"
	.string "Tidak ada yang tahu apa yang menanti di sana…\p"
	.string "Pikiran itu saja sudah membuat darahku\n"
	.string "mendidih sebagai seorang pelaut!\p"
	.string "Naiklah, anak muda!$"

FarawayIsland_Entrance_Text_SailorReturn:
	.string "KAPT. BRINEY bisa sangat menjengkelkan\n"
	.string "tidak tetap…\p"
	.string "Apakah kamu ingin kembali ke LILYCOVE?$"

BirthIsland_Harbor_Text_SailorReturn:
	.string "Pulau yang aneh bentuknya, ya?\n"
	.string "Apakah kamu ingin kembali ke LILYCOVE?$"

EventTicket_Text_OddTicketsWhereTo:
	.string "Apakah kamu yang membawa tiket-tiket\n"
	.string "aneh itu?\p"
	.string "… … …Hm.\p"
	.string "Tiket-tiket ini akan membawamu ke pulau-pulau\n"
	.string "yang sangat, sangat jauh.\p"
	.string "Tidak ada yang tahu apa yang menanti di sana,\n"
	.string "atau apa yang mungkin terjadi di sana.\p"
	.string "Pikiran itu saja sudah membuat darahku\n"
	.string "mendidih sebagai seorang pelaut!\p"
	.string "Naiklah, anak muda!\n"
	.string "Ke mana kita akan berlayar lebih dulu?$"

NavelRock_Harbor_Text_SailorReturn:
	.string "Apakah… Apakah kamu mendengar itu?\n"
	.string "Geraman rendah dari dalam sana.\p"
	.string "Apakah kamu yakin aman?\n"
	.string "Menurutmu kita harus pergi?$"

FarawayIsland_Entrance_Text_Sign:
	.string "Tulisannya memudar seolah-olah\n"
	.string "ditulis sudah lama sekali…\p"
	.string "“…ber, hari ke-6\n"
	.string "Jika ada manusia…menginjakkan kaki di sini…\l"
	.string "lagi…biarkan itu orang yang baik hati…\l"
	.string "…dengan harapan itu, aku pergi…”$"

FarawayIsland_Interior_Text_Mew:
	.string "Myuu…$"
