EventTicket_Text_ShowOldSeaMap:
	.string "Feri ke SLATEPORT adalah…\p"
	.string "Maaf?\n"
	.string "Bisakah kita berlayar ke tempat ini di peta?\p"
	.string "Aku tahu seseorang yang akan membantumu lebih baik.\n"
	.string "Mohon tunggu.$"

EventTicket_Text_ThatPass:
	.string "Feri ke SLATEPORT adalah…\p"
	.string "Oh?\n"
	.string "PASS itu…$"

EventTicket_Text_ShowEonTicket:
	.string "Aye, kawan, apakah kamu yang membawa\n"
	.string "PASS yang aneh itu?\p"
	.string "Aku akan memberitahumu, kamu mencoba mencapai\n"
	.string "pulau kecil yang jauh di selatan.\p"
	.string "Tidak ada yang tahu apa yang akan kita temui\n"
	.string "setelah kita sampai di sana, aye.\l"
	.string "Itu membuatku merinding!\p"
	.string "Semuanya naik!$"

EventTicket_Text_SouthernIslandSailBack:
	.string "Aye, kawan, tidak ada apa-apa di sini\n"
	.string "untuk dilihat atau dilakukan di pulau yang terlupakan ini.\p"
	.string "Bagaimana kalau kita berlayar kembali ke LILYCOVE?$"

EventTicket_Text_SailHome:
	.string "Aye, benar!\n"
	.string "Kita akan berlayar pulang!$"

EventTicket_Text_AsYouLike:
	.string "Aye, benar, seperti yang kamu mau.$"

SouthernIsland_Interior_Text_Sign:
	.string "“Semua mimpi hanyalah realitas lain.\n"
	.string "Jangan pernah lupa…”$"

SouthernIsland_Exterior_Text_Sign:
	.string "“Mereka yang ingatannya memudar mencari\n"
	.string "untuk mengukirnya di hati mereka…”$"
