LilycoveCity_DepartmentStore_1F_Text_LotteryCornerDrawTicket:
	.string "Ini adalah POKéMON LOTTERY CORNER.\p"
	.string "Semua pembeli di DEPARTMENT STORE kami\n"
	.string "mendapatkan kesempatan untuk menarik POKéMON LOTO TICKET.\p"
	.string "Jika nomor LOTO TICKET cocok dengan\n"
	.string "nomor ID salah satu POKéMON-mu,\l"
	.string "kamu akan menerima hadiah yang luar biasa.\p"
	.string "Apakah kamu ingin menarik POKéMON\n"
	.string "LOTO TICKET?$"

LilycoveCity_DepartmentStore_1F_Text_ComeBackTomorrow:
	.string "Silakan kembali besok.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain:
	.string "Silakan kunjungi lagi.$"

LilycoveCity_DepartmentStore_1F_Text_PleasePickTicket:
	.string "Silakan pilih LOTO TICKET.\n"
	.string "…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

LilycoveCity_DepartmentStore_1F_Text_TicketNumberIsXPleaseWait:
	.string "Nomor LOTO TICKET adalah {STR_VAR_1}.\p"
	.string "Aku perlu memeriksa nomor ini\n"
	.string "untuk melihat apakah cocok dengan nomor\l"
	.string "ID salah satu POKéMON-mu. Mohon tunggu.$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPartyMon:
	.string "Selamat!\p"
	.string "Nomor ID {STR_VAR_1} timmu\n"
	.string "cocok dengan nomor LOTO TICKET-mu!$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPCMon:
	.string "Congratulations!\p"
	.string "Nomor ID {STR_VAR_1} di PC-mu\n"
	.string "cocok dengan nomor LOTO TICKET-mu!$"

LilycoveCity_DepartmentStore_1F_Text_NoNumbersMatched:
	.string "Maaf.\n"
	.string "Tidak ada nomor yang cocok.$"

LilycoveCity_DepartmentStore_1F_Text_TwoDigitsMatched:
	.string "Dua digit cocok, jadi kamu memenangkan\n"
	.string "hadiah ketiga!\l"
	.string "Kamu memenangkan {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_ThreeDigitsMatched:
	.string "Tiga digit cocok, jadi kamu memenangkan\n"
	.string "hadiah kedua!\l"
	.string "Kamu memenangkan {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_FourDigitsMatched:
	.string "Empat digit cocok, jadi kamu memenangkan\n"
	.string "hadiah pertama!\l"
	.string "Kamu memenangkan {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_AllFiveDigitsMatched:
	.string "Ya ampun, kelima digitnya\n"
	.string "cocok!\p"
	.string "Kamu memenangkan hadiah jackpot!\n"
	.string "Kamu memenangkan {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_NoRoomForThis:
	.string "Oh?\n"
	.string "Sepertinya kamu tidak punya ruang untuk ini.\p"
	.string "Tolong buat ruang di TAS-mu dan\n"
	.string "beri tahu aku.$"

LilycoveCity_DepartmentStore_1F_Text_PrizeWeveBeenHolding:
	.string "{PLAYER}?\n"
	.string "Ya, aku sudah menunggumu.\p"
	.string "Ini adalah hadiah yang kami simpan\n"
	.string "untukmu.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain2:
	.string "Silakan kunjungi lagi.$"
