MatchCall_WildBattleText1::
	.string "Hai! Halo, {PLAYER}! Ini\n"
	.string "{STR_VAR_1}.\p"
	.string "Aku melihat {STR_VAR_2} ini\n"
	.string "beberapa waktu lalu, tapi Aku tidak\l"
	.string "berhasil menangkapnya.\p"
	.string "Padahal sudah dekat sekali! Sampai\n"
	.string "jumpa lagi!$"

MatchCall_WildBattleText2::
	.string "Halo, {PLAYER}. Ini {STR_VAR_1}.\p"
	.string "Aku mencoba menangkap {STR_VAR_2}\n"
	.string "yang bagus barusan.\p"
	.string "Tapi, dia lolos. Aku benar-benar\n"
	.string "kecewa!\p"
	.string "Oke, sampai jumpa!$"

MatchCall_WildBattleText3::
	.string "Hai, {PLAYER}! Ini Aku,\n"
	.string "{STR_VAR_1}.\p"
	.string "Aku baru saja mencoba menangkap\n"
	.string "{STR_VAR_2} ini, tapi dia kabur.\p"
	.string "Padahal sudah dekat sekali!\p"
	.string "Ini merusak hariku… Baiklah, sampai\n"
	.string "jumpa!$"

MatchCall_WildBattleText4::
	.string "Hei, {PLAYER}. Ini {STR_VAR_1}.\p"
	.string "Kamu tahu POKéMON {STR_VAR_2}? Aku\n"
	.string "hampir mendapatkannya.\p"
	.string "Baru saja. Aku pikir Aku berhasil,\n"
	.string "tapi dia kabur.\p"
	.string "Kalau Aku melihatnya lagi, Aku\n"
	.string "pasti akan menangkapnya.\p"
	.string "Oke, sampai nanti.$"

MatchCall_WildBattleText5::
	.string "Hai, {PLAYER}! Ini {STR_VAR_1}. Apa\n"
	.string "Kamu sudah menangkap POKéMON\l"
	.string "akhir-akhir ini?\p"
	.string "Barusan Aku hampir saja\n"
	.string "menangkapnya, tapi dia lepas.\p"
	.string "Baiklah, hati-hati!$"

MatchCall_WildBattleText6::
	.string "Hei, {PLAYER}. Ini {STR_VAR_1}.\n"
	.string "Sudah tangkap POKéMON akhir-akhir\l"
	.string "ini?\p"
	.string "Kemarin Aku hampir menangkapnya.\n"
	.string "Tapi entah bagaimana dia lolos.\p"
	.string "Kamu hati-hati.$"

MatchCall_WildBattleText7::
	.string "…Uh, {PLAYER}? Ini Aku,\n"
	.string "{STR_VAR_1}.\p"
	.string "Oh, tunggu! Tunggu! Aku bisa\n"
	.string "menangkap {STR_VAR_2} ini…\p"
	.string "Aaarrrgh! Dia kabur! Padahal sudah\n"
	.string "sedekat itu!$"

MatchCall_WildBattleText8::
	.string "Oh, {PLAYER}, apa kabar? Ini\n"
	.string "{STR_VAR_1}.\p"
	.string "Apa Kamu berhasil menangkap POKéMON\n"
	.string "akhir-akhir ini?\p"
	.string "Aku sudah sangat dekat barusan,\n"
	.string "tapi targetku lepas.\p"
	.string "Aku harus berusaha lebih keras!\n"
	.string "Sampai jumpa lagi!$"

MatchCall_WildBattleText9::
	.string "Oh, {PLAYER}, halo! Ini\n"
	.string "{STR_VAR_1}!\p"
	.string "Jadi? Apa Kamu sudah mengumpulkan\n"
	.string "lebih banyak POKéMON?\p"
	.string "Aku sedang sial! Mereka semua lolos\n"
	.string "dariku!\p"
	.string "Sampai jumpa!$"

MatchCall_WildBattleText10::
	.string "Oh, {PLAYER}, halo… Ini\n"
	.string "{STR_VAR_1}.\p"
	.string "Dengar, Aku hampir sekali menangkap\n"
	.string "{STR_VAR_2} ini…\p"
	.string "Tapi, dia berhasil menghindariku…\p"
	.string "Aku harus berusaha lebih keras.\n"
	.string "Sampai ketemu.$"

MatchCall_WildBattleText11::
	.string "Ah, {PLAYER}. Ini {STR_VAR_1}.\n"
	.string "Bagaimana kabarmu?\p"
	.string "Aku mencoba menangkap {STR_VAR_2}\n"
	.string "liar tadi, tapi dia berhasil kabur.\p"
	.string "Aku merasa kalah…$"

MatchCall_WildBattleText12::
	.string "Halo, {PLAYER}. Ini Aku,\n"
	.string "{STR_VAR_1}. Apa Kamu masih\l"
	.string "menangkap POKéMON?\p"
	.string "Aku juga sudah mencoba\n"
	.string "menangkapnya, tapi tidak mudah.\p"
	.string "Jalan POKéMON itu mendalam!$"

MatchCall_WildBattleText13::
	.string "Ah, halo, {PLAYER}! Ini\n"
	.string "{STR_VAR_1}! Apa Kamu sudah\l"
	.string "menangkap POKéMON?\p"
	.string "Aku sudah mencoba menangkapnya\n"
	.string "sendiri, tapi hasilnya sedikit.\p"
	.string "Jalan POKéMON itu mendalam!$"

MatchCall_WildBattleText14::
	.string "Oh, hai, {PLAYER}, apa kabar? Ini\n"
	.string "{STR_VAR_1}.\p"
	.string "Baru saja, Aku mencoba menangkap\n"
	.string "{STR_VAR_2} yang lucu.\p"
	.string "Tapi dia kabur! Wah, Aku\n"
	.string "benar-benar kecewa!\p"
	.string "Dadah!$"

MatchCall_WildBattleText15::
	.string "Hei, {PLAYER}! Ini {STR_VAR_1}!\p"
	.string "Aku sedang berpikir untuk mencoba\n"
	.string "menangkap beberapa POKéMON.\p"
	.string "Tapi Aku tidak bisa menemukan satu\n"
	.string "pun. Ini membingungkan Aku!\p"
	.string "Aku sudah kehabisan akal! Sampai\n"
	.string "ketemu!$"

MatchCall_NegativeBattleText1::
	.string "Hai! Halo, {PLAYER}! Ini\n"
	.string "{STR_VAR_1}.\p"
	.string "Aku mencoba melawan TRAINER lain,\n"
	.string "tapi Aku kalah.\p"
	.string "Itu benar-benar mengecewakan.\n"
	.string "Sampai jumpa lagi!$"

MatchCall_NegativeBattleText2::
	.string "Halo, {PLAYER}. Ini {STR_VAR_1}.\p"
	.string "Aku menantang orang lain setelah\n"
	.string "kita bertarung.\p"
	.string "Aku hampir menang, tapi akhirnya\n"
	.string "Aku kalah. Sudahlah!$"

MatchCall_NegativeBattleText3::
	.string "Hai, {PLAYER}! Ini Aku,\n"
	.string "{STR_VAR_1}.\p"
	.string "Aku baru saja kalah telak dalam\n"
	.string "pertarungan.\p"
	.string "Kurasa Aku perlu melatih timku\n"
	.string "lebih banyak lagi!$"

MatchCall_NegativeBattleText4::
	.string "Hei, {PLAYER}. Ini {STR_VAR_1}.\p"
	.string "Aku mencoba bertarung lagi kemarin,\n"
	.string "tapi Aku tidak berhasil menang.\p"
	.string "Timku perlu lebih banyak pelatihan.\n"
	.string "Oke, sampai nanti.$"

MatchCall_NegativeBattleText5::
	.string "Hai, {PLAYER}! Ini {STR_VAR_1}.\p"
	.string "Bagaimana kabarmu?\p"
	.string "Aku terus bertarung, tapi Aku tidak\n"
	.string "sering menang.\p"
	.string "Aku tidak bisa menguasainya.\n"
	.string "Baiklah, hati-hati!$"

MatchCall_NegativeBattleText6::
	.string "Hei, {PLAYER}. Ini {STR_VAR_1}.\p"
	.string "Bagaimana kabarmu?\p"
	.string "Aku sudah bertarung keras\n"
	.string "akhir-akhir ini, tapi sedikit\l"
	.string "berhasil.\p"
	.string "Aku tidak bisa menemukan ritmenya.\n"
	.string "Kamu hati-hati.$"

MatchCall_NegativeBattleText7::
	.string "Ini {STR_VAR_1}. Bagaimana kabar\n"
	.string "akhir-akhir ini?\p"
	.string "Aku kalah bertarung kemarin, dan\n"
	.string "itu memenuhi pikiranku.\p"
	.string "Aku harus menyusun rencana… Sampai\n"
	.string "jumpa.$"

MatchCall_NegativeBattleText8::
	.string "Oh, {PLAYER}, apa kabar? Ini\n"
	.string "{STR_VAR_1}.\p"
	.string "Bagaimana kabar POKéMON-mu? Aku\n"
	.string "kalah bertarung tempo hari.\p"
	.string "Aku harus berusaha lebih keras!\n"
	.string "Sampai jumpa lagi!$"

MatchCall_NegativeBattleText9::
	.string "Oh, {PLAYER}, halo! Ini\n"
	.string "{STR_VAR_1}!\p"
	.string "Dengar, dengar, Kamu harus dengar\n"
	.string "ini!\p"
	.string "Aku bertarung POKéMON tadi, tapi\n"
	.string "Aku kalah di detik terakhir.\p"
	.string "Oh, ini membuatku kesal!$"

MatchCall_NegativeBattleText10::
	.string "Oh, {PLAYER}, halo… Ini\n"
	.string "{STR_VAR_1}.\p"
	.string "Baru saja, Aku bertarung. Tapi Aku\n"
	.string "kalah.\p"
	.string "Aku perlu melatih POKéMON-ku lebih\n"
	.string "banyak. Sampai ketemu.$"

MatchCall_NegativeBattleText11::
	.string "Ah, {PLAYER}. Ini {STR_VAR_1}.\n"
	.string "Bagaimana POKéMON-mu?\p"
	.string "Aku baru saja kalah lagi dalam\n"
	.string "pertarungan.\p"
	.string "Baiklah, sampai jumpa!$"

MatchCall_NegativeBattleText12::
	.string "Halo, {PLAYER}. Ini Aku,\n"
	.string "{STR_VAR_1}. Apa Kamu masih\l"
	.string "bertarung keras?\p"
	.string "Sedangkan Aku, Aku kalah baru-baru\n"
	.string "ini, jadi Aku melatih ulang timku.\p"
	.string "Mari bertemu lagi.$"

MatchCall_NegativeBattleText13::
	.string "Ah, halo, {PLAYER}! Ini\n"
	.string "{STR_VAR_1}! Apa Kamu sudah\l"
	.string "menangkap POKéMON?\p"
	.string "Aku sudah mencoba menangkapnya\n"
	.string "sendiri, tapi sedikit berhasil.\p"
	.string "Jalan POKéMON itu mendalam!\p"
	.string "Oh, hai, {PLAYER}. Ini {STR_VAR_1}.$"

MatchCall_NegativeBattleText14::
	.string "Apa Kamu baik-baik saja?\p"
	.string "Tapi, Kamu harus pulang sesekali.\p"
	.string "Dadah!\p"
	.string "Hai! Halo, {PLAYER}! Ini\n"
	.string "{STR_VAR_1}!$"

MatchCall_PositiveBattleText1::
	.string "Aku melawan TRAINER lain tadi. Aku\n"
	.string "menang! Aku menang!\p"
	.string "{STR_VAR_2}-ku bekerja keras\n"
	.string "untukku. Ini hebat sekali!\p"
	.string "Halo, {PLAYER}! Ini {STR_VAR_1}!$"

MatchCall_PositiveBattleText2::
	.string "Aku bertarung kemarin dan Aku\n"
	.string "menang! Ini luar biasa!\p"
	.string "Hai, {PLAYER}! Ini Aku,\n"
	.string "{STR_VAR_1}! Bagaimana\l"
	.string "pertarunganmu?$"

MatchCall_PositiveBattleText3::
	.string "Aku, Aku bertarung tempo hari, dan\n"
	.string "{STR_VAR_2}-ku tampil hebat!\p"
	.string "Lain kali kita bertarung, {PLAYER},\n"
	.string "Aku tidak akan kalah lagi!\p"
	.string "Hei, {PLAYER}. Ini {STR_VAR_1}.$"

MatchCall_PositiveBattleText4::
	.string "Aku bertarung tadi. Aku berhasil\n"
	.string "menang, tapi tipis sekali.\p"
	.string "{STR_VAR_2}-ku menunjukkan\n"
	.string "penampilan yang menginspirasi.\p"
	.string "Hai, {PLAYER}! Ini {STR_VAR_1}.$"

MatchCall_PositiveBattleText5::
	.string "Bagaimana kabarmu? Sering\n"
	.string "bertarung?\p"
	.string "Aku baru saja menang tadi!\n"
	.string "{STR_VAR_2}-ku hebat!\p"
	.string "Tunggu saja. Aku akan mengalahkanmu\n"
	.string "lain kali! Baiklah, hati-hati!\p"
	.string "Hei, {PLAYER}. Ini {STR_VAR_1}.$"

MatchCall_PositiveBattleText6::
	.string "Bagaimana kabarmu?\p"
	.string "Aku sedang beruntung. Aku baru saja\n"
	.string "memenangkan pertarungan.\p"
	.string "Saat kita bertarung lagi, Aku yakin\n"
	.string "tidak akan kalah!\p"
	.string "{PLAYER}? Ini {STR_VAR_1}.$"

MatchCall_PositiveBattleText7::
	.string "{STR_VAR_2}-ku kuat sekali! Dia\n"
	.string "memenangkanku pertarungan barusan!\p"
	.string "Aku tidak sabar untuk bertarung\n"
	.string "ulang denganmu.\p"
	.string "Oh, {PLAYER}, apa kabar? Ini\n"
	.string "{STR_VAR_1}.$"

MatchCall_PositiveBattleText8::
	.string "Aku harap Kamu baik-baik saja. Aku\n"
	.string "ingin memberitahu Kamu, Aku baru\l"
	.string "saja menang.\p"
	.string "{STR_VAR_2}-ku berusaha sangat\n"
	.string "keras untuk meraih kemenangan itu.\p"
	.string "Sampai jumpa lagi!\p"

MatchCall_PositiveBattleText9::
	.string "Oh, {PLAYER}{KUN}, hai! Ini\n"
	.string "{STR_VAR_1}!\p"
	.string "Bagaimana kabar POKéMON kamu?\n"
	.string "POKéMON milikku baru saja\l"
	.string "memenangkan pertarungan!\p"
	.string "{STR_VAR_2} milikku sangat\n"
	.string "spektakuler, aku harus bilang\l"
	.string "begitu!\p"
	.string "Aku berharap aku bisa\n"
	.string "menunjukkannya padamu! Sampai jumpa\l"
	.string "lagi!$"

MatchCall_PositiveBattleText10::
	.string "Oh, {PLAYER}{KUN}, halo… Ini\n"
	.string "{STR_VAR_1}.\p"
	.string "Bagaimana kabarmu?\p"
	.string "POKéMON milikku terlihat penuh\n"
	.string "energi.\p"
	.string "Aku baru saja memenangkan\n"
	.string "pertarungan bersama mereka. Sampai\l"
	.string "jumpa.$"

MatchCall_PositiveBattleText11::
	.string "Ah, {PLAYER}{KUN}. Ini {STR_VAR_1}.\p"
	.string "Apakah kamu ikut pertarungan\n"
	.string "akhir-akhir ini? Aku baru saja\l"
	.string "menang lagi hari ini!\p"
	.string "Aku sedang beruntung! Gahahaha!\n"
	.string "Baiklah, sampai jumpa!$"

MatchCall_PositiveBattleText12::
	.string "Halo, {PLAYER}{KUN}. Ini aku,\n"
	.string "{STR_VAR_1}.\p"
	.string "Aku harap kamu baik-baik saja? Aku\n"
	.string "masih penuh semangat!\p"
	.string "Baru saja, aku memenangkan\n"
	.string "pertandingan lain. Aku belum mau\l"
	.string "menyerah pada kalian, para junior!$"

MatchCall_PositiveBattleText13::
	.string "Ah, halo, {PLAYER}{KUN}! Ini\n"
	.string "{STR_VAR_1}!\p"
	.string "Aku harap kamu baik-baik saja. Aku\n"
	.string "masih bersemangat!\p"
	.string "Yah, aku baru saja memenangkan\n"
	.string "pertarungan lagi. Oh, aku belum\l"
	.string "akan kalah dari anak muda!\p"
	.string "Sampai jumpa lagi!$"

MatchCall_PositiveBattleText14::
	.string "Oh, hai, {PLAYER}{KUN}. Ini\n"
	.string "{STR_VAR_1}.\p"
	.string "Aku baru saja bertarung, dan\n"
	.string "{STR_VAR_2} milikku luar biasa!\p"
	.string "Aku berharap kamu bisa melihatnya,\n"
	.string "{PLAYER}{KUN}. Sampai jumpa!$"

MatchCall_SameRouteBattleRequestText1::
	.string "Hai! {PLAYER}, halo! Ini\n"
	.string "{STR_VAR_1}.\p"
	.string "Hah? Tunggu, kamu dekat\n"
	.string "{STR_VAR_2}?\p"
	.string "Oh, wah, kalau begitu kita harus\n"
	.string "bertarung! Aku akan menunggu!\l"
	.string "Sampai jumpa!$"

MatchCall_SameRouteBattleRequestText2::
	.string "Halo, {PLAYER}! Ini {STR_VAR_1}.\p"
	.string "Oh? Kamu kebetulan ada di sekitar\n"
	.string "{STR_VAR_2} sekarang?\p"
	.string "Apakah kamu mau bertarung sekarang?\n"
	.string "Aku akan menunggumu! Sampai jumpa!$"

MatchCall_SameRouteBattleRequestText3::
	.string "Hei, {PLAYER}! Ini aku,\n"
	.string "{STR_VAR_1}.\p"
	.string "Oh, hei, apakah kamu dekat\n"
	.string "{STR_VAR_2} sekarang?\p"
	.string "Bagaimana kalau kamu bertarung\n"
	.string "denganku sekarang?\p"
	.string "Aku tidak akan kalah lagi! Aku akan\n"
	.string "menunggu! Sampai jumpa!$"

MatchCall_SameRouteBattleRequestText4::
	.string "Hei, {PLAYER}{KUN}. {STR_VAR_1} di\n"
	.string "sini.\p"
	.string "Di mana kamu sekarang? Hah?\n"
	.string "{STR_VAR_2}?\p"
	.string "Mau bertarung sekarang? Aku akan\n"
	.string "menunggumu. Sampai jumpa!$"

MatchCall_SameRouteBattleRequestText5::
	.string "Hai, {PLAYER}{KUN}! Ini\n"
	.string "{STR_VAR_1}. Bagaimana kabarmu?\p"
	.string "Kamu ada di mana sekarang?\n"
	.string "{STR_VAR_2}?\p"
	.string "Nah, bagaimana kalau kita langsung\n"
	.string "adakan pertandingan ulang cepat?\p"
	.string "Aku akan mengawasimu. Sampai jumpa\n"
	.string "lagi!$"

MatchCall_SameRouteBattleRequestText6::
	.string "Hei, {PLAYER}{KUN}. {STR_VAR_1} di\n"
	.string "sini. Bagaimana kabar POKéMON kamu?\p"
	.string "Oh, benarkah? Kamu ada di sekitar\n"
	.string "{STR_VAR_2}?\p"
	.string "Kalau begitu, lebih baik kita\n"
	.string "adakan pertandingan ulang.\p"
	.string "Aku bisa menunggu, tentu saja.\n"
	.string "Sampai jumpa!$"

MatchCall_SameRouteBattleRequestText7::
	.string "…Er, {PLAYER}{KUN}? {STR_VAR_1} di\n"
	.string "sini…\p"
	.string "Oh, kamu kebetulan ada di sekitar\n"
	.string "{STR_VAR_2}?\p"
	.string "Kalau begitu, ayo bertarung.\n"
	.string "Maksudku, sekarang juga.\p"
	.string "Aku akan menunjukkan POKéMON\n"
	.string "milikku. Aku akan menunggumu.$"

MatchCall_SameRouteBattleRequestText8::
	.string "Oh, {PLAYER}{KUN}, apa kabar? Ini\n"
	.string "{STR_VAR_1} bicara.\p"
	.string "Aku harap kamu baik-baik saja. Oh,\n"
	.string "kamu dekat {STR_VAR_2}.\p"
	.string "Kalau begitu, apakah kamu mau\n"
	.string "bertarung denganku?\p"
	.string "Aku akan menunggumu. Sampai jumpa\n"
	.string "lagi!$"

MatchCall_SameRouteBattleRequestText9::
	.string "Oh, {PLAYER}{KUN}, hai! Ini\n"
	.string "{STR_VAR_1}!\p"
	.string "Apakah kamu baik-baik saja? Oh,\n"
	.string "kamu dekat {STR_VAR_2}?\p"
	.string "Oh, kalau begitu, bukankah\n"
	.string "sebaiknya kita bertarung?\p"
	.string "Jangan membuatku menunggu terlalu\n"
	.string "lama!$"

MatchCall_SameRouteBattleRequestText10::
	.string "Oh, {PLAYER}{KUN}, halo… Ini\n"
	.string "{STR_VAR_1}.\p"
	.string "Bagaimana kabarmu? Oh, kamu dekat\n"
	.string "{STR_VAR_2}.\p"
	.string "Kalau begitu, kita harus bertarung\n"
	.string "sekarang.\p"
	.string "Aku siap dan menunggu. Cepatlah!$"

MatchCall_SameRouteBattleRequestText11::
	.string "Ah, {PLAYER}{KUN}. Ini {STR_VAR_1}.\p"
	.string "Ah, jadi kamu ada di {STR_VAR_2}\n"
	.string "sekarang?\p"
	.string "Nah, kalau begitu, kita harus\n"
	.string "bertarung, bukan?\p"
	.string "Aku akan menunggumu di sini! Sampai\n"
	.string "jumpa sebentar lagi!$"

MatchCall_SameRouteBattleRequestText12::
	.string "Halo, {PLAYER}{KUN}. Ini aku,\n"
	.string "{STR_VAR_1}. Kamu ada di mana\l"
	.string "sekarang?\p"
	.string "{STR_VAR_2}? Itu cukup dekat!\p"
	.string "Bagaimana kalau kita bertarung\n"
	.string "sekarang?\p"
	.string "Aku bisa menunggu. Sampai jumpa!$"

MatchCall_SameRouteBattleRequestText13::
	.string "Ah, halo, {PLAYER}{KUN}! Ini\n"
	.string "{STR_VAR_1}!\p"
	.string "Aku harap kamu baik-baik saja. Oh,\n"
	.string "kamu dekat {STR_VAR_2}?\p"
	.string "Karena itu tidak terlalu jauh,\n"
	.string "datanglah menemuiku untuk\l"
	.string "bertarung.\p"
	.string "Aku akan menunggumu. Sampai nanti.$"

MatchCall_SameRouteBattleRequestText14::
	.string "Oh, hai, {PLAYER}{KUN}. Ini\n"
	.string "{STR_VAR_1}.\p"
	.string "Kamu di mana? …{STR_VAR_2}? Itu\n"
	.string "sangat dekat.\p"
	.string "Bukankah sebaiknya kita bertarung?\p"
	.string "Aku akan mencarimu! Sampai jumpa!$"

MatchCall_DifferentRouteBattleRequestText1::
	.string "Hai! {PLAYER}, halo! Ini\n"
	.string "{STR_VAR_1}.\p"
	.string "Mau bertarung denganku?\p"
	.string "Aku akan menunggumu di sekitar\n"
	.string "{STR_VAR_2}!$"

MatchCall_DifferentRouteBattleRequestText2::
	.string "Halo, {PLAYER}! Ini {STR_VAR_1}.\p"
	.string "Apakah kamu mau bertarung lagi\n"
	.string "denganku?\p"
	.string "Kamu bisa menemukanku di sekitar\n"
	.string "{STR_VAR_2}. Aku akan menunggu!$"

MatchCall_DifferentRouteBattleRequestText3::
	.string "Hei, {PLAYER}! Ini aku,\n"
	.string "{STR_VAR_1}.\p"
	.string "POKéMON milikku jadi jauh lebih\n"
	.string "tangguh sejak terakhir kali.\p"
	.string "Aku ingin melihat seberapa kuat\n"
	.string "mereka bersama POKéMON kamu,\l"
	.string "{PLAYER}.\p"
	.string "Jadi, ayo kita bertarung!\p"
	.string "Aku akan menunggumu di sekitar\n"
	.string "{STR_VAR_2}.$"

MatchCall_DifferentRouteBattleRequestText4::
	.string "Hei, {PLAYER}{KUN}. {STR_VAR_1} di\n"
	.string "sini. Bagaimana kabarmu?\p"
	.string "POKéMON milikku menjadi cukup\n"
	.string "tangguh akhir-akhir ini.\p"
	.string "Hei, bagaimana kalau kita bertarung\n"
	.string "lagi denganku?\p"
	.string "Ayo kita bertemu di sekitar\n"
	.string "{STR_VAR_2}, oke?$"

MatchCall_DifferentRouteBattleRequestText5::
	.string "Hai, {PLAYER}{KUN}! Ini\n"
	.string "{STR_VAR_1}.\p"
	.string "POKéMON milikku tumbuh dengan baik.\p"
	.string "Aku benar-benar ingin bertarung\n"
	.string "lagi denganmu.\p"
	.string "Aku akan menunggumu di sekitar\n"
	.string "{STR_VAR_2}. Sampai jumpa lagi!$"

MatchCall_DifferentRouteBattleRequestText6::
	.string "Hei, {PLAYER}{KUN}. {STR_VAR_1} di\n"
	.string "sini. Aku harap kamu baik-baik\l"
	.string "saja.\p"
	.string "Aku berpikir ingin bertarung lagi\n"
	.string "denganmu. Bagaimana menurut kamu?\p"
	.string "Jika kamu ingin bertarung,\n"
	.string "datanglah ke {STR_VAR_2}.\p"
	.string "Sampai jumpa!$"

MatchCall_DifferentRouteBattleRequestText7::
	.string "…Er, {PLAYER}{KUN}? {STR_VAR_1} di\n"
	.string "sini… Jadi? Apakah POKéMON kamu\l"
	.string "berkembang?\p"
	.string "Milikku pasti jadi lebih kuat. Aku\n"
	.string "ingin menunjukkannya padamu.\p"
	.string "Aku akan ada di sekitar\n"
	.string "{STR_VAR_2}. Temui aku untuk\l"
	.string "pertandingan.\p"
	.string "Sampai jumpa.$"

MatchCall_DifferentRouteBattleRequestText8::
	.string "Oh, {PLAYER}{KUN}, apa kabar? Ini\n"
	.string "{STR_VAR_1} bicara.\p"
	.string "Aku harap kamu baik-baik saja.\n"
	.string "POKéMON milikku sangat lincah.\p"
	.string "Jika kamu berada di area ini,\n"
	.string "tolong adakan pertandingan ulang\l"
	.string "denganku.\p"
	.string "Aku akan berada di sekitar\n"
	.string "{STR_VAR_2}. Sampai saat itu,\l"
	.string "selamat tinggal!$"

MatchCall_DifferentRouteBattleRequestText9::
	.string "Oh, {PLAYER}{KUN}, hai! Ini\n"
	.string "{STR_VAR_1}! Bagaimana kabar\l"
	.string "POKéMON kamu?\p"
	.string "POKéMON milikku terus membaik. Aku\n"
	.string "ingin menunjukkannya padamu,\l"
	.string "{PLAYER}{KUN}.\p"
	.string "Aku ada di sekitar {STR_VAR_2}\n"
	.string "sekarang, jadi mari kita bertarung\l"
	.string "jika kamu dekat.\p"
	.string "Semoga kita segera bertemu!$"

MatchCall_DifferentRouteBattleRequestText10::
	.string "Oh, {PLAYER}{KUN}, halo… Ini\n"
	.string "{STR_VAR_1}. Jadi, bagaimana\l"
	.string "kabarmu?\p"
	.string "POKéMON milikku tumbuh jauh lebih\n"
	.string "kuat dari sebelumnya.\p"
	.string "Aku ingin sekali bertarung lagi\n"
	.string "denganmu, {PLAYER}{KUN}.\p"
	.string "Aku akan berada di sekitar\n"
	.string "{STR_VAR_2}. Temui aku jika kamu\l"
	.string "dekat.$"

MatchCall_DifferentRouteBattleRequestText11::
	.string "Ah, {PLAYER}{KUN}. Ini {STR_VAR_1}.\n"
	.string "Kamu mungkin ada di mana sekarang?\p"
	.string "POKéMON milikku penuh semangat.\n"
	.string "Mereka terlihat menantikan untuk\l"
	.string "bertemu POKéMON kamu,\n"
	.string "{PLAYER}{KUN}.\p"
	.string "Aku ada di sekitar {STR_VAR_2}\n"
	.string "sekarang. Aku harap kamu akan\l"
	.string "mencari kami.$"

MatchCall_DifferentRouteBattleRequestText12::
	.string "Halo, {PLAYER}{KUN}. Ini aku,\n"
	.string "{STR_VAR_1}.\p"
	.string "Aku harus memberitahumu,\n"
	.string "akhir-akhir ini POKéMON-ku tumbuh\l"
	.string "menjadi sangat kuat.\p"
	.string "Aku ingin mengadu mereka dalam\n"
	.string "pertarungan melawan kamu,\l"
	.string "{PLAYER}{KUN}.\p"
	.string "Kami akan berada di sekitar\n"
	.string "{STR_VAR_2}. Datang dan temui kami\l"
	.string "kapan saja!$"

MatchCall_DifferentRouteBattleRequestText13::
	.string "Ah, halo, {PLAYER}{KUN}! Ini\n"
	.string "{STR_VAR_1}! Apakah POKéMON-mu\l"
	.string "baik-baik saja?\p"
	.string "POKéMON-ku sangat sehat, mereka\n"
	.string "terlihat mustahil untuk kalah!\p"
	.string "Aku pasti senang bisa bertarung\n"
	.string "lagi dengan kamu.\p"
	.string "Jika kamu dekat {STR_VAR_2},\n"
	.string "datanglah menemui kami.$"

MatchCall_DifferentRouteBattleRequestText14::
	.string "Oh, hai, {PLAYER}{KUN}. Ini\n"
	.string "{STR_VAR_1}. Kuharap kamu baik-baik\l"
	.string "saja.\p"
	.string "Oh, ya! POKéMON-ku jauh lebih kuat\n"
	.string "dari sebelumnya.\p"
	.string "Tidakkah menurutmu kita harus\n"
	.string "bertarung, {PLAYER}{KUN}?\p"
	.string "Kami akan menunggumu di sekitar\n"
	.string "{STR_VAR_2}.\p"
	.string "Datang dan temui kami kapan saja,\n"
	.string "ya?$"

MatchCall_PersonalizedText1::
	.string "Ini aku, si pencinta gunung,\n"
	.string "{STR_VAR_1}!\p"
	.string "Nah, sejak kita bertemu, apakah\n"
	.string "kamu jadi lebih menghargai gunung?\p"
	.string "Aku jarang melihatmu di gunung…\p"
	.string "Lain kali, kita akan bertemu di\n"
	.string "sekitar {STR_VAR_2}.$"

MatchCall_PersonalizedText2::
	.string "Ini {STR_VAR_1}. Halo.\p"
	.string "Aku baru saja menceritakan tentang\n"
	.string "kamu kepada seorang PELATIH baru.\p"
	.string "Aku memberitahunya tentang PELATIH\n"
	.string "kuat yang memelihara POKéMON dengan\l"
	.string "hati-hati.\p"
	.string "Aku harap kamu akan menjadi PELATIH\n"
	.string "yang dikagumi semua orang.\p"
	.string "Aku harap kita bertemu lagi!$"

MatchCall_PersonalizedText3::
	.string "Halo! Ini {STR_VAR_1}.\p"
	.string "Aku suka tempatku sekarang.\n"
	.string "Menyenangkan dengan aroma manis!\p"
	.string "Kurasa seseorang menanam BERRIES,\n"
	.string "dan itu mekar.\p"
	.string "Sampai jumpa lagi nanti!$"

MatchCall_PersonalizedText4::
	.string "Halo! Tiga puluh tahun eksplorasi,\n"
	.string "{STR_VAR_1} siap melayani kamu!\p"
	.string "Sepertinya kamu bepergian ke sana\n"
	.string "kemari dengan energik.\p"
	.string "Apakah kamu menemukan reruntuhan\n"
	.string "baru? Tolong beritahu aku jika iya!\p"
	.string "Sekarang, permisi, aku harus\n"
	.string "menjelajahi reruntuhan.$"

MatchCall_PersonalizedText5::
	.string "Ini {STR_VAR_1}!\p"
	.string "Tahukah kamu apa yang aku lakukan\n"
	.string "hari ini? Melihat ombak dari\l"
	.string "pantai!\p"
	.string "Huh… Ombaknya berkilauan. Laut\n"
	.string "terlihat paling cantik dari sini.\l"
	.string "Aku mulai lapar, jadi sampai jumpa!$"

MatchCall_PersonalizedText6::
	.string "Kunyah-kunyah… Oh, hai, ini\n"
	.string "{STR_VAR_1}. Aku suka makan di\l"
	.string "pantai.\p"
	.string "POKéMON-ku dan aku baik-baik saja.\n"
	.string "Kami sudah terisi penuh! Aku mau\l"
	.string "berenang. Sampai jumpa!$"

MatchCall_PersonalizedText7::
	.string "Halo, ini {STR_VAR_1}…\p"
	.string "Aku agak bosan dengan seluruh\n"
	.string "urusan COOLTRAINER ini…\p"
	.string "Semua orang mengira aku adalah\n"
	.string "PELATIH yang sempurna, dan itu\l"
	.string "membuatku berusaha memenuhi harapan\n"
	.string "itu.\p"
	.string "Tapi kurasa itulah konsekuensi\n"
	.string "menjadi COOLTRAINER.\p"
	.string "Aku hanya perlu berusaha keras… dan\n"
	.string "tersenyum, lalu menanggungnya.\p"
	.string "Kamu adalah satu-satunya orang yang\n"
	.string "bisa aku curhati seperti ini.\p"
	.string "Tapi saat aku bertemu kamu lagi,\n"
	.string "jangan khawatir, aku tidak akan\l"
	.string "mengeluh!$"

MatchCall_PersonalizedText8::
	.string "Yahoo, ini {STR_VAR_1}! Bagaimana\n"
	.string "kabarmu?\p"
	.string "Aku telah melatih POKéMON-ku dengan\n"
	.string "kamu sebagai target.\p"
	.string "Aku tidak berniat kalah saat kita\n"
	.string "bertarung lagi.\p"
	.string "Bukankah menyenangkan memiliki\n"
	.string "teman PELATIH? Mari kita bertemu\l"
	.string "lagi!$"

MatchCall_PersonalizedText9::
	.string "Ini {STR_VAR_1}… Sekarang, di\n"
	.string "belakangmu… Bukankah ada sesuatu…?\p"
	.string "Kekuatan POKéMON yang tidur di sini\n"
	.string "di MT. PYRE…\p"
	.string "Itu memberitahuku tentang kamu…\p"
	.string "Kamu harus segera pergi dan jangan\n"
	.string "pernah menoleh ke belakang…\p"
	.string "Kekeh… Selamat tinggal…$"

MatchCall_PersonalizedText10::
	.string "Ini {STR_VAR_1}. Apa kabar?\p"
	.string "Bukankah nyaman kita bisa mengobrol\n"
	.string "seperti ini dari jauh?\p"
	.string "Dulu, jika aku ingin berbicara\n"
	.string "dengan siapa pun, aku harus meminta\l"
	.string "ayahku mengantarku…\p"
	.string "Aku harus pergi sekarang. Aku\n"
	.string "senang kita sempat mengobrol.$"

MatchCall_PersonalizedText11::
	.string "Ini {STR_VAR_1}! Maukah kamu\n"
	.string "mendengarkan ini?\p"
	.string "Aku sangat suka SAFARI ZONE, tapi\n"
	.string "setiap kali aku pergi, aku selalu\l"
	.string "tersesat!\p"
	.string "Semua rumput tinggi itu! Dan\n"
	.string "areanya terlalu luas!\p"
	.string "Aku merasa lebih baik setelah\n"
	.string "melampiaskan itu!\p"
	.string "Aku pergi ke SAFARI ZONE lagi!\n"
	.string "Sampai jumpa!$"

MatchCall_PersonalizedText12::
	.string "Halo, {STR_VAR_1} di sini. Ya,\n"
	.string "benar, aku kaya, ya.\p"
	.string "Aku harus memberitahumu, kekayaanku\n"
	.string "bertambah sejak kita terakhir\l"
	.string "bertemu.\p"
	.string "Terlebih lagi, POKéMON-ku juga\n"
	.string "semakin kuat.\p"
	.string "Aku tidak bisa menghilangkan\n"
	.string "perasaan bahwa dunia ini ada\l"
	.string "untukku!\p"
	.string "Oh, tidak perlu bicara sepatah kata\n"
	.string "pun! Semua orang tahu itu benar!\p"
	.string "Oh, kamu harus memaafkan aku, aku\n"
	.string "harus menghadiri jamuan makan malam\l"
	.string "formal.$"

MatchCall_PersonalizedText13::
	.string "Ufufufufu… Ini aku, {STR_VAR_1}…\p"
	.string "Bisakah kamu menebak apa yang\n"
	.string "sedang aku lihat? Sepasang\l"
	.string "{STR_VAR_2} sedang bertarung.\p"
	.string "Mungkin aku akan mencoba menangkap\n"
	.string "pemenangnya… Ufufufufufu…\p"
	.string "Aku… Aku agak sibuk sekarang. Aku\n"
	.string "harus pergi.$"

MatchCall_PersonalizedText14::
	.string "Oh, ini {STR_VAR_1}!\p"
	.string "Aku baru saja berpikir aku mulai\n"
	.string "bosan dengan ABANDONED SHIP.\p"
	.string "Tapi karena aku sudah di sini, dan\n"
	.string "aku ingin mengalahkan kamu sekali,\l"
	.string "aku akan tinggal sedikit lebih\n"
	.string "lama.\p"
	.string "Jika kamu merasa terdorong, kenapa\n"
	.string "kamu tidak datang menemuiku?\p"
	.string "Kurasa hari ini akan menjadi hari\n"
	.string "di mana aku akhirnya menantang pria\l"
	.string "di sebelah untuk bertanding.\p"
	.string "Sampai jumpa!$"

MatchCall_PersonalizedText15::
	.string "Aku {STR_VAR_1}! Pria lautan!\p"
	.string "Kamu tahu apa yang aku pikirkan?\p"
	.string "Para PELATIH di laut adalah yang\n"
	.string "terkuat dari yang terkuat!\p"
	.string "Kamu harus belajar dariku dan\n"
	.string "berlatih di laut…\p"
	.string "Ups, ombak besar naik!\p"
	.string "Ini kesempatan latihan yang bagus!\n"
	.string "Maaf, tapi aku harus pergi!$"

MatchCall_PersonalizedText16::
	.string "Ini {STR_VAR_1}! Dengar, aku telah\n"
	.string "mengajar karate pada POKéMON-ku.\p"
	.string "Tapi sekarang mereka lebih baik\n"
	.string "dariku! Aku hanya kalah dari\l"
	.string "mereka!\p"
	.string "Tapi meskipun aku kalah dari\n"
	.string "POKéMON, aku tidak akan kalah dari\l"
	.string "PELATIH lain, tentu saja tidak!\p"
	.string "Kita harus bertarung lagi! Ugwaah!$"

MatchCall_PersonalizedText17::
	.string "Ini aku, {STR_VAR_1}. Bagaimana\n"
	.string "perjalananmu berjalan?\p"
	.string "…Wah, benarkah? Kedengarannya\n"
	.string "sangat merangsang!\p"
	.string "Kurasa aku bisa menulis lagu\n"
	.string "tentang salah satu episode\l"
	.string "perjalananmu.\p"
	.string "…Oh, hei, aku merasakannya. Aku\n"
	.string "mendengar riffs di kepalaku.\p"
	.string "Sebaiknya aku segera menulis lagu\n"
	.string "ini dengan benar, jadi aku harus\l"
	.string "pergi! Sampai nanti!$"

MatchCall_PersonalizedText18::
	.string "Ini {STR_VAR_1}… Dengarkan lagu\n"
	.string "baruku.\p"
	.string "Lalala, {STR_VAR_2}, {STR_VAR_2}!\n"
	.string "Kenapa kamu menjadi {STR_VAR_2}\l"
	.string "itu? Kenapa aku tidak bisa menjadi\n"
	.string "kamu, {STR_VAR_2}? Lala,\l"
	.string "{STR_VAR_2} dan {STR_VAR_1},\n"
	.string "{STR_VAR_1} dan {STR_VAR_2}…\p"
	.string "Ulangi chorus, perlahan menghilang…$"

MatchCall_PersonalizedText19::
	.string "Aku {STR_VAR_1}, kamu tahu, ahli\n"
	.string "berkemah!\p"
	.string "Saat kita bertarung, aku tak bisa\n"
	.string "menghindar dari kekalahan darimu.\p"
	.string "Bagaimanapun juga, keahlianku\n"
	.string "adalah berkemah.\p"
	.string "Tapi menang atau kalah, aku suka\n"
	.string "bertarung saat aku berkemah.\p"
	.string "Bertarunglah dengan kami lagi, oke?\n"
	.string "Oh, dan mari kita berkemah juga!$"

MatchCall_PersonalizedText20::
	.string "Ini aku, aku, {STR_VAR_1}!\p"
	.string "Sejujurnya, aku ingin mendaki\n"
	.string "gunung lain selain yang ini.\p"
	.string "Tapi aku tidak yakin apakah akan\n"
	.string "ada wanita seperti di MT. CHIMNEY.\p"
	.string "Jika kamu tahu gunung lain di\n"
	.string "sekitar sini yang ada wanitanya,\l"
	.string "beri tahu aku!\p"
	.string "Ehehehe, sampai jumpa!$"

MatchCall_PersonalizedText21::
	.string "… … … … … … … … … … … … Ini\n"
	.string "{STR_VAR_1}…\p"
	.string "… … … … … … … … … … … … Sekian\n"
	.string "untuk hari ini…$"

MatchCall_PersonalizedText22::
	.string "Ini {STR_VAR_1}. Hari ini, aku\n"
	.string "punya firasat bahwa aku akan\l"
	.string "mengobrol dengan kamu.\p"
	.string "Keinginanku untuk mengalahkanmu\n"
	.string "terus bertambah siang dan malam.\p"
	.string "Kamu punya rival seperti itu, kan?\n"
	.string "Kuharap itu aku…\p"
	.string "Aku senang kamu mendengarku. Sampai\n"
	.string "jumpa!$"

MatchCall_PersonalizedText23::
	.string "Ini {STR_VAR_1}.\p"
	.string "Ketika ada PELATIH kuat di dekat\n"
	.string "sini, entah kenapa terkadang aku\l"
	.string "bisa merasakannya.\p"
	.string "Apakah kamu lewat dekat sini,\n"
	.string "{PLAYER}{KUN}? Mungkin itu kamu.\p"
	.string "Aku akan menunggu kunjunganmu.\n"
	.string "Sampai jumpa!$"

MatchCall_PersonalizedText24::
	.string "Halo, ini {STR_VAR_1}. Kamu\n"
	.string "terdengar baik-baik saja,\l"
	.string "{PLAYER}{KUN}.\p"
	.string "Aku sudah berkeliling dunia, tapi\n"
	.string "aku harus bilang aku sangat\l"
	.string "menyukai wilayah ini.\p"
	.string "Aku berencana tinggal di sini\n"
	.string "sebentar. Mungkin kita bisa bertemu\l"
	.string "lagi?\p"
	.string "Aku tidak melupakan teknikmu yang\n"
	.string "memukau.\p"
	.string "Aku sangat mengharapkan tanding\n"
	.string "ulang.$"

MatchCall_PersonalizedText25::
	.string "Snivel… Ini… {STR_VAR_1}… …Sob…\p"
	.string "ROXANNE memarahiku di kelas hari\n"
	.string "ini.\p"
	.string "Tapi aku sama sekali tidak\n"
	.string "membencinya.\p"
	.string "ROXANNE memberitahuku persis apa\n"
	.string "kesalahanku agar aku bisa belajar\l"
	.string "darinya.\p"
	.string "Tentu saja aku akan pergi ke\n"
	.string "SEKOLAH PELATIH besok!\p"
	.string "Sampai jumpa nanti!$"

MatchCall_PersonalizedText26::
	.string "Ini {STR_VAR_1}!\p"
	.string "ROXANNE mengizinkanku bertarung\n"
	.string "dengannya kemarin.\p"
	.string "Hasilnya… Mengerikan, seperti yang\n"
	.string "sudah Kamu duga.\p"
	.string "Tapi aku senang sekali ROXANNE mau\n"
	.string "menerima tantanganku!\p"
	.string "Kamu tidak akan percaya betapa aku\n"
	.string "semakin mengaguminya!\p"
	.string "Aku akan benar-benar fokus dan\n"
	.string "bekerja! Aku harus pergi!$"

MatchCall_PersonalizedText27::
	.string "Hai, aku ANNA! Hari ini aku bersama\n"
	.string "rekan junior-ku, MEG, lagi.\p"
	.string "Aku sangat suka merawat MEG dan\n"
	.string "POKéMON. Mereka lucu sekali!\p"
	.string "Aku berharap aku bisa merawat\n"
	.string "mereka seperti adik-adikku!\p"
	.string "Oh, hai, MEG! Apa Kamu sudah\n"
	.string "mengambil rotinya?\p"
	.string "Hah? Tidak, tidak, aku tidak\n"
	.string "memperlakukan Kamu seperti budak\l"
	.string "pribadiku!\p"
	.string "Kamu kalah dalam pertandingan, jadi\n"
	.string "Kamu harus membeli roti sebagai\l"
	.string "hukuman!\p"
	.string "Aku tidak akan memperlakukanmu\n"
	.string "seperti budak, MEG! Kamu terlalu\l"
	.string "istimewa bagiku!\p"
	.string "Aku harus pergi sekarang. Sudah\n"
	.string "waktunya camilan kita!$"

MatchCall_PersonalizedText28::
	.string "Aku cinta POKéMON! Aku {STR_VAR_1}\n"
	.string "dari KLUB PENGGEMAR!\p"
	.string "Kamu harus dengar ini! POKéMON\n"
	.string "manisku…\p"
	.string "Dengus! Wahaha! Aku tidak bisa\n"
	.string "berkata lebih banyak! Ini rahasia!\l"
	.string "Saking lucunya tak terlukiskan!\p"
	.string "Oh, {STR_VAR_2} manisku memohon\n"
	.string "{POKEBLOCK}!\p"
	.string "Dia adalah gambaran kelucuan!\p"
	.string "Maaf, aku tidak bisa bicara\n"
	.string "sekarang! Kamu harus mendengarnya\l"
	.string "lain kali!$"

MatchCall_PersonalizedText29::
	.string "Ohoho!\p"
	.string "Ini {STR_VAR_1}! Aku tidak sabar\n"
	.string "menceritakan tentang POKéMON\l"
	.string "kesayanganku!\p"
	.string "Kumohon, Kamu harus mendengarkan\n"
	.string "ini. Ini tentang {STR_VAR_2}\l"
	.string "kesayanganku.\p"
	.string "Setiap kali ada yang\n"
	.string "menggendongnya, ia langsung\l"
	.string "melompat ke pelukanku!\p"
	.string "Oh… Oh… Mungkinkah ada yang lebih\n"
	.string "membahagiakan dari ini?\p"
	.string "Oh, rasanya sungguh surgawi!\p"
	.string "Aku senang sekali bisa berbagi\n"
	.string "kebahagiaanku dengan Kamu.\p"
	.string "Yah, aku harus pergi. Sampai jumpa!$"

MatchCall_PersonalizedText30::
	.string "Aku… {STR_VAR_1}. Orang-orang\n"
	.string "memanggilku AHLI.\p"
	.string "Tapi ada satu hal yang aku tahu.\n"
	.string "Aku tidak bisa menjadi AHLI hanya\l"
	.string "dengan kekuatanku sendiri.\p"
	.string "Hanya dengan bantuan POKéMON\n"
	.string "seorang PELATIH bisa menjadi AHLI.\p"
	.string "Hmph! Aku rasa aku baru saja\n"
	.string "mengatakan sesuatu yang dalam dan\l"
	.string "mendalam!\p"
	.string "Aku akan meninggalkanmu dalam\n"
	.string "suasana hati yang baik!$"

MatchCall_PersonalizedText31::
	.string "Aku {STR_VAR_1}. Aku senang\n"
	.string "mengobrol dengan Kamu!\p"
	.string "Aku merasa hidup dan segar berendam\n"
	.string "di bak air panas ini.\p"
	.string "Aku sudah bertarung melawan banyak\n"
	.string "PELATIH muda sejak kita bertemu,\l"
	.string "tapi Kamu masih yang terbaik di\n"
	.string "antara mereka.\p"
	.string "Aku membayangkan Kamu akan menjadi\n"
	.string "AHLI di usia tua Kamu! Ohohoho…$"

MatchCall_PersonalizedText32::
	.string "Asyik! Ini {STR_VAR_1}! Ada apa?\p"
	.string "Mungkin aku hanya membayangkannya,\n"
	.string "tapi ketika aku menang, celana\l"
	.string "pendekku terasa, yah, lebih enak.\n"
	.string "Secara materi.\p"
	.string "Apa maksudku? Agak sulit\n"
	.string "dijelaskan, tapi… Bagaimana ya\l"
	.string "mengatakannya… Celana pendekku\n"
	.string "terasa lebih halus!\p"
	.string "Dan saat aku bertarung melawanmu,\n"
	.string "{PLAYER}{KUN}, celana pendekku\l"
	.string "terasa menjijikkan dan kasar.\p"
	.string "… … … … … … Kamu tidak benar-benar\n"
	.string "percaya kan? Ehehehe, itu saja!\l"
	.string "Sampai jumpa!$"

MatchCall_PersonalizedText33::
	.string "Ahoy! {STR_VAR_1} di sini!\p"
	.string "Seperti biasa, aku memancing dengan\n"
	.string "semangat liar!\p"
	.string "Apakah ada tempat lain selain laut\n"
	.string "dan sungai yang bisa aku gunakan\l"
	.string "untuk memancing?\p"
	.string "Aku punya dorongan kuat untuk\n"
	.string "memancing hampir di mana saja!\p"
	.string "Aduh, sialan! Kailku kusut!\p"
	.string "Aku harus pergi! Carikan aku tempat\n"
	.string "memancing baru!$"

MatchCall_PersonalizedText34::
	.string "Hei! Aku {STR_VAR_1}. Apakah Kamu\n"
	.string "bersantai?\p"
	.string "Sejak aku masih kecil, kau tahu,\n"
	.string "aku selalu tenang, ya?\p"
	.string "Aku tidak pernah suka terlalu stres\n"
	.string "atau terburu-buru.\p"
	.string "Tapi siapa sangka, sekarang aku\n"
	.string "adalah seorang TRIATLET.\p"
	.string "Kamu tidak akan pernah tahu ke mana\n"
	.string "hidup akan membawamu, jika Kamu\l"
	.string "mengerti maksudku.\p"
	.string "Kamu Pelatih sekarang, tapi siapa\n"
	.string "tahu apa yang akan terjadi di masa\l"
	.string "depan, ya?\p"
	.string "Bayangkan Kamu jadi guru, atau\n"
	.string "mungkin seniman. Keren, kan?\p"
	.string "Tapi, hei, santai saja. Nikmati.\n"
	.string "Sampai jumpa.$"

MatchCall_PersonalizedText35::
	.string "Ini {STR_VAR_1}! Aku sedang\n"
	.string "bersepeda sekarang.\p"
	.string "Aku suka berenang dan berlari, tapi\n"
	.string "bersepeda adalah cinta pertamaku!\p"
	.string "Itu membuat seluruh tubuhku terasa\n"
	.string "menyatu dengan angin.\p"
	.string "Itu menggairahkanku seolah aku\n"
	.string "sedang terbang!\p"
	.string "Oke! Hari ini, aku akan mencetak\n"
	.string "rekor baru JALAN SEPEDA!\p"
	.string "Kamu juga harus mencoba\n"
	.string "tantangannya! Sampai jumpa!$"

MatchCall_PersonalizedText36::
	.string "Yo, ini {STR_VAR_1}! Aku sedang\n"
	.string "berada di tengah-tengah triathlon!\p"
	.string "Tapi, hei, aku selalu punya waktu\n"
	.string "untuk mengobrol santai!\p"
	.string "Berolahraga bersama POKéMON rasanya\n"
	.string "sangat menyenangkan!\p"
	.string "Tanpa bertukar kata, kami serasi\n"
	.string "seolah berbagi satu hati.\p"
	.string "Sungguh menginspirasi!\p"
	.string "Terengah… Mengobrol sambil berlari…\n"
	.string "Aku jadi lemas… Terengah… Harus…\l"
	.string "pergi…$"

MatchCall_PersonalizedText37::
	.string "Hai, aku {STR_VAR_1}. Jika Kamu\n"
	.string "ingin meningkatkan daya tahan,\l"
	.string "latihan di dataran tinggi adalah\n"
	.string "jawabannya!\p"
	.string "Coba berlari di puncak gunung. Kamu\n"
	.string "akan cepat terengah-engah!\p"
	.string "Aku juga mulai kekurangan oksigen!\n"
	.string "Sampai jumpa!$"

MatchCall_PersonalizedText38::
	.string "Oh, ini {STR_VAR_1}, halo.\p"
	.string "Aku sudah banyak berenang tapi\n"
	.string "sepertinya aku masih belum bisa\l"
	.string "mencapai EVERGRANDE.\p"
	.string "Mungkin aku hanya berputar-putar.\p"
	.string "Tidak, tidak, itu tidak mungkin.\n"
	.string "Wahahaha. Hati-hati!$"

MatchCall_PersonalizedText39::
	.string "Hei, aku {STR_VAR_1}… Aduh!\p"
	.string "Ciprat!\p"
	.string "Blug-blug-blug-blug…\p"
	.string "Byur!\p"
	.string "Whiff-whiff! Whiff-whiff!\p"
	.string "Hei! Maaf soal itu! Aku baru saja\n"
	.string "memakai minyak berjemur.\p"
	.string "Jadi POKéNAV-ku tergelincir dari\n"
	.string "tanganku dan jatuh ke air!\p"
	.string "Tapi, wah, POKéNAV buatan DEVON\n"
	.string "tangguh. Dia selamat dari celupan\l"
	.string "itu!\p"
	.string "Ngomong-ngomong, aku sibuk\n"
	.string "berjemur, jadi mari kita mengobrol\l"
	.string "lain kali.$"

MatchCall_PersonalizedText40::
	.string "Halo, ini {STR_VAR_1}.\p"
	.string "Dari tiga acara triathlon, aku\n"
	.string "paling suka berenang.\p"
	.string "Tapi jika aku terlalu lama di laut,\n"
	.string "bukankah kulitku akan keriput\l"
	.string "seperti buah prem?\p"
	.string "Ooh, triathlon adalah ujian\n"
	.string "ketahanan manusia yang melelahkan!\l"
	.string "Sampai jumpa!$"

MatchCall_PersonalizedText41::
	.string "Halo, {PLAYER}{KUN}. {STR_VAR_1} di\n"
	.string "sini.\p"
	.string "Bagaimana kabar POKéMON Kamu?\p"
	.string "POKéMON NAGAKU tampaknya berada\n"
	.string "dalam kondisi puncak. Sampai jumpa\l"
	.string "dulu.$"

MatchCall_PersonalizedText42::
	.string "{STR_VAR_1} di sini.\p"
	.string "{STR_VAR_2}-ku menjadi jauh lebih\n"
	.string "tangguh dari terakhir kali.\p"
	.string "Aku tidak akan kalah lagi darimu.\n"
	.string "Tunggu saja lain kali!\p"
	.string "Sampai jumpa!$"

MatchCall_PersonalizedText43::
	.string "Aku {STR_VAR_1} di sini.\p"
	.string "Aku telah melanjutkan studiku dalam\n"
	.string "seni persembunyian.\p"
	.string "Tapi aku terlalu berhasil. Tidak\n"
	.string "ada yang bisa menemukanku.\l"
	.string "Kesuksesanku membuatku kesepian…\p"
	.string "Aku menghilang seperti asap!\n"
	.string "Selamat tinggal!$"

MatchCall_PersonalizedText44::
	.string "Ini {STR_VAR_1}. Aku terus berlatih\n"
	.string "sejak kita bertemu.\p"
	.string "{STR_VAR_2}-ku menjadi cukup\n"
	.string "tangguh.\p"
	.string "Berlatih di pantai memang efektif,\n"
	.string "seperti yang aku duga. Sampai\l"
	.string "jumpa!$"

MatchCall_PersonalizedText45::
	.string "Apa kabar? Ini {STR_VAR_1}.\p"
	.string "Aku ingin tahu kapan abu vulkanik\n"
	.string "menjijikkan ini akan berhenti\l"
	.string "berjatuhan?\p"
	.string "Jika terlalu tebal, itu akan\n"
	.string "menutupi pola pada payungku…\p"
	.string "Mari berjanji untuk bertemu lagi!$"

MatchCall_PersonalizedText46::
	.string "Hai, {STR_VAR_1} di sini.\p"
	.string "Tahukah Kamu bahwa lebih mudah\n"
	.string "mengapung di laut daripada di\l"
	.string "kolam?\p"
	.string "Hanya dengan berbaring diam,\n"
	.string "tubuhmu akan mengapung dengan\l"
	.string "sendirinya.\p"
	.string "Tapi jika Kamu mengapung terlalu\n"
	.string "lama, hati-hati jangan sampai\l"
	.string "terbawa terlalu jauh.\p"
	.string "…Aku ada di mana ya? Aku harus\n"
	.string "pergi!$"

MatchCall_PersonalizedText47::
	.string "Oh, {PLAYER}{KUN}, halo! Ini\n"
	.string "{STR_VAR_1}. Aku sekarang berada di\l"
	.string "pegunungan.\p"
	.string "Tapi tanahnya terlalu bergelombang.\n"
	.string "Aku tidak bisa mendirikan tendaku\l"
	.string "di sini…\p"
	.string "Oh, aku punya ide cemerlang!\p"
	.string "Mungkin aku bisa meminta POKéMON-ku\n"
	.string "untuk meratakan tanah di sini!\p"
	.string "Aku akan mencobanya! Sampai jumpa!$"

MatchCall_PersonalizedText48::
	.string "Oh, hai, hai, ini {STR_VAR_1}!\p"
	.string "Aku memelihara POKéMON bersama LIV!\n"
	.string "Kami berusaha keras!\p"
	.string "Jika kami berusaha lebih keras,\n"
	.string "bisakah kami menjadi nomor satu?\l"
	.string "Sampai jumpa!$"

MatchCall_PersonalizedText49::
	.string "{STR_VAR_1} di sini!\p"
	.string "Aku seorang PELAUT, tapi aku tidak\n"
	.string "di atas kapal sekarang.\p"
	.string "Aku jadi bertanya-tanya-apa sebutan\n"
	.string "untuk PELAUT yang ada di darat?\p"
	.string "Itulah yang aku pikirkan sambil\n"
	.string "menatap ombak.\p"
	.string "Baiklah, sampai jumpa!$"

MatchCall_PersonalizedText50::
	.string "Ini {STR_VAR_1}. Jadi? Apa Kamu\n"
	.string "dapat POKéMON lagi?\p"
	.string "Jika Kamu menangkap POKéMON baru,\n"
	.string "Kamu harus datang dan\l"
	.string "menunjukkannya padaku.\p"
	.string "Aku janji tidak akan merengek\n"
	.string "memintanya. Aku akan menunggu.\l"
	.string "Sampai jumpa.$"

MatchCall_PersonalizedText51::
	.string "Ini {STR_VAR_1}.\p"
	.string "Apa Kamu membesarkan POKéMON-mu\n"
	.string "dengan cara yang optimal?\p"
	.string "Udara di tempatku bersih. Ini\n"
	.string "adalah lingkungan yang sempurna\l"
	.string "untuk membesarkan POKéMON.\p"
	.string "Jika Kamu ingin fokus membesarkan\n"
	.string "POKéMON, Kamu harus datang ke\l"
	.string "{STR_VAR_2}. Jaga diri baik-baik.$"

MatchCall_PersonalizedText52::
	.string "Hai, ini {STR_VAR_1}.\p"
	.string "Aku memberikan {POKEBLOCK} ke\n"
	.string "{STR_VAR_2}-ku. Sepertinya dia\l"
	.string "sangat menyukainya.\p"
	.string "Rupanya POKéMON punya kesukaan dan\n"
	.string "ketidaksukaan mereka sendiri\l"
	.string "terhadap {POKEBLOCK}.\p"
	.string "Aku merasa itu cukup menarik. Jaga\n"
	.string "diri baik-baik.$"

MatchCall_PersonalizedText53::
	.string "{STR_VAR_1} di sini.\p"
	.string "Jika Kamu bekerja sama dengan\n"
	.string "POKéMON, seseorang bisa merasa\l"
	.string "nyaman di alam liar.\p"
	.string "Semua orang harus menyadari itu dan\n"
	.string "lebih sering bekerja sama dengan\l"
	.string "POKéMON.\p"
	.string "Itu akan ideal. Aku benar-benar\n"
	.string "berpikir begitu.\p"
	.string "Aku pikir Kamu berada di jalur yang\n"
	.string "benar! Sampai jumpa lagi!$"

MatchCall_PersonalizedText54::
	.string "Hai, ini {STR_VAR_1}. Kamu tahu,\n"
	.string "TRAINER yang selalu siap!\p"
	.string "{PLAYER}{KUN}, apa Kamu punya cukup\n"
	.string "item? Apa POKéMON-mu siap beraksi?\p"
	.string "Menjaga segalanya sempurna di\n"
	.string "sekitarmu sepanjang waktu adalah\l"
	.string "rahasia agar perjalananmu terus\n"
	.string "berlanjut.\p"
	.string "Sebaiknya aku pergi memeriksa\n"
	.string "persediaanku sendiri! Selalu\l"
	.string "waspada!$"

MatchCall_PersonalizedText55::
	.string "Ini {STR_VAR_1}! Ini {STR_VAR_1}!\p"
	.string "{STR_VAR_2} adalah jalan yang\n"
	.string "sangat sibuk, jadi aku ditantang\l"
	.string "oleh berbagai TRAINER setiap hari.\p"
	.string "Hari ini, aku memenangkan lima\n"
	.string "pertarungan dan hanya kalah tiga!\p"
	.string "Bagaimana kabarmu hari ini?\n"
	.string "Ceritakan padaku lain kali, ya?$"

MatchCall_PersonalizedText56::
	.string "Ini aku, {STR_VAR_1}.\p"
	.string "Aku populer karena aku punya banyak\n"
	.string "POKéMON SERANGGA, kan?\p"
	.string "Nah, aku membawa banyak serangga\n"
	.string "favoritku ke sekolah hari ini.\p"
	.string "Gadis yang aku suka mulai menangis!\n"
	.string "Silakan tertawa jika Kamu mau.\p"
	.string "Aku harus mencoba mengajarinya apa\n"
	.string "yang membuat POKéMON SERANGGA\l"
	.string "begitu menarik.\p"
	.string "Sengau... Sampai jumpa!$"

MatchCall_PersonalizedText57::
	.string "Hah! Hah! Hah! Hah!\p"
	.string "Hai! Ini {STR_VAR_1}! Hah! Hah!\p"
	.string "Mencoba mengobrol... Sambil\n"
	.string "memanjat... Adalah latihan keras...\l"
	.string "Hah! Hah!\p"
	.string "Ugh! Aduh... Sekarang lebih\n"
	.string "curam... Kita akan mengobrol...\l"
	.string "lain kali... Hah! Hah! Hah!$"

MatchCall_PersonalizedText58::
	.string "Oh, hai!\p"
	.string "Aku masih mencari harta karun\n"
	.string "bersama KIRA!\p"
	.string "Mungkin tidak ada harta karun di\n"
	.string "sini sama sekali...\p"
	.string "Tapi yang penting adalah aku\n"
	.string "mencari bersama KIRA.\p"
	.string "Oh, hei, KIRA! Ke-kenapa Kamu\n"
	.string "marah?\p"
	.string "Aku tidak mengabaikanmu, sayang!\n"
	.string "Kamu satu-satunya bagiku!\p"
	.string "...{PLAYER}, aku harus pergi,\n"
	.string "sampai jumpa!$"

MatchCall_PersonalizedText59::
	.string "Ini {STR_VAR_1}!\p"
	.string "Aku pergi ke GYM DEWFORD lagi untuk\n"
	.string "latihan.\p"
	.string "BRAWLY, PEMIMPIN GYM, sepertinya\n"
	.string "lebih kuat sekarang.\p"
	.string "Katanya jadi kuat karena ombak\n"
	.string "liar…\p"
	.string "Tapi dia masih keren seperti biasa.\n"
	.string "Para wanita memujanya! Terus\l"
	.string "terang, itu membuatku iri.\p"
	.string "Aku penasaran… Apakah temannya\n"
	.string "BRUNO sama seperti BRAWLY?\p"
	.string "Kamu tahu, semua berkeringat atau\n"
	.string "bau, dan cenderung memanggil orang\l"
	.string "“ombak besar,” atau semacamnya.\p"
	.string "Tapi, hei, sifat iri ini tidak\n"
	.string "pantas, kan?\p"
	.string "Lupakan saja obrolan ini pernah\n"
	.string "terjadi, bagaimana? Sampai jumpa!$"

MatchCall_PersonalizedText60::
	.string "Senang rasanya mengobrol dengan\n"
	.string "TRAINER muda sepertimu.\p"
	.string "Aku membayangkan Kamu akan terus\n"
	.string "menikmati POKéMON di usia berapa\l"
	.string "pun.\p"
	.string "Bukankah akan menyenangkan jika\n"
	.string "Kamu memiliki kemitraan seperti\l"
	.string "kami?\p"
	.string "Tentu saja, {PLAYER}{KUN}, Kamu\n"
	.string "sudah menikmati kepercayaan dan\l"
	.string "persahabatan dari POKéMON-mu\n"
	.string "sekarang.\p"
	.string "Kamu sudah memiliki potensi untuk\n"
	.string "hubungan yang panjang dan abadi!\p"
	.string "Hahaha! Jangan pernah berkecil\n"
	.string "hati!$"

MatchCall_PersonalizedText61::
	.string "Hai, ini {STR_VAR_1}! Kami baru\n"
	.string "saja memenangkan pertarungan!\p"
	.string "Kami memang tidak sering menang,\n"
	.string "tapi kali ini melawan perenang\l"
	.string "keren.\p"
	.string "Kakakku marah besar!\p"
	.string "Dia ingin berpura-pura lemah untuk\n"
	.string "membuat kesan!\p"
	.string "Dia selalu memarahiku, entah kami\n"
	.string "menang atau kalah!\p"
	.string "{PLAYER}{KUN}, bisakah Kamu\n"
	.string "mengatakan sesuatu padanya lain\l"
	.string "kali?\p"
	.string "Oke, sampai jumpa!$"

MatchCall_PersonalizedText62::
	.string "{STR_VAR_1} di sini, ya. Aku pergi\n"
	.string "ke laut kemarin.\p"
	.string "Aku berharap menemukan reruntuhan\n"
	.string "baru untuk dijelajahi.\p"
	.string "Tapi entah bagaimana ombak\n"
	.string "sepertinya membawaku kembali ke\l"
	.string "tempat aku memulai.\p"
	.string "Aku juga masih lemah dalam\n"
	.string "bertarung... Silakan saja\l"
	.string "mengejekku... Tapi aku tidak akan\n"
	.string "menyerah.\p"
	.string "Hariku akan tiba ketika aku\n"
	.string "menemukan reruntuhan baru!\p"
	.string "Hanya itu yang ingin aku katakan!\n"
	.string "Selamat tinggal untuk saat ini!$"

MatchCall_PersonalizedText63::
	.string "Ahoy! Ini aku, {STR_VAR_1}! Aku ada\n"
	.string "di RUTE 108 sekarang! Dengan kata\l"
	.string "lain, tempat aku selalu berada!\p"
	.string "Hari ini, seorang PERENANG cantik\n"
	.string "berenang melewatiku!\p"
	.string "Jadi, aku mengejutkannya dengan\n"
	.string "teriakan!\p"
	.string "Dan dia memberiku tatapan tajam\n"
	.string "yang tidak menyenangkan!\p"
	.string "Sekian dari RUTE 108!\n"
	.string "Dipersembahkan oleh {STR_VAR_1}!$"

MatchCall_PersonalizedText64::
	.string "Ini {STR_VAR_1}!\p"
	.string "Aku agak sibuk, tapi aku pikir aku\n"
	.string "harus memberitahumu bahwa aku telah\l"
	.string "mengalahkan lima TRAINER lagi hari\n"
	.string "ini.\p"
	.string "Jika aku mempertahankan kecepatan\n"
	.string "ini, aku mungkin bisa mengalahkanmu\l"
	.string "lain kali.\p"
	.string "Aku rasa kita akan menjadi rival\n"
	.string "yang baik, Kamu dan aku. Sampai\l"
	.string "jumpa dulu!$"

MatchCall_BattleFrontierStreakText1::
	.string "Hai! Ini {STR_VAR_1}. Aku dengar\n"
	.string "beritanya!\p"
	.string "Mereka bilang Kamu tampil luar\n"
	.string "biasa di {STR_VAR_2}.\p"
	.string "Keren sekali, {STR_VAR_3}\n"
	.string "kemenangan beruntun? Sampai jumpa!$"

MatchCall_BattleFrontierStreakText2::
	.string "Halo, ini {STR_VAR_1}! Aku dengar\n"
	.string "tentang Kamu!\p"
	.string "Mereka bilang Kamu memenangkan\n"
	.string "{STR_VAR_3} pertarungan beruntun di\l"
	.string "{STR_VAR_2}.\p"
	.string "Itu istimewa! Aku juga harus\n"
	.string "berusaha lebih keras! Sampai jumpa!$"

MatchCall_BattleFrontierStreakText3::
	.string "Hei, {PLAYER}! Ini aku,\n"
	.string "{STR_VAR_1}.\p"
	.string "Aku dengar Kamu mengamuk di\n"
	.string "{STR_VAR_2}!\p"
	.string "Rentetan kemenangan {STR_VAR_3}\n"
	.string "yang besar... Itu rekor besar,\l"
	.string "bukan?\p"
	.string "Aku juga harus segera memperbaiki\n"
	.string "diri! Sampai jumpa!$"

MatchCall_BattleFrontierStreakText4::
	.string "Hei, {PLAYER}{KUN}. {STR_VAR_1} di\n"
	.string "sini. Ada apa?\p"
	.string "Ada rumor yang beredar bahwa Kamu\n"
	.string "meraih {STR_VAR_3} kemenangan\l"
	.string "beruntun di {STR_VAR_2}.\p"
	.string "Aku juga harus meningkatkan\n"
	.string "kemampuanku. Sampai jumpa!$"

MatchCall_BattleFrontierStreakText5::
	.string "Hai, {PLAYER}{KUN}! Ini\n"
	.string "{STR_VAR_1}.\p"
	.string "Kamu berada di {STR_VAR_2} dan\n"
	.string "memenangkan {STR_VAR_3} pertarungan\l"
	.string "berturut-turut? Luar biasa!\p"
	.string "Aku sebaiknya lebih banyak melatih\n"
	.string "POKéMON-ku. Sampai jumpa!$"

MatchCall_BattleFrontierStreakText6::
	.string "Hei, {PLAYER}{KUN}. {STR_VAR_1} di\n"
	.string "sini. Apa kabar?\p"
	.string "Ngomong-ngomong, aku dengar Kamu\n"
	.string "berhasil meraih prestasi\l"
	.string "{STR_VAR_3} kemenangan beruntun di\n"
	.string "{STR_VAR_2}.\p"
	.string "Itu menginspirasiku untuk fokus\n"
	.string "membesarkan timku.$"

MatchCall_BattleFrontierStreakText7::
	.string "...Er, {PLAYER}{KUN}? {STR_VAR_1}\n"
	.string "di sini...\p"
	.string "Oh, ya, Kamu ada di {STR_VAR_2},\n"
	.string "kan?\p"
	.string "Dan Kamu memenangkan {STR_VAR_3}\n"
	.string "pertarungan berturut-turut.\p"
	.string "Oh, itu ada POKéMON langka! Aku\n"
	.string "harus pergi!$"

MatchCall_BattleFrontierStreakText8::
	.string "Oh, {PLAYER}{KUN}, apa kabar? Ini\n"
	.string "{STR_VAR_1} yang bicara. Aku harap\l"
	.string "Kamu baik-baik saja.\p"
	.string "Oh, tapi, Kamu memang baik. Aku\n"
	.string "dengar Kamu memenangkan {STR_VAR_3}\l"
	.string "pertandingan berturut-turut di\n"
	.string "{STR_VAR_2}.\p"
	.string "Itu sangat mengesankan! Aku harap\n"
	.string "Kamu terus sukses.$"

MatchCall_BattleFrontierStreakText9::
	.string "Oh, {PLAYER}{KUN}, hai! Ini\n"
	.string "{STR_VAR_1}!\p"
	.string "Aku dengar! Rentetan kemenangan\n"
	.string "{STR_VAR_3}-mu di {STR_VAR_2}!\p"
	.string "Itu sangat keren! Aku juga harus\n"
	.string "berusaha lebih keras!$"

MatchCall_BattleFrontierStreakText10::
	.string "Oh, {PLAYER}{KUN}, halo... Ini\n"
	.string "{STR_VAR_1}.\p"
	.string "Kamu memenangkan {STR_VAR_3}\n"
	.string "pertarungan beruntun di\l"
	.string "{STR_VAR_2}?\p"
	.string "Itu pencapaian yang luar biasa. Aku\n"
	.string "harus bekerja lebih keras.$"

MatchCall_BattleFrontierStreakText11::
	.string "Ah, {PLAYER}{KUN}. Ini {STR_VAR_1}.\p"
	.string "Aku dengar Kamu adalah momok di\n"
	.string "{STR_VAR_2}?\p"
	.string "Kamu memenangkan, berapa,\n"
	.string "{STR_VAR_3} pertandingan\l"
	.string "berturut-turut?\p"
	.string "Kamu hebat, Kamu. Aku ingin tahu\n"
	.string "berapa banyak yang bisa aku\l"
	.string "menangkan?$"

MatchCall_BattleFrontierStreakText12::
	.string "Halo, {PLAYER}. Ini aku,\n"
	.string "{STR_VAR_1}. Apa kabar kamu\l"
	.string "baik-baik saja?\p"
	.string "Aku dengar kabar tentang kamu.\n"
	.string "Katanya kamu menang {STR_VAR_3}\l"
	.string "pertarungan beruntun di tempat\n"
	.string "bernama {STR_VAR_2}?\p"
	.string "Itu hebat sekali. Sampai jumpa!$"

MatchCall_BattleFrontierStreakText13::
	.string "Ah, halo, {PLAYER}! Ini\n"
	.string "{STR_VAR_1}! Aku harap kamu sehat\l"
	.string "selalu.\p"
	.string "Katanya kamu menang {STR_VAR_3}\n"
	.string "pertarungan beruntun di\l"
	.string "{STR_VAR_2}.\p"
	.string "Aku kagum dengan semangat kamu!\n"
	.string "Sampai nanti.$"

MatchCall_BattleFrontierStreakText14::
	.string "Oh, hai, {PLAYER}. Ini {STR_VAR_1}.\p"
	.string "Aku dengar tentang kamu! Bukankah\n"
	.string "kamu baru saja menang {STR_VAR_3}\l"
	.string "pertarungan beruntun di\n"
	.string "{STR_VAR_2}?\p"
	.string "Kamu menginspirasi! Dah!$"

MatchCall_BattleFrontierRecordStreakText1::
	.string "Hai! Ini {STR_VAR_1}. Aku dengar\n"
	.string "kabarnya!\p"
	.string "Katanya kamu hebat sekali di\n"
	.string "{STR_VAR_2}.\p"
	.string "Keren banget--{STR_VAR_3}\n"
	.string "kemenangan beruntun? Sampai jumpa!$"

MatchCall_BattleFrontierRecordStreakText2::
	.string "Halo, ini {STR_VAR_1}! Aku dengar\n"
	.string "tentang kamu!\p"
	.string "Mereka bilang kamu menang\n"
	.string "{STR_VAR_3} pertarungan beruntun di\l"
	.string "{STR_VAR_2}.\p"
	.string "Itu istimewa! Aku juga harus\n"
	.string "berusaha lebih keras! Sampai jumpa!$"

MatchCall_BattleFrontierRecordStreakText3::
	.string "Hei, {PLAYER}! Ini aku,\n"
	.string "{STR_VAR_1}.\p"
	.string "Aku dengar kamu mengamuk di\n"
	.string "{STR_VAR_2}!\p"
	.string "Rentetan {STR_VAR_3} kemenangan…\n"
	.string "Itu rekor besar, kan?\p"
	.string "Aku juga harus lebih serius! Sampai\n"
	.string "ketemu nanti!$"

MatchCall_BattleFrontierRecordStreakText4::
	.string "Hei, {PLAYER}. {STR_VAR_1} di sini.\n"
	.string "Ada apa?\p"
	.string "Ada rumor yang beredar bahwa kamu\n"
	.string "meraih {STR_VAR_3} kemenangan\l"
	.string "beruntun di {STR_VAR_2}.\p"
	.string "Aku juga harus meningkatkan diri.\n"
	.string "Sampai jumpa!$"

MatchCall_BattleFrontierRecordStreakText5::
	.string "Hai, {PLAYER}! Ini {STR_VAR_1}.\p"
	.string "Kamu ada di {STR_VAR_2} dan menang\n"
	.string "{STR_VAR_3} pertarungan\l"
	.string "berturut-turut? Hebat sekali!\p"
	.string "Aku? Aku rasa aku berkembang.\n"
	.string "Sampai ketemu nanti!$"

MatchCall_BattleFrontierRecordStreakText6::
	.string "Hei, {PLAYER}. {STR_VAR_1} di sini.\n"
	.string "Bagaimana kabarmu?\p"
	.string "Ngomong-ngomong, aku dengar kamu\n"
	.string "mencapai prestasi {STR_VAR_3}\l"
	.string "kemenangan beruntun di {STR_VAR_2}.\p"
	.string "Aku sendiri harus mencoba lebih\n"
	.string "keras! Sampai ketemu nanti!$"

MatchCall_BattleFrontierRecordStreakText7::
	.string "…Eh, {PLAYER}? Ini {STR_VAR_1}…\p"
	.string "Oh, ya, kamu ada di {STR_VAR_2},\n"
	.string "kan?\p"
	.string "Dan kamu menang {STR_VAR_3}\n"
	.string "pertarungan berturut-turut.\p"
	.string "Oh, ada POKéMON langka lewat! Aku\n"
	.string "harus pergi!$"

MatchCall_BattleFrontierRecordStreakText8::
	.string "Oh, {PLAYER}, apa kabar? Ini\n"
	.string "{STR_VAR_1} bicara. Aku harap kamu\l"
	.string "baik-baik saja.\p"
	.string "Ah, tentu saja kamu baik. Aku\n"
	.string "dengar kamu menang {STR_VAR_3}\l"
	.string "pertandingan beruntun di\n"
	.string "{STR_VAR_2}.\p"
	.string "Itu sangat mengesankan! Aku juga\n"
	.string "harus melatih POKéMON-ku!$"

MatchCall_BattleFrontierRecordStreakText9::
	.string "Oh, {PLAYER}, hai! Ini {STR_VAR_1}!\p"
	.string "Aku dengar! Rentetan {STR_VAR_3}\n"
	.string "kemenangan kamu di {STR_VAR_2}!\p"
	.string "Itu keren sekali! Aku juga harus\n"
	.string "berusaha lebih keras!$"

MatchCall_BattleFrontierRecordStreakText10::
	.string "Oh, {PLAYER}, halo… Ini\n"
	.string "{STR_VAR_1}.\p"
	.string "Kamu menang {STR_VAR_3} pertarungan\n"
	.string "beruntun di {STR_VAR_2}?\p"
	.string "Itu pencapaian yang luar biasa. Aku\n"
	.string "harus bekerja lebih keras.$"

MatchCall_BattleFrontierRecordStreakText11::
	.string "Ah, {PLAYER}. Ini {STR_VAR_1}.\p"
	.string "Aku dengar kamu ditakuti di\n"
	.string "{STR_VAR_2}?\p"
	.string "Kamu menang, berapa, {STR_VAR_3}\n"
	.string "pertandingan berturut-turut?\p"
	.string "Kamu hebat. Aku bertanya-tanya,\n"
	.string "berapa banyak yang bisa aku\l"
	.string "menangkan?$"

MatchCall_BattleFrontierRecordStreakText12::
	.string "Halo, {PLAYER}. Ini aku,\n"
	.string "{STR_VAR_1}. Apa kabar kamu\l"
	.string "baik-baik saja?\p"
	.string "Aku dengar kabar tentang kamu.\n"
	.string "Katanya kamu menang {STR_VAR_3}\l"
	.string "pertarungan beruntun di tempat\n"
	.string "bernama {STR_VAR_2}?\p"
	.string "Itu hebat sekali. Sampai jumpa!$"

MatchCall_BattleFrontierRecordStreakText13::
	.string "Ah, halo, {PLAYER}! Ini\n"
	.string "{STR_VAR_1}! Aku harap kamu sehat\l"
	.string "selalu.\p"
	.string "Katanya kamu menang {STR_VAR_3}\n"
	.string "pertarungan beruntun di\l"
	.string "{STR_VAR_2}.\p"
	.string "Aku kagum dengan semangat kamu!\n"
	.string "Sampai nanti.$"

MatchCall_BattleFrontierRecordStreakText14::
	.string "Oh, hai, {PLAYER}. Ini {STR_VAR_1}.\n"
	.string "Aku dengar tentang kamu!\p"
	.string "Bukankah kamu baru saja menang\n"
	.string "{STR_VAR_3} pertarungan beruntun di\l"
	.string "{STR_VAR_2}?\p"
	.string "Kamu menginspirasi! Dah!$"

MatchCall_BattleDomeText1::
	.string "Hai! {PLAYER}? Halo, ini\n"
	.string "{STR_VAR_1}! Aku dengar kabarnya!\p"
	.string "Kamu menjadi juara di {STR_VAR_2}\n"
	.string "sebanyak {STR_VAR_3} kali?\p"
	.string "Keren banget! Aku harus melakukan\n"
	.string "yang lebih baik! Sampai jumpa!$"

MatchCall_BattleDomeText2::
	.string "Halo, ini {STR_VAR_1}! Aku dengar\n"
	.string "tentang kamu!\p"
	.string "Mereka bilang kamu memenangkan\n"
	.string "{STR_VAR_3} gelar di {STR_VAR_2}.\p"
	.string "Itu super! Aku bertanya-tanya,\n"
	.string "bisakah aku menjadi juara?$"

MatchCall_BattleDomeText3::
	.string "Hei, {PLAYER}! Ini aku,\n"
	.string "{STR_VAR_1}. Bagaimana kabarnya?\p"
	.string "Aku dengar kamu memenangkan acara\n"
	.string "{STR_VAR_3} kali di {STR_VAR_2}!\p"
	.string "Tambah satu lagi lain kali! Sampai\n"
	.string "ketemu nanti!$"

MatchCall_BattleDomeText4::
	.string "Hei, {PLAYER}. Ini {STR_VAR_1}.\p"
	.string "Aku dengar kamu menjadi juara di\n"
	.string "{STR_VAR_2} sebanyak {STR_VAR_3}\l"
	.string "kali.\p"
	.string "Kedengarannya kamu bekerja keras.\n"
	.string "Aku akan berusaha menyamai kamu!$"

MatchCall_BattleDomeText5::
	.string "Hai, {PLAYER}! Ini {STR_VAR_1}.\p"
	.string "Aku dengar kamu menang total\n"
	.string "{STR_VAR_3} kali di {STR_VAR_2}.\p"
	.string "Aku juga harus mulai serius! Sampai\n"
	.string "ketemu nanti!$"

MatchCall_BattleDomeText6::
	.string "Hei, {PLAYER}? Ini {STR_VAR_1}.\n"
	.string "Bagaimana kabarmu?\p"
	.string "Ngomong-ngomong, aku dengar kamu\n"
	.string "menjadi juara {STR_VAR_3} kali di\l"
	.string "{STR_VAR_2}.\p"
	.string "Aku harus melatih POKéMON-ku\n"
	.string "sebelum kamu semakin jauh di depan.$"

MatchCall_BattleDomeText7::
	.string "{PLAYER}? Ini {STR_VAR_1}.\p"
	.string "Kamu ada di {STR_VAR_2} dan menjadi\n"
	.string "juara {STR_VAR_3} kali?\p"
	.string "Itu keren. Ngomong-ngomong, apa\n"
	.string "kamu akhir-akhir ini menangkap\l"
	.string "POKéMON langka?\p"
	.string "Oh, begitu. Oke, dah.$"

MatchCall_BattleDomeText8::
	.string "Oh, {PLAYER}, apa kabar? Ini\n"
	.string "{STR_VAR_1} bicara. Aku harap kamu\l"
	.string "baik-baik saja. Ah, tentu saja kamu\n"
	.string "baik.\p"
	.string "Aku dengar kamu memenangkan\n"
	.string "{STR_VAR_3} gelar di {STR_VAR_2}.\p"
	.string "Aku harus melatih POKéMON-ku\n"
	.string "seperti kamu. Sampai jumpa lagi.$"

MatchCall_BattleDomeText9::
	.string "Oh, {PLAYER}, hai! Ini {STR_VAR_1}!\p"
	.string "Aku dengar! Kamu meraih gelar\n"
	.string "{STR_VAR_3} kali di {STR_VAR_2}!\p"
	.string "Itu keren sekali! Aku juga harus\n"
	.string "berusaha lebih keras!$"

MatchCall_BattleDomeText10::
	.string "Oh, {PLAYER}, halo. Ini\n"
	.string "{STR_VAR_1}.\p"
	.string "Kamu menang {STR_VAR_3} kali\n"
	.string "berturut-turut di {STR_VAR_2}?\p"
	.string "Itu pencapaian yang luar biasa. Aku\n"
	.string "harus bekerja lebih keras.$"

MatchCall_BattleDomeText11::
	.string "Ah, {PLAYER}. Ini {STR_VAR_1}.\p"
	.string "Aku dengar kamu ditakuti di\n"
	.string "{STR_VAR_2}?\p"
	.string "Kamu menang, berapa, {STR_VAR_3}\n"
	.string "kali berturut-turut sekarang?\p"
	.string "Aku bertanya-tanya, bisakah aku\n"
	.string "menjadi juara?\p"
	.string "…Hampir mustahil? Yah, sampai\n"
	.string "jumpa!$"

MatchCall_BattleDomeText12::
	.string "Halo, {PLAYER}. Ini aku,\n"
	.string "{STR_VAR_1}. Apa kabar kamu\l"
	.string "baik-baik saja?\p"
	.string "Kamu memenangkan {STR_VAR_3} acara\n"
	.string "di tempat bernama {STR_VAR_2}?\p"
	.string "Itu hebat sekali. Sampai jumpa!$"

MatchCall_BattleDomeText13::
	.string "Ah, halo, {PLAYER}! Ini\n"
	.string "{STR_VAR_1}! Aku harap kamu sehat\l"
	.string "selalu.\p"
	.string "Katanya kamu memenangkan\n"
	.string "{STR_VAR_3} acara di {STR_VAR_2}?\p"
	.string "Aku kagum dengan semangat kamu!\n"
	.string "Sampai nanti.$"

MatchCall_BattleDomeText14::
	.string "Oh, hai, {PLAYER}. Ini {STR_VAR_1}.\n"
	.string "Aku dengar tentang kamu!\p"
	.string "Bukankah kamu memenangkan\n"
	.string "{STR_VAR_3} gelar di {STR_VAR_2}?\p"
	.string "Kamu menginspirasi! Sampai ketemu\n"
	.string "lagi!$"

MatchCall_BattlePikeText1::
	.string "Hai! {PLAYER}? Halo, ini\n"
	.string "{STR_VAR_1}! Aku dengar kabarnya!\p"
	.string "Kamu berhasil melewati {STR_VAR_3}\n"
	.string "ruangan di {STR_VAR_2}!\p"
	.string "Itu keren! Sampai jumpa!$"

MatchCall_BattlePikeText2::
	.string "Halo, ini {STR_VAR_1}! Aku dengar\n"
	.string "tentang kamu!\p"
	.string "Mereka bilang kamu berhasil\n"
	.string "melewati {STR_VAR_3} ruangan di\l"
	.string "{STR_VAR_2}.\p"
	.string "Aku harus berusaha jauh lebih\n"
	.string "keras! Dah!$"

MatchCall_BattlePikeText3::
	.string "Hei, {PLAYER}! Ini aku,\n"
	.string "{STR_VAR_1}. Bagaimana kabarnya?\p"
	.string "Aku dengar kamu berhasil melewati\n"
	.string "{STR_VAR_3} ruangan di {STR_VAR_2}!\p"
	.string "Coba lakukan yang lebih baik lagi\n"
	.string "lain kali! Sampai ketemu nanti!$"

MatchCall_BattlePikeText4::
	.string "Halo, {PLAYER}{KUN}. Ini\n"
	.string "{STR_VAR_1}.\p"
	.string "Aku dengar Kamu berhasil\n"
	.string "menaklukkan {STR_VAR_3} ruangan di\l"
	.string "{STR_VAR_2}.\p"
	.string "Aku harus melatih POKéMON-ku agar\n"
	.string "bisa mengimbangi Kamu!$"

MatchCall_BattlePikeText5::
	.string "Hai, {PLAYER}{KUN}! Ini\n"
	.string "{STR_VAR_1}.\p"
	.string "Aku dengar Kamu melewati\n"
	.string "{STR_VAR_3} ruangan di {STR_VAR_2}.\p"
	.string "Aku juga harus bekerja keras!\n"
	.string "Sampai jumpa!$"

MatchCall_BattlePikeText6::
	.string "Hei, {PLAYER}{KUN}? Ini\n"
	.string "{STR_VAR_1}. Apa kabar?\p"
	.string "Ngomong-ngomong, Aku dengar Kamu\n"
	.string "berhasil menembus {STR_VAR_3}\l"
	.string "ruangan di {STR_VAR_2}.\p"
	.string "Aku harus meningkatkan POKéMON-ku\n"
	.string "sebelum Kamu semakin jauh di depan.$"

MatchCall_BattlePikeText7::
	.string "{PLAYER}{KUN}? Ini {STR_VAR_1}.\p"
	.string "Kamu ada di {STR_VAR_2} dan\n"
	.string "memenangkan {STR_VAR_3} ruangan?\p"
	.string "Hebat sekali.\p"
	.string "Oh, ada POKéMON langka lewat! Oke,\n"
	.string "sampai jumpa.$"

MatchCall_BattlePikeText8::
	.string "Oh, {PLAYER}{KUN}, apa kabar? Ini\n"
	.string "{STR_VAR_1}. Aku harap Kamu\l"
	.string "baik-baik saja. Oh, tentu saja Kamu\n"
	.string "baik.\p"
	.string "Aku dengar Kamu berhasil melewati\n"
	.string "{STR_VAR_3} ruangan di {STR_VAR_2}.\p"
	.string "Itu sangat mengesankan! Aku harus\n"
	.string "melatih POKéMON-ku seperti Kamu.\l"
	.string "Sampai bertemu lagi.$"

MatchCall_BattlePikeText9::
	.string "Oh, {PLAYER}{KUN}, hai! Ini\n"
	.string "{STR_VAR_1}!\p"
	.string "Aku dengar! Kamu berhasil\n"
	.string "memenangkan {STR_VAR_3} ruangan di\l"
	.string "{STR_VAR_2}!\p"
	.string "Keren sekali! Aku juga harus\n"
	.string "berusaha lebih keras!$"

MatchCall_BattlePikeText10::
	.string "Oh, {PLAYER}{KUN}, halo. Ini\n"
	.string "{STR_VAR_1}.\p"
	.string "Kamu berhasil memenangkan\n"
	.string "{STR_VAR_3} ruangan di {STR_VAR_2}?\p"
	.string "Itu pencapaian yang luar biasa. Aku\n"
	.string "harus bekerja lebih keras.$"

MatchCall_BattlePikeText11::
	.string "Ah, {PLAYER}{KUN}. Ini {STR_VAR_1}.\p"
	.string "Aku dengar Kamu ditakuti di\n"
	.string "{STR_VAR_2}?\p"
	.string "Kamu berhasil melewati, berapa,\n"
	.string "{STR_VAR_3} ruangan? Itu pasti\l"
	.string "berarti.\p"
	.string "Aku ingin tahu apakah Aku bisa\n"
	.string "menjadi juara?\p"
	.string "…Mustahil, ya? Baiklah, sampai\n"
	.string "jumpa!$"

MatchCall_BattlePikeText12::
	.string "Halo, {PLAYER}{KUN}. Ini Aku,\n"
	.string "{STR_VAR_1}. Apa Kamu sehat?\p"
	.string "Kamu berhasil memenangkan\n"
	.string "{STR_VAR_3} ruangan di tempat\l"
	.string "bernama {STR_VAR_2}?\p"
	.string "Itu kisah yang menarik. Sampai\n"
	.string "jumpa!$"

MatchCall_BattlePikeText13::
	.string "Ah, halo, {PLAYER}{KUN}! Ini\n"
	.string "{STR_VAR_1}! Aku harap Kamu selalu\l"
	.string "sehat.\p"
	.string "Mereka bilang Kamu menang di\n"
	.string "{STR_VAR_3} ruangan di {STR_VAR_2}?\p"
	.string "Aku kagum dengan energimu! Sampai\n"
	.string "nanti.$"

MatchCall_BattlePikeText14::
	.string "Oh, hai, {PLAYER}{KUN}. Ini\n"
	.string "{STR_VAR_1}. Aku dengar tentang\l"
	.string "Kamu!\p"
	.string "Bukankah Kamu berhasil melewati\n"
	.string "{STR_VAR_3} ruangan di {STR_VAR_2}?\p"
	.string "Kamu adalah inspirasi! Sampai\n"
	.string "bertemu lagi!$"

MatchCall_BattlePyramidText1::
	.string "Hai! {PLAYER}? Halo, ini\n"
	.string "{STR_VAR_1}! Aku dengar beritanya!\p"
	.string "Kamu naik {STR_VAR_3} lantai di\n"
	.string "dalam {STR_VAR_2}, benar?\p"
	.string "Itu luar biasa! Aku harus mencoba\n"
	.string "tantangan itu.$"

MatchCall_BattlePyramidText2::
	.string "Halo, ini {STR_VAR_1}! Aku dengar\n"
	.string "tentang Kamu!\p"
	.string "Mereka bilang Kamu berhasil\n"
	.string "menembus {STR_VAR_3} lantai di\l"
	.string "{STR_VAR_2}.\p"
	.string "Wow, itu fantastis! Aku juga harus\n"
	.string "meningkatkan POKéMON-ku!$"

MatchCall_BattlePyramidText3::
	.string "Hai, {PLAYER}! Ini Aku,\n"
	.string "{STR_VAR_1}. Bagaimana kabarmu?\p"
	.string "Aku dengar Kamu naik {STR_VAR_3}\n"
	.string "lantai di {STR_VAR_2}!\p"
	.string "Coba lakukan yang lebih baik lagi\n"
	.string "lain kali! Sampai jumpa!$"

MatchCall_BattlePyramidText4::
	.string "Hei, {PLAYER}{KUN}. Ini\n"
	.string "{STR_VAR_1}.\p"
	.string "Aku dengar Kamu mendaki {STR_VAR_3}\n"
	.string "lantai di {STR_VAR_2}.\p"
	.string "Aku harus bekerja keras dan mencoba\n"
	.string "mengimbangi!$"

MatchCall_BattlePyramidText5::
	.string "Hai, {PLAYER}{KUN}! Ini\n"
	.string "{STR_VAR_1}.\p"
	.string "Aku dengar Kamu naik {STR_VAR_3}\n"
	.string "lantai di {STR_VAR_2}.\p"
	.string "Aku juga harus bekerja keras!\n"
	.string "Sampai jumpa!$"

MatchCall_BattlePyramidText6::
	.string "Hei, {PLAYER}{KUN}? Ini\n"
	.string "{STR_VAR_1}. Apa kabar?\p"
	.string "Ngomong-ngomong, Aku dengar Kamu\n"
	.string "melewati {STR_VAR_3} lantai di\l"
	.string "{STR_VAR_2}.\p"
	.string "Aku harus meningkatkan POKéMON-ku\n"
	.string "sebelum Kamu semakin jauh di depan.$"

MatchCall_BattlePyramidText7::
	.string "{PLAYER}{KUN}? Ini {STR_VAR_1}.\p"
	.string "Kamu ada di {STR_VAR_2} dan\n"
	.string "memenangkan {STR_VAR_3} lantai?\p"
	.string "Keren. Apakah ada POKéMON langka di\n"
	.string "sana?\p"
	.string "Tidak, ya? Oke, sampai jumpa.$"

MatchCall_BattlePyramidText8::
	.string "Oh, {PLAYER}{KUN}, apa kabar? Ini\n"
	.string "{STR_VAR_1}. Aku harap Kamu\l"
	.string "baik-baik saja. Oh, tentu saja Kamu\n"
	.string "baik.\p"
	.string "Aku dengar Kamu berhasil melewati\n"
	.string "{STR_VAR_3} lantai di {STR_VAR_2}.\p"
	.string "Itu sangat mengesankan! Aku harus\n"
	.string "melatih POKéMON-ku seperti Kamu.\l"
	.string "Sampai bertemu lagi.$"

MatchCall_BattlePyramidText9::
	.string "Oh, {PLAYER}{KUN}, hai! Ini\n"
	.string "{STR_VAR_1}!\p"
	.string "Aku dengar! Kamu berhasil\n"
	.string "memenangkan {STR_VAR_3} lantai di\l"
	.string "{STR_VAR_2}!\p"
	.string "Keren sekali! Aku juga harus\n"
	.string "berusaha lebih keras!$"

MatchCall_BattlePyramidText10::
	.string "Oh, {PLAYER}{KUN}, halo. Ini\n"
	.string "{STR_VAR_1}.\p"
	.string "Kamu naik {STR_VAR_3} lantai di\n"
	.string "dalam {STR_VAR_2}?\p"
	.string "Itu pencapaian yang luar biasa. Aku\n"
	.string "harus bekerja lebih keras.$"

MatchCall_BattlePyramidText11::
	.string "Ah, {PLAYER}{KUN}. Ini {STR_VAR_1}.\p"
	.string "Aku dengar Kamu adalah momok di\n"
	.string "{STR_VAR_2}?\p"
	.string "Kamu berhasil naik melewati, apa,\n"
	.string "{STR_VAR_3} lantai? Itu pasti\l"
	.string "berarti.\p"
	.string "Aku ingin tahu apakah Aku bisa\n"
	.string "menjadi juara?\p"
	.string "…Sepertinya mustahil? Baiklah,\n"
	.string "sampai jumpa!$"

MatchCall_BattlePyramidText12::
	.string "Halo, {PLAYER}{KUN}. Ini Aku,\n"
	.string "{STR_VAR_1}. Apa Kamu sehat?\p"
	.string "Kamu berhasil memenangkan\n"
	.string "{STR_VAR_3} lantai di tempat\l"
	.string "bernama {STR_VAR_2}?\p"
	.string "Itu kisah yang menarik. Sampai\n"
	.string "jumpa!$"

MatchCall_BattlePyramidText13::
	.string "Ah, halo, {PLAYER}{KUN}! Ini\n"
	.string "{STR_VAR_1}! Aku harap Kamu selalu\l"
	.string "sehat.\p"
	.string "Mereka bilang Kamu mendaki\n"
	.string "{STR_VAR_3} lantai di {STR_VAR_2}?\p"
	.string "Aku kagum dengan energimu! Sampai\n"
	.string "nanti.$"

MatchCall_BattlePyramidText14::
	.string "Oh, hai, {PLAYER}{KUN}. Ini\n"
	.string "{STR_VAR_1}. Aku dengar tentang\l"
	.string "Kamu!\p"
	.string "Bukankah Kamu berhasil melewati\n"
	.string "{STR_VAR_3} lantai di {STR_VAR_2}?\p"
	.string "Kamu adalah inspirasi! Sampai\n"
	.string "bertemu lagi!$"

MatchCall_Text_Mom1::
	.string "IBU: Ayahmu dan Kamu... Semua orang\n"
	.string "terpikat oleh POKéMON.\p"
	.string "Apa sih daya tarik POKéMON itu?\p"
	.string "Aku? Aku suka POKéMON yang bisa\n"
	.string "membantu pekerjaan rumah tanggaku\l"
	.string "sehari-hari.$"

MatchCall_Text_Mom2::
	.string "IBU: Hai, {PLAYER}! Ayahmu\n"
	.string "mengurung diri di GYM PETALBURG.\p"
	.string "Dia pulang sesekali. Tapi setelah\n"
	.string "menghabiskan semua makanan yang\l"
	.string "ada, dia kembali ke GYM.\p"
	.string "Kurasa kekalahan dari Kamu adalah\n"
	.string "pukulan besar bagi harga dirinya!$"

MatchCall_Text_Mom3::
	.string "IBU: {PLAYER}… Jangan khawatirkan\n"
	.string "Aku atau rumah ini.\p"
	.string "Kenakan SEPATU LARI itu sampai\n"
	.string "rusak, Nak!$"

MatchCall_Text_Roxanne1::
	.string "ROXANNE: Oh, halo, {PLAYER}!\p"
	.string "Aku sudah berlatih keras sejak kita\n"
	.string "bertemu.\p"
	.string "Aku masih butuh waktu lagi sebelum\n"
	.string "Aku bisa membuka kembali GYM.\p"
	.string "Tapi ketika Aku sudah siap, tolong\n"
	.string "kunjungi GYM-ku untuk tanding\l"
	.string "ulang!$"

MatchCall_Text_Roxanne2::
	.string "ROXANNE: Apakah ini {PLAYER}?\n"
	.string "Selamat! Aku sudah banyak mendengar\l"
	.string "tentang Kamu!\p"
	.string "Sedangkan Aku, Aku butuh waktu lagi\n"
	.string "sebelum Aku bisa membuka kembali\l"
	.string "GYM.\p"
	.string "Tapi ketika Aku sudah siap, tolong\n"
	.string "kunjungi GYM-ku untuk tanding\l"
	.string "ulang!$"

MatchCall_Text_Roxanne3::
	.string "ROXANNE: {PLAYER}! GYM-ku sudah\n"
	.string "siap!\p"
	.string "Tolong kunjungi RUSTBORO kapan pun\n"
	.string "Kamu bisa!$"

MatchCall_Text_Roxanne4::
	.string "ROXANNE: Di GYM RUSTBORO, kenyataan\n"
	.string "bahwa kita pernah bertarung,\l"
	.string "{PLAYER}, adalah sebuah kehormatan.$"

MatchCall_Text_Brawly1::
	.string "BRAWLY: Hei, {PLAYER}{KUN}!\p"
	.string "Aku belajar banyak dari pertarungan\n"
	.string "kita.\p"
	.string "Aku berniat untuk memulai latihan\n"
	.string "lagi, lalu membuka kembali GYM.\p"
	.string "Butuh waktu sebelum Aku siap\n"
	.string "menjalankan GYM lagi.\p"
	.string "Tapi jika Aku bisa membuka kembali\n"
	.string "GYM, Aku ingin Kamu menantang kami\l"
	.string "lagi.$"

MatchCall_Text_Brawly2::
	.string "BRAWLY: Hei, {PLAYER}{KUN}!\n"
	.string "Selamat!\p"
	.string "Kabar tentang prestasimu sampai\n"
	.string "terbawa ombak pasang!\p"
	.string "Sepertinya Aku perlu lebih banyak\n"
	.string "melatih diri.\p"
	.string "Butuh waktu sebelum Aku siap\n"
	.string "menjalankan GYM lagi.\p"
	.string "Tapi jika Aku bisa membuka kembali\n"
	.string "GYM, Aku ingin Kamu menantang kami\l"
	.string "lagi.$"

MatchCall_Text_Brawly3::
	.string "BRAWLY: Hei, {PLAYER}{KUN}! GYM-ku\n"
	.string "sudah siap beraksi!\p"
	.string "Kembali ke DEWFORD kapan saja untuk\n"
	.string "tantangan lain!$"

MatchCall_Text_Brawly4::
	.string "BRAWLY: {PLAYER}{KUN}, kurasa Aku\n"
	.string "tidak akan pernah bosan bertarung\l"
	.string "melawan Kamu!$"

MatchCall_Text_Wattson1::
	.string "WATTSON: Oh, ini Kamu!\p"
	.string "Setelah Kamu pergi, Aku sudah\n"
	.string "mengulang latihanku dari awal.\p"
	.string "Menurutku Aku butuh sedikit waktu\n"
	.string "lagi untuk membuka kembali GIM-ku.\p"
	.string "Kamu harus menunggu sampai saat\n"
	.string "itu! Wahahahaha!$"

MatchCall_Text_Wattson2::
	.string "WATTSON: Wahahahaha!\p"
	.string "Kamu benar-benar berhasil, kan? Aku\n"
	.string "sudah mendapat kabar tentang Kamu!\p"
	.string "Sepertinya Aku masih harus berlatih\n"
	.string "lagi.\p"
	.string "Menurutku Aku butuh sedikit waktu\n"
	.string "lagi untuk membuka kembali GIM-ku.\p"
	.string "Kamu harus menunggu sampai saat\n"
	.string "itu! Wahahahaha!$"

MatchCall_Text_Wattson3::
	.string "WATTSON: Oh, ini Kamu! GIM-ku sudah\n"
	.string "siap!\p"
	.string "Kunjungi MAUVILLE kapan saja!\n"
	.string "Wahahahaha!$"

MatchCall_Text_Wattson4::
	.string "WATTSON: Wahahaha!\p"
	.string "Pertarungan dengan Kamu selalu\n"
	.string "penuh dengan kekuatan yang\l"
	.string "mengejutkan!$"

MatchCall_Text_Flannery1::
	.string "FLANNERY: {PLAYER}…\p"
	.string "Ketika kita bertarung, Aku belajar\n"
	.string "betapa tidak dewasanya Aku.\p"
	.string "Tapi Aku belum selesai!\p"
	.string "Aku akan mengulang latihanku dan\n"
	.string "membuka kembali GIM.\p"
	.string "Ketika saatnya tiba, {PLAYER},\n"
	.string "tolong tantang kami lagi.$"

MatchCall_Text_Flannery2::
	.string "FLANNERY: Halo, {PLAYER}? Selamat!\p"
	.string "Kabar kesuksesan Kamu telah\n"
	.string "mencapai kami bagai panasnya gunung\l"
	.string "berapi!\p"
	.string "Latihan kami berjalan sangat baik\n"
	.string "di sini.\p"
	.string "Ketika GIM siap, tanda akan muncul\n"
	.string "di sebelah namaku dalam daftar\l"
	.string "PANGGILAN TANDING.$"

MatchCall_Text_Flannery3::
	.string "FLANNERY: Oh, {PLAYER}? GIM kami\n"
	.string "sudah siap!\p"
	.string "Datanglah ke LAVARIDGE untuk\n"
	.string "berendam di mata air panas dan\l"
	.string "menerima tantangan!$"

MatchCall_Text_Flannery4::
	.string "FLANNERY: {PLAYER}… Aku yakin Kamu\n"
	.string "terus menjadi lebih baik dalam\l"
	.string "latihan setiap saat.$"

MatchCall_Text_Winona1::
	.string "WINONA: Halo, {PLAYER}!\p"
	.string "Berkat pertarungan kita, Aku jadi\n"
	.string "mengerti titik lemahku!\p"
	.string "Ketika Aku membuka kembali GIM, Aku\n"
	.string "tidak akan kalah lagi!$"

MatchCall_Text_Winona2::
	.string "WINONA: Kamu berhasil, {PLAYER}!\p"
	.string "Berita tentang JUARA baru telah\n"
	.string "sampai kepada kami di FORTREE!\p"
	.string "Tapi… Kali berikutnya kita\n"
	.string "bertarung, hasilnya tidak akan\l"
	.string "berakhir sama.$"

MatchCall_Text_Winona3::
	.string "WINONA: Apakah ini {PLAYER}? GIM\n"
	.string "kami sudah beroperasi lagi!\p"
	.string "Kami menunggu Kamu di FORTREE!$"

MatchCall_Text_Winona4::
	.string "WINONA: {PLAYER}… Walaupun Aku\n"
	.string "telah kalah, sayapku tidak akan\l"
	.string "pernah patah.\p"
	.string "Ya, sama persis seperti Kamu yang\n"
	.string "tidak pernah kehilangan arah\l"
	.string "mimpimu.$"

MatchCall_Text_TateLiza1::
	.string "TATE: Oh! Kamu… LIZA: {PLAYER}!\p"
	.string "TATE: Kami sedang berlatih lagi…\n"
	.string "LIZA: Supaya kami bisa membuka\l"
	.string "kembali GIM kami!\p"
	.string "TATE: Ketika GIM kami siap… LIZA:\n"
	.string "Ketika GIM kami siap…\p"
	.string "TATE: Tanda akan muncul di samping\n"
	.string "nama kami… LIZA: Pada daftar\l"
	.string "PANGGILAN TANDING.$"

MatchCall_Text_TateLiza2::
	.string "TATE: {PLAYER}, selamat! LIZA:\n"
	.string "{PLAYER}, selamat!\p"
	.string "TATE: Kami berdua… LIZA: Masih\n"
	.string "berlatih!\p"
	.string "TATE: Kami butuh waktu lebih, tapi…\n"
	.string "LIZA: Ketika GIM kami siap…\p"
	.string "TATE: Tanda akan muncul di samping\n"
	.string "nama kami… LIZA: Pada daftar\l"
	.string "PANGGILAN TANDING.$"

MatchCall_Text_TateLiza3::
	.string "TATE: {PLAYER}! LIZA: {PLAYER}!\p"
	.string "TATE: GIM kami sudah siap! LIZA:\n"
	.string "GIM kami sudah siap!\p"
	.string "TATE: Silakan berkunjung ke… LIZA:\n"
	.string "MOSSDEEP kapan saja!$"

MatchCall_Text_TateLiza4::
	.string "TATE: {PLAYER}, pertarungan yang\n"
	.string "kita jalani… LIZA: Adalah\l"
	.string "pengalaman yang tak ternilai.\p"
	.string "TATE: Alangkah baiknya jika… LIZA:\n"
	.string "Kita semua bisa bertarung lagi!$"

MatchCall_Text_Juan1::
	.string "JUAN: Hmm… {PLAYER}{KUN}… Benarkah\n"
	.string "itu?\p"
	.string "Pertarungan kita bersama-itu\n"
	.string "membangkitkan ingatan tentang saat\l"
	.string "Aku pertama kali bertemu WALLACE.\p"
	.string "Mungkin Kamu adalah seorang jenius\n"
	.string "yang mungkin bisa melampaui\l"
	.string "WALLACE!$"

MatchCall_Text_Juan2::
	.string "JUAN: Fufu… {PLAYER}{KUN}… Kamu\n"
	.string "akhirnya mencapai tujuanmu.\p"
	.string "Mataku dalam menilai bakat tidak\n"
	.string "salah…\p"
	.string "Aku berharap mendapat kesempatan\n"
	.string "lain untuk bertemu dengan Kamu,\l"
	.string "karena Kamu telah mencapai puncak\n"
	.string "kekuatan dan kehormatan.$"

MatchCall_Text_Juan3::
	.string "JUAN: Hoho… {PLAYER}{KUN}…\p"
	.string "GIM SOOTOPOLIS kami akhirnya dibuka\n"
	.string "kembali.\p"
	.string "Jika Kamu ingin menemuiku, Kamu\n"
	.string "dipersilakan berkunjung kapan saja.$"

MatchCall_Text_Juan4::
	.string "JUAN: {PLAYER}{KUN}…\p"
	.string "Seperti musik terbaik, pertarungan\n"
	.string "yang kita lakukan bersama memicu\l"
	.string "inspirasi di hatiku…\p"
	.string "Ketika Aku memejamkan mata, Aku\n"
	.string "melihat bayangan Kamu melayang\l"
	.string "bersama melodi…$"

MatchCall_Text_Sidney::
	.string "SIDNEY: Yo, {PLAYER}!\p"
	.string "Jika Kamu ingin bertarung lagi\n"
	.string "denganku, kembalilah kapan pun Kamu\l"
	.string "mau ke LIGA POKéMON.\p"
	.string "Aku akan selalu ada di sini! Aku\n"
	.string "akan menunggu!$"

MatchCall_Text_Phoebe::
	.string "PHOEBE: Hai, {PLAYER}!\p"
	.string "Bagaimana kalau kembali ke sini\n"
	.string "lagi lain waktu?\p"
	.string "Aku ingin melihat seberapa erat\n"
	.string "ikatan Kamu dengan POKéMON-mu.$"

MatchCall_Text_Glacia::
	.string "GLACIA: Halo, {PLAYER}.\p"
	.string "Aku harap Kamu tidak menjadi puas\n"
	.string "dengan kekuatanmu?\p"
	.string "Jika Kamu merasa perlu mendinginkan\n"
	.string "sedikit emosimu yang panas,\l"
	.string "datanglah ke LIGA POKéMON…$"

MatchCall_Text_Drake::
	.string "DRAKE: Suara itu… {PLAYER}, ya?\n"
	.string "Kamu terdengar baik-baik saja…\p"
	.string "Aku mengerti bahwa sekarang ada\n"
	.string "fasilitas bernama BATAS PERTARUNGAN\l"
	.string "yang menguji kemampuan PELATIH.\p"
	.string "Namun, jika Kamu ingin mendapatkan\n"
	.string "pertarungan yang sesungguhnya,\l"
	.string "tidak ada yang bisa menggantikan\n"
	.string "LIGA POKéMON!\p"
	.string "Kamu setuju, {PLAYER}?$"

MatchCall_Text_Wallace::
	.string "WALLACE: Halo, {PLAYER}{KUN}. Apa\n"
	.string "Kamu sudah bertemu STEVEN?\p"
	.string "Dia adalah… Sebenarnya sangat\n"
	.string "terampil.\p"
	.string "Namun, dia adalah jiwa aneh yang\n"
	.string "jarang bertarung.\p"
	.string "Sebaliknya, dia lebih suka mencari\n"
	.string "batu langka.\p"
	.string "Aku yakin dia sedang menggali di\n"
	.string "gua atau gunung terjal di suatu\l"
	.string "tempat.\p"
	.string "Tapi apa sebenarnya batu langka\n"
	.string "itu? Yang bisa kupikirkan hanyalah\l"
	.string "METEORIT…$"

MatchCall_Text_MayRayquazaCall:
	.string "… … … … … … … … … … … Beep!\p"
	.string "MAY: Hai, {PLAYER}{KUN}!\p"
	.string "Aku baru saja berada di PACIFIDLOG\n"
	.string "beberapa waktu lalu.\p"
	.string "Aku melihat POKéMON hijau raksasa\n"
	.string "terbang tinggi di langit.\p"
	.string "Aku… Aku belum pernah melihat yang\n"
	.string "seperti itu.\p"
	.string "Aku ingin tahu itu apa. Apakah ini\n"
	.string "mungkin penemuan besar?\p"
	.string "… … … … … … … … … … … Klik!$"

MatchCall_Text_BrendanRayquazaCall:
	.string "… … … … … … … … … … … Beep!\p"
	.string "BRENDAN: Hei, {PLAYER}! Aku baru\n"
	.string "saja berada di PACIFIDLOG.\p"
	.string "Aku melihat POKéMON hijau besar ini\n"
	.string "terbang melintasi langit.\p"
	.string "Aku belum pernah melihat sesuatu\n"
	.string "yang begitu menakjubkan sebelumnya.\p"
	.string "Aku harap Kamu bisa melihatnya,\n"
	.string "{PLAYER}.\p"
	.string "… … … … … … … … … … … Klik!$"

MatchCall_Text_May1::
	.string "MAY: Hai, {PLAYER}{KUN}!\p"
	.string "MR. BRINEY pensiun sebagai PELAUT,\n"
	.string "tapi Aku terkadang masih melihatnya\l"
	.string "di laut bersama PEEKO\n"
	.string "peliharaannya.\p"
	.string "Dia pasti masih mencintai laut.$"

MatchCall_Text_May2::
	.string "MAY: Hai, {PLAYER}{KUN}!\p"
	.string "Kamu tahu kota-kota kecil seperti\n"
	.string "PETALBURG dan DEWFORD punya GIM?\p"
	.string "Entah kenapa, pelabuhan besar\n"
	.string "SLATEPORT tidak punya GIM.\p"
	.string "Ketika mereka akhirnya membangun\n"
	.string "GIM di sana, Aku harus melamar\l"
	.string "untuk menjadi PEMIMPIN.$"

MatchCall_Text_May3::
	.string "MAY: Hai, {PLAYER}{KUN}!\p"
	.string "Apa Kamu ingat pria bernama\n"
	.string "PEMOTONG di RUSTBORO? Dia punya\l"
	.string "rumah di sana, ingat?\p"
	.string "Nah, Aku tahu adik laki-lakinya\n"
	.string "tinggal di MAUVILLE.\p"
	.string "Bisakah Kamu menebak namanya?\p"
	.string "… … … … … … … … … … … …\p"
	.string "Pria PEMENGGAL BATU!$"

MatchCall_Text_May4::
	.string "MAY: {PLAYER}{KUN}?\p"
	.string "TEROWONGAN RUSTURF… Mereka\n"
	.string "menamainya begitu karena terowongan\l"
	.string "itu menghubungkan RUSTBORO dan\n"
	.string "VERDANTURF.$"

MatchCall_Text_May5::
	.string "MAY: {PLAYER}{KUN}, apa kabar?\p"
	.string "Aku sekarang ada di RUTE 111.\p"
	.string "Aku akan beristirahat di rumah\n"
	.string "seorang wanita tua.\p"
	.string "Dia tinggal di utara gurun.$"

MatchCall_Text_May6::
	.string "MAY: Hai, {PLAYER}{KUN}!\p"
	.string "Apa Kamu tahu tentang MENARA\n"
	.string "FATAMORGANA di gurun?\p"
	.string "Mereka bilang, seperti fatamorgana,\n"
	.string "menara itu tampaknya muncul dan\l"
	.string "menghilang secara misterius.\p"
	.string "Aku harap Aku bisa melihatnya.$"

MatchCall_Text_May7::
	.string "MAY: {PLAYER}{KUN}, yahuu! Aku\n"
	.string "sekarang ada di RUTE 119.\p"
	.string "Ada sungai besar di sini, dan\n"
	.string "sering hujan.\p"
	.string "Aku basah kuyup!$"

MatchCall_Text_May8::
	.string "MAY: {PLAYER}{KUN}, hai.\p"
	.string "GUNUNG PYRE adalah monumen bagi\n"
	.string "POKéMON yang telah mengakhiri\l"
	.string "hidupnya.\p"
	.string "Mungkin akibatnya, tempat ini\n"
	.string "dipenuhi oleh banyak POKéMON tipe\l"
	.string "HANTU!$"

MatchCall_Text_May9::
	.string "MAY: Hai, {PLAYER}{KUN}!\p"
	.string "Aku sedang berpikir untuk pergi ke\n"
	.string "mata air panas di LAVARIDGE.\p"
	.string "Tapi dalam perjalanan, di sekitar\n"
	.string "JAGGED PASS, Aku bertemu dengan\l"
	.string "beberapa karakter berpenampilan\n"
	.string "buruk. Suasananya tidak enak!$"

MatchCall_Text_May10::
	.string "MAY: Hai, {PLAYER}{KUN}! Apa Kamu\n"
	.string "lihat berita?\p"
	.string "Mereka bilang KAPETEN STERN\n"
	.string "menemukan GUA DASAR LAUT saat\l"
	.string "ekspedisi kapal selamnya.$"

MatchCall_Text_May11::
	.string "MAY: Hai, {PLAYER}! Bukankah ini\n"
	.string "keren?\p"
	.string "Bahkan tanpa perahu, Kamu bisa\n"
	.string "menyeberangi lautan menggunakan\l"
	.string "gerakan POKéMON.\p"
	.string "Tahukah Kamu, ada lagi lho?\p"
	.string "Ada gerakan POKéMON yang membuat\n"
	.string "Kamu bisa pergi ke dasar laut.$"

MatchCall_Text_May12::
	.string "MAY: Hai, {PLAYER}! Semoga semuanya\n"
	.string "baik-baik saja!\p"
	.string "Apakah Kamu pernah di laut dan\n"
	.string "jalan ke seberang terhalang?\p"
	.string "Coba menyelam jauh ke bawah air dan\n"
	.string "ikuti parit laut.\p"
	.string "Ketika Kamu sampai di seberang,\n"
	.string "naiklah ke permukaan. Mudah, kan!$"

MatchCall_Text_May13::
	.string "MAY: Hai, {PLAYER}!\p"
	.string "Bagaimana kabarmu? Apakah Kamu\n"
	.string "sedang mengisi POKéDEX-mu?\p"
	.string "Aku dengar rumor bahwa ada POKéMON\n"
	.string "super kuno di luar sana. Dan ada\l"
	.string "tiga!\p"
	.string "Aku ingin sekali melihatnya walau\n"
	.string "hanya satu…$"

MatchCall_Text_May14::
	.string "MAY: {PLAYER}! Aku dengar rumornya!\p"
	.string "Kamu mengalahkan PEMIMPIN GYM\n"
	.string "SOOTOPOLIS?\p"
	.string "Itu berarti Kamu tidak perlu jauh\n"
	.string "lagi, ya kan?$"

MatchCall_Text_May15::
	.string "MAY: Tidak ada satu pun PELATIH\n"
	.string "yang tersisa di HOENN yang tidak\l"
	.string "tahu siapa Kamu, {PLAYER}!\p"
	.string "Ketika Aku memberi tahu orang-orang\n"
	.string "bahwa Aku berteman denganmu,\l"
	.string "{PLAYER}, mereka semua terkejut!$"

MatchCall_Text_Brendan1::
	.string "BRENDAN: Hei, {PLAYER}!\p"
	.string "BRINEY pensiun sebagai PELAUT, tapi\n"
	.string "Aku masih sering melihatnya di laut\l"
	.string "bersama PEEKO peliharaannya.\p"
	.string "Kurasa dia pasti masih mencintai\n"
	.string "laut.$"

MatchCall_Text_Brendan2::
	.string "BRENDAN: Hei, {PLAYER}!\p"
	.string "Aku tidak mengerti bagaimana\n"
	.string "kota-kota kecil seperti PETALBURG\l"
	.string "dan DEWFORD punya GYM.\p"
	.string "Maksudku, padahal pelabuhan besar\n"
	.string "SLATEPORT tidak punya GYM.\p"
	.string "Ketika mereka akhirnya membangun\n"
	.string "GYM di sana, Aku harus melamar jadi\l"
	.string "PEMIMPIN.$"

MatchCall_Text_Brendan3::
	.string "BRENDAN: Yo, {PLAYER}!\p"
	.string "Apakah Kamu ingat seseorang bernama\n"
	.string "SI PEMOTONG di RUSTBORO? Dia punya\l"
	.string "rumah di sana, kan?\p"
	.string "Nah, ternyata adik laki-lakinya\n"
	.string "tinggal di MAUVILLE.\p"
	.string "Bisakah Kamu menebak namanya?\p"
	.string "… … … … … … … … … … … …\p"
	.string "SI PEMECAH BATU!$"

MatchCall_Text_Brendan4::
	.string "BRENDAN: Suara ini… {PLAYER}?\p"
	.string "Mereka memberi nama TEROWONGAN\n"
	.string "RUSTURF karena menghubungkan\l"
	.string "RUSTBORO dan VERDANTURF.\p"
	.string "Apakah Kamu tahu itu?$"

MatchCall_Text_Brendan5::
	.string "BRENDAN: {PLAYER}, ada apa?\p"
	.string "Hei, Aku sekarang ada di RUTE 111.\p"
	.string "Aku akan beristirahat di rumah\n"
	.string "seorang wanita tua di utara gurun.\p"
	.string "Jika Kamu di daerah ini, Kamu harus\n"
	.string "mengunjunginya juga.$"

MatchCall_Text_Brendan6::
	.string "BRENDAN: Hei, {PLAYER}!\p"
	.string "Apakah Kamu tahu tentang MENARA\n"
	.string "FATAMORGANA di gurun?\p"
	.string "Mereka bilang, seperti fatamorgana,\n"
	.string "menara itu hanya terlihat\l"
	.string "kadang-kadang.\p"
	.string "Aku ingin melihatnya!$"

MatchCall_Text_Brendan7::
	.string "BRENDAN: Siapa ini? Oh, {PLAYER}?\n"
	.string "Tebak apa? Aku sekarang ada di RUTE\l"
	.string "119.\p"
	.string "Di sini ada sungai besar, dan\n"
	.string "selalu hujan.\p"
	.string "Aku basah kuyup sampai ke tulang!$"

MatchCall_Text_Brendan8::
	.string "BRENDAN: {PLAYER}!\p"
	.string "GUNUNG PYRE adalah monumen bagi\n"
	.string "POKéMON yang telah berakhir\l"
	.string "hidupnya.\p"
	.string "Itu mungkin sebabnya tempat itu\n"
	.string "dipenuhi banyak POKéMON tipe HANTU!$"

MatchCall_Text_Brendan9::
	.string "BRENDAN: Hai, {PLAYER}.\p"
	.string "Aku sedang dalam perjalanan kembali\n"
	.string "ke pemandian air panas di\l"
	.string "LAVARIDGE.\p"
	.string "Tapi di sekitar JAGGED PASS, Aku\n"
	.string "bertemu dengan beberapa orang yang\l"
	.string "tampak jahat.\p"
	.string "Para bajingan itu… Kurasa mereka\n"
	.string "TIM MAGMA.$"

MatchCall_Text_Brendan10::
	.string "BRENDAN: Hai, {PLAYER}! Apakah Kamu\n"
	.string "mendengar beritanya?\p"
	.string "Mereka bilang KAP. STERN menemukan\n"
	.string "GUA DASAR LAUT saat melakukan\l"
	.string "ekspedisi kapal selamnya.$"

MatchCall_Text_Brendan11::
	.string "BRENDAN: Hai, {PLAYER}! Bukankah\n"
	.string "ini luar biasa?\p"
	.string "Bahkan tanpa perahu, Kamu bisa\n"
	.string "menyeberangi laut menggunakan\l"
	.string "gerakan POKéMON.\p"
	.string "Dan, ada gerakan yang memungkinkan\n"
	.string "Kamu melakukan perjalanan ke dasar\l"
	.string "laut.\p"
	.string "Wah, POKéMON bisa melakukan apa\n"
	.string "saja!$"

MatchCall_Text_Brendan12::
	.string "BRENDAN: Hai, {PLAYER}! Bagaimana\n"
	.string "kabarmu?\p"
	.string "Pernahkah Kamu mendapati jalan ke\n"
	.string "seberang terhalang saat berada di\l"
	.string "laut?\p"
	.string "Coba menyelam jauh ke bawah air dan\n"
	.string "ikuti parit di dasarnya.\p"
	.string "Ketika Kamu sampai di seberang,\n"
	.string "naiklah ke permukaan. Sederhana!$"

MatchCall_Text_Brendan13::
	.string "BRENDAN: Hai, {PLAYER}!\p"
	.string "Bagaimana kabarmu? Berhasil mengisi\n"
	.string "POKéDEX-mu?\p"
	.string "Aku dengar rumor bahwa ada POKéMON\n"
	.string "super kuno di luar sana. Dan bukan\l"
	.string "hanya satu--tiga!\p"
	.string "Aku ingin sekali menangkap walau\n"
	.string "hanya satu…$"

MatchCall_Text_Brendan14::
	.string "BRENDAN: {PLAYER}! Aku dengar\n"
	.string "rumornya!\p"
	.string "Kamu mengalahkan PEMIMPIN GYM\n"
	.string "SOOTOPOLIS? Keren!\p"
	.string "Kamu sudah sangat dekat sekarang!$"

MatchCall_Text_Brendan15::
	.string "BRENDAN: Tidak ada PELATIH di\n"
	.string "seluruh HOENN yang tidak tahu siapa\l"
	.string "Kamu, {PLAYER}!\p"
	.string "Ketika Aku memberi tahu orang-orang\n"
	.string "bahwa Aku berteman denganmu,\l"
	.string "{PLAYER}, mereka menjadi sangat\n"
	.string "iri!$"

MatchCall_Text_Wally1::
	.string "WALLY: Oh, {PLAYER}!\p"
	.string "Aku menjadi lebih sehat dan lebih\n"
	.string "bugar secara fisik.\p"
	.string "Aku harap Aku bisa segera menjadi\n"
	.string "PELATIH sepertimu, {PLAYER}!$"

MatchCall_Text_Wally2::
	.string "WALLY: {PLAYER}, halo!\p"
	.string "Setelah TEROWONGAN RUSTURF dibuka,\n"
	.string "WANDA sangat bahagia!$"

MatchCall_Text_Wally3::
	.string "WALLY: Oh, {PLAYER}!\p"
	.string "Aku… Aku meninggalkan rumah pamanku\n"
	.string "di VERDANTURF tanpa memberi tahu\l"
	.string "siapa pun.\p"
	.string "Aku ingin tahu apakah dia marah\n"
	.string "padaku…\p"
	.string "{PLAYER}, Kamu mengerti perasaanku,\n"
	.string "kan?$"

MatchCall_Text_Wally4::
	.string "WALLY: {PLAYER}? Ini Aku, WALLY!\p"
	.string "Dunia PELATIH sangat menakjubkan!\p"
	.string "Ketika Aku membawa POKéMON-ku,\n"
	.string "segala macam orang menyapa!\p"
	.string "Seolah-olah semua orang terhubung\n"
	.string "melalui POKéMON!$"

MatchCall_Text_Wally5::
	.string "WALLY: {PLAYER}? Ini keren! RALTS\n"
	.string "yang kita tangkap bersama itu? Dia\l"
	.string "berevolusi, {PLAYER}!\p"
	.string "Mungkin Aku berbakat…\p"
	.string "Oh, tapi Aku tidak boleh besar\n"
	.string "kepala seperti itu!\p"
	.string "Bagaimanapun, POKéMON-lah yang\n"
	.string "harus dipuji!$"

MatchCall_Text_Wally6::
	.string "… … … … … … … … … … … …\p"
	.string "WALLY tampaknya berada di luar area\n"
	.string "layanan POKéNAV…$"

MatchCall_Text_Wally7::
	.string "WALLY: Oh, {PLAYER}!\p"
	.string "Sebelum Aku bertemu denganmu, Aku\n"
	.string "hampir tidak pernah meninggalkan\l"
	.string "rumahku…\p"
	.string "Tapi sekarang, Aku berpetualang\n"
	.string "dengan POKéMON-ku sendiri…\p"
	.string "{PLAYER}… Terima kasih…$"

MatchCall_Text_Scott1::
	.string "SCOTT: Halo, {PLAYER}!\p"
	.string "Kamu tahu kan kalau POKéMON bisa\n"
	.string "ditemukan di mana saja?\p"
	.string "Seperti di pegunungan, di laut, di\n"
	.string "rumput tinggi di mana pun?\p"
	.string "Sama seperti POKéMON, Kamu juga\n"
	.string "bisa menemukan PELATIH di mana\l"
	.string "saja.\p"
	.string "Akibatnya, Aku juga harus buru-buru\n"
	.string "ke mana-mana. Sibuk sekali!$"

MatchCall_Text_Scott2::
	.string "SCOTT: Aku sedang di RUTE 119\n"
	.string "sekarang. Penuh dengan PELATIH!\p"
	.string "Sepertinya juga ditumbuhi rumput\n"
	.string "tinggi di mana-mana.\p"
	.string "Berjalan-jalan dengan celana pendek\n"
	.string "di sini membuatku geli!$"

MatchCall_Text_Scott3::
	.string "SCOTT: Hai, hai, {PLAYER}!\p"
	.string "Apakah Kamu sudah sempat mendaki\n"
	.string "GUNUNG PYRE?\p"
	.string "Tempat itu adalah monumen bagi\n"
	.string "POKéMON yang telah tiada.\p"
	.string "Itu adalah tempat yang harus didaki\n"
	.string "setiap PELATIH setidaknya sekali.$"

MatchCall_Text_Scott4::
	.string "SCOTT: Hai, {PLAYER}!\p"
	.string "Aku sudah mendengar tentang\n"
	.string "geng-geng aneh ini yang meresahkan.\p"
	.string "TIM MAGMA dan TIM AQUA, kurasa\n"
	.string "mereka itu.\p"
	.string "Aku pikir pasti ada beberapa\n"
	.string "PELATIH terampil di antara mereka.\p"
	.string "…Tapi jika mereka adalah preman…$"

MatchCall_Text_Scott5::
	.string "SCOTT: Oh, hai, {PLAYER}.\p"
	.string "Mungkinkah ada PELATIH tangguh di\n"
	.string "dasar laut?\p"
	.string "Aku tidak bisa pergi memeriksanya\n"
	.string "sendiri. Pertama, Aku tidak bisa\l"
	.string "berenang. Dan Aku tidak memelihara\n"
	.string "POKéMON…$"

MatchCall_Text_Scott6::
	.string "SCOTT: Hai, hai, {PLAYER}!\p"
	.string "Kamu tahu kan bahwa Kamu bisa\n"
	.string "menantang LIGA POKéMON setelah Kamu\l"
	.string "mengumpulkan semua LENCANA GYM?\p"
	.string "Dengan bakatmu, menjadi JUARA\n"
	.string "bukanlah sekadar impian.\p"
	.string "Tapi tahukah Kamu? Ada tempat yang\n"
	.string "bahkan lebih baik.\p"
	.string "Tapi, hanya itu yang bisa Aku\n"
	.string "katakan untuk saat ini.\p"
	.string "Itu adalah sesuatu yang bisa Kamu\n"
	.string "nantikan.\p"
	.string "Setelah Kamu memenangkan jalanmu\n"
	.string "melalui LIGA POKéMON dan masuk ke\l"
	.string "BALAI KETENARAN!$"

MatchCall_Text_Scott7::
	.string "… … … … … … … … … … … …\p"
	.string "SCOTT tampaknya berada di luar area\n"
	.string "layanan POKéNAV…$"

MatchCall_Text_Norman1::
	.string "AYAH: Di RUSTBORO, ada seorang pria\n"
	.string "yang menggunakan nama aneh, SI\l"
	.string "PEMOTONG.\p"
	.string "Jika Kamu berada di daerah itu,\n"
	.string "Kamu harus mengunjunginya.$"

MatchCall_Text_Norman2::
	.string "Hm... Sedikit demi sedikit, tapi\n"
	.string "juga pasti, kamu semakin tangguh,\l"
	.string "{PLAYER}.\p"
	.string "Semakin kuat kamu, semakin jauh dan\n"
	.string "tinggi kamu terbang meninggalkan\l"
	.string "Ibu dan aku...\p"
	.string "Perasaan ini sulit dijelaskan.$"

MatchCall_Text_Norman3::
	.string "Ayah lihat... Kamu sudah\n"
	.string "mengumpulkan empat LENCANA GYM...\p"
	.string "Sekarang sudah tak terhindarkan.\n"
	.string "Kita akan bertarung seperti yang\l"
	.string "aku janjikan.\p"
	.string "Datanglah kapan saja. Kami semua\n"
	.string "akan menunggumu!$"

MatchCall_Text_Norman4::
	.string "{PLAYER}! Sebaiknya kamu sesekali\n"
	.string "mengunjungi Ibu.\p"
	.string "Aku akan tetap di sini dan\n"
	.string "melipatgandakan latihanku.\p"
	.string "Jalan pertarungan itu mendalam dan\n"
	.string "tak kenal ampun!$"

MatchCall_Text_Norman5::
	.string "Oh, hai, {PLAYER}!\p"
	.string "Apa itu? LAMBANG MAGMA? Aku tidak\n"
	.string "tahu apa-apa tentang itu.\p"
	.string "Tapi dengan nama seperti itu,\n"
	.string "mungkin ada hubungannya dengan\l"
	.string "gunung berapi!$"

MatchCall_Text_Norman6::
	.string "Hiyah! Haah! Dwah!\p"
	.string "...Oh? {PLAYER}!\p"
	.string "Kamu memergoki aku tepat di tengah\n"
	.string "sesi latihan POKéMON!$"

MatchCall_Text_Norman7::
	.string "{PLAYER}! Siapa sangka kamu akan\n"
	.string "menjadi JUARA LIGA POKéMON...\p"
	.string "Baiklah! Aku tidak akan tertinggal!\p"
	.string "Hm? {PLAYER}? Waktunya tepat\n"
	.string "sekali!$"

MatchCall_Text_Norman8::
	.string "Kali ini, aku akan menantangmu\n"
	.string "untuk bertarung.\p"
	.string "Aku menunggu di GYM PETALBURG.\n"
	.string "Terima tantanganku kapan saja!\p"
	.string "...Kamu membuatku kagum, {PLAYER}.\n"
	.string "Seberapa tinggi lagi kamu akan\l"
	.string "terbang?$"

MatchCall_Text_Norman9::
	.string "Hai, {PLAYER}!$"

MatchCall_Text_Steven1::
	.string "Kamu sudah ke MAUVILLE?\p"
	.string "Kamu harus mengunjungi TOKO SEPEDA\n"
	.string "dan mendapatkan SEPEDA MACH.\p"
	.string "Lalu, coba jelajahi GUA GRANIT\n"
	.string "dengan saksama.\p"
	.string "Kamu mungkin menemukan penemuan\n"
	.string "baru di sana.\p"
	.string "Hai, {PLAYER}!$"

MatchCall_Text_Steven2::
	.string "Aku sudah bertemu banyak PELATIH\n"
	.string "yang berbeda sejauh ini.\p"
	.string "Tapi kamu unik. Kamu tidak seperti\n"
	.string "yang lain.\p"
	.string "Hai, {PLAYER}! Saat kamu\n"
	.string "berpetualangan dengan POKéMON-mu,\l"
	.string "apa yang kamu pikirkan?$"

MatchCall_Text_Steven3::
	.string "Apakah kamu menganggap mereka\n"
	.string "sebagai mitra yang kuat?\p"
	.string "Apakah kamu menganggap mereka\n"
	.string "sebagai teman yang menyenangkan?\p"
	.string "Tergantung bagaimana kamu berpikir,\n"
	.string "makna petualanganmu akan berubah.\p"
	.string "Halo? {PLAYER}?\p"
	.string "Aku sedang menghadapi sedikit\n"
	.string "masalah di PUSAT ANTARIKSA.$"

MatchCall_Text_Steven4::
	.string "Maaf, tapi aku tidak bisa bicara\n"
	.string "sekarang. Sampai jumpa!\p"
	.string "Oh! {PLAYER}!\p"
	.string "Tidak perlu bicara. Sudah lewat\n"
	.string "waktunya untuk bicara.$"

MatchCall_Text_Steven5::
	.string "Kamu harus percaya pada dirimu\n"
	.string "sendiri dan melakukan yang benar.\p"
	.string "... ... ... ... ... ...\p"
	.string "Sepertinya STEVEN tidak menerima\n"
	.string "panggilan itu...$"

MatchCall_Text_Steven6::
	.string "{PLAYER}... Selamat karena masuk ke\n"
	.string "BALAI KETENARAN.\p"
	.string "... ... ... ... ... ... ... ... ...\n"
	.string "... ... ...$"

MatchCall_Text_Steven7::
	.string "Aku harap kita bisa bertemu lagi di\n"
	.string "suatu tempat!\p"
	.string "Oh, {PLAYER}! Aku sudah dengar\n"
	.string "tentang kamu!\p"
	.string "Sepertinya POKéNAV-mu sudah\n"
	.string "ditingkatkan dengan PANGGILAN\l"
	.string "TANDING.$"

MatchCall_Text_BirchRegisterCall:
	.string "Nah, aku juga harus mendaftar!\p"
	.string "Dengan begitu, aku bisa memeriksa\n"
	.string "POKéDEX-mu bahkan saat kamu berada\l"
	.string "di lapangan.\p"
	.string "... ... ... ... ... ...\p"
	.string "PROF. BIRCH telah didaftarkan di\n"
	.string "POKéNAV.\p"
	.string "Jika seseorang memiliki POKéDEX dan\n"
	.string "POKéNAV, mempelajari POKéMON jadi\l"
	.string "lebih menyenangkan, ya?$"

MatchCall_Text_RegisteredBirch:
	.string "Oh? {PLAYER}!$"

MatchCall_Text_UnusedProfBirch:
	.string "Karena kamu meneleponku, POKéNAV\n"
	.string "pasti berfungsi dengan baik!$"

MatchCall_Text_MrStone1::
	.string "Orang lain juga akan didaftarkan,\n"
	.string "jadi coba telepon mereka juga!\p"
	.string "Bagus! Bagus! Kamu tampaknya cukup\n"
	.string "senang!\p"
	.string "Hm... Bagaimana aku bisa tahu itu?\p"
	.string "Itu karena aku sedang melihatmu\n"
	.string "dari jendela kantorku!\p"
	.string "Wahahaha! Sampai jumpa lagi!\p"
	.string "Oh? {PLAYER}!\p"
	.string "Ada apa? Apakah kamu lupa tentang\n"
	.string "tugas kecilku itu?$"

MatchCall_Text_MrStone2::
	.string "Aku butuh kamu mengirimkan suratku\n"
	.string "kepada STEVEN di DEWFORD.\p"
	.string "Setelah itu, kirimkan paket kami\n"
	.string "kepada KAPTEN STERN di SLATEPORT.\p"
	.string "Kamu ingat, bukan?\p"
	.string "Sekarang, karena aku adalah\n"
	.string "PRESIDEN yang sibuk, aku harus\l"
	.string "pergi! Sampai jumpa!\p"
	.string "Oh! {PLAYER}!\p"
	.string "Ah, jadi kamu sudah bertemu STEVEN!\n"
	.string "Kalau begitu, aku harus memberimu\l"
	.string "hadiah!$"

MatchCall_Text_MrStone3::
	.string "Ketika kamu mengunjungi RUSTBORO\n"
	.string "lagi, datanglah menemuiku di\l"
	.string "kantorku.\p"
	.string "Aku akan menunggumu!\p"
	.string "Oh! {PLAYER}!\p"
	.string "Tahukah kamu bahwa DEVON menggali\n"
	.string "TEROWONGAN RUSTURF?$"

MatchCall_Text_MrStone4::
	.string "Tapi kami menghentikan operasi itu\n"
	.string "untuk melindungi POKéMON di area\l"
	.string "tersebut.\p"
	.string "Itu hal yang mudah, sungguh.\p"
	.string "Lebih penting membiarkan POKéMON\n"
	.string "hidup damai daripada memikirkan\l"
	.string "kenyamanan kita sendiri.\p"
	.string "Halo, halo, {PLAYER}!\p"
	.string "Aku dengar dari seseorang di\n"
	.string "PETALBURG bahwa kamu adalah anak\l"
	.string "NORMAN!$"

MatchCall_Text_MrStone5::
	.string "Pantasan saja kamu makhluk yang\n"
	.string "sangat cakap!\p"
	.string "Apa itu?\p"
	.string "Kamu melawan ayahmu sendiri dan\n"
	.string "mengalahkannya?$"

MatchCall_Text_MrStone6::
	.string "Itu mencengangkan!\p"
	.string "Aku tidak tahu aku berteman dengan\n"
	.string "seseorang yang begitu istimewa!\l"
	.string "Wahaha!\p"
	.string "Halo! Ini DEVON KORPORA... Oh,\n"
	.string "halo, {PLAYER}!\p"
	.string "PRESIDEN kami ada di sini sebentar\n"
	.string "yang lalu, tapi dia sudah keluar.$"

MatchCall_Text_MrStone7::
	.string "PRESIDEN kami sibuk, tapi kamu\n"
	.string "tampaknya sama sibuknya, {PLAYER}.\p"
	.string "...Hah? ...Apa itu?\p"
	.string "GROU... Ya? ...DON?$"

MatchCall_Text_MrStone8::
	.string "Kamu terputus... ...tidak bisa\n"
	.string "dengar...\p"
	.string "BZZZZ...\p"
	.string "...Hah? ...Apa itu?\p"
	.string "Gua da... Ya? ...Sinar...?$"

MatchCall_Text_MrStone9::
	.string "Kamu terputus... ...tidak bisa\n"
	.string "dengar...\p"
	.string "BZZZZ...\p"
	.string "{PLAYER}! Ini aku!\p"
	.string "Kamu rupanya terlibat dalam segala\n"
	.string "macam hal, tapi aku, karena sibuk,\l"
	.string "tidak tahu persis apa itu!$"

MatchCall_Text_MrStone10::
	.string "Namun, aku mendesakmu untuk\n"
	.string "mengambil jalan yang kamu yakini\l"
	.string "dan menapakinya.\p"
	.string "Aku akan selalu mendukungmu! Jaga\n"
	.string "dirimu!\p"
	.string "... ... ... ... ... ... Mungkinkah\n"
	.string "ini {PLAYER}?\p"
	.string "Suaramu begitu penuh keyakinan, aku\n"
	.string "sampai tidak langsung mengenalimu!$"

MatchCall_Text_MrStone11::
	.string "Hm! Kamu harus datang mengunjungi\n"
	.string "kami di DEVON kapan-kapan!\p"