@ Only contains the text for the Mauville Man named Giddy. The rest is in scripts/mauville_man.inc
GiddyText_SoPretty::
	.string " sangat cantik!$"

GiddyText_SoDarling::
	.string " sangat manis!$"

GiddyText_SoRelaxed::
	.string " sangat santai!$"

GiddyText_SoSunny::
	.string " sangat cerah!$"

GiddyText_SoDesirable::
	.string " sangat menarik!$"

GiddyText_SoExciting::
	.string " sangat seru!$"

GiddyText_SoAmusing::
	.string " sangat lucu!$"

GiddyText_SoMagical::
	.string " sangat ajaib!$"

GiddyText_Is::
	.string " adalah$"

GiddyText_DontYouAgree::
	.string "\n"
	.string "Kamu setuju, kan?$"

GiddyText_ISoWantToGoOnAVacation::
	.string "Aku sangat ingin pergi liburan.\n"
	.string "Apa kamu tahu tempat yang bagus?$"

GiddyText_IBoughtCrayonsWith120Colors::
	.string "Aku membeli krayon dengan 120 warna!\n"
	.string "Bukankah itu bagus?$"

GiddyText_WouldntItBeNiceIfWeCouldFloat::
	.string "Bukankah menyenangkan jika kita bisa\n"
	.string "terbang di atas awan gelembung?$"

GiddyText_WhenYouWriteOnASandyBeach::
	.string "Saat kamu menulis di pantai berpasir,\n"
	.string "tulisan itu akan terhapus. Itu membuatku sedih.$"

GiddyText_WhatsTheBottomOfTheSeaLike::
	.string "Bagaimana dasar laut itu?\n"
	.string "Sekali saja aku ingin sekali pergi!$"

GiddyText_WhenYouSeeTheSettingSunDoesIt::
	.string "Saat kamu melihat matahari terbenam, apakah itu\n"
	.string "membuatmu ingin pulang?$"

GiddyText_LyingBackInTheGreenGrass::
	.string "Berbaring di rumput hijau…\n"
	.string "Oh, ini sangat, sangat menyenangkan!$"

GiddyText_SecretBasesAreSoWonderful::
	.string "MARKAS RAHASIA sangat menakjubkan!\n"
	.string "Tidak bisakah kamu merasakan kegembiraannya?$"
