MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce:
	.string "Jurus ini hanya bisa dipelajari\n"
	.string "sekali. Tidak apa-apa?$"

MoveTutor_Text_SwaggerTeach:
	.string "Heh! POKéMON-ku benar-benar hebat!\n"
	.string "Dia lebih keren dari POKéMON mana pun!\p"
	.string "Aku menyombongkan diri dengan gaya seperti itu\n"
	.string "ketika KETUA memarahiku.\p"
	.string "Itu membuat gayaku hilang.\p"
	.string "Jika kamu mau, aku akan mengajarkan jurus\n"
	.string "SWAGGER kepada POKéMON-mu.$"

MoveTutor_Text_SwaggerDeclined:
	.string "Apa, tidak? Tidakkah kamu bisa\n"
	.string "masuk ke dalam semangatnya?$"

MoveTutor_Text_SwaggerWhichMon:
	.string "Baiklah, POKéMON mana yang ingin\n"
	.string "belajar SWAGGER?$"

MoveTutor_Text_SwaggerTaught:
	.string "Aku akan memuji POKéMON-ku mulai sekarang\n"
	.string "tanpa kesombongan.$"

MoveTutor_Text_RolloutTeach:
	.string "Tahukah kamu bahwa kamu bisa pergi dari\n"
	.string "sini jauh ke arah sana\l"
	.string "tanpa mengubah arah?\p"
	.string "Aku bahkan mungkin bisa berguling\n"
	.string "ke arah itu.\p"
	.string "Menurutmu POKéMON-mu juga akan\n"
	.string "ingin berguling?\p"
	.string "Aku bisa mengajarinya jurus ROLLOUT\n"
	.string "jika kamu mau.$"

MoveTutor_Text_RolloutDeclined:
	.string "Kamu tidak perlu malu.\n"
	.string "Ayo berguling!$"

MoveTutor_Text_RolloutWhichMon:
	.string "Ehehe, tentu saja! Akan bagus jika\n"
	.string "POKéMON itu mirip denganku.$"

MoveTutor_Text_RolloutTaught:
	.string "Berguling-guling di rumput membuatku\n"
	.string "senang. Ayo, kita berguling!$"

MoveTutor_Text_FuryCutterTeach:
	.string "Ada jurus yang semakin kuat\n"
	.string "jika kamu terus menggunakannya berturut-turut.\p"
	.string "Ini adalah jurus tipe SERANGGA, dan itu\n"
	.string "sangat keren.\p"
	.string "Namanya FURY CUTTER.\n"
	.string "Mau aku ajarkan ke POKéMON?$"

MoveTutor_Text_FuryCutterDeclined:
	.string "Kita tidak sefrekuensi.$"

MoveTutor_Text_FuryCutterWhichMon:
	.string "Hore!\n"
	.string "Tunjukkan padaku POKéMON mana yang harus aku ajarkan.$"

MoveTutor_Text_FuryCutterTaught:
	.string "Aku senang melihat apakah\n"
	.string "jurus itu terus mengenai berturut-turut!$"

MoveTutor_MimicTeach:
	.string "Ah, anak muda!\p"
	.string "Aku juga anak muda, tapi aku meniru\n"
	.string "gaya dan ucapan orang tua\l"
	.string "kota ini.\p"
	.string "Bagaimana menurutmu, anak muda?\n"
	.string "Apakah kamu setuju jika aku\l"
	.string "menawarkan untuk mengajarkan jurus MIMIC?$"

MoveTutor_MimicDeclined:
	.string "Oh, boo! Aku ingin mengajarkan MIMIC\n"
	.string "kepada POKéMON-mu!$"

MoveTutor_Text_MimicWhichMon:
	.string "Fwofwo! Dan aku akan melakukannya!\n"
	.string "Biarkan aku melihat POKéMON\l"
	.string "yang ingin kamu ajarkan.$"

MoveTutor_Text_MimicTaught:
	.string "MIMIC adalah jurus yang sangat dalam.\p"
	.string "Bisakah kamu mengeksekusinya dengan sempurna\n"
	.string "seperti aku…?$"

MoveTutor_Text_MetronomeTeach:
	.string "Aku ingin segala macam hal!\n"
	.string "Tapi uang sakuku sudah habis…\p"
	.string "Bukankah menyenangkan jika ada\n"
	.string "mantra yang membuat uang muncul ketika\l"
	.string "kamu menggerakkan jari?\p"
	.string "Jika kamu mau, aku bisa mengajarkan POKéMON-mu\n"
	.string "jurus METRONOME.\p"
	.string "Uang tidak akan muncul, tapi POKéMON-mu\n"
	.string "akan menggerakkan jari. Ya?$"

MoveTutor_Text_MetronomeDeclined:
	.string "Oke. Aku akan ada di sini jika kamu berubah\n"
	.string "pikiran.$"

MoveTutor_Text_MetronomeWhichMon:
	.string "Oke! Aku akan mengajarinya!\n"
	.string "POKéMON mana yang harus aku ajarkan?$"

MoveTutor_Text_MetronomeTaught:
	.string "Ketika POKéMON menggerakkan jarinya\n"
	.string "seperti METRONOME, segala macam hal baik\l"
	.string "terjadi.\p"
	.string "Bukankah menyenangkan jika kita juga\n"
	.string "bisa menggunakannya?$"

MoveTutor_Text_SleepTalkTeach:
	.string "Cih! Istriku mengandalkan HIDDEN\n"
	.string "POWER untuk tetap terjaga.\p"
	.string "Dia seharusnya tidur siang saja sepertiku,\n"
	.string "dan SLEEP TALK.\p"
	.string "Aku bisa mengajar POKéMON-mu cara\n"
	.string "SLEEP TALK. Tertarik?$"

MoveTutor_Text_SleepTalkDeclined:
	.string "Oh, baiklah, baiklah. Kamu juga ingin tetap terjaga\n"
	.string "dengan HIDDEN POWER…$"

MoveTutor_Text_SleepTalkWhichMon:
	.string "Ah, anak yang menghargai!\n"
	.string "POKéMON mana yang harus aku ajarkan?$"

MoveTutor_Text_SleepTalkTaught:
	.string "Aku belum pernah berhasil melakukan\n"
	.string "trik koin istriku dengan benar.\p"
	.string "Aku akan senang jika aku berhasil melakukannya\n"
	.string "bahkan saat aku SLEEP TALK…$"

MoveTutor_Text_SubstituteTeach:
	.string "Ketika aku melihat dunia yang luas dari atas\n"
	.string "sini di atap…\p"
	.string "Aku berpikir betapa menyenangkannya jika ada\n"
	.string "lebih dari satu diriku\l"
	.string "agar aku bisa menikmati berbagai macam kehidupan.\p"
	.string "Tentu saja itu tidak mungkin.\n"
	.string "Terkekeh…\p"
	.string "Aku tahu! Apakah kamu tertarik\n"
	.string "agar POKéMON belajar SUBSTITUTE?$"

MoveTutor_Text_SubstituteDeclined:
	.string "Oh, tidak?\p"
	.string "POKéMON bisa membuat salinan\n"
	.string "dirinya sendiri menggunakannya, kamu tahu.$"

MoveTutor_Text_SubstituteWhichMon:
	.string "Terkekeh…\n"
	.string "POKéMON mana yang ingin kamu\l"
	.string "aku ajarkan SUBSTITUTE?$"

MoveTutor_Text_SubstituteTaught:
	.string "Kita sebagai manusia harus menikmati\n"
	.string "hidup kita sepenuhnya!\p"
	.string "Aku harap kamu juga akan begitu!$"

MoveTutor_Text_DynamicPunchTeach:
	.string "Aku tidak bisa melakukan ini lagi!\p"
	.string "Ini benar-benar tanpa harapan!\p"
	.string "Aku seorang TRAINER tipe FIGHTING,\n"
	.string "jadi aku tidak bisa menang di GYM MOSSDEEP\l"
	.string "tidak peduli seberapa keras aku mencoba!\p"
	.string "Argh! Pukul! Pukul! Pukul!\n"
	.string "Pukul! Pukul! Pukul!\p"
	.string "Apa, jangan melihatku seperti itu!\n"
	.string "Aku hanya memukul tanah!\p"
	.string "Atau apakah kamu ingin aku mengajar\n"
	.string "POKéMON-mu DYNAMICPUNCH?$"

MoveTutor_Text_DynamicPunchDeclined:
	.string "Sial! Kamu bahkan mengejekku?\n"
	.string "Pukul! Pukul! Pukul!$"

MoveTutor_Text_DynamicPunchWhichMon:
	.string "Apa? Kamu mau? Kamu orang baik!\n"
	.string "POKéMON mana yang harus aku ajarkan?$"

MoveTutor_Text_DynamicPunchTaught:
	.string "Aku ingin kamu menang di GYM MOSSDEEP\n"
	.string "menggunakan DYNAMICPUNCH itu!$"

MoveTutor_Text_DoubleEdgeTeach:
	.string "Sigh…\p"
	.string "PEMIMPIN GYM SOOTOPOLIS benar-benar\n"
	.string "mengagumkan.\p"
	.string "Tapi itu juga berarti aku punya banyak\n"
	.string "saingan untuk perhatiannya.\p"
	.string "Dia punya daya tarik dengan DOUBLE-EDGE.\n"
	.string "Aku bahkan tidak bisa menarik perhatiannya.\p"
	.string "Tolong, biarkan aku mengajari POKéMON-mu\n"
	.string "jurus DOUBLE-EDGE!$"

MoveTutor_Text_DoubleEdgeDeclined:
	.string "Oh…\n"
	.string "Bahkan kamu menolakku…$"

MoveTutor_Text_DoubleEdgeWhichMon:
	.string "Oke, POKéMON mana yang harus aku ajarkan\n"
	.string "DOUBLE-EDGE?$"

MoveTutor_Text_DoubleEdgeTaught:
	.string "Aku tidak akan hidup untuk cinta lagi!\n"
	.string "Aku akan menjadi tangguh!$"

MoveTutor_Text_ExplosionTeach:
	.string "Aku tidak berniat untuk tidak ke mana-mana\n"
	.string "dengan cepat di tempat terpencil seperti ini selamanya.\p"
	.string "Lihat saja aku, aku akan pergi ke kota\n"
	.string "dan menjadi sangat populer.\p"
	.string "Serius, aku akan menyebabkan\n"
	.string "LEDakan popularitas yang besar!\p"
	.string "Jika kamu tidak sengaja mendengarnya, aku dengan senang hati\n"
	.string "akan mengajarkan EXPLOSION kepada POKéMON-mu!$"

MoveTutor_Text_ExplosionDeclined:
	.string "Gaah! Kamu menolakku karena\n"
	.string "aku tinggal di desa?$"

MoveTutor_Text_ExplosionWhichMon:
	.string "Baik! LEDAKAN!\n"
	.string "POKéMON mana yang ingin meledak?$"

MoveTutor_Text_ExplosionTaught:
	.string "Sudah lama aku mengajari POKéMON\n"
	.string "cara menggunakan EXPLOSION, tapi aku belum\l"
	.string "memicu LEDAKAN-ku sendiri…\p"
	.string "Mungkin karena jauh di lubuk hati,\n"
	.string "aku lebih suka tinggal di sini…$"
