gText_ObtainedTheItem::
	.string "{STR_VAR_2} didapatkan!$"

gText_TheBagIsFull::
	.string "TAS penuh…$"

gText_PutItemInPocket::
	.string "{PLAYER} menyimpan {STR_VAR_2}\n"
	.string "di SAKU {STR_VAR_3}.$"

gText_PlayerFoundOneItem::
	.string "{PLAYER} menemukan satu {STR_VAR_2}!$"

gText_TooBadBagIsFull::
	.string "Sayang sekali!\n"
	.string "TAS penuh…$"

gText_PlayerPutItemInBag::
	.string "{PLAYER} menyimpan {STR_VAR_2}\n"
	.string "di TAS.$"

gText_ObtainedTheDecor::
	.string "{STR_VAR_2} didapatkan!$"

gText_NoRoomLeftForAnother::
	.string "Sayang sekali! Tidak ada ruang lagi untuk\n"
	.string "{STR_VAR_2} lain…$"

gText_TheDecorWasTransferredToThePC::
	.string "{STR_VAR_2} dipindahkan\n"
	.string "ke PC.$"

gText_ObtainedTheItems::
	.string "Mendapatkan {STR_VAR_1} {STR_VAR_2}!$"

gText_PlayerFoundItems::
	.string "{PLAYER} menemukan {STR_VAR_1} {STR_VAR_2}!$"
