gText_PkmnTransferredSomeonesPC::
	.string "{STR_VAR_2} dipindahkan ke\n"
	.string "PC SESEORANG.\p"
	.string "Itu ditempatkan di\n"
	.string "BOX “{STR_VAR_1}.”$"

gText_PkmnTransferredLanettesPC::
	.string "{STR_VAR_2} dipindahkan ke\n"
	.string "PC LANETTE.\p"
	.string "Itu ditempatkan di\n"
	.string "BOX “{STR_VAR_1}.”$"

gText_PkmnTransferredSomeonesPCBoxFull::
	.string "BOX “{STR_VAR_3}” di\n"
	.string "PC SESEORANG penuh.\p"
	.string "{STR_VAR_2} dipindahkan ke\n"
	.string "BOX “{STR_VAR_1}.”$"

gText_PkmnTransferredLanettesPCBoxFull::
	.string "BOX “{STR_VAR_3}” di\n"
	.string "PC LANETTE penuh.\p"
	.string "{STR_VAR_2} dipindahkan ke\n"
	.string "BOX “{STR_VAR_1}.”$"

gText_PkmnSentToPCAfterCatch::
	.string "{STR_VAR_2} dikirim ke\n"
	.string "PC {B_PC_CREATOR_NAME}.\p"
	.string "Itu ditempatkan di\n"
	.string "BOX “{STR_VAR_1}”.$"

gText_NoMoreRoomForPokemon::
	.string "Tidak ada ruang lagi untuk POKéMON!\p"
	.string "POKéMON BOXES penuh dan\n"
	.string "tidak bisa menerima lagi!$"

gText_NicknameThisPokemon::
	.string "Apakah kamu ingin memberikan nama panggilan\n"
	.string "kepada {STR_VAR_1} ini?$"
