gText_WouldYouLikeToRestYourPkmn::
	.string "Halo, selamat datang di\n"
	.string "POKéMON CENTER.\p"
	.string "Kami memulihkan POKéMON-mu yang lelah\n"
	.string "hingga pulih sepenuhnya.\p"
	.string "Apakah kamu ingin mengistirahatkan\nPOKéMON-mu?$"

gText_IllTakeYourPkmn::
	.string "Oke, aku akan mengambil POKéMON-mu\n"
	.string "selama beberapa detik.$"

gText_RestoredPkmnToFullHealth::
	.string "Terima kasih sudah menunggu.\p"
	.string "Kami sudah memulihkan POKéMON-mu\n"
	.string "hingga pulih sepenuhnya.$"

gText_WeHopeToSeeYouAgain::
	.string "Kami berharap bisa bertemu kamu lagi!$"

gText_WelcomeCutShort::
	.string "Halo, selamat datang di\n"
	.string "POKéMON CENTER.\p"
	.string "Kami memulihkan POKéMON-mu yang lelah\n"
	.string "hingga pulih sepenuhnya.\p"
	.string "Apakah kamu ingin…$"

gText_NoticesGoldCard::
	.string "Ka-kartu itu…\n"
	.string "Mungkinkah itu… KARTU EMAS?!\p"
	.string "Oh, warna emasnya sangat cemerlang!\n"
	.string "Empat bintangnya tampak berkilau!\p"
	.string "Aku pernah melihat beberapa TRAINER dengan\n"
	.string "KARTU PERAK sebelumnya, tapi, {PLAYER},\l"
	.string "kamu adalah TRAINER pertama yang pernah\l"
	.string "kulihat dengan KARTU EMAS!\p"
	.string "Oke, {PLAYER}, tolong izinkan aku\n"
	.string "kehormatan untuk mengistirahatkan POKéMON-mu!$"

gText_YouWantTheUsual::
	.string "Aku senang melihatmu, {PLAYER}!\n"
	.string "Kamu mau yang biasa, kan?$"

gText_IllTakeYourPkmn2::
	.string "Oke, aku akan mengambil POKéMON-mu\n"
	.string "selama beberapa detik.$"

gText_ThankYouForWaiting::
	.string "Terima kasih sudah menunggu.$"

gText_WeHopeToSeeYouAgain2::
	.string "Kami berharap bisa bertemu kamu lagi!$"
