gBirchDexRatingText_AreYouCurious::
	.string "PROF. BIRCH: Ah, {PLAYER}{KUN}!\p"
	.string "Apakah kamu ingin tahu bagaimana\n"
	.string "POKéDEX-mu berkembang?$"

gBirchDexRatingText_Cancel::
	.string "Hm? Oh, kamu belum menangkap cukup\n"
	.string "POKéMON untuk membuatnya berharga.$"

gBirchDexRatingText_SoYouveSeenAndCaught::
	.string "Hmhm…\p"
	.string "Jadi, kamu sudah melihat {STR_VAR_1} POKéMON,\n"
	.string "dan kamu sudah menangkap {STR_VAR_2} POKéMON…$"

gBirchDexRatingText_LessThan10::
	.string "Pergilah ke area berumput lebih sering dan cari\n"
	.string "POKéMON lebih hati-hati.$"

gBirchDexRatingText_LessThan20::
	.string "Kurasa kamu sudah mulai terbiasa.\n"
	.string "Tapi, ini akan lebih sulit dari sini.$"

gBirchDexRatingText_LessThan30::
	.string "Beberapa POKéMON hanya muncul di\n"
	.string "area tertentu.\l"
	.string "Kamu harus gigih.$"

gBirchDexRatingText_LessThan40::
	.string "Yah, bisa ditambah lagi kuantitasnya,\n"
	.string "tapi ini sudah lebih mirip\l"
	.string "POKéDEX sekarang.$"

gBirchDexRatingText_LessThan50::
	.string "Ini berjalan cukup baik.\n"
	.string "Teruslah berusaha.$"

gBirchDexRatingText_LessThan60::
	.string "Apakah kamu menggunakan JORAN?\n"
	.string "Ada banyak POKéMON di laut.$"

gBirchDexRatingText_LessThan70::
	.string "Daripada hanya menangkap POKéMON,\n"
	.string "bagaimana kalau membuat mereka berevolusi juga?$"

gBirchDexRatingText_LessThan80::
	.string "Ini akan menjadi POKéDEX yang\n"
	.string "fantastis.\l"
	.string "Itu yang kurasakan.$"

gBirchDexRatingText_LessThan90::
	.string "Kamu sudah mengumpulkan sebanyak ini…\n"
	.string "Bakatmu luar biasa!$"

gBirchDexRatingText_LessThan100::
	.string "Apakah kamu sudah mengunjungi SAFARI ZONE?\p"
	.string "Aku dengar ada beberapa POKéMON yang\n"
	.string "hanya bisa ditangkap di sana.$"

gBirchDexRatingText_LessThan110::
	.string "Kamu akhirnya mencapai\n"
	.string "angka 100 jenis.\p"
	.string "Ini adalah POKéDEX yang mengesankan!$"

gBirchDexRatingText_LessThan120::
	.string "Mungkin ada POKéMON yang bisa ditemukan\n"
	.string "menggunakan ROCK SMASH.$"

gBirchDexRatingText_LessThan130::
	.string "Kamu harus mendapatkan lebih banyak POKéMON\n"
	.string "dengan bertukar dengan orang lain.$"

gBirchDexRatingText_LessThan140::
	.string "Aku pernah mendengar tentang POKéMON yang berevolusi\n"
	.string "ketika mereka benar-benar mencintai\l"
	.string "TRAINER mereka.$"

gBirchDexRatingText_LessThan150::
	.string "Aku tidak tahu bahwa ada begitu\n"
	.string "banyak spesies POKéMON di wilayah\l"
	.string "HOENN.$"

gBirchDexRatingText_LessThan160::
	.string "Kadang-kadang, beberapa POKéMON muncul\n"
	.string "dalam jumlah besar seperti wabah.\p"
	.string "Jangan lewatkan kesempatan seperti\n"
	.string "itu.$"

gBirchDexRatingText_LessThan170::
	.string "Seseorang bisa mendapatkan gambaran yang sangat baik tentang\n"
	.string "POKéMON di wilayah HOENN\l"
	.string "dengan melihat POKéDEX-mu.$"

gBirchDexRatingText_LessThan180::
	.string "Aku akan mengatakan kamu sudah memenuhi syarat sebagai\n"
	.string "POKéMON PROFESSOR, dan yang baik\l"
	.string "pula!$"

gBirchDexRatingText_LessThan190::
	.string "Dengan POKéDEX selengkap ini,\n"
	.string "kamu benar-benar profesional dalam hal ini!$"

gBirchDexRatingText_LessThan200::
	.string "Kamu sangat dekat untuk menyelesaikan\n"
	.string "POKéDEX ini.\l"
	.string "Aku bisa merasakannya!$"

gBirchDexRatingText_DexCompleted::
	.string "Selamat!\n"
	.string "POKéDEX-mu sudah lengkap!$"

gBirchDexRatingText_OnANationwideBasis::
	.string "Hmhm…\n"
	.string "Secara nasional…\p"
	.string "Kamu sudah melihat {STR_VAR_1} POKéMON,\n"
	.string "dan kamu sudah menangkap {STR_VAR_2} POKéMON…$"
