Questionnaire_Text_FillOut::
	.string "Ada kuesioner.\n"
	.string "Apakah kamu ingin mengisinya?$"

Questionnaire_Text_ThankYou::
	.string "Terima kasih sudah meluangkan waktu untuk\n"
	.string "mengisi kuesioner kami.\p"
	.string "Masukanmu akan digunakan untuk\n"
	.string "referensi di masa mendatang.$"

Questionnaire_Text_YouKnowThoseWordsGift::
	.string "Oh, halo!\n"
	.string "Kamu tahu kata-kata itu?\p"
	.string "Itu berarti kamu pasti tahu tentang\n"
	.string "MYSTERY GIFT.\p"
	.string "Mulai sekarang, kamu seharusnya\n"
	.string "menerima MYSTERY GIFT!$"

Questionnaire_Text_YouCanAccessMysteryGift::
	.string "Setelah kamu menyimpan permainanmu, kamu bisa\n"
	.string "mengakses MYSTERY GIFT.$"

Questionnaire_Text_YouKnowThoseWordsEvent::
	.string "Oh, halo!\n"
	.string "Kamu tahu kata-kata itu?\p"
	.string "Itu berarti kamu pasti tahu tentang\n"
	.string "MYSTERY EVENT.$"

Questionnaire_Text_YouCanAccessMysteryEvent::
	.string "Setelah kamu menyimpan permainanmu, kamu bisa\n"
	.string "mengakses MYSTERY EVENT.$"

MysteryGift_Text_TheresATicketForYou::
	.string "Terima kasih sudah menggunakan\n"
	.string "Sistem MYSTERY EVENT.\p"
	.string "Kamu pasti {PLAYER}.\n"
	.string "Ada tiket di sini untukmu.$"

MysteryGift_Text_TryUsingItAtLilycovePort::
	.string "Tampaknya ini untuk digunakan di\n"
	.string "pelabuhan KOTA LILYCOVE.\p"
	.string "Mengapa tidak mencobanya dan melihat\n"
	.string "tentang apa itu?$"
