	.align 2
gText_ConfirmSave::
	.string "Apakah kamu ingin menyimpan permainan?$"

gText_AlreadySavedFile::
	.string "Sudah ada berkas tersimpan.\n"
	.string "Apakah tidak apa-apa untuk menimpanya?$"

gText_SavingDontTurnOff::
	.string "MENYIMPAN…\n"
	.string "JANGAN MATIKAN DAYA.$"

gText_PlayerSavedGame::
	.string "{PLAYER} menyimpan permainan.$"

gText_DifferentSaveFile::
	.string "PERINGATAN!\p"
	.string "Ada berkas permainan lain yang\n"
	.string "sudah tersimpan.\p"
	.string "Jika kamu menyimpan sekarang, petualangan\n"
	.string "berkas lain, termasuk item dan\l"
	.string "POKéMON, akan sepenuhnya hilang.\p"
	.string "Apakah kamu yakin ingin menyimpan sekarang\n"
	.string "dan menimpa berkas simpanan lainnya?$"

gText_SaveError::
	.string "Kesalahan penyimpanan.\p"
	.string "Mohon tukar\n"
	.string "memori cadangan.$"

gText_SavingDontTurnOffPower::
	.string "MENYIMPAN…\n"
	.string "JANGAN MATIKAN DAYA.$"
