SecretBase_Text_Trainer0Intro:
	.string "Apakah kamu sudah membuat MARKAS RAHASIA?\p"
	.string "Aku pergi ke sana, sini, ke mana-mana sebelum\n"
	.string "memilih tempat ini.\p"
	.string "Karena kamu sudah di sini, bagaimana kalau\n"
	.string "kita bertarung?$"

SecretBase_Text_Trainer0AcceptBattle:
	.string "Oke!\n"
	.string "Kami datang!$"

SecretBase_Text_Trainer0DeclineBattle:
	.string "Hah?\n"
	.string "Oh, kamu tidak bisa sekarang…$"

SecretBase_Text_Trainer0Defeated::
	.string "Waaargh! Kamu terlalu kuat!\n"
	.string "Tentang kekalahanku… Tolong rahasiakan!$"

SecretBase_Text_Trainer0PostBattle:
	.string "Bagaimana pendapatmu tentang MARKAS RAHASIA-ku?\n"
	.string "Datang kunjungi aku lagi besok.$"

SecretBase_Text_Trainer0PreChampion:
	.string "Apakah kamu sudah membuat MARKAS RAHASIA?\p"
	.string "Aku pergi ke sana, sini, ke mana-mana sebelum\n"
	.string "memilih tempat ini.\p"
	.string "Silakan bersantai!$"

SecretBase_Text_Trainer5Intro:
	.string "Ada banyak tempat di mana\n"
	.string "kamu bisa membuat MARKAS RAHASIA.\p"
	.string "Tapi aku paling suka tempat ini.\n"
	.string "Tidakkah menurutmu ini bagus?\p"
	.string "Oh, maukah kamu bertarung?$"

SecretBase_Text_Trainer5AcceptBattle:
	.string "Oke, mari kita mulai!$"

SecretBase_Text_Trainer5DeclineBattle:
	.string "Oh…\n"
	.string "Kamu tidak bisa sekarang, oke.$"

SecretBase_Text_Trainer5Defeated::
	.string "Hmmm… Kami kalah…\n"
	.string "Tapi jangan bilang siapa-siapa!\l"
	.string "Itu rahasia rahasia!$"

SecretBase_Text_Trainer5PostBattle:
	.string "Jika kamu di daerah ini lagi,\n"
	.string "aku harap kamu akan mengunjungiku.$"

SecretBase_Text_Trainer5PreChampion:
	.string "Ada banyak tempat di mana kamu bisa\n"
	.string "membuat MARKAS RAHASIA.\p"
	.string "Tapi aku paling suka tempat ini.\n"
	.string "Tidakkah menurutmu ini bagus?$"

SecretBase_Text_Trainer1Intro:
	.string "Ini adalah tempat populer.\n"
	.string "Selalu terisi.\p"
	.string "Oh! Apakah kamu juga berpikir untuk\n"
	.string "mengambil tempat ini?\p"
	.string "Baiklah, kamu bisa mendapatkan tempat ini\n"
	.string "jika kamu bisa mengalahkanku.$"

SecretBase_Text_Trainer1AcceptBattle:
	.string "Oke!\n"
	.string "Aku akan mempertahankan MARKAS RAHASIA-ku!$"

SecretBase_Text_Trainer1DeclineBattle:
	.string "Hah? Benarkah?\n"
	.string "Kamu tidak tertarik dengan tempat ini?$"

SecretBase_Text_Trainer1Defeated::
	.string "Aku tidak bisa melanjutkan!\n"
	.string "Aku menyerah!$"

SecretBase_Text_Trainer1PostBattle:
	.string "Oke, ketika aku pindah suatu hari nanti,\n"
	.string "tempat ini akan menjadi milikmu!$"

SecretBase_Text_Trainer1PreChampion:
	.string "Ini adalah tempat populer.\n"
	.string "Selalu terisi.\p"
	.string "Aku menunggu lama agar tempat ini dibuka.\n"
	.string "Aku akhirnya bisa menggunakannya!$"

SecretBase_Text_Trainer6Intro:
	.string "Selamat datang di LABORATORIUM POKéMON-ku.\p"
	.string "Aku melakukan penelitian tentang pertarungan secara\n"
	.string "rahasia.\p"
	.string "Maukah kamu melihat seberapa kuat aku?$"

SecretBase_Text_Trainer6AcceptBattle:
	.string "Aku akan habis-habisan!$"

SecretBase_Text_Trainer6DeclineBattle:
	.string "Oh.\n"
	.string "Lain kali saja, kalau begitu!$"

SecretBase_Text_Trainer6Defeated::
	.string "Hmm… Aku masih banyak yang harus dipelajari.\n"
	.string "Aku harus belajar lebih banyak lagi.$"

SecretBase_Text_Trainer6PostBattle:
	.string "Terima kasih sudah bertarung denganku.\n"
	.string "Silakan datang lagi besok.$"

SecretBase_Text_Trainer6PreChampion:
	.string "Selamat datang di LABORATORIUM POKéMON-ku.\p"
	.string "Aku melakukan penelitian tentang pertarungan secara\n"
	.string "rahasia.$"

SecretBase_Text_Trainer2Intro:
	.string "Rumah besar memang bagus, tapi aku lebih suka\n"
	.string "tempat seperti ini.\p"
	.string "Aku menyukainya karena semua jenis orang\n"
	.string "datang mengunjungiku.\p"
	.string "Jadi, bagaimana kalau kita bertarung?$"

SecretBase_Text_Trainer2AcceptBattle:
	.string "Begitulah!$"

SecretBase_Text_Trainer2DeclineBattle:
	.string "Ketika kamu siap, panggil aku!$"

SecretBase_Text_Trainer2Defeated::
	.string "Aww! Selesai!\n"
	.string "Tapi tetap menyenangkan untuk bertarung!$"

SecretBase_Text_Trainer2PostBattle:
	.string "Yah, bagaimanapun, aku harus membeli beberapa\n"
	.string "dekorasi dan furnitur.\p"
	.string "Aku ingin MARKAS RAHASIA-ku menjadi tempat\n"
	.string "yang bisa dinikmati orang lain.$"

SecretBase_Text_Trainer2PreChampion:
	.string "Rumah besar memang bagus, tapi aku lebih suka\n"
	.string "tempat seperti ini.\p"
	.string "Aku menyukainya karena semua jenis orang\n"
	.string "datang mengunjungiku.$"

SecretBase_Text_Trainer7Intro:
	.string "Aku sangat suka berbelanja dekorasi\n"
	.string "dan furnitur.\p"
	.string "Aku juga sangat suka membesarkan POKéMON.\p"
	.string "Jika kamu bersedia, maukah kamu bertarung\n"
	.string "dengan POKéMON-ku?$"

SecretBase_Text_Trainer7AcceptBattle:
	.string "Terima kasih.\n"
	.string "Haruskah kita mulai?$"

SecretBase_Text_Trainer7DeclineBattle:
	.string "Oh.\n"
	.string "Betapa mengecewakan…$"

SecretBase_Text_Trainer7Defeated::
	.string "Aku menyerah…$"

SecretBase_Text_Trainer7PostBattle:
	.string "Itu semua menyenangkan!\n"
	.string "Aku harus pergi berbelanja sekarang.$"

SecretBase_Text_Trainer7PreChampion:
	.string "Aku sangat suka berbelanja dekorasi\n"
	.string "dan furnitur.\p"
	.string "Aku juga sangat suka membesarkan POKéMON.\n"
	.string "sebanyak itu.$"

SecretBase_Text_Trainer3Intro:
	.string "Beberapa orang membuat MARKAS RAHASIA mereka di\n"
	.string "tempat-tempat yang sulit ditemukan.\l"
	.string "Apakah mereka hanya ingin bersembunyi?\p"
	.string "Tapi karena kamu menemukanku, bagaimana kalau kita\n"
	.string "bertarung?$"

SecretBase_Text_Trainer3AcceptBattle:
	.string "Aku tidak akan menyerah dengan mudah!$"

SecretBase_Text_Trainer3DeclineBattle:
	.string "Oh… Apakah kamu mungkin lelah mencari\n"
	.string "tempat ini?$"

SecretBase_Text_Trainer3Defeated::
	.string "Aku kalah…$"

SecretBase_Text_Trainer3PostBattle:
	.string "Di mana MARKAS RAHASIA-mu?\n"
	.string "Aku harus mengunjungimu di sana.$"

SecretBase_Text_Trainer3PreChampion:
	.string "Beberapa orang membuat MARKAS RAHASIA mereka di\n"
	.string "tempat-tempat yang sulit ditemukan.\l"
	.string "Apakah mereka hanya ingin bersembunyi?$"

SecretBase_Text_Trainer8Intro:
	.string "Orang-orang memberitahuku bahwa kamu bisa mendapatkan\n"
	.string "dekorasi dengan beberapa cara.\p"
	.string "Kita harus balapan untuk melihat siapa yang bisa\n"
	.string "mendapatkan dekorasi dan furnitur yang lebih bagus!\p"
	.string "Sementara itu, mau bertarung?$"

SecretBase_Text_Trainer8AcceptBattle:
	.string "Ini MARKAS RAHASIA-ku.\n"
	.string "Aku tidak boleh kalah!$"

SecretBase_Text_Trainer8DeclineBattle:
	.string "Aku akan bertarung denganmu kapan saja.$"

SecretBase_Text_Trainer8Defeated::
	.string "Hah?\n"
	.string "Apakah aku baru saja kalah?$"

SecretBase_Text_Trainer8PostBattle:
	.string "Aku tidak akan kalah dalam mengumpulkan dekorasi.\n"
	.string "Datang kunjungi lagi!$"

SecretBase_Text_Trainer8PreChampion:
	.string "Orang-orang memberitahuku bahwa kamu bisa mendapatkan\n"
	.string "dekorasi dengan beberapa cara.\p"
	.string "Kita harus balapan untuk melihat siapa yang bisa\n"
	.string "mendapatkan dekorasi dan furnitur yang lebih bagus!$"

SecretBase_Text_Trainer4Intro:
	.string "Aku menemukan tempat yang kusuka, dan aku menghiasnya\n"
	.string "dengan dekorasi favoritku.\p"
	.string "Aku membesarkan POKéMON favoritku dan tumbuh\n"
	.string "lebih kuat bersamanya.\p"
	.string "Itu yang kulakukan.\n"
	.string "Mau bertarung denganku?$"

SecretBase_Text_Trainer4AcceptBattle:
	.string "Tunjukkan padaku kemampuanmu!$"

SecretBase_Text_Trainer4DeclineBattle:
	.string "Kurasa ada saatnya kamu tidak\n"
	.string "bersemangat.$"

SecretBase_Text_Trainer4Defeated::
	.string "Aku tahu persis terbuat dari apa kamu sekarang.$"

SecretBase_Text_Trainer4PostBattle:
	.string "Kita berdua bisa menjadi lebih kuat.\n"
	.string "Mari kita terus berusaha!$"

SecretBase_Text_Trainer4PreChampion:
	.string "Aku menemukan tempat yang kusuka, dan aku menghiasnya\n"
	.string "dengan dekorasi favoritku.\p"
	.string "Aku membesarkan POKéMON favoritku dan tumbuh\n"
	.string "lebih kuat bersamanya.\p"
	.string "Setiap hari adalah hari yang menyenangkan.$"

SecretBase_Text_Trainer9Intro:
	.string "Kamu bisa belajar banyak tentang selera\n"
	.string "dan perasaan orang dari jenis\l"
	.string "dekorasi yang mereka miliki, dan bagaimana mereka\l"
	.string "menampilkannya.\p"
	.string "Bagaimana pendapatmu tentang seleraku?\n"
	.string "Apakah kamu tidak bisa berkata-kata?\p"
	.string "Mau melihat seleraku dalam bertarung?$"

SecretBase_Text_Trainer9AcceptBattle:
	.string "Tidak ada menahan diri!$"

SecretBase_Text_Trainer9DeclineBattle:
	.string "Aku akan senang menunjukkan gayaku\n"
	.string "kapan saja.$"

SecretBase_Text_Trainer9Defeated::
	.string "Kamu sangat berbakat!\n"
	.string "Kekuatanmu tampaknya tidak terbatas…$"

SecretBase_Text_Trainer9PostBattle:
	.string "Bagaimana pendapatmu tentang gayaku?\n"
	.string "Aku akan terus memolesnya!$"

SecretBase_Text_Trainer9PreChampion:
	.string "Kamu bisa belajar banyak tentang selera\n"
	.string "dan perasaan orang dari jenis\l"
	.string "dekorasi yang mereka miliki, dan bagaimana mereka\l"
	.string "menampilkannya.\p"
	.string "Bagaimana pendapatmu tentang seleraku?\n"
	.string "Apakah kamu tidak bisa berkata-kata?$"
