ShoalCave_LowTideEntranceRoom_Text_AreYouPlanningOnGoingInThere:
	.string "Apakah kamu berencana untuk masuk\n"
	.string "lebih dalam ke sana?\p"
	.string "Bagaimana kalau kamu membawakanku\n"
	.string "SHOAL SALT dan SHOAL SHELL?\p"
	.string "Aku bisa membuatkanmu sesuatu yang bagus jika\n"
	.string "kamu membawakanku bahan-bahannya.$"

ShoalCave_LowTideEntranceRoom_Text_BringMe4ShoalSaltAndShells:
	.string "Jika kamu membawakanku masing-masing empat\n"
	.string "SHOAL SALT dan SHOAL SHELL,\l"
	.string "Aku bisa membuatkanmu SHELL BELL…\p"
	.string "Kamu bisa mendapatkan bahan-bahan itu\n"
	.string "setiap hari.$"

ShoalCave_LowTideEntranceRoom_Text_WouldYouLikeShellBell:
	.string "Oh, hei! SHOAL SALT dan SHOAL SHELL!\n"
	.string "Dan cukup banyak juga!\p"
	.string "Maukah kamu aku buatkan\n"
	.string "SHELL BELL dengan itu?$"

ShoalCave_LowTideEntranceRoom_Text_MakeShellBellRightAway:
	.string "Baiklah, kalau begitu! Aku akan membuatkanmu\n"
	.string "SHELL BELL segera.\p"
	.string "… … … … … … … …\n"
	.string "… … … … … … … …\p"
	.string "Selesai!$"

ShoalCave_LowTideEntranceRoom_Text_ExplainShellBell:
	.string "Biarkan POKéMON memegang itu.\n"
	.string "Dia pasti akan menyukainya.\p"
	.string "Kenapa, suara lonceng SHELL BELL…\n"
	.string "Sangat indah!\p"
	.string "Kamu bisa mendapatkan bahan-bahannya setiap hari,\n"
	.string "jadi aku bisa membuatkanmu lebih banyak.$"

ShoalCave_LowTideEntranceRoom_Text_WantedToMakeShellBell:
	.string "Oh… Begitukah…\n"
	.string "Aku ingin membuat SHELL BELL…$"

ShoalCave_LowTideEntranceRoom_Text_NoSpaceInYourBag:
	.string "Kamu tidak punya ruang di TAS-mu\n"
	.string "jika aku harus membuatnya untukmu.\p"
	.string "Kamu harus membuat ruang dan kembali\n"
	.string "untuk SHELL BELL.$"

ShoalCave_Text_WasShoalSaltNowNothing:
	.string "Ada SHOAL SALT di sini.\n"
	.string "Tapi, tidak ada apa-apa di sini sekarang.$"

ShoalCave_Text_WasShoallShellNowNothing:
	.string "Ada SHOAL SHELL di sini.\n"
	.string "Tapi, tidak ada apa-apa di sini sekarang.$"
