LilycoveCity_ContestLobby_Text_InterviewRequest:
.string "Oh, halo! Kamu baru saja mengikuti\n"
.string "POKéMON CONTEST, kan?\l"
.string "Itu terlihat jelas dari POKéMON-mu.\p"
.string "Aku seorang reporter. Aku sedang membuat\n"
.string "berita tentang POKéMON CONTESTS.\p"
.string "Kalau boleh, apa kamu bersedia menjawab\n"
.string "beberapa pertanyaan?$"

LilycoveCity_ContestLobby_Text_DescribeContest:
.string "Oh, kamu mau?\n"
.string "Terima kasih.\p"
.string "Singkatnya, bagaimana kamu menggambarkan\n"
.string "CONTEST yang baru saja kamu ikuti?$"

LilycoveCity_ContestLobby_Text_WhatImageWhenYouHearX:
.string "Ah, begitu.\n"
.string "Komentar yang sangat mencerahkan.\p"
.string "Jadi lebih memahami seperti apa\n"
.string "CONTEST-nya.\p"
.string "Aku punya satu pertanyaan terakhir.\p"
.string "Saat kamu mendengar kata “{STR_VAR_2}”,\n"
.string "gambaran apa yang kamu dapatkan?$"

LilycoveCity_ContestLobby_Text_ThatsAllForInterview:
.string "Begitu, ya!\p"
.string "Jadi begitu caramu membayangkan konsep\n"
.string "dari “{STR_VAR_2}”.\p"
.string "Terima kasih!\n"
.string "Kamu memberiku beberapa ide bagus.\p"
.string "Sepertinya aku bisa menulis berita yang\n"
.string "bagus tentang POKéMON CONTESTS sekarang.\p"
.string "Mungkin, mungkin saja, berita ini bahkan\n"
.string "akan tayang di televisi.\l"
.string "Kuharap kamu menantikannya!$"

LilycoveCity_ContestLobby_Text_PleaseDoShareStoryWithMe:
.string "Oh, sayang sekali…\p"
.string "Baiklah, jika kamu menemukan cerita\n"
.string "yang bagus, tolong bagikan denganku, ya.$"

LilycoveCity_ContestLobby_Text_LookingForwardToNextContest:
.string "Aku akan menantikan POKéMON CONTEST\n"
.string "kamu berikutnya.$"

gTVBravoTrainerText00::
.string "Yeah!\n"
.string "Saatnya BRAVO TRAINER!\p"
.string "Hari ini, kita akan membahas POKéMON\n"
.string "milik {STR_VAR_1}.\p"
.string "POKéMON ini memiliki Peringkat\n"
.string "{STR_VAR_3} di Kategori {STR_VAR_2}.$"

gTVBravoTrainerText01::
.string "Memperkenalkan {STR_VAR_2} si\n"
.string "{STR_VAR_1}!\p"
.string "Nama panggilan {STR_VAR_2}…\p"
.string "Bahkan nama panggilannya memancarkan\n"
.string "aura yang menyatakan “{STR_VAR_3}”!$"

gTVBravoTrainerText02::
.string "Ngomong-ngomong, saat TRAINER {STR_VAR_1}\n"
.string "memasukkan POKéMON-nya ke CONTEST,\l"
.string "kami berhasil mendapatkan beberapa\l"
.string "kutipan penuh semangat tentang partner\l"
.string "setianya.$"

gTVBravoTrainerText03::
.string "Saat ditanya tentang CONTEST setelahnya,\n"
.string "{STR_VAR_1} dengan senang hati menjawab\l"
.string "sambil tersenyum lebar, “{STR_VAR_2}!”\p"
.string "Tentu saja, POKéMON {STR_VAR_1} menempati\n"
.string "urutan {STR_VAR_3} di CONTEST.\p"
.string "Kalimat itu sangat cocok untuk {STR_VAR_1}\n"
.string "saat ini, menurutku!$"

gTVBravoTrainerText04::
.string "Saat ditanya tentang CONTEST setelahnya,\n"
.string "{STR_VAR_1} menjawab dengan sedikit\l"
.string "rasa pahit, “{STR_VAR_2}.”\p"
.string "Tentu saja, POKéMON {STR_VAR_1} menempati\n"
.string "urutan {STR_VAR_3} di CONTEST.\p"
.string "Kekecewaan {STR_VAR_1} terdengar sangat\n"
.string "jelas, menurutku!$"

gTVBravoTrainerText05::
.string "Tidakkah kamu juga ingin tahu apa yang\n"
.string "{STR_VAR_1} bayangkan tentang {STR_VAR_2}?\p"
.string "Tentu saja kami penasaran!\n"
.string "Jadi kami bertanya, tentu saja!\p"
.string "Jawabannya terangkum dengan sempurna:\n"
.string "“{STR_VAR_3}!”\p"
.string "Itulah yang direpresentasikan oleh\n"
.string "konsep {STR_VAR_2} bagi {STR_VAR_1}!$"

gTVBravoTrainerText06::
.string "Jurus terakhir {STR_VAR_2} yang\n"
.string "digunakan oleh {STR_VAR_1} sepenuhnya\l"
.string "tentang “{STR_VAR_3}”!$"

gTVBravoTrainerText07::
.string "Bravo, {STR_VAR_1}!\n"
.string "Bravo, {STR_VAR_2}!\p"
.string "Aku harap kita bisa melihat {STR_VAR_1}\n"
.string "mencapai tingkatan yang lebih tinggi!\p"
.string "Waktu kita sudah habis!\n"
.string "Sampai jumpa lain waktu!$"

gTVBravoTrainerText08::
.string "Memperkenalkan {STR_VAR_1} milik\n"
.string "TRAINER!$"

BattleFrontier_BattleTowerLobby_Text_InterviewRequest::
.string "Halo! Kamu TRAINER yang baru saja\n"
.string "bertarung, kan?\p"
.string "Aku sedang mengumpulkan wawancara dengan\n"
.string "para TRAINER di mana-mana.\p"
.string "Bolehkah aku meminta beberapa patah kata\n"
.string "darimu tentang kesanmu dalam bertarung?$"

BattleFrontier_BattleTowerLobby_Text_HowDidBattleTowerTurnOut::
.string "Kamu mau? Sungguh?\n"
.string "Terima kasih!\l"
.string "Kalau begitu, uh…\p"
.string "Bagaimana hasil di BATTLE TOWER hari\n"
.string "ini?\p"
.string "Apakah kamu puas dengan pertarungannya?\n"
.string "Atau kamu tidak senang?$"

BattleFrontier_BattleTowerLobby_Text_SorryWeDisturbedYou::
.string "Oh…\n"
.string "Maaf kami mengganggumu.\p"
.string "Tolong beri kami wawancara lain kali\n"
.string "saat kamu mengunjungi BATTLE TOWER.$"

BattleFrontier_BattleTowerLobby_Text_ObviousYouHadGreatBattle::
.string "Tentu saja!\p"
.string "Raut kepuasan yang tidak salah lagi\n"
.string "di wajahmu…\p"
.string "Jelas sekali kamu telah melalui\n"
.string "pertarungan yang hebat.$"

BattleFrontier_BattleTowerLobby_Text_DifficultToMakeBattleTurnOutAsPlanned::
.string "Oh, begitu…\p"
.string "Yah, memang sulit untuk membuat sebuah\n"
.string "pertarungan berjalan persis seperti\l"
.string "yang direncanakan.$"

BattleFrontier_BattleTowerLobby_Text_DescribeYourBattle::
.string "Oh, oh, bolehkah aku bertanya satu\n"
.string "lagi?\p"
.string "Jika kamu harus mendeskripsikan\n"
.string "kesanmu tentang pertarungan ini dengan\l"
.string "satu kalimat, apa itu?$"

BattleFrontier_BattleTowerLobby_Text_ThatsGreatLine::
.string "Oh, itu sangat keren!\p"
.string "Kalimat yang bagus!\n"
.string "Aku harap kamu juga hebat lain kali.\p"
.string "Semoga kita bertemu lagi!$"

BattleFrontier_BattleTowerLobby_Text_SilentType::
.string "Oh, begitu…\p"
.string "Tetap saja, menjadi tipe pendiam juga\n"
.string "keren, kan?\p"
.string "Aku harap kamu memberiku kesempatan\n"
.string "untuk berbagi pemikiranmu lagi!$"

BattleFrontier_BattleTowerLobby_Text_LookingForwardToNextBattle::
.string "Aku akan menantikan pertarunganmu\n"
.string "selanjutnya!$"

BravoTrainerBattleTower_Text_Intro::
.string "Yeah!\n"
.string "Saatnya BRAVO TRAINER!\p"
.string "Hari ini, kita akan membahas {STR_VAR_1},\n"
.string "yang menerima tantangan BATTLE TOWER!\p"
.string "Untuk tantangan itu, {STR_VAR_1} mendaftarkan\n"
.string "satu {STR_VAR_2} yang hebat.$"

BravoTrainerBattleTower_Text_NewRecord::
.string "Pasangan ini mencetak rekor baru {STR_VAR_2}\n"
.string "kemenangan beruntun di kompetisi\l"
.string "{STR_VAR_1}!\l"
.string "Bravo, TRAINER!$"

BravoTrainerBattleTower_Text_Lost::
.string "Keduanya akhirnya menyerah pada\n"
.string "{STR_VAR_1} di pertandingan nomor\l"
.string "{STR_VAR_2}.\l"
.string "Usaha yang bagus, TRAINER!\p"
.string "Tapi, hei, sial sekali bertemu\n"
.string "{STR_VAR_1} begitu cepat di tantangan ini.\p"
.string "Kami menanyakan kesan TRAINER pada\n"
.string "pertandingan dengan {STR_VAR_1}.$"

BravoTrainerBattleTower_Text_Won::
.string "Keduanya memenangkan semuanya dengan\n"
.string "mengalahkan {STR_VAR_2} milik {STR_VAR_1}\l"
.string "secara telak.\l"
.string "Bravo, TRAINER!\p"
.string "Mengalahkan bahkan {STR_VAR_1}…\n"
.string "Sulit dipercaya! Sungguh menakjubkan!\p"
.string "Kami menanyakan kesan TRAINER pada\n"
.string "momen kemenangannya.$"

BravoTrainerBattleTower_Text_LostFinal::
.string "Setelah serangkaian kemenangan, pasangan\n"
.string "ini akhirnya menyerah pada {STR_VAR_2}\l"
.string "milik {STR_VAR_1}, rintangan terakhir\l"
.string "mereka.\p"
.string "Usaha yang bagus, TRAINER!\p"
.string "Tetap saja, kamu harus memberi pujian.\n"
.string "Kamu tidak sering melihat kombinasi\l"
.string "terkenal seperti {STR_VAR_1} dan {STR_VAR_2}.\p"
.string "Kami menanyakan kesan TRAINER pada\n"
.string "pertarungan melawan pasangan selebriti itu.$"

BravoTrainerBattleTower_Text_Satisfied::
.string "Inilah yang dikatakan TRAINER:\n"
.string "“Aku puas!”\p"
.string "Bukankah itu jawaban yang menyegarkan?\n"
.string "Bravo, TRAINER!\p"
.string "Bukankah luar biasa bisa bertarung\n"
.string "dengan kepuasan penuh?\p"
.string "Aku tahu persis seberapa puasnya\n"
.string "saat mendengar TRAINER mengatakan ini:$"

BravoTrainerBattleTower_Text_Unsatisfied::
.string "Inilah yang dikatakan TRAINER:\n"
.string "“Aku tidak puas…”\p"
.string "TRAINER kita jelas sedikit murung\n"
.string "saat itu diucapkan.\p"
.string "Tetap saja, tidak mudah bisa bertarung\n"
.string "dengan kepuasan penuh, kan?\p"
.string "Ngomong-ngomong, aku tahu seberapa tidak\n"
.string "puasnya TRAINER kita saat mendengar ini:$"

BravoTrainerBattleTower_Text_None1::
.string "Tidak ada$"

BravoTrainerBattleTower_Text_None2::
.string "Tidak ada$"

BravoTrainerBattleTower_Text_None3::
.string "Tidak ada$"

BravoTrainerBattleTower_Text_None4::
.string "Tidak ada$"

BravoTrainerBattleTower_Text_Response::
.string "“{STR_VAR_1}.”$"

BravoTrainerBattleTower_Text_ResponseSatisfied::
.string "“{STR_VAR_1}.”\n"
.string "Bukankah itu hebat?\p"
.string "Itu benar-benar mengekspresikan\n"
.string "kegembiraan {STR_VAR_2}, menurutku.\p"
.string "Pertarungan dengan {STR_VAR_3} di\n"
.string "akhir… Itu benar-benar yang kamu sebut\l"
.string "“{STR_VAR_1}”!$"

BravoTrainerBattleTower_Text_ResponseUnsatisfied::
.string "“{STR_VAR_1}.”\n"
.string "Bukankah itu cocok?\p"
.string "Pertarungan dengan {STR_VAR_3} di\n"
.string "akhir… Kamu tidak bisa menggambarkannya\l"
.string "sebagai apa pun selain “{STR_VAR_1}”!\p"
.string "Kekecewaan {STR_VAR_2} terdengar sangat\n"
.string "jelas, menurutku!$"

BravoTrainerBattleTower_Text_Outro::
.string "Bravo, {STR_VAR_1}!\n"
.string "Bravo, {STR_VAR_2}!\p"
.string "Aku harap kita bisa melihat {STR_VAR_1}\n"
.string "mencapai tingkatan yang lebih tinggi!\p"
.string "Waktu kita sudah habis!\n"
.string "Sampai jumpa lain waktu!$"

SlateportCity_PokemonFanClub_Text_InterviewRequestHasName:
.string "Wow!\p"
.string "Jelas terlihat bahwa kamu mencurahkan\n"
.string "cintamu pada {STR_VAR_1}-mu.\p"
.string "Oke, namanya {STR_VAR_2}.\p"
.string "Bolehkah aku meminta bantuanmu?\p"
.string "Aku seorang reporter TV, dan aku sedang\n"
.string "menjalankan survei tentang POKéMON.\p"
.string "Apakah kamu bersedia menjawab beberapa\n"
.string "pertanyaan sederhana untukku?$"

SlateportCity_PokemonFanClub_Text_HereGoesQuickAnswers:
.string "Bagus! Terima kasih!\p"
.string "Oke, kita mulai.\n"
.string "Aku hanya butuh jawaban cepat, oke?$"

SlateportCity_PokemonFanClub_Text_DescribeFeelingsFirstMetMon:
.string "Saat pertama kali bertemu {STR_VAR_1},\n"
.string "apa yang kamu rasakan?\p"
.string "Bagaimana kamu menggambarkan perasaanmu\n"
.string "saat itu?$"

SlateportCity_PokemonFanClub_Text_LikenMonToSomethingYouLike:
.string "{STR_VAR_1}-mu dirawat dengan penuh kasih.\p"
.string "Jika kamu mengibaratkannya dengan sesuatu\n"
.string "yang kamu sukai, apa itu?$"

SlateportCity_PokemonFanClub_Text_WhatAttractedYouAboutMon:
.string "Pertanyaan ini juga berkaitan dengan\n"
.string "{STR_VAR_1} kesayanganmu.\p"
.string "Apa yang membuatmu tertarik pada\n"
.string "{STR_VAR_1}?$"

SlateportCity_PokemonFanClub_Text_WhatDoPokemonMeanToYou:
.string "Oke, masuk akal.\p"
.string "Pertanyaan berikutnya mungkin sedikit\n"
.string "sulit.\p"
.string "Ini dia…\p"
.string "Apa arti POKéMON bagimu?$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview:
.string "Begitu, ya!\p"
.string "Hmhm…\p"
.string "Oke!\n"
.string "Terima kasih sudah membantuku.\p"
.string "Menyenangkan dan mencerahkan bisa\n"
.string "mengobrol denganmu.\p"
.string "Mungkin saja wawancara kita akan\n"
.string "tayang di TV. Tonton dan lihat, ya!\p"
.string "Oke, itu saja.\n"
.string "Sampai jumpa!$"

SlateportCity_PokemonFanClub_Text_HereIfYouGetUrgeToTellMe:
.string "Oh, oke…\p"
.string "Baiklah, jika kamu ingin memberitahuku\n"
.string "tentang POKéMON, aku akan ada di sini!$"

SlateportCity_PokemonFanClub_Text_EnjoyDoingInterviews:
.string "Aku menikmati pekerjaan ini--bisa belajar\n"
.string "tentang POKéMON dengan melakukan wawancara.$"

SlateportCity_PokemonFanClub_Text_InterviewRequest:
.string "Hai, sepertinya kamu sangat dekat dengan\n"
.string "{STR_VAR_1}-mu.\p"
.string "Kamu tahu tidak?\n"
.string "Aku seorang reporter TV.\p"
.string "Aku berkeliling mewawancarai orang-orang\n"
.string "tentang POKéMON.\p"
.string "Aku ingin tahu apakah kamu bersedia\n"
.string "menceritakan sedikit tentang {STR_VAR_1}-mu?$"

SlateportCity_PokemonFanClub_Text_TellMeAnythingAboutYourMon:
.string "Wow, terima kasih!\p"
.string "Oke, kalau begitu, tolong ceritakan apa\n"
.string "saja yang kamu suka tentang {STR_VAR_1}-mu.$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview2:
.string "Wow…\n"
.string "Cerita yang menarik.\p"
.string "Kamu benar-benar akrab dengan {STR_VAR_1},\n"
.string "ya?\p"
.string "Aku merasa ceritamu akan menjadi\n"
.string "tayangan TV yang bagus.\p"
.string "Aku janji akan mengubah ini menjadi\n"
.string "acara yang menghibur.\l"
.string "Nantikan, ya.\p"
.string "Oke, itu saja.\n"
.string "Sampai jumpa!$"

gTVFanClubOpinionsText00::
.string "KAMI ADALAH POKéMON FAN CLUB!\p"
.string "Kita mengudara!\p"
.string "Di program ini, kami mendapatkan\n"
.string "pendapatmu, dan aku meneriakkannya\l"
.string "atas namamu!\l"
.string "Bukankah konsep program yang fantastis?\p"
.string "Hari ini, kami membawakan laporan ini\n"
.string "dari reporter kami, yang kami kirim ke\l"
.string "POKéMON FAN CLUB.\p"
.string "Jadi, siapakah penggemar POKéMON\n"
.string "pilihan hari ini?\p"
.string "… … … … … … … …\p"
.string "{STR_VAR_1}!\p"
.string "Jadi, mari kita dengar apa yang\n"
.string "{STR_VAR_1} katakan tentang {STR_VAR_3}\l"
.string "si {STR_VAR_2}.\p"
.string "Dan, aku akan meneriakkan kata-kata\n"
.string "cinta itu dengan keras di TV!\p"
.string "Hoo-hah!\p"
.string "Mari berteriak!$"

gTVFanClubOpinionsText01::
.string "Kami bertanya pada {STR_VAR_1}, “Saat\n"
.string "pertama kali melihat {STR_VAR_2}-mu,\l"
.string "apa pikiran pertamamu?”\p"
.string "“{STR_VAR_3}!”\p"
.string "Yeahah! Teriakkan yang sangat bagus!\p"
.string "Bukankah itu membawa kembali kenangan\n"
.string "masa lalu?$"

gTVFanClubOpinionsText02::
.string "Kami bertanya pada {STR_VAR_1}, “Jika kamu\n"
.string "mengibaratkan {STR_VAR_2}-mu dengan\l"
.string "sesuatu, itu akan menjadi…”\p"
.string "… … … … … … … …\p"
.string "“{STR_VAR_3}!”\p"
.string "Whoah-oh, ide yang orisinal!\p"
.string "Kamu bisa merasakan intensitas perasaan\n"
.string "yang dimiliki TRAINER untuk {STR_VAR_2}.$"

gTVFanClubOpinionsText03::
.string "Dan mari kita lihat…\n"
.string "Apa yang membuat {STR_VAR_2} itu begitu\n"
.string "menarik bagi {STR_VAR_1}?\p"
.string "… … … … … … … …\p"
.string "“{STR_VAR_3}!”\p"
.string "Whoa! Pernyataan yang spektakuler!\p"
.string "Cinta TRAINER pada {STR_VAR_2} terdengar\n"
.string "sangat jelas!$"

gTVFanClubOpinionsText04::
.string "Hm? Oh, masih ada lagi.\n"
.string "Mari kita lihat!\p"
.string "Coba kulihat…\p"
.string "Kami bertanya pada {STR_VAR_1}, “Apa arti\n"
.string "POKéMON bagimu?”\p"
.string "… … … … … …\p"
.string "“{STR_VAR_3}!”\p"
.string "Bravo!\p"
.string "Itu teriakan terbaik yang kudapat\n"
.string "seharian ini!\p"
.string "“{STR_VAR_3}!”\p"
.string "Membuatmu ingin meneriakkannya berulang\n"
.string "kali!\p"
.string "Sekarang setelah kita mendapat teriakan\n"
.string "hebat, saatnya mengucapkan selamat\l"
.string "tinggal sampai jumpa lagi!\p"
.string "Jadi, mari kita semua berteriak sekali\n"
.string "lagi!\n"
.string "Bersama-sama…\p"
.string "“{STR_VAR_3}!”$"

gTVFanClubText00::
.string "KAMI ADALAH POKéMON FAN CLUB!\p"
.string "Kita mengudara!\p"
.string "Hari ini, kita akan mulai dengan\n"
.string "SUDUT SURVEI POKéMON.\p"
.string "Dari semua kisah yang dijalin oleh\n"
.string "POKéMON dan TRAINER, drama baru\l"
.string "mengejutkan apa yang akan menarik\l"
.string "perhatian kita hari ini?\p"
.string "Coba kulihat…\p"
.string "Yang ini!\p"
.string "Kita akan mulai dengan surat ini!\p"
.string "Ini surat dari {STR_VAR_1} tentang\n"
.string "{STR_VAR_2} kesayangannya.\p"
.string "Mari kita lihat seberapa besar semangat\n"
.string "penulis kita mengekspresikan cintanya\l"
.string "pada {STR_VAR_2}!\l"
.string "Hmhm…$"

gTVFanClubText01::
.string "Whoah!\n"
.string "Surat yang luar biasa!$"

gTVFanClubText02::
.string "Aku menyukainya, jadi ini dia lagi!$"

gTVFanClubText03::
.string "Surat yang bagus pantas dibaca berulang\n"
.string "kali!$"

gTVFanClubText04::
.string "Bagian “{STR_VAR_3},” itu benar-benar\n"
.string "menekankan dampak emosional!\p"
.string "Ini surat yang bagus dengan kedalaman\n"
.string "hati yang nyata!$"

gTVFanClubText05::
.string "Terutama bagian “{STR_VAR_3}” itu!\p"
.string "Aku suka bagaimana “{STR_VAR_3}”\n"
.string "digunakan!$"

gTVFanClubText06::
.string "Ngomong-ngomong, dan ini tidak penting,\n"
.string "tapi “{STR_VAR_3}” adalah ucapan yang\l"
.string "bagus.\p"
.string "Aku sering menggunakan “{STR_VAR_3}”\n"
.string "dalam percakapan akhir-akhir ini.$"

gTVFanClubText07::
.string "Jika aku harus menilai surat ini,\n"
.string "aku akan memberinya {STR_VAR_3} poin.\p"
.string "Lain kali, aku mengharapkan surat yang\n"
.string "lebih baik lagi, {STR_VAR_1}!\p"
.string "A-oops, lihat jam berapa sekarang?\n"
.string "Saatnya mengucapkan selamat tinggal\n"
.string "sampai jumpa lagi!$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequest:
.string "Oh?\n"
.string "Apakah kamu mungkin suka POKéMON?\p"
.string "Aku sedang bertugas dengan jaringan TV.\p"
.string "Aku sedang mengumpulkan cerita tentang\n"
.string "POKéMON dan TRAINER yang terjadi\l"
.string "baru-baru ini.\p"
.string "Jika kamu tidak keberatan, bisakah kamu\n"
.string "menceritakan sesuatu tentang dirimu?$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequestShort:
.string "Aku sedang mengumpulkan cerita tentang\n"
.string "POKéMON dan TRAINER yang terjadi\l"
.string "baru-baru ini.\p"
.string "Jika kamu tidak keberatan, bisakah kamu\n"
.string "menceritakan sesuatu tentang dirimu?$"

SlateportCity_OceanicMuseum_1F_Text_TellMeExperienceInvolvingPokemon:
.string "Oh, kamu mau?\n"
.string "Terima kasih!\p"
.string "Kalau begitu, tolong ceritakan apa pun\n"
.string "yang menarik yang kamu alami baru-baru\l"
.string "ini yang melibatkan POKéMON.$"

SlateportCity_OceanicMuseum_1F_Text_LetMeKnowIfYouHaveStory:
.string "Oh, begitu…\p"
.string "Baiklah, jika kamu punya cerita menarik\n"
.string "untuk diceritakan, tolong beritahu aku.$"

SlateportCity_OceanicMuseum_1F_Text_ThatsAllForInterview:
.string "Oh, cerita yang membangkitkan semangat!\p"
.string "Aku akan pastikan ceritamu ditayangkan\n"
.string "di televisi.\p"
.string "Seharusnya akan ditayangkan suatu saat,\n"
.string "jadi tolong nantikan, ya.$"

SlateportCity_OceanicMuseum_1F_Text_BetterWriteUpStory:
.string "Hmmm…\n"
.string "Aku punya cerita bagus untuk program TV.\p"
.string "Sebaiknya aku segera menuliskannya!$"

gTVRecentHappeningsText00::
.string "Halo, saatnya KEJADIAN TERKINI.\p"
.string "Bagi para POKéMON TRAINER, setiap hari\n"
.string "adalah sebuah dongeng.\p"
.string "Yang ingin kami lakukan adalah\n"
.string "memperkenalkanmu pada beberapa kisah\l"
.string "POKéMON ini.\p"
.string "Hari ini, kami membawakan kisah\n"
.string "TRAINER {STR_VAR_1}.\p"
.string "Apa yang dialami {STR_VAR_1} baru-baru\n"
.string "ini? Mari kita cari tahu.\p"
.string "Coba kulihat…$"

gTVRecentHappeningsText01::
.string "Bukankah itu mencerahkan?\p"
.string "Cerita itu memberimu gambaran jelas\n"
.string "tentang apa yang dialami {STR_VAR_1}\l"
.string "baru-baru ini.\l"
.string "Seolah-olah kita ada di sana sebagai\n"
.string "saksi!$"

gTVRecentHappeningsText02::
.string "“{STR_VAR_3}.” Itu\n"
.string "menekankan cerita dan memberinya\l"
.string "kedalaman.$"

gTVRecentHappeningsText03::
.string "“{STR_VAR_3}.”\n"
.string "Itu memberi cerita nuansa tempat.\l"
.string "Itu memungkinkan kita membayangkan\n"
.string "latar cerita.$"

gTVRecentHappeningsText04::
.string "Bagian “{STR_VAR_3}” dari cerita\n"
.string "sangat ekspresif.$"

gTVRecentHappeningsText05::
.string "{STR_VAR_1} telah menceritakan kisah\n"
.string "indah yang melibatkan POKéMON.\p"
.string "Dan sekarang kisah {STR_VAR_1} terukir\n"
.string "tak terhapuskan di jiwamu juga.\p"
.string "Itu saja untuk hari ini.\n"
.string "Silakan tonton lagi lain waktu.$"

gTVMassOutbreakText00::
.string "Salam!\n"
.string "Saatnya BERITA POKéMON.\p"
.string "Kami baru saja menerima kabar tentang\n"
.string "kejadian yang sangat langka.\p"
.string "Ada laporan tentang kemunculan massal\n"
.string "{STR_VAR_2} di sekitar {STR_VAR_1}.\p"
.string "{STR_VAR_2}, seperti yang mungkin kamu\n"
.string "tahu, dikenal sebagai POKéMON yang\l"
.string "langka dan sulit ditemukan.\p"
.string "Sepertinya ini adalah kesempatan langka\n"
.string "untuk melihat kemunculan misterius\l"
.string "{STR_VAR_2} di alam liar.\p"
.string "Itulah berita di BERITA POKéMON.$"

gTV3CheersForPokeblocksText00::
.string "MC: Kami harap kamu dalam semangat yang\n"
.string "baik, “3 SORAKAN UNTUK {POKEBLOCK}S”\l"
.string "hadir di sini!\p"
.string "Hari ini, kita akan memeriksa {POKEBLOCK}\n"
.string "yang dicampur oleh {STR_VAR_1} dan rekan-rekannya.\p"
.string "Tanpa basa-basi, aku akan memberikannya\n"
.string "kepada POKéMON gourmet-ku, GULPIN.\p"
.string "… … … … … …\n"
.string "… … … … … …$"

gTV3CheersForPokeblocksText01::
.string "GULPIN: Gubi! Gubii!\p"
.string "MC: Dan hasilnya sangat {STR_VAR_1}!\n"
.string "GULPIN bilang rasanya “{STR_VAR_2}!”\p"
.string "Terima kasih banyak, {STR_VAR_3}!$"

gTV3CheersForPokeblocksText02::
.string "Performa pencampuran {STR_VAR_1} kurang\n"
.string "memuaskan.\p"
.string "Jika TRAINER ini bisa mencampur lebih\n"
.string "baik, {POKEBLOCK}-nya akan jauh lebih\l"
.string "enak.$"

gTV3CheersForPokeblocksText03::
.string "GULPIN: Gubi! Gubii!\p"
.string "MC: Hmm… Terlalu {STR_VAR_1}.\n"
.string "GULPIN bilang rasanya “{STR_VAR_2}!”\p"
.string "Sepertinya kesalahan {STR_VAR_3}\n"
.string "merusak kualitas pencampuran…$"

gTV3CheersForPokeblocksText04::
.string "Sayang sekali usaha keras {STR_VAR_1}\n"
.string "menjadi sia-sia.\p"
.string "Semoga {STR_VAR_2} bisa menunjukkan\n"
.string "penampilan yang lebih baik lain kali!$"

gTV3CheersForPokeblocksText05::
.string "Tonton lagi lain waktu!\n"
.string "Slogan kami adalah “3 SORAKAN UNTUK\n"
.string "{POKEBLOCK}S!”$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer::
.string "Hai!\p"
.string "Aku penggemar berat {STR_VAR_1}.\n"
.string "Apa pendapatmu tentang {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_ThatsWhatYouThink::
.string "Begitu, begitu. Itulah yang kamu\n"
.string "pikirkan tentang TRAINER itu.$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer::
.string "Apakah kamu benar-benar lupa\n"
.string "tentang {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer2::
.string "Aku penggemar berat {STR_VAR_1}.\n"
.string "Apa pendapatmu tentang {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_HowStrongRateTrainer::
.string "Seberapa kuat kamu menilai {STR_VAR_1}\n"
.string "dalam skala seratus?$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer2::
.string "Apakah kamu benar-benar lupa\n"
.string "tentang {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_YouShouldMeetTrainer::
.string "Oh, begitu!\n"
.string "Kamu harus bertemu {STR_VAR_1} suatu\n"
.string "saat.\l"
.string "Aku yakin kamu juga akan menjadi\n"
.string "penggemarnya!$"

LilycoveCity_PokemonTrainerFanClub_Text_ThankYouIllShareThisInfo::
.string "Begitu, begitu.\p"
.string "Terima kasih!\n"
.string "Itu sangat berguna untuk diketahui.\p"
.string "Aku akan membagikan informasi ini\n"
.string "dengan penggemar {STR_VAR_1} lainnya\l"
.string "dan mendiskusikannya.$"

LilycoveCity_PokemonTrainerFanClub_HopeYouCatchTVSpecial::
.string "Akan ada acara TV spesial tentang\n"
.string "{STR_VAR_1} segera.\p"
.string "Aku harap kamu menontonnya!$"

gTVTrainerFanClubSpecialText00::
.string "KLUB PENGGEMAR TRAINER\n"
.string "{STR_VAR_1} SPESIAL!\p"
.string "Ini adalah persembahan khusus untuk\n"
.string "para penggemar {STR_VAR_1} di seluruh\l"
.string "HOENN!\p"
.string "Hari ini, kami mengajukan pertanyaan,\n"
.string "“Apa pendapat orang tentang {STR_VAR_1}?”\p"
.string "Kami mengajukan pertanyaan itu kepada\n"
.string "{STR_VAR_2} sebagai perwakilan TRAINER.\p"
.string "Kami bertanya, “Dalam satu kata,\n"
.string "bagaimana kamu mendeskripsikan\l"
.string "{STR_VAR_1}?”\p"
.string "Jawabannya: “{STR_VAR_3}.”\p"
.string "Salut untuk {STR_VAR_2}!\n"
.string "Pendapat yang tajam!\p"
.string "“{STR_VAR_3} {STR_VAR_1}.”\n"
.string "Kedengarannya sangat bagus!\p"
.string "{STR_VAR_2} juga menilai kekuatan\n"
.string "{STR_VAR_1} dari 0 hingga 100.$"

gTVTrainerFanClubSpecialText01::
.string "Skornya adalah {STR_VAR_3} poin!\n"
.string "Itu skor yang sangat tinggi!\p"
.string "{STR_VAR_2} jelas sangat menghormati\n"
.string "{STR_VAR_1}.$"

gTVTrainerFanClubSpecialText02::
.string "Skornya adalah {STR_VAR_3} poin!\n"
.string "Itu skor yang cukup bagus.\p"
.string "{STR_VAR_2} pasti menganggap\n"
.string "{STR_VAR_1} sebagai saingan.$"

gTVTrainerFanClubSpecialText03::
.string "Skornya adalah {STR_VAR_3} poin!\n"
.string "Itu skor yang agak lemah.\p"
.string "{STR_VAR_2} pasti menganggap\n"
.string "{STR_VAR_1} hanya sebagai pendamping.$"

gTVTrainerFanClubSpecialText04::
.string "Skornya adalah {STR_VAR_3} poin!\n"
.string "Itu skor yang buruk.\p"
.string "{STR_VAR_2} pasti menganggap\n"
.string "{STR_VAR_1} sebagai bawahan.$"

gTVTrainerFanClubSpecialText05::
.string "Itu dia, teman-teman!\p"
.string "Aku pikir kita semua belajar sesuatu\n"
.string "yang baru tentang {STR_VAR_1}.\p"
.string "Sebagai penutup, aku akan meninggalkanmu\n"
.string "dengan kata-kata {STR_VAR_2}.\p"
.string "{STR_VAR_3} {STR_VAR_1}!$"

gTVNameRaterText00::
.string "Dan sekarang, saatnya untuk…\n"
.string "ACARA PENILAI NAMA.\p"
.string "Aku meramal nasib POKéMON-mu dari\n"
.string "nama panggilan yang kamu berikan.\p"
.string "Aku memberikan nasihat, dan itu\n"
.string "adalah nasihat yang berguna.\p"
.string "Hari ini, aku akan membaca nama\n"
.string "panggilan {STR_VAR_3} dari POKéMON\l"
.string "{STR_VAR_2} milik {STR_VAR_1}.\p"
.string "Hmhm…\p"
.string "Hmm…\n"
.string "Nama panggilan ini…$"

gTVNameRaterText01::
.string "Nama panggilan yang mengisyaratkan bakat\n"
.string "dalam banyak cara berbeda.\p"
.string "Aku mendorong TRAINER ini untuk berani\n"
.string "dan mengambil banyak tantangan.$"

gTVNameRaterText02::
.string "Nama panggilan yang sangat cocok dengan\n"
.string "{STR_VAR_1}, nama TRAINER-nya.\p"
.string "Ini menunjukkan bahwa kamu akan menjalin\n"
.string "kemitraan yang baik dengan waktu yang\l"
.string "tepat.$"

gTVNameRaterText03::
.string "Nama panggilan yang cocok untuk individu\n"
.string "unik dari POKéMON!\p"
.string "Jika dibesarkan dengan benar, keunikan\n"
.string "POKéMON ini akan berkembang pesat!$"

gTVNameRaterText04::
.string "Nama panggilan yang akan memelihara sisi\n"
.string "peduli dan welas asih dari POKéMON.\p"
.string "Jika dibesarkan dengan benar, POKéMON ini\n"
.string "akan menunjukkan kehangatan sejati!$"

gTVNameRaterText05::
.string "Nama panggilan yang sangat bagus yang\n"
.string "mengisyaratkan kehebatan yang akan datang.\p"
.string "Aku penasaran dengan apa yang akan\n"
.string "terjadi di masa depan POKéMON ini.$"

gTVNameRaterText06::
.string "Nama panggilan yang bagus yang seharusnya\n"
.string "membuat POKéMON sehat dan kuat!\p"
.string "POKéMON itu seharusnya tetap bugar dan\n"
.string "kuat untuk waktu yang sangat lama.$"

gTVNameRaterText07::
.string "Nama panggilan yang bagus yang seharusnya\n"
.string "membuat POKéMON sangat aktif!\p"
.string "Aku pikir POKéMON ini akan menjadi\n"
.string "penampil yang kuat dalam pertarungan.$"

gTVNameRaterText08::
.string "Nama panggilan yang menarik yang\n"
.string "seharusnya membuat POKéMON sangat\l"
.string "menawan!\p"
.string "Aku tidak ragu bahwa POKéMON ini akan\n"
.string "menjadi pesona di POKéMON CONTESTS.$"

gTVNameRaterText09::
.string "Nama panggilan {STR_VAR_1} berakar pada\n"
.string "huruf “{STR_VAR_3}.”\p"
.string "Huruf itu didukung oleh huruf pertama\n"
.string "“{STR_VAR_2},” yang memberinya kesan\l"
.string "kehadiran yang kuat sebagai nama\l"
.string "panggilan.$"

gTVNameRaterText10::
.string "Nama panggilan {STR_VAR_1} sangat\n"
.string "berbentuk dengan cara yang menyenangkan.\p"
.string "Kehadiran huruf “{STR_VAR_2}” dan\n"
.string "“{STR_VAR_3}”--itu luar biasa bagus!$"

gTVNameRaterText11::
.string "Nama panggilan {STR_VAR_1}--memiliki\n"
.string "nuansa yang luhur dan mengalir.\p"
.string "Aliran dari huruf awal “{STR_VAR_2}” ke\n"
.string "“{STR_VAR_3}” sangat indah.$"

gTVNameRaterText12::
.string "Mari kita periksa contoh-contoh nama\n"
.string "panggilan bagus lainnya, oke?$"

gTVNameRaterText13::
.string "Coba contoh ini. Ambil bagian dari\n"
.string "nama TRAINER {STR_VAR_1}, dan akhiri\l"
.string "dengan nama panggilan bagus {STR_VAR_2}{STR_VAR_3}.$"

gTVNameRaterText14::
.string "Nama panggilan {STR_VAR_2}{STR_VAR_3} juga\n"
.string "akan berfungsi dengan baik.$"

gTVNameRaterText15::
.string "Nama spesies POKéMON {STR_VAR_2} dapat\n"
.string "digunakan sebagai dasar untuk membuat\l"
.string "nama panggilan {STR_VAR_1}{STR_VAR_3}.$"

gTVNameRaterText16::
.string "{STR_VAR_1}{STR_VAR_3} juga akan menjadi\n"
.string "nama panggilan yang efektif.$"

gTVNameRaterText17::
.string "Yang harus selalu dihindari adalah\n"
.string "menggunakan nama spesies POKéMON lain.\p"
.string "Misalnya, hindari mengambil nama\n"
.string "{STR_VAR_2} untuk membuat nama panggilan\l"
.string "{STR_VAR_1}{STR_VAR_3}.\l"
.string "Itu tidak dapat diterima.$"

gTVNameRaterText18::
.string "Aku harus mengatakan bahwa {STR_VAR_1}\n"
.string "adalah nama panggilan yang cukup bagus.\p"
.string "Aku harap TRAINER akan terus\n"
.string "memperlakukan {STR_VAR_1} dengan cinta.\p"
.string "Itu saja untuk acara hari ini.\n"
.string "Semoga kita bertemu lagi.$"

gTVPokemonAnglerText00::
.string "PEMANCING {STR_VAR_2}\p"
.string "PENGUMUM: Halo! Hari ini, kita akan\n"
.string "mendapatkan tips memancing {STR_VAR_2}.\p"
.string "GURU, saran apa yang bisa Anda berikan\n"
.string "untuk menangkap {STR_VAR_2}?\p"
.string "GURU: Hm? Menangkap {STR_VAR_2}?\n"
.string "Baiklah, biar kuberitahu, bersabarlah\n"
.string "dan tunggu. Itulah intinya.\p"
.string "Lihat {STR_VAR_1} di sana?\n"
.string "TRAINER itu contoh yang baik.\p"
.string "TRAINER itu sudah kehilangan\n"
.string "{STR_VAR_3} POKéMON.\p"
.string "Tapi di sana {STR_VAR_1} menunggu.\n"
.string "Tidak menyerah.\n"
.string "Itulah hukum untuk menangkap {STR_VAR_2}.\p"
.string "PENGUMUM: Begitu…\p"
.string "Oh! {STR_VAR_1} akhirnya mendaratkan\n"
.string "{STR_VAR_2} yang sulit ditangkap!\p"
.string "TRAINER itu tampak hampir menangis\n"
.string "karena kegirangan!\p"
.string "Melihat ekspresi gembira itu, aku jadi\n"
.string "ingin memancing juga!\p"
.string "Para penonton, mengapa tidak mengambil\n"
.string "ini sebagai isyarat untuk mencoba\l"
.string "memancing {STR_VAR_2}?\p"
.string "Sampai siaran kami berikutnya, selamat\n"
.string "tinggal dan selamat memancing untuk\l"
.string "kalian semua!$"

gTVPokemonAnglerText01::
.string "PEMANCING {STR_VAR_2}\p"
.string "PENGUMUM: Halo! Hari ini, kita akan\n"
.string "mendapatkan tips memancing {STR_VAR_2}.\p"
.string "GURU, saran apa yang bisa Anda berikan\n"
.string "untuk menangkap {STR_VAR_2}?\p"
.string "GURU: Hm? Menangkap {STR_VAR_2}?\n"
.string "Baiklah, biar kuberitahu, gunakan\n"
.string "pancingmu dengan semangat!\p"
.string "Lihat {STR_VAR_1} di sana?\n"
.string "Lihat bagaimana pancingnya ditangani?\p"
.string "TRAINER itu sudah menangkap {STR_VAR_3}\n"
.string "berturut-turut.\p"
.string "PENGUMUM: Luar biasa!\n"
.string "Seperti badai…\p"
.string "Melihat teknik sekaliber itu, aku jadi\n"
.string "ingin memancing juga.\p"
.string "Para penonton, mengapa tidak mengambil\n"
.string "ini sebagai isyarat untuk mencoba\l"
.string "memancing {STR_VAR_2}?\p"
.string "Sampai siaran kami berikutnya, selamat\n"
.string "tinggal dan selamat memancing untuk\l"
.string "kalian semua!$"

gTVPokemonTodayFailedText00::
.string "Halo!\p"
.string "Saatnya untuk POKéMON TODAY!\p"
.string "BIG SIS: Hai! Apakah semua orang ceria\n"
.string "dan bersemangat hari ini?\p"
.string "Hari ini, kita akan melihat POKéMON\n"
.string "{STR_VAR_2} milik {STR_VAR_1}!\p"
.string "BIG BRO: Yeah! Itulah yang akan kita\n"
.string "lakukan!$"

gTVPokemonTodayFailedText01::
.string "Oh!\n"
.string "Berbicara tentang {STR_VAR_1}…\p"
.string "BIG SIS, aku melihat TRAINER itu dengan\n"
.string "mataku sendiri!\p"
.string "BIG SIS: Oh, apa yang kamu lihat?\p"
.string "BIG BRO: Yah, aku harus pergi ke\n"
.string "{STR_VAR_2}.\p"
.string "Saat itulah aku kebetulan bertemu\n"
.string "{STR_VAR_1}, yang sedang mencoba\l"
.string "menangkap POKéMON {STR_VAR_3}, tapi…$"

gTVPokemonTodayFailedText02::
.string "POKéMON itu berhasil kabur!\p"
.string "Akhirnya menghabiskan sebanyak ini\n"
.string "POKé BALL: {STR_VAR_2}!\p"
.string "Kamu seharusnya melihat ekspresi\n"
.string "frustrasi di wajah {STR_VAR_1} saat\l"
.string "POKéMON itu kabur!$"

gTVPokemonTodayFailedText03::
.string "Tapi {STR_VAR_1} ceroboh dan membuat\n"
.string "POKéMON itu pingsan!\p"
.string "Akhirnya menghabiskan sebanyak ini\n"
.string "POKé BALL: {STR_VAR_2}!\p"
.string "Kamu seharusnya melihat ekspresi kaget\n"
.string "di wajah {STR_VAR_1} saat POKéMON itu\l"
.string "pingsan!$"

gTVPokemonTodayFailedText04::
.string "BIG SIS: Hei, sudahlah!\n"
.string "Itu tidak baik!\p"
.string "Kamu tidak seharusnya menertawakan\n"
.string "kemalangan orang lain!\p"
.string "Oh, kasihan {STR_VAR_1}.\n"
.string "Sayang sekali!\p"
.string "BIG BRO: Itu benar!\n"
.string "Maaf sudah tertawa.$"

gTVPokemonTodayFailedText05::
.string "BIG SIS: Bufufu…\p"
.string "BIG BRO: Hei!\n"
.string "Kamu juga baru saja tertawa!\p"
.string "BIG SIS: Hah?!\p"
.string "Aku tidak tertawa!\n"
.string "Sungguh, aku tidak tertawa!\p"
.string "Oh, kasihan {STR_VAR_1}.\n"
.string "Sayang sekali!\p"
.string "BIG BRO: …$"

gTVPokemonTodayFailedText06::
.string "BIG SIS: Cukup bercandanya!\n"
.string "Mari kita lihat POKéMON hari ini…\p"
.string "Hah?\n"
.string "Waktu kita sudah habis?\p"
.string "Aww!\n"
.string "Kita tidak bisa membahas POKéMON hari\n"
.string "ini!\p"
.string "BIG BRO: Sampai jumpa lagi lain waktu!\p"
.string "BIG SIS: Hei, jangan akhiri acara ini\n"
.string "tanpaku!$"

gTVPokemonTodaySuccessfulText00::
.string "Halo!\p"
.string "Saatnya untuk POKéMON TODAY!\p"
.string "BIG SIS: Hai! Apakah semua orang ceria\n"
.string "dan bersemangat hari ini?\p"
.string "Hari ini, kita akan melihat POKéMON\n"
.string "{STR_VAR_2} milik {STR_VAR_1}!\p"
.string "BIG BRO: Yeah! Itulah yang akan kita\n"
.string "lakukan!$"

gTVPokemonTodaySuccessfulText01::
.string "BIG SIS: {STR_VAR_1} memberikan nama\n"
.string "panggilan {STR_VAR_3} kepada {STR_VAR_2}!\p"
.string "Sepertinya {STR_VAR_3} mendapatkan\n"
.string "perawatan yang baik dan penuh kasih!$"

gTVPokemonTodaySuccessfulText02::
.string "BIG BRO: TRAINER harus melempar\n"
.string "sebanyak ini POKé BALL untuk\l"
.string "menangkapnya: {STR_VAR_3}!\p"
.string "Akhirnya hanya butuh satu {STR_VAR_2}\n"
.string "untuk menangkapnya!$"

gTVPokemonTodaySuccessfulText03::
.string "BIG SIS: Jika begitu mudah ditangkap,\n"
.string "pasti takdir yang mempertemukan\l"
.string "{STR_VAR_1} dan {STR_VAR_2}!$"

gTVPokemonTodaySuccessfulText04::
.string "BIG SIS: Wow! Keren sekali!\p"
.string "Tapi tahu kan kata orang, POKéMON\n"
.string "yang butuh banyak usaha untuk\l"
.string "ditangkap akan mendapatkan cinta dari\l"
.string "TRAINER-nya!$"

gTVPokemonTodaySuccessfulText05::
.string "BIG SIS: {STR_VAR_2} milik {STR_VAR_1} adalah\n"
.string "POKéMON yang berkesan karena butuh\l"
.string "MASTER BALL yang tak ternilai untuk\l"
.string "menangkapnya!\p"
.string "BIG BRO: Wow! Itu super-hebat!\p"
.string "BIG SIS: {STR_VAR_1} pasti sangat\n"
.string "menginginkan {STR_VAR_2} itu, pasti!$"

gTVPokemonTodaySuccessfulText06::
.string "BIG BRO: Lalu memberikan nama panggilan\n"
.string "{STR_VAR_3} kepada {STR_VAR_2} itu…\p"
.string "Kamu benar-benar mendapatkan gambaran\n"
.string "bagus tentang selera TRAINER {STR_VAR_1}.\p"
.string "BIG SIS: Aku setuju dengan pendapat itu!$"

gTVPokemonTodaySuccessfulText07::
.string "Jika itu aku, aku akan memberikan nama\n"
.string "panggilan itu untuk sesuatu seperti\l"
.string "{STR_VAR_3} ini!\p"
.string "BIG BRO: Whoa! Itu bisa menjadi awal\n"
.string "dari sesuatu yang baru!$"

gTVPokemonTodaySuccessfulText08::
.string "{STR_VAR_2} si {STR_VAR_1}?\n"
.string "Bukankah itu terdengar sempurna?\p"
.string "Huruf-hurufnya dan semuanya--terdengar\n"
.string "sangat pas untuk POKéMON {STR_VAR_1}!\p"
.string "BIG BRO: Ya, benar sekali!$"

gTVPokemonTodaySuccessfulText09::
.string "Sejauh yang aku tahu, tidak ada TRAINER\n"
.string "yang pernah memberikan nama panggilan\l"
.string "{STR_VAR_2} kepada {STR_VAR_1} mereka!\p"
.string "BIG BRO: Itu menunjukkan betapa\n"
.string "hebatnya selera TRAINER dalam memilih\l"
.string "nama panggilan!$"

gTVPokemonTodaySuccessfulText10::
.string "Lain kali aku menangkap POKéMON,\n"
.string "aku harus memberinya nama {STR_VAR_2}.\p"
.string "BIG BRO: Hah? Aku juga!\n"
.string "Aku akan menggunakan nama panggilan\n"
.string "{STR_VAR_2} juga!$"

gTVPokemonTodaySuccessfulText11::
.string "BIG SIS: Oh, tidak!\n"
.string "Lihat jam berapa sekarang!\p"
.string "Baiklah, teman-teman, sekian untuk\n"
.string "hari ini.\n"
.string "Sampai jumpa lagi lain waktu!\p"
.string "BIG BRO: Ingat, bisa jadi POKéMON-mu\n"
.string "yang akan menjadi sorotan lain kali!$"

SmartShopper_Text_Intro::
.string "Halo!\p"
.string "Saatnya untuk PEMBELI CERDAS HARI INI.\p"
.string "PEWAWANCARA: Apa kabar, pemirsa?\p"
.string "Hari ini kita mengunjungi sebuah toko\n"
.string "di {STR_VAR_2}.\p"
.string "Mari kita periksa apa saja yang laris\n"
.string "manis baru-baru ini.$"

SmartShopper_Text_ClerkNormal::
.string "Mari kita wawancarai penjaga toko untuk\n"
.string "mendapatkan informasinya.\p"
.string "Hai, bagaimana bisnismu?\p"
.string "PENJAGA: Oh, kami sangat baik.\p"
.string "Baru-baru ini, {STR_VAR_2} terjual\n"
.string "sangat laris.\p"
.string "Bahkan, beberapa hari yang lalu seorang\n"
.string "TRAINER bernama {STR_VAR_1} membeli\l"
.string "{STR_VAR_3}.$"

SmartShopper_Text_RandomComment1::
.string "PEWAWANCARA: TRAINER itu membeli\n"
.string "{STR_VAR_3} {STR_VAR_2}S? Banyak sekali!\p"
.string "Kalau boleh bilang, {STR_VAR_1} pasti\n"
.string "sedang menimbun untuk perjalanan jauh\l"
.string "ke tempat-tempat terpencil.\p"
.string "Untuk bepergian, {STR_VAR_2}S sangat\n"
.string "penting!$"

SmartShopper_Text_RandomComment2::
.string "PEWAWANCARA: Berbicara tentang item\n"
.string "{STR_VAR_2}, aku baru saja membeli\l"
.string "{STR_VAR_3} baru-baru ini.\p"
.string "Lagi pula, {STR_VAR_2} adalah item\n"
.string "yang bagus!$"

SmartShopper_Text_RandomComment3::
.string "PEWAWANCARA: {STR_VAR_2}?!\n"
.string "Tapi {STR_VAR_3} buah?!\p"
.string "Aku tidak menyangka akan ada orang yang\n"
.string "membeli sebanyak itu.\p"
.string "Ya ampun, aku hanya mampu membeli satu\n"
.string "atau dua sekaligus…$"

SmartShopper_Text_RandomComment4::
.string "PEWAWANCARA: Suatu kali, aku membeli\n"
.string "banyak sekali item {STR_VAR_2}.\p"
.string "Tapi ternyata terlalu banyak.\n"
.string "Aku akhirnya menyesal…\p"
.string "Sejak itu, aku hanya membeli apa yang\n"
.string "benar-benar aku butuhkan…\p"
.string "Oops!\p"
.string "Tidak ada gunanya membicarakan aku!$"

SmartShopper_Text_SecondItem::
.string "PENJAGA: {STR_VAR_1} juga membeli item\n"
.string "{STR_VAR_2} dalam jumlah besar,\n"
.string "mengambil {STR_VAR_3}.\p"
.string "PEWAWANCARA: Oh, itu cerdas.\n"
.string "{STR_VAR_2} juga item yang sangat bagus.$"

SmartShopper_Text_ThirdItem::
.string "PENJAGA: Dan, TRAINER itu juga membeli\n"
.string "{STR_VAR_3} item {STR_VAR_2}.$"

SmartShopper_Text_DuringSale::
.string "PENJAGA: Ditambah lagi, saat itu sedang\n"
.string "ada diskon besar.\n"
.string "Itu belanja yang cerdas.$"

SmartShopper_Text_OutroNormal::
.string "PEWAWANCARA: Hmm… {STR_VAR_1} terdengar\n"
.string "seperti pemburu barang murah yang cerdik!\p"
.string "Totalnya, pembelian {STR_VAR_1} mencapai…\p"
.string "¥{STR_VAR_2}?!\n"
.string "Jumlah yang luar biasa!\p"
.string "Oops! Waktu kita habis!\n"
.string "Sampai jumpa di siaran kami berikutnya!$"

SmartShopper_Text_IsVIP::
.string "PENJAGA: {STR_VAR_1} adalah pelanggan\n"
.string "VIP, tidak diragukan lagi.$"

SmartShopper_Text_ClerkMax::
.string "Mari kita wawancarai penjaga toko untuk\n"
.string "mendapatkan informasinya.\p"
.string "Hai, bagaimana bisnismu?\p"
.string "PENJAGA: Oh, bisnis kami luar biasa.\n"
.string "Hampir kewalahan.\p"
.string "Baru-baru ini, seorang TRAINER bernama\n"
.string "{STR_VAR_1} membeli item {STR_VAR_2}\l"
.string "dalam jumlah besar.\p"
.string "TRAINER itu hampir menghabiskan seluruh\n"
.string "stok {STR_VAR_2}S kami.\p"
.string "Aku tidak pernah bermimpi ada pelanggan\n"
.string "yang membutuhkan begitu banyak\l"
.string "{STR_VAR_2}S.\l"
.string "Benar-benar tidak pernah terdengar!\p"
.string "PEWAWANCARA: Jadi sekitar 100 atau 200\n"
.string "terjual?\p"
.string "PENJAGA: Oh, tidak, jauh lebih banyak!\p"
.string "PEWAWANCARA: Ya ampun!\n"
.string "{STR_VAR_1} pasti pembeli istimewa!\p"
.string "PENJAGA: {STR_VAR_1} adalah pelanggan\n"
.string "VIP, tidak diragukan lagi.$"

SmartShopper_Text_OutroMax::
.string "PEWAWANCARA: Hmm…\n"
.string "Luar biasa.\p"
.string "Tapi kenapa TRAINER itu perlu membeli\n"
.string "begitu banyak?\p"
.string "… …\p"
.string "Misteri semakin dalam, tapi waktu kita\n"
.string "habis hari ini.\l"
.string "Sampai jumpa di siaran kami berikutnya!\p"
.string "Tetap saja, {STR_VAR_1} benar-benar\n"
.string "sebuah teka-teki…$"

gTVWorldOfMastersText00::
.string "DUNIA PARA MASTER\p"
.string "Halo, pemirsa.\p"
.string "Mungkin kamu tahu seorang TRAINER\n"
.string "bernama {STR_VAR_1}.\p"
.string "{STR_VAR_1} terkenal sebagai master\n"
.string "dalam menangkap POKéMON.\p"
.string "Pencarian {STR_VAR_1} untuk POKéMON\n"
.string "bergantung sepenuhnya pada pencarian\l"
.string "cermat dengan berjalan kaki.\p"
.string "Pada suatu hari yang tak terlupakan,\n"
.string "TRAINER itu berjalan sekitar {STR_VAR_2}\l"
.string "langkah.\p"
.string "Total POKéMON yang ditangkap hari itu\n"
.string "mencapai {STR_VAR_3} yang mengesankan!$"

gTVWorldOfMastersText01::
.string "Prestasi luar biasa itu pasti mungkin\n"
.string "terjadi karena kepercayaan antara\l"
.string "TRAINER dan {STR_VAR_1}.$"

gTVWorldOfMastersText02::
.string "Master itu menangkap {STR_VAR_3} terakhir\n"
.string "hari itu di dekat {STR_VAR_2}.\p"
.string "POKéMON itu tampaknya menikmati status\n"
.string "khusus sebagai pemegang rekor.\p"
.string "TRAINER terampil harus didorong untuk\n"
.string "menantang rekor bagus ini.\p"
.string "Itu saja untuk hari ini.\n"
.string "Silakan tonton lagi lain waktu.$"

gTVTodaysRivalTrainerText00::
.string "SAINGAN TRAINER HARI INI!\p"
.string "Halo, sesama POKéMON TRAINER!\n"
.string "Apa kabar kita semua hari ini?\p"
.string "Hari ini, seperti setiap hari lainnya,\n"
.string "kita akan memeriksa salah satu saingan\l"
.string "kita!$"

gTVTodaysRivalTrainerText07::
.string "Saingan TRAINER hari ini adalah\n"
.string "{STR_VAR_1}, yang sekarang ada di sekitar\l"
.string "{STR_VAR_3}.\p"
.string "{STR_VAR_1} sejauh ini telah mendaftarkan\n"
.string "{STR_VAR_2} POKéMON di POKéDEX.$"

gTVTodaysRivalTrainerText08::
.string "Saingan TRAINER hari ini adalah\n"
.string "{STR_VAR_1}, yang sekarang berada di\l"
.string "SECRET BASE.\p"
.string "{STR_VAR_1} sejauh ini telah mendaftarkan\n"
.string "{STR_VAR_2} POKéMON di POKéDEX.$"

gTVTodaysRivalTrainerText09::
.string "Saingan TRAINER hari ini adalah\n"
.string "{STR_VAR_1}.\p"
.string "Sejauh ini, {STR_VAR_1} telah mendaftarkan\n"
.string "{STR_VAR_2} POKéMON di POKéDEX.$"

gTVTodaysRivalTrainerText10::
.string "Saingan TRAINER hari ini adalah\n"
.string "{STR_VAR_1}, yang sekarang berada di\l"
.string "atas feri.\p"
.string "{STR_VAR_1} sejauh ini telah mendaftarkan\n"
.string "{STR_VAR_2} POKéMON di POKéDEX.$"

.string "$"

gTVTodaysRivalTrainerText01::
.string "Dan berapa banyak BADGE yang dimiliki\n"
.string "saingan kita? Jumlahnya adalah {STR_VAR_1}!$"

gTVTodaysRivalTrainerText02::
.string "Tapi saingan kita belum mendapatkan\n"
.string "satu BADGE pun!$"

gTVTodaysRivalTrainerText03::
.string "Saingan kita belum mendapatkan satu\n"
.string "pun Simbol BATTLE FRONTIER.$"

gTVTodaysRivalTrainerText04::
.string "Mari kita lihat berapa banyak Simbol\n"
.string "BATTLE FRONTIER yang dimiliki saingan\l"
.string "kita.\p"
.string "Simbol Emas: {STR_VAR_1}!\n"
.string "Simbol Perak: {STR_VAR_2}!$"

gTVTodaysRivalTrainerText05::
.string "Saingan kita telah mengumpulkan\n"
.string "{STR_VAR_1} Battle Point di BATTLE\l"
.string "FRONTIER.$"

gTVTodaysRivalTrainerText06::
.string "Jadi, bagaimana perbandinganmu dengan\n"
.string "{STR_VAR_1}?\p"
.string "Petualangan terus berlanjut!\p"
.string "Sesama TRAINER!\p"
.string "Mari kita semua terus maju dan\n"
.string "mendahului saingan kita!$"

TrendWatcher_Text_Intro::
.string "JARINGAN PENGAWAS TREN DEWFORD!\p"
.string "MC: Ada apa?\n"
.string "Kita akan tetap nyata dengan berita\n"
.string "terbaru tentang apa yang sedang tren\l"
.string "dan terjadi di DEWFORD.\p"
.string "Tamu kita hari ini adalah orang tua\n"
.string "ini yang terkenal sebagai ahli dalam\l"
.string "segala hal di DEWFORD.\p"
.string "Orang tua: Senang berada di sini.\p"
.string "MC: Mari kita langsung ke intinya.\p"
.string "Apa pendapatmu tentang apa yang sedang\n"
.string "digandrungi oleh orang-orang baik di\l"
.string "DEWFORD?\p"
.string "Orang tua: {STR_VAR_1} {STR_VAR_2}.\p"
.string "MC: {STR_VAR_1} {STR_VAR_2},\n"
.string "katamu?\p"
.string "Orang tua: Tidak.\p"
.string "{STR_VAR_1} {STR_VAR_2} tidak pernah\n"
.string "populer sama sekali.\p"
.string "Apakah kamu ingin mendengarnya?\p"
.string "MC: Uh, tidak. Yang ingin kami tahu\n"
.string "adalah apa yang sedang tren saat ini…$"

@ Identik dengan di bawah, mungkin berbeda di bahasa lain
TrendWatcher_Text_MaleTaughtMePhrase::
.string "Orang tua: {STR_VAR_1} {STR_VAR_2}\n"
.string "adalah apa yang diajarkan {STR_VAR_3}\l"
.string "dari LITTLEROOT kepadaku sebagai\l"
.string "sesuatu yang trendi…$"

TrendWatcher_Text_FemaleTaughtMePhrase::
.string "Orang tua: {STR_VAR_1} {STR_VAR_2}\n"
.string "adalah apa yang diajarkan {STR_VAR_3}\l"
.string "dari LITTLEROOT kepadaku sebagai\l"
.string "sesuatu yang trendi…$"

TrendWatcher_Text_PhraseWasHopeless::
.string "Tapi itu sama sekali tidak ada harapan.\p"
.string "Festival {STR_VAR_1} {STR_VAR_2}!\p"
.string "Kontes {STR_VAR_1} {STR_VAR_2}!\p"
.string "Aku mencoba mengajari semua orang\n"
.string "sebaik mungkin, tapi…\p"
.string "Mungkin bagian {STR_VAR_1} saja\n"
.string "tidak tepat…\p"
.string "MC: Uh, permisi, kawan, aku perlu\n"
.string "mendengar tentang apa yang sedang tren\l"
.string "sekarang…$"

@ Identik dengan di bawah, mungkin berbeda di bahasa lain
TrendWatcher_Text_MaleTellMeBigger::
.string "Orang tua: {STR_VAR_3}!\n"
.string "Tolong, beritahu aku sesuatu yang lebih\n"
.string "besar dari {STR_VAR_1} {STR_VAR_2} itu!$"

TrendWatcher_Text_FemaleTellMeBigger::
.string "Orang tua: {STR_VAR_3}!\n"
.string "Tolong, beritahu aku sesuatu yang lebih\n"
.string "besar dari {STR_VAR_1} {STR_VAR_2} itu!$"

TrendWatcher_Text_Outro::
.string "MC: …Uh… Jadi, itu dia, kalian\n"
.string "semua yang trendi di luar sana!\p"
.string "{STR_VAR_1} {STR_VAR_2}…uh…\n"
.string "Tidak menjadi tren atau terjadi di\n"
.string "DEWFORD!\p"
.string "Waktuku habis. Sampai jumpa!\p"
.string "Orang tua: {STR_VAR_1} {STR_VAR_2}!$"

gTVHoennTreasureInvestigatorsText00::
.string "INVESTIGATOR HARTA KARUN HOENN!\p"
.string "Hai, teman-teman!\n"
.string "Baru-baru ini dapat item rahasia?\p"
.string "Seperti biasa, kita akan memeriksa\n"
.string "laporan saksi mata tentang rahasia\l"
.string "dari seluruh penjuru!\p"
.string "Mari kita mulai dengan sebuah surat.\n"
.string "Bunyinya, “{STR_VAR_1} ditemukan!”$"

gTVHoennTreasureInvestigatorsText01::
.string "Wow, sebaiknya kita periksa surat ini!\n"
.string "Biar kubacakan untukmu.\p"
.string "…INVESTIGATOR yang terhormat,\n"
.string "Semoga Anda baik-baik saja.\p"
.string "Baru-baru ini aku melihat {STR_VAR_2}\n"
.string "di suatu tempat di sekitar {STR_VAR_3}.\p"
.string "TRAINER itu menemukan item\n"
.string "{STR_VAR_1}. Itu membuatku iri.\p"
.string "…Yah, bagus, {STR_VAR_2}!\p"
.string "Pemirsa, biarkan itu memotivasi kamu\n"
.string "untuk menyalakan ITEMFINDER dan mencari!\p"
.string "Aku akan menunggu berita menarik dari\n"
.string "kalian semua!$"

gTVHoennTreasureInvestigatorsText02::
.string "Wow, sebaiknya kita periksa surat ini!\n"
.string "Biar kubacakan untukmu.\p"
.string "…INVESTIGATOR yang terhormat,\n"
.string "Semoga Anda baik-baik saja.\p"
.string "Baru-baru ini aku melihat {STR_VAR_2}\n"
.string "di sebuah feri.\p"
.string "TRAINER itu menemukan item\n"
.string "{STR_VAR_1}. Itu membuatku iri.\p"
.string "…Yah, bagus, {STR_VAR_2}!\p"
.string "Pemirsa, biarkan itu memotivasi kamu\n"
.string "untuk menyalakan ITEMFINDER dan mencari!\p"
.string "Aku akan menunggu berita menarik dari\n"
.string "kalian semua!$"

gTVFindThatGamerText00::
.string "TEMUKAN GAMER ITU!\p"
.string "Hei, semua gamer!\n"
.string "Bagaimana putaran {STR_VAR_2}-mu?\p"
.string "Seperti biasa, kita akan menyoroti\n"
.string "seorang TRAINER langka yang telah\l"
.string "mengunjungi GAME CORNER!\p"
.string "Hari ini, gamer no. 1 kita adalah…\n"
.string "{STR_VAR_1}!$"

gTVFindThatGamerText01::
.string "{STR_VAR_1} memainkan game {STR_VAR_2}\n"
.string "dan memenangkan {STR_VAR_3} KOIN yang\l"
.string "langka.\p"
.string "“Saat {STR_VAR_1} datang, kita perlu\n"
.string "memastikan kita punya cukup KOIN.”\p"
.string "Itulah yang digumamkan oleh para\n"
.string "petugas GAME CORNER saat gamer kita\l"
.string "sedang bermain!\p"
.string "Pemirsa, sebaiknya perhatikan KOIN-mu\n"
.string "seperti {STR_VAR_1} jika kamu mengunjungi\l"
.string "GAME CORNER dan bermain game {STR_VAR_2}.\p"
.string "Ini siaran langsung dari GAME CORNER--\n"
.string "di mana kamu bisa merasakan keseruannya!\p"
.string "Itu saja untuk hari ini!$"

gTVFindThatGamerText02::
.string "{STR_VAR_1} memainkan game {STR_VAR_2}\n"
.string "dan kehilangan {STR_VAR_3} KOIN.\p"
.string "“Saat {STR_VAR_1} datang, penjualan\n"
.string "KOIN kami sepertinya meningkat.”\p"
.string "Itulah yang dikatakan para petugas\n"
.string "GAME CORNER saat gamer kita sedang\l"
.string "bermain!$"

gTVFindThatGamerText03::
.string "Pemirsa, sebaiknya perhatikan KOIN-mu\n"
.string "seperti {STR_VAR_1} jika kamu mengunjungi\l"
.string "GAME CORNER dan bermain game {STR_VAR_2}.\p"
.string "Ini siaran langsung dari GAME CORNER--\n"
.string "di mana kamu bisa merasakan keseruannya!\p"
.string "Itu saja untuk hari ini!$"

gTVBreakingNewsText00::
.string "BERITA TERKINI TV!$"

gTVBreakingNewsText01::
.string "{STR_VAR_2} langka ditangkap oleh\n"
.string "{STR_VAR_1}!\p"
.string "Kami siaran langsung dari sekitar\n"
.string "{STR_VAR_3}!\p"
.string "{STR_VAR_1} berhasil menangkap\n"
.string "{STR_VAR_2} langka di sini tadi!$"

gTVBreakingNewsText02::
.string "Saat {STR_VAR_1} bertemu {STR_VAR_2}\n"
.string "langka, TRAINER mengirimkan POKéMON\l"
.string "{STR_VAR_3}.$"

gTVBreakingNewsText03::
.string "Dalam pertarungan, jumlah POKé BALL\n"
.string "yang dilempar oleh TRAINER adalah\l"
.string "{STR_VAR_1}.\p"
.string "Pada akhirnya, POKéMON langka itu\n"
.string "ditangkap oleh {STR_VAR_2} yang\l"
.string "digunakan terakhir.$"

gTVBreakingNewsText04::
.string "Pada saat itu, {STR_VAR_2} bergema\n"
.string "dengan raungan kemenangan {STR_VAR_1}.\p"
.string "Aku harus bilang aku sedikit iri pada\n"
.string "{STR_VAR_1}. Aku juga ingin meraung.\p"
.string "…Itu mengakhiri siaran langsung dari\n"
.string "adegan bahagia!$"

gTVBreakingNewsText05::
.string "{STR_VAR_1} gagal menangkap {STR_VAR_2}\n"
.string "langka!\p"
.string "Kami siaran langsung dari sekitar\n"
.string "{STR_VAR_3}!\p"
.string "Di sinilah {STR_VAR_1} gagal menangkap\n"
.string "{STR_VAR_2} langka!$"

gTVBreakingNewsText06::
.string "Saat {STR_VAR_1} bertemu {STR_VAR_2}\n"
.string "langka, TRAINER mengirimkan POKéMON\l"
.string "{STR_VAR_3}.$"

gTVBreakingNewsText07::
.string "TRAINER membuat {STR_VAR_2} menggunakan\n"
.string "jurus {STR_VAR_1}.\p"
.string "Tanpa sengaja, TRAINER membuat\n"
.string "POKéMON langka itu pingsan…$"

gTVBreakingNewsText12::
.string "Namun, {STR_VAR_1} panik saat melihat\n"
.string "{STR_VAR_2} langka.\p"
.string "Dalam kebingungan, TRAINER memerintahkan\n"
.string "{STR_VAR_3} untuk menyerang.\p"
.string "Tanpa sengaja, TRAINER membuat\n"
.string "POKéMON langka itu pingsan.$"

gTVBreakingNewsText08::
.string "Pada saat itu, {STR_VAR_2} bergema\n"
.string "dengan jeritan frustrasi {STR_VAR_1}…$"

gTVBreakingNewsText09::
.string "Namun, sepertinya {STR_VAR_1} kehabisan\n"
.string "POKé BALL.\p"
.string "TRAINER harus menghentikan pertarungan\n"
.string "dengan {STR_VAR_2} langka.\p"
.string "Pada saat itu, {STR_VAR_3} bergema\n"
.string "dengan jeritan frustrasi {STR_VAR_1}…$"

gTVBreakingNewsText10::
.string "Namun, {STR_VAR_2} melarikan diri\n"
.string "tanpa peringatan.\p"
.string "Pada saat itu, {STR_VAR_3} bergema\n"
.string "dengan jeritan frustrasi {STR_VAR_1}…$"

gTVBreakingNewsText11::
.string "Aku harus bilang aku kasihan pada\n"
.string "{STR_VAR_1}. Kenapa, itu membuatku ingin\l"
.string "menjerit juga.\p"
.string "…Itu mengakhiri siaran langsung dari\n"
.string "adegan melankolis!$"

gTVSecretBaseVisitText00::
.string "Halo, teman-teman!\n"
.string "Saatnya lagi untuk KUNJUNGAN\n"
.string "SECRET BASE.\p"
.string "Hari ini, kita mengunjungi SECRET BASE\n"
.string "milik {STR_VAR_1}.\p"
.string "Bagaimana {STR_VAR_1} mempersonalisasi\n"
.string "SECRET BASE-nya?\p"
.string "Mari kita cari tahu!\n"
.string "… … … … … …$"

gTVSecretBaseVisitText01::
.string "Oh!\n"
.string "Luar biasa!\p"
.string "{STR_VAR_2} ini…\n"
.string "Ini bukan sesuatu yang diharapkan\n"
.string "ditemukan di sini!$"

gTVSecretBaseVisitText02::
.string "Oh!\n"
.string "Luar biasa!\p"
.string "Tidak ada satu pun perabot atau barang\n"
.string "interior!\p"
.string "Manusia biasa tidak bisa berharap untuk\n"
.string "meniru pernyataan berani ini!\p"
.string "Sederhana, tapi meledak, ya, meledak\n"
.string "dengan keliaran!\p"
.string "Aku angkat topi padamu, {STR_VAR_1}.\n"
.string "Pasti kamu!$"

gTVSecretBaseVisitText03::
.string "Oh! Aku mengerti!\n"
.string "Dengan sangat jelas, aku melihatnya!\p"
.string "{STR_VAR_2} ini ada di sini…\n"
.string "Ini mengirimkan pesan yang efektif!$"

gTVSecretBaseVisitText04::
.string "Oh! Aku mengerti!\n"
.string "Dengan sangat jelas, aku melihatnya!\p"
.string "Ruang ini sengaja dikosongkan dari\n"
.string "barang-barang interior!\p"
.string "Ini mengirimkan pesan yang efektif!$"

gTVSecretBaseVisitText05::
.string "Wheeew!\p"
.string "Pasangan {STR_VAR_2} dengan {STR_VAR_3}!\p"
.string "Ini adalah kombinasi impian jika pernah\n"
.string "ada!$"

gTVSecretBaseVisitText06::
.string "Wheeew!\p"
.string "Penempatan {STR_VAR_2} ini di sini…\p"
.string "Ia memiliki kehadiran yang mengisi\n"
.string "seluruh SECRET BASE!$"

gTVSecretBaseVisitText07::
.string "Wheeew!\p"
.string "Tidak ada apa pun di sini.\p"
.string "Ruang kosong ini memiliki efek pada\n"
.string "seluruh SECRET BASE.$"

gTVSecretBaseVisitText08::
.string "Oh!\n"
.string "Ini dia {STR_VAR_1}!\l"
.string "Mari kita tantang TRAINER itu!\p"
.string "… … … … … …\n"
.string "… … … … … …$"

gTVSecretBaseVisitText09::
.string "Huft…\n"
.string "Aku harus mengakui kehebatan {STR_VAR_1}.\p"
.string "POKéMON TRAINER itu benar-benar layak\n"
.string "menyandang gelar JUARA.\p"
.string "Mereka memberikan banyak bukti ketangguhan\n"
.string "{STR_VAR_1} sebagai TRAINER.\p"
.string "Bahwa {STR_VAR_2} tahu jurus {STR_VAR_3}…\p"
.string "Itu menunjukkan TRAINER seperti apa\n"
.string "{STR_VAR_1} itu.\p"
.string "Tentu, itu pelajaran yang berharga!$"

gTVSecretBaseVisitText10::
.string "Aiyeeh!\n"
.string "Aku harus mengakui kehebatan {STR_VAR_1}.\p"
.string "POKéMON TRAINER itu sangat tangguh!\p"
.string "Mereka memberikan banyak bukti kegigihan\n"
.string "{STR_VAR_1} sebagai TRAINER.\p"
.string "Bahwa {STR_VAR_2} tahu jurus {STR_VAR_3}…\p"
.string "Itu menunjukkan TRAINER seperti apa\n"
.string "{STR_VAR_1} itu.\p"
.string "Tentu, itu pelajaran yang berharga!$"

gTVSecretBaseVisitText11::
.string "Wheeew!\n"
.string "Aku harus mengakui kehebatan {STR_VAR_1}.\p"
.string "POKéMON TRAINER itu jelas dibesarkan\n"
.string "dengan cara yang seimbang.\p"
.string "Mereka memberikan banyak bukti\n"
.string "kepedulian {STR_VAR_1} sebagai TRAINER.\p"
.string "Bahwa {STR_VAR_2} tahu jurus {STR_VAR_3}…\p"
.string "Itu menunjukkan TRAINER seperti apa\n"
.string "{STR_VAR_1} itu.\p"
.string "Tentu, itu pelajaran yang berharga!$"

gTVSecretBaseVisitText12::
.string "Wah, wah!\n"
.string "Aku harus mengakui kehebatan {STR_VAR_1}.\p"
.string "POKéMON TRAINER itu menunjukkan\n"
.string "potensi besar untuk pertumbuhan di masa depan.\p"
.string "Mereka mewakili harapan dan impian\n"
.string "{STR_VAR_1}.\p"
.string "Bahwa {STR_VAR_2} tahu jurus {STR_VAR_3}…\p"
.string "Itu menunjukkan TRAINER seperti apa\n"
.string "{STR_VAR_1} itu.\p"
.string "Tentu, itu pelajaran yang berharga!$"

gTVSecretBaseVisitText13::
.string "Aku harus bilang, SECRET BASE yang luar\n"
.string "biasa!\p"
.string "Pemirsa, jika ada kesempatan,\n"
.string "kunjungi SECRET BASE {STR_VAR_1}.\p"
.string "Sampai jumpa lagi, aku pamit!$"

gTVPokemonLotteryWinnerFlashReportText00::
.string "Menarik!\n"
.string "Dramatis!\p"
.string "Ini adalah LAPORAN KILAT PEMENANG\n"
.string "LOTERE POKéMON!\p"
.string "Halo! Kami siaran langsung dari SUDUT\n"
.string "LOTERE POKéMON di lantai dasar LILYCOVE\l"
.string "DEPARTMENT STORE!\p"
.string "Seperti biasa, TRAINER beruntung\n"
.string "lainnya muncul hari ini!\p"
.string "Nama TRAINER itu…\n"
.string "{STR_VAR_1}!\p"
.string "{STR_VAR_1} memenangkan hadiah\n"
.string "{STR_VAR_2} dan membawa pulang\l"
.string "{STR_VAR_3}!\p"
.string "{STR_VAR_1}!\n"
.string "Selamat!\p"
.string "Pemirsa, jangan hanya menonton,\n"
.string "ikutlah beraksi!\p"
.string "Kami semua di LILYCOVE DEPARTMENT\n"
.string "STORE menantikan kunjunganmu\l"
.string "berikutnya!\p"
.string "Ini adalah siaran langsung dari\n"
.string "LILYCOVE DEPARTMENT STORE, menawarkan\l"
.string "pilihan terbaik di seluruh HOENN!$"

gTVThePokemonBattleSeminarText00::
.string "SEMINAR PERTARUNGAN POKéMON!\p"
.string "Kami memeriksa pertarungan untuk melihat\n"
.string "pelajaran apa yang bisa kita ambil dari\l"
.string "orang lain.\p"
.string "Studi kasus hari ini adalah pertarungan\n"
.string "{STR_VAR_1}.\p"
.string "{STR_VAR_2} milik {STR_VAR_1} sedang\n"
.string "bertarung dengan satu {STR_VAR_3}…$"

gTVThePokemonBattleSeminarText01::
.string "Dan itu menggunakan jurus {STR_VAR_3}\n"
.string "pada {STR_VAR_2}…\p"
.string "Hmm… {STR_VAR_1}!\n"
.string "Itu hal yang salah untuk dilakukan!$"

gTVThePokemonBattleSeminarText02::
.string "Selain jurus yang salah, {STR_VAR_1}\n"
.string "milik TRAINER juga tahu$"

gTVThePokemonBattleSeminarText03::
.string "jurus {STR_VAR_1}, {STR_VAR_2}, dan\n"
.string "{STR_VAR_3}.$"

gTVThePokemonBattleSeminarText04::
.string "jurus {STR_VAR_1} dan {STR_VAR_2}.$"

gTVThePokemonBattleSeminarText05::
.string "jurus {STR_VAR_2}.$"

gTVThePokemonBattleSeminarText06::
.string "Jadi, dalam situasi ini, apa yang\n"
.string "seharusnya digunakan oleh TRAINER?\p"
.string "… … … … … …\n"
.string "Jurus {STR_VAR_1}!\p"
.string "Jurus {STR_VAR_1} akan jauh lebih baik\n"
.string "daripada {STR_VAR_2}.\p"
.string "Pemirsa, aku mendorongmu untuk belajar\n"
.string "dari kasus ini dan bertarung dengan\l"
.string "cerdas!\p"
.string "Sampai jumpa lagi, selamat tinggal!$"

gTVTrainerFanClubText00::
.string "Semua bersama-sama!\n"
.string "KLUB PENGGEMAR TRAINER!\p"
.string "MC: Bagaimana kabar semua?\n"
.string "Hari ini, kita telah mengumpulkan para\n"
.string "penggemar TRAINER super populer\l"
.string "{STR_VAR_1}!\p"
.string "PENGGEMAR: Wrooooooaaaaah!\p"
.string "PENGGEMAR: {STR_VAR_1}!\p"
.string "MC: Semuanya!\n"
.string "Bagaimana kalian menyukai {STR_VAR_1}?!/p"
.string "PENGGEMAR: Kami cinta {STR_VAR_1}!\p"
.string "MC: Apa yang kalian cintai dari\n"
.string "{STR_VAR_1}?!$"

gTVTrainerFanClubText01::
.string "PENGGEMAR: Cara keren mereka melempar\n"
.string "POKé BALL!$"

gTVTrainerFanClubText02::
.string "PENGGEMAR: Cara menggemaskan mereka\n"
.string "berlari!$"

gTVTrainerFanClubText03::
.string "PENGGEMAR: Bagaimana TRAINER menjadi\n"
.string "tangguh saat keadaan menjadi sulit!$"

gTVTrainerFanClubText04::
.string "PENGGEMAR: Pengetahuan TRAINER tentang\n"
.string "POKéMON!$"

gTVTrainerFanClubText05::
.string "PENGGEMAR: Kebaikan TRAINER terhadap\n"
.string "semua POKéMON!$"

gTVTrainerFanClubText06::
.string "PENGGEMAR: Teknik mengendarai SEPEDA\n"
.string "TRAINER yang luar biasa!$"

gTVTrainerFanClubText07::
.string "PENGGEMAR: Gaya membeli item TRAINER\n"
.string "yang mengesankan!$"

gTVTrainerFanClubText08::
.string "PENGGEMAR: Cara menawan TRAINER\n"
.string "memberi nama panggilan POKéMON!$"

gTVTrainerFanClubText09::
.string "PENGGEMAR: Gaya apik TRAINER dalam\n"
.string "menghias SECRET BASE!$"

gTVTrainerFanClubText10::
.string "PENGGEMAR: Cara berani TRAINER\n"
.string "menggunakan TM!$"

gTVTrainerFanClubText11::
.string "MC: Seperti yang baru saja kamu lihat,\n"
.string "{STR_VAR_1} sedang naik daun! Sangat\l"
.string "naik daun, yow!\p"
.string "Di antara PENGGEMAR {STR_VAR_1} ada\n"
.string "slogan khusus!\p"
.string "MC: Saat aku bilang {STR_VAR_1},\n"
.string "kamu bilang…\p"
.string "PENGGEMAR: {STR_VAR_2}!\p"
.string "PENGGEMAR: {STR_VAR_3}!\p"
.string "PENGGEMAR: {STR_VAR_2}!\p"
.string "PENGGEMAR: {STR_VAR_3}!\p"
.string "MC: Benar, saat seseorang berkata,\n"
.string "“{STR_VAR_1}”…\p"
.string "Balas dengan, “{STR_VAR_2}\n"
.string "{STR_VAR_3}!”\p"
.string "Itu memiliki nada yang unik!\n"
.string "Aku mengerti mengapa orang menjadi\n"
.string "PENGGEMAR {STR_VAR_1}!\p"
.string "Oke, kamu, di depan TV, bergabunglah\n"
.string "dengan kami!\n"
.string "Semua bersama-sama!\p"
.string "MC: Saat aku bilang {STR_VAR_1},\n"
.string "kamu bilang…\p"
.string "PENGGEMAR: {STR_VAR_2}!\p"
.string "PENGGEMAR: {STR_VAR_3}!\p"
.string "PENGGEMAR: {STR_VAR_2}!\p"
.string "PENGGEMAR: {STR_VAR_3}!\p"
.string "MC: Terima kasih telah bergabung dengan\n"
.string "kami, semua PENGGEMAR liar {STR_VAR_1}!\l"
.string "Itu saja acaranya! Sampai jumpa lagi!\p"
.string "MC: Saat aku bilang {STR_VAR_1},\n"
.string "kamu bilang…\p"
.string "PENGGEMAR: {STR_VAR_2}!\p"
.string "PENGGEMAR: {STR_VAR_3}!$"

TVSpotTheCuties_Text_Intro::
.string "TEMUKAN YANG IMUT!\n"
.string "POKéMON DENGAN PITA!\p"
.string "Halo, pemirsa manisku!\p"
.string "Aku tahu kamu akan setuju, tapi\n"
.string "POKéMON yang memakai PITA sungguh\l"
.string "indah!\p"
.string "Hari ini, aku ingin berbagi denganmu\n"
.string "POKéMON cantik yang kulihat saat\l"
.string "sedang berjalan-jalan di kota.\p"
.string "POKéMON cantik pilihan hari ini adalah\n"
.string "{STR_VAR_2} milik {STR_VAR_1}.$"

TVSpotTheCuties_Text_RibbonsLow::
.string "Jumlah PITA yang dikenakan {STR_VAR_2}\n"
.string "adalah {STR_VAR_3}.\p"
.string "Itu menunjukkan betapa {STR_VAR_1}\n"
.string "sangat menyayangi POKéMON itu.$"

TVSpotTheCuties_Text_RibbonsMid::
.string "{STR_VAR_2} mengenakan {STR_VAR_3} PITA\n"
.string "yang luar biasa!\p"
.string "Itu menunjukkan komitmen {STR_VAR_1}\n"
.string "terhadap POKéMON itu!$"

TVSpotTheCuties_Text_RibbonsHigh::
.string "{STR_VAR_2} mengenakan {STR_VAR_3} PITA\n"
.string "yang luar biasa!\p"
.string "Itu menunjukkan dedikasi total\n"
.string "{STR_VAR_1} sebagai kolektor!$"

TVSpotTheCuties_Text_RibbonIntro::
.string "Mari kita lihat lebih dekat banyak\n"
.string "PITA yang dikenakan oleh {STR_VAR_2}.$"

TVSpotTheCuties_Text_RibbonChampion::
.string "PITA JUARA sangat menarik.\p"
.string "{STR_VAR_2} menerimanya saat memasuki\n"
.string "HALL OF FAME.\p"
.string "Itu benar-benar menonjolkan keberanian\n"
.string "{STR_VAR_2}.\p"
.string "{STR_VAR_2} dan PITA JUARA!\n"
.string "Kombinasinya super efektif!$"

TVSpotTheCuties_Text_RibbonCool::
.string "PITA KEREN sangat menarik.\p"
.string "{STR_VAR_2} menerimanya karena memenangkan\n"
.string "CONTEST KEREN.\p"
.string "Itu benar-benar menonjolkan kekerenan\n"
.string "{STR_VAR_2}.\p"
.string "{STR_VAR_2} dan PITA KEREN!\n"
.string "Kombinasinya super efektif!$"

TVSpotTheCuties_Text_RibbonBeauty::
.string "PITA CANTIK sangat menarik.\p"
.string "{STR_VAR_2} menerimanya karena memenangkan\n"
.string "CONTEST CANTIK.\p"
.string "Itu benar-benar menonjolkan kecantikan\n"
.string "{STR_VAR_2}.\p"
.string "{STR_VAR_2} dan PITA CANTIK!\n"
.string "Kombinasinya super efektif!$"

TVSpotTheCuties_Text_RibbonCute::
.string "PITA IMUT sangat menarik.\p"
.string "{STR_VAR_2} menerimanya karena memenangkan\n"
.string "CONTEST IMUT.\p"
.string "Itu benar-benar menonjolkan keimutan\n"
.string "{STR_VAR_2}.\p"
.string "{STR_VAR_2} dan PITA IMUT!\n"
.string "Kombinasinya super efektif!$"

TVSpotTheCuties_Text_RibbonSmart::
.string "PITA PINTAR sangat menarik.\p"
.string "{STR_VAR_2} menerimanya karena memenangkan\n"
.string "CONTEST PINTAR.\p"
.string "Itu benar-benar menonjolkan kepintaran\n"
.string "{STR_VAR_2}.\p"
.string "{STR_VAR_2} dan PITA PINTAR!\n"
.string "Kombinasinya super efektif!$"

TVSpotTheCuties_Text_RibbonTough::
.string "PITA TANGGUH sangat menarik.\p"
.string "{STR_VAR_2} menerimanya karena memenangkan\n"
.string "CONTEST TANGGUH.\p"
.string "Itu benar-benar menonjolkan ketangguhan\n"
.string "{STR_VAR_2}.\p"
.string "{STR_VAR_2} dan PITA TANGGUH!\n"
.string "Kombinasinya super efektif!$"

TVSpotTheCuties_Text_RibbonWinning::
.string "PITA PEMENANG sangat menarik.\p"
.string "{STR_VAR_2} menerimanya atas prestasinya\n"
.string "di BATTLE TOWER.\p"
.string "Itu benar-benar menonjolkan kekuatan\n"
.string "{STR_VAR_2}.\p"
.string "{STR_VAR_2} dan PITA PEMENANG!\n"
.string "Kombinasinya super efektif!$"

TVSpotTheCuties_Text_RibbonVictory::
.string "PITA KEMENANGAN sangat menarik.\p"
.string "{STR_VAR_2} menerimanya atas prestasinya\n"
.string "di BATTLE TOWER.\p"
.string "Itu benar-benar menonjolkan kekuatan\n"
.string "luar biasa {STR_VAR_2}.\p"
.string "{STR_VAR_2} dan PITA KEMENANGAN!\n"
.string "Kombinasinya super efektif!$"

TVSpotTheCuties_Text_RibbonArtist::
.string "PITA SENIMAN sangat menarik.\p"
.string "{STR_VAR_2} menerimanya karena menjadi\n"
.string "model untuk seorang seniman.\p"
.string "Itu benar-benar menonjolkan pesona\n"
.string "bintang pop {STR_VAR_2}.\p"
.string "{STR_VAR_2} dan PITA SENIMAN!\n"
.string "Kombinasinya super efektif!$"

TVSpotTheCuties_Text_RibbonEffort::
.string "PITA Pekerja Keras sangat menarik.\p"
.string "{STR_VAR_2} menerimanya karena menjadi\n"
.string "pekerja yang sangat berdedikasi.\p"
.string "Itu benar-benar menonjolkan tekad\n"
.string "{STR_VAR_2}.\p"
.string "{STR_VAR_2} dan PITA Pekerja Keras!\n"
.string "Kombinasinya super efektif!$"

TVSpotTheCuties_Text_Outro::
.string "…Huft…\p"
.string "PITA dan POKéMON…\n"
.string "Mereka sangat cocok bersama!\p"
.string "Sebelum aku pingsan,\n"
.string "aku pamit pada kalian semua!$"

gTVPokemonNewsBattleFrontierText00::
.string "Salam!\n"
.string "Saatnya untuk BERITA POKéMON.\p"
.string "Kami punya berita menggembirakan dari\n"
.string "BATTLE FRONTIER.$"

gTVPokemonNewsBattleFrontierText01::
.string "TRAINER {STR_VAR_1} mencetak rekor baru\n"
.string "{STR_VAR_2} kemenangan beruntun saat\l"
.string "berada di tantangan SINGLE BATTLE ROOM\l"
.string "BATTLE TOWER.\p"
.string "Ini untuk {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText02::
.string "TRAINER {STR_VAR_1} mencetak rekor baru\n"
.string "{STR_VAR_2} kemenangan beruntun saat\l"
.string "berada di tantangan DOUBLE BATTLE ROOM\l"
.string "BATTLE TOWER.\p"
.string "Ini untuk {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText03::
.string "TRAINER {STR_VAR_1} mencetak rekor baru\n"
.string "{STR_VAR_2} kemenangan beruntun saat\l"
.string "berada di tantangan MULTI BATTLE ROOM\l"
.string "BATTLE TOWER.\p"
.string "Ini untuk {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText04::
.string "TRAINER {STR_VAR_1} mencetak rekor baru\n"
.string "{STR_VAR_2} kemenangan beruntun saat\l"
.string "berada di tantangan LINK MULTI BATTLE\l"
.string "ROOM BATTLE TOWER.\p"
.string "Ini untuk {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText05::
.string "TRAINER {STR_VAR_1} mencetak rekor baru\n"
.string "{STR_VAR_2} kejuaraan beruntun saat\l"
.string "bertanding di Turnamen SINGLE BATTLE\l"
.string "BATTLE DOME.\p"
.string "Ini untuk {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText06::
.string "TRAINER {STR_VAR_1} mencetak rekor baru\n"
.string "{STR_VAR_2} kejuaraan beruntun saat\l"
.string "bertanding di Turnamen DOUBLE BATTLE\l"
.string "BATTLE DOME.\p"
.string "Ini untuk {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText07::
.string "TRAINER {STR_VAR_1} mencetak rekor baru\n"
.string "{STR_VAR_2} kemenangan beruntun saat\l"
.string "berada di tantangan Battle Swap Single\l"
.string "BATTLE FACTORY.\p"
.string "Ini untuk {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText08::
.string "TRAINER {STR_VAR_1} mencetak rekor baru\n"
.string "{STR_VAR_2} kemenangan beruntun saat\l"
.string "berada di tantangan Battle Swap Double\l"
.string "BATTLE FACTORY.\p"
.string "Ini untuk {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText09::
.string "TRAINER {STR_VAR_1} mencetak rekor baru\n"
.string "membersihkan {STR_VAR_2} ruangan saat\l"
.string "berada di tantangan Battle Choice\l"
.string "BATTLE PIKE.\p"
.string "Ini untuk {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText10::
.string "TRAINER {STR_VAR_1} mencetak rekor baru\n"
.string "{STR_VAR_2} kemenangan beruntun saat\l"
.string "bertanding di Turnamen Set KO\l"
.string "BATTLE ARENA.\p"
.string "Ini untuk {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText11::
.string "TRAINER {STR_VAR_1} mencetak rekor baru\n"
.string "{STR_VAR_2} kemenangan beruntun saat\l"
.string "berada di tantangan SINGLE BATTLE HALL\l"
.string "BATTLE PALACE.\p"
.string "Ini untuk {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText12::
.string "TRAINER {STR_VAR_1} mencetak rekor baru\n"
.string "{STR_VAR_2} kemenangan beruntun saat\l"
.string "berada di tantangan DOUBLE BATTLE HALL\l"
.string "BATTLE PALACE.\p"
.string "Ini untuk {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText13::
.string "TRAINER {STR_VAR_1} mencetak rekor baru\n"
.string "membersihkan {STR_VAR_2} lantai saat\l"
.string "berada di tantangan Battle Quest\l"
.string "BATTLE PYRAMID.\p"
.string "Ini untuk {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText14::
.string "Dan untuk ketiga POKéMON, {STR_VAR_1},\n"
.string "{STR_VAR_2}, dan {STR_VAR_3}!\p"
.string "Selamat atas performa pemecah\n"
.string "rekor kalian!$"

gTVPokemonNewsBattleFrontierText15::
.string "Dan untuk kedua POKéMON, {STR_VAR_1}\n"
.string "dan {STR_VAR_2}!\p"
.string "Selamat atas performa pemecah\n"
.string "rekor kalian!$"

gTVPokemonNewsBattleFrontierText16::
.string "Dan untuk keempat POKéMON: {STR_VAR_1}!\p"
.string "{STR_VAR_2}!\p"
.string "{STR_VAR_3}!$"

gTVPokemonNewsBattleFrontierText17::
.string "Dan {STR_VAR_1}!\p"
.string "Selamat atas performa pemecah\n"
.string "rekor kalian!$"

gTVPokemonNewsBattleFrontierText18::
.string "Semoga ada lebih banyak prestasi\n"
.string "pemecah rekor dari {STR_VAR_1} dan\l"
.string "POKéMON setianya!\p"
.string "Itulah berita di BERITA POKéMON!$"

gTVWhatsNo1InHoennTodayText00::
.string "APA YANG NO. 1 DI HOENN HARI INI?\n"
.string "Ya, saatnya lagi!\p"
.string "Halo, pemirsa! Apakah kamu memberikan\n"
.string "yang terbaik dalam apa pun yang kamu\l"
.string "lakukan?\p"
.string "Mari kita lihat TRAINER yang melakukan\n"
.string "yang terbaik hari ini!\p"
.string "TRAINER no. 1 hari ini tidak lain\n"
.string "adalah {STR_VAR_1}!$"

gTVWhatsNo1InHoennTodayText01::
.string "Dalam satu hari, {STR_VAR_1} memutar\n"
.string "SLOT di GAME CORNER {STR_VAR_2} kali.\p"
.string "Saat bermain, {STR_VAR_1} terdengar\n"
.string "bergumam, “Bagiku, gulungan itu bahkan\l"
.string "tidak bergerak…”\l"
.string "Bukankah itu menarik?$"

gTVWhatsNo1InHoennTodayText02::
.string "Dalam satu hari, {STR_VAR_1} bermain\n"
.string "game ROULETTE di GAME CORNER {STR_VAR_2}\l"
.string "kali.\p"
.string "Saat bermain, {STR_VAR_1} berteriak,\n"
.string "“Biarkan bola yang memutuskan!”\p"
.string "Mata TRAINER itu fokus dan wajahnya\n"
.string "menunjukkan konsentrasi.$"

gTVWhatsNo1InHoennTodayText03::
.string "Dalam satu hari, {STR_VAR_1} bertarung\n"
.string "dengan POKéMON liar {STR_VAR_2} kali!\p"
.string "Tampaknya, POKéMON {STR_VAR_1} telah\n"
.string "tumbuh jauh lebih kuat.\p"
.string "Mereka tampak bersemangat untuk bertarung\n"
.string "di mana saja, kapan saja, dan bagaimana\l"
.string "saja!$"

gTVWhatsNo1InHoennTodayText04::
.string "Hanya dalam satu hari, {STR_VAR_1}\n"
.string "memutar BERRY BLENDER {STR_VAR_2} kali!\p"
.string "Menjelang akhir, bahkan {STR_VAR_1}\n"
.string "tampak pusing.\p"
.string "TRAINER itu tampak terhuyung-huyung\n"
.string "seperti SPINDA!$"

gTVWhatsNo1InHoennTodayText05::
.string "Hanya dalam satu hari, {STR_VAR_1}\n"
.string "menanam {STR_VAR_2} BERRIES!\p"
.string "Akibatnya, pakaian {STR_VAR_1} menjadi\n"
.string "kotor karena tanah.\p"
.string "Di tempat TRAINER menanam, tak terhitung\n"
.string "bunga telah mekar.\p"
.string "Bunga-bunga itu dikatakan dapat menenangkan\n"
.string "emosi orang.$"

gTVWhatsNo1InHoennTodayText06::
.string "Hanya dalam satu hari, {STR_VAR_1}\n"
.string "memetik {STR_VAR_2} BERRIES!\p"
.string "TAS {STR_VAR_1} menjadi begitu penuh\n"
.string "dengan BERRIES, TRAINER itu kesulitan\l"
.string "berjalan setelahnya!$"

gTVWhatsNo1InHoennTodayText07::
.string "Hanya dalam satu hari, {STR_VAR_1}\n"
.string "mendapatkan {STR_VAR_2} Battle Points!\p"
.string "{STR_VAR_1} kemudian terlihat bingung\n"
.string "dengan pilihan menukarkan Battle Points\l"
.string "dengan item keren atau dekorasi interior\l"
.string "yang bagus.\p"
.string "TRAINER itu dilaporkan tersenyum\n"
.string "sambil memikirkan pilihan.$"

gTVWhatsNo1InHoennTodayText08::
.string "Wah, bukankah itu sesuatu!\p"
.string "{STR_VAR_1}!\n"
.string "Kamu adalah TRAINER no. 1 hari ini!\p"
.string "Pemirsa, ambillah semangat dari\n"
.string "{STR_VAR_1}!\n"
.string "Kamu juga bisa menjadi no. 1 setiap\n"
.string "hari!$"

TVSecretBaseSecrets_Text_Intro::
.string "RAHASIA SECRET BASE!\p"
.string "Apa yang dilakukan TRAINER secara\n"
.string "rahasia di SECRET BASE?\p"
.string "Hari ini, kita menyelidiki SECRET BASE\n"
.string "milik {STR_VAR_1}.\p"
.string "Oh? Sepertinya {STR_VAR_2} datang\n"
.string "berkunjung.\p"
.string "Mari kita intip!\p"
.string "Apa yang akan dilakukan {STR_VAR_2}?$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext1::
.string "Apa yang akan dilakukan {STR_VAR_2}\n"
.string "selanjutnya?$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext2::
.string "Dan sekarang, apa yang akan dilakukan\n"
.string "{STR_VAR_2}?$"

TVSecretBaseSecrets_Text_TookXStepsBeforeLeaving::
.string "Pada akhirnya, {STR_VAR_2} mengambil\n"
.string "{STR_VAR_3} langkah di SECRET BASE\l"
.string "{STR_VAR_1} sebelum pergi.$"

TVSecretBaseSecrets_Text_BaseFailedToInterestPlayer::
.string "Hmm…\p"
.string "Tampaknya SECRET BASE {STR_VAR_1}\n"
.string "gagal menarik minat {STR_VAR_2}…$"

TVSecretBaseSecrets_Text_PlayerEnjoyedBase::
.string "{STR_VAR_2} tampaknya sangat menikmati\n"
.string "SECRET BASE {STR_VAR_1}.$"

TVSecretBaseSecrets_Text_PlayerHugeFanOfBase::
.string "{STR_VAR_2} tampaknya telah menjadi\n"
.string "penggemar berat SECRET BASE {STR_VAR_1}.$"

TVSecretBaseSecrets_Text_Outro::
.string "Pemirsa mungkin ingin melihat SECRET\n"
.string "BASE {STR_VAR_1} juga.\p"
.string "Tonton lagi lain waktu saat kita\n"
.string "mengunjungi SECRET BASE lain! Terima\l"
.string "kasih telah bergabung dengan kami!$"

TVSecretBaseSecrets_Text_StoppedMoving1::
.string "Pengunjung telah berhenti!\p"
.string "Pengunjung tidak bergerak sama sekali!\p"
.string "Apakah SECRET BASE {STR_VAR_1} begitu\n"
.string "tidak mengesankan?$"

TVSecretBaseSecrets_Text_StoppedMoving2::
.string "Pengunjung telah berhenti!\p"
.string "Pengunjung tidak bergerak sama sekali!\p"
.string "Apakah karena kelelahan?\n"
.string "Apakah pengunjung sudah lelah?$"

TVSecretBaseSecrets_Text_UsedChair::
.string "Pengunjung duduk di kursi!\n"
.string "Pengunjung sedang duduk!\p"
.string "Lihatlah ekspresi senangnya!\p"
.string "Kursi itu pasti sangat nyaman untuk\n"
.string "mendapatkan respons seperti itu!$"

TVSecretBaseSecrets_Text_UsedBalloon::
.string "Pengunjung menyerbu balon!\p"
.string "Meletus!\n"
.string "Oh, ya ampun, meletus!\p"
.string "Pengunjung tampak terkejut dengan\n"
.string "suara tiba-tiba itu!$"

TVSecretBaseSecrets_Text_UsedTent::
.string "Pengunjung memasuki TENDA!\p"
.string "Pengunjung berlari-lari!\p"
.string "Oh, ampun, pengunjung sedang\n"
.string "bersenang-senang!\p"
.string "Pengunjung tampak terkejut dengan\n"
.string "ukuran TENDA!$"

TVSecretBaseSecrets_Text_UsedPlant::
.string "Pengunjung sedang memeriksa\n"
.string "tanaman dalam pot!\p"
.string "Pengunjung ternyata memiliki selera\n"
.string "yang dewasa!$"

TVSecretBaseSecrets_Text_UsedGoldShield::
.string "Pengunjung sedang memeriksa\n"
.string "PERISAI EMAS!\p"
.string "Mata pengunjung tampak berbinar\n"
.string "karena takjub!$"

TVSecretBaseSecrets_Text_UsedSilverShield::
.string "Pengunjung sedang memeriksa\n"
.string "PERISAI PERAK!\p"
.string "Pengunjung tampak terbelalak!$"

TVSecretBaseSecrets_Text_UsedGlassOrnament::
.string "Pengunjung sedang memeriksa\n"
.string "HIASAN KACA!\p"
.string "Oh, tidak!\p"
.string "Pengunjung menyentuhnya!\p"
.string "Jadi penuh dengan sidik jari…$"

TVSecretBaseSecrets_Text_UsedTV::
.string "Pengunjung sedang menonton televisi!\p"
.string "Sepertinya kita punya penggemar berat\n"
.string "TV!$"

TVSecretBaseSecrets_Text_UsedMudBall::
.string "Pengunjung menginjak BOLA LUMPUR!\p"
.string "Pengunjung terlihat senang!$"

TVSecretBaseSecrets_Text_UsedBag::
.string "…Oh?\p"
.string "Pengunjung sedang meraih TAS mereka\n"
.string "sendiri dan mengobrak-abriknya!\p"
.string "Pengunjung mengeluarkan satu\n"
.string "{STR_VAR_2}!\p"
.string "Lihatlah senyum pengunjung saat\n"
.string "memegang {STR_VAR_2}!\p"
.string "Seperti iklan TV!$"

TVSecretBaseSecrets_Text_UsedCushion::
.string "Pengunjung mengambil bantal dan…$"

TVSecretBaseSecrets_Text_HitCushion::
.string "…mulai memukulnya!\p"
.string "Apakah pengunjung sedang stres berat?$"

TVSecretBaseSecrets_Text_HuggedCushion::
.string "…memeluknya erat!\p"
.string "Mungkinkah pengunjung sedang merasa\n"
.string "senang tentang sesuatu?$"

TVSecretBaseSecrets_Text_BattledWon::
.string "Pengunjung sedang mengobrol dengan\n"
.string "{STR_VAR_1}!\p"
.string "Sepertinya mereka akan bertarung!\p"
.string "Dan…\p"
.string "Itu pengunjungnya!\n"
.string "Pengunjung memenangkan pertandingan tandang!\p"
.string "Pengunjung sedang melakukan tarian\n"
.string "kemenangan!$"

TVSecretBaseSecrets_Text_BattledLost::
.string "Pengunjung sedang mengobrol dengan\n"
.string "{STR_VAR_1}!\p"
.string "Sepertinya mereka akan bertarung!\p"
.string "Dan…\p"
.string "Itu {STR_VAR_1}!\n"
.string "Pengunjung telah kalah!\p"
.string "Pengunjung terlihat sedih!$"

TVSecretBaseSecrets_Text_DeclinedBattle::
.string "Pengunjung sedang mengobrol dengan\n"
.string "{STR_VAR_1}!\p"
.string "Sepertinya mereka akan bertarung!\p"
.string "Dan…\p"
.string "Tidak, pengunjung menolak!\p"
.string "Tidak akan ada pertarungan!\p"
.string "Apakah pengunjung merasa {STR_VAR_1}\n"
.string "tidak menarik?$"

TVSecretBaseSecrets_Text_UsedPoster::
.string "Pengunjung sedang menatap poster\n"
.string "dengan saksama!\p"
.string "Apakah poster itu sesuai dengan selera\n"
.string "pengunjung?\p"
.string "…Tapi… Ada sesuatu yang mengganggu\n"
.string "dari tatapan pengunjung.$"

TVSecretBaseSecrets_Text_UsedNoteMat::
.string "Pengunjung menginjak NOTE MAT!\p"
.string "…Hmm…\n"
.string "Pengunjung menciptakan nada yang lucu!$"

TVSecretBaseSecrets_Text_BattledDraw::
.string "Pengunjung sedang mengobrol dengan\n"
.string "{STR_VAR_1}!\p"
.string "Sepertinya mereka akan bertarung!\p"
.string "Dan…\p"
.string "Seri!\n"
.string "Tidak ada yang terselesaikan!\p"
.string "Kedua TRAINER tampak sangat kecewa!$"

TVSecretBaseSecrets_Text_UsedSpinMat::
.string "Pengunjung menginjak SPIN MAT!\p"
.string "Sepertinya pengunjung pusing!\p"
.string "Pengunjung terhuyung-huyung!\n"
.string "Awas!$"

TVSecretBaseSecrets_Text_UsedSandOrnament::
.string "Pengunjung sedang meraih HIASAN PASIR!\p"
.string "Oh!\p"
.string "Hancur!\n"
.string "Hancur berkeping-keping!\p"
.string "Pengunjung terlihat malu dan bersalah!$"

TVSecretBaseSecrets_Text_UsedDesk::
.string "Pengunjung sedang menggosok meja dengan\n"
.string "jari mereka!\p"
.string "Tampaknya, pengunjung tidak menyukai\n"
.string "debu!\p"
.string "Pengunjung ternyata sangat peduli\n"
.string "dengan kebersihan!$"

TVSecretBaseSecrets_Text_UsedBrick::
.string "Pengunjung sedang menatap BATA!\p"
.string "Mungkin pengunjung sedang memikirkan\n"
.string "objek di atas BATA.$"

TVSecretBaseSecrets_Text_UsedSolidBoard::
.string "Pengunjung sedang berjalan melintasi\n"
.string "PAPAN PADAT.\p"
.string "Pengunjung terus melihat ke bawah.\p"
.string "Pengunjung tampaknya sangat pemalu\n"
.string "dan berhati-hati!$"

TVSecretBaseSecrets_Text_UsedFence::
.string "Pengunjung sedang menatap PAGAR dengan\n"
.string "saksama!\p"
.string "Apakah ide baru untuk jebakan muncul\n"
.string "di kepala pengunjung?$"

TVSecretBaseSecrets_Text_UsedGlitterMat::
.string "Pengunjung menginjak TIKAR BERKILAU!\p"
.string "Pengunjung sedang berpose macam-macam!\p"
.string "Pengunjung tampaknya sedang berfantasi\n"
.string "menjadi seorang idola!$"

TVSecretBaseSecrets_Text_UsedTire::
.string "Pengunjung sedang menatap BAN dengan\n"
.string "saksama!\p"
.string "Mungkinkah pengunjung sedang memikirkan\n"
.string "jenis mobil yang akan menggunakannya?$"

TVSecretBaseSecrets_Text_UsedStand::
.string "Pengunjung menaiki PENYANGGA!\p"
.string "Pengunjung sedang melihat ke seberang\n"
.string "BASE {STR_VAR_1} dari atas!\p"
.string "Dan…\p"
.string "Mengeluarkan raungan!\n"
.string "Pengunjung sedang meraung!$"

TVSecretBaseSecrets_Text_BrokeDoor::
.string "Pengunjung menabrak PINTU YANG DAPAT\n"
.string "DIHANCURKAN!\p"
.string "Pengunjung tertawa terbahak-bahak!$"

TVSecretBaseSecrets_Text_UsedDoll::
.string "Pengunjung sedang berbicara dengan BONEKA!\p"
.string "…Agak menyeramkan…$"

TVSecretBaseSecrets_Text_UsedSlide::
.string "Pengunjung sedang menaiki tangga\n"
.string "di PEROSOTAN!\p"
.string "Dan…\p"
.string "Pengunjung meluncur ke bawah!\p"
.string "Sepertinya pengunjung sedang bersenang-senang!$"

TVSecretBaseSecrets_Text_UsedSlideButDidntGoDown::
.string "Pengunjung sedang menaiki tangga\n"
.string "di PEROSOTAN!\p"
.string "Dan…\p"
.string "Pengunjung turun kembali melalui\n"
.string "tangga!\p"
.string "Apakah pengunjung tiba-tiba ciut nyali?$"

TVSecretBaseSecrets_Text_UsedJumpMat::
.string "Pengunjung menginjak TIKAR LOMPAT!\p"
.string "Pengunjung melompat sekali!\p"
.string "Melompat dua kali!\p"
.string "Dan pendaratan yang sukses!\p"
.string "Pengunjung bertepuk tangan!\n"
.string "Sungguh pertunjukan solo!$"

gTVSafariFanClubText00::
.string "KLUB PENGGEMAR SAFARI!\p"
.string "REPORTER: Baiklah, teman-teman!\n"
.string "Melempar SAFARI BALL, kan?\p"
.string "Kamu bisa yakin aku ada di sini di ZONA\n"
.string "SAFARI yang penuh dengan POKéMON luar\l"
.string "biasa!\p"
.string "Mari kita mulai dan mengobrol dengan\n"
.string "rekan baik PEMANDU SAFARI ini!\p"
.string "Baiklah, kawan, bagaimana penampilan\n"
.string "para TRAINER yang berkunjung?$"

gTVSafariFanClubText01::
.string "PEMANDU: Semua orang tampaknya berusaha\n"
.string "keras.\p"
.string "{STR_VAR_1} melakukannya dengan sangat\n"
.string "baik.\p"
.string "Tadi, {STR_VAR_1} menangkap {STR_VAR_2}\n"
.string "POKéMON.$"

gTVSafariFanClubText02::
.string "TRAINER itu pintar dengan {POKEBLOCK}S.\n"
.string "Menggunakan {STR_VAR_2} saat itu, kurasa.$"

gTVSafariFanClubText03::
.string "TRAINER itu tidak menggunakan satu pun\n"
.string "{POKEBLOCK}! Tidak satu pun!\p"
.string "Itu baru seorang ahli.$"

gTVSafariFanClubText04::
.string "REPORTER: Begitukah?\p"
.string "Sepertinya kawan kita {STR_VAR_1}\n"
.string "adalah master SAFARI yang tangguh!\p"
.string "PEMANDU: Aku harap TRAINER itu kembali\n"
.string "dan menunjukkan teknik hebatnya.$"

gTVSafariFanClubText05::
.string "PEMANDU: Sepertinya tidak ada yang\n"
.string "berhasil dengan baik.\p"
.string "{STR_VAR_1} mengalami nasib yang sangat\n"
.string "buruk.\p"
.string "Tadi, TRAINER itu hanya berhasil\n"
.string "menangkap {STR_VAR_2} POKéMON.$"

gTVSafariFanClubText06::
.string "PEMANDU: Sepertinya tidak ada yang\n"
.string "berhasil dengan baik.\p"
.string "{STR_VAR_1} mengalami nasib yang sangat\n"
.string "buruk.\p"
.string "Tadi, TRAINER itu tidak menangkap satu\n"
.string "pun POKéMON. Tidak satu pun!$"

gTVSafariFanClubText07::
.string "TRAINER itu memang menggunakan\n"
.string "{POKEBLOCK}S. Menggunakan {STR_VAR_2}\l"
.string "saat itu, kurasa.\p"
.string "Tapi, aku berharap TRAINER itu bisa\n"
.string "sedikit lebih baik dalam hal ini.$"

gTVSafariFanClubText08::
.string "Kurasa TRAINER itu akan lebih beruntung\n"
.string "menggunakan {POKEBLOCK}S, yang tidak\l"
.string "digunakan sama sekali saat itu.$"

gTVSafariFanClubText09::
.string "REPORTER: Begitukah?\p"
.string "Sepertinya kawan kita {STR_VAR_1}\n"
.string "membutuhkan lebih banyak pengalaman\l"
.string "SAFARI.\p"
.string "PEMANDU: Aku harap TRAINER itu\n"
.string "berkunjung berulang kali untuk\l"
.string "membiasakan diri.$"

gTVSafariFanClubText10::
.string "REPORTER: Tentu saja!\n"
.string "Menghadapi tantangan itu penting!\p"
.string "Pemirsa, datanglah ke SAFARI dan\n"
.string "terima tantangannya sendiri!\p"
.string "Sampai jumpa lagi, cheerio!$"

ContestLiveUpdates_Text_Intro::
.string "“LAPORAN LANGSUNG POKéMON CONTEST!”\p"
.string "MC: Terima kasih telah bergabung dengan\n"
.string "kami!\p"
.string "Kami siaran langsung dari lokasi\n"
.string "{STR_VAR_1} yang baru saja berakhir.\p"
.string "Aula masih dipenuhi penonton yang\n"
.string "enggan pergi.\p"
.string "Penonton: {STR_VAR_2}!\p"
.string "Penonton: {STR_VAR_3}!\p"
.string "MC: Seperti yang baru saja kamu dengar,\n"
.string "CONTEST dimenangkan oleh POKéMON\l"
.string "{STR_VAR_2} dari {STR_VAR_3}.\p"
.string "Penonton: {STR_VAR_2}!\n"
.string "Kamu yang terbaik!\p"
.string "Penonton: {STR_VAR_3}!\n"
.string "Bagus!\p"
.string "MC: Mari kita dengar apa yang ingin\n"
.string "dikatakan para penggemar tentang\l"
.string "CONTEST ini.$"

ContestLiveUpdates_Text_WonBothRounds::
.string "Penonton: {STR_VAR_2} menjadi yang\n"
.string "terbaik di penilaian pertama dan kedua!\p"
.string "{STR_VAR_2} itu akan terus menang!$"

ContestLiveUpdates_Text_BetterRound2::
.string "Penonton: {STR_VAR_2} tidak berhasil\n"
.string "dengan baik di penilaian pertama,\l"
.string "tetapi berhasil di penilaian kedua!\p"
.string "Itu adalah comeback ajaib untuk\n"
.string "{STR_VAR_2} itu. Yippee!$"

ContestLiveUpdates_Text_EqualRounds::
.string "Penonton: {STR_VAR_2} tetap konsisten\n"
.string "sepanjang penilaian pertama dan kedua.\p"
.string "{STR_VAR_3} dan {STR_VAR_2}, mereka\n"
.string "bukan kombinasi biasa!$"

ContestLiveUpdates_Text_BetterRound1::
.string "Penonton: Dalam hal menjadi {STR_VAR_1},\n"
.string "{STR_VAR_2} itu luar biasa.\p"
.string "Aku harap ia membuat penampilan yang\n"
.string "lebih baik lain kali.$"

ContestLiveUpdates_Text_GotNervous::
.string "Penonton: Saat {STR_VAR_2} gugup,\n"
.string "aku tidak bisa menahan diri untuk\l"
.string "berteriak memberi semangat.\p"
.string "Aku ingin mengatakan ini kepada\n"
.string "{STR_VAR_2} itu, “Selamat!”$"

ContestLiveUpdates_Text_StartledFoes::
.string "Penonton: Penampilan {STR_VAR_2} itu\n"
.string "bahkan mengejutkanku!\p"
.string "{STR_VAR_2}, kamu luar biasa!$"

ContestLiveUpdates_Text_UsedCombo::
.string "Penonton: Penampilan kombo {STR_VAR_2}\n"
.string "itu menakjubkan!\p"
.string "Itu mengguncangku sampai ke inti!$"

ContestLiveUpdates_Text_ExcitingAppeal::
.string "Penonton: Penampilan {STR_VAR_2} yang\n"
.string "menang membuat jantungku berdebar!$"

ContestLiveUpdates_Text_WasCool::
.string "{STR_VAR_2}!\n"
.string "Kamu keren!$"

ContestLiveUpdates_Text_WasBeautiful::
.string "{STR_VAR_2}!\n"
.string "Kamu cantik!$"

ContestLiveUpdates_Text_WasCute::
.string "{STR_VAR_2}!\n"
.string "Kamu imut!$"

ContestLiveUpdates_Text_WasSmart::
.string "{STR_VAR_2}!\n"
.string "Kamu pintar!$"

ContestLiveUpdates_Text_WasTough::
.string "{STR_VAR_2}!\n"
.string "Kamu tangguh!$"

ContestLiveUpdates_Text_VeryExcitingAppeal::
.string "Penonton: Penampilan {STR_VAR_2} yang\n"
.string "menang masih membuat jantungku berdebar!$"

ContestLiveUpdates_Text_VeryCool::
.string "{STR_VAR_2}!\n"
.string "Kamu benar-benar keren!$"

ContestLiveUpdates_Text_VeryBeautiful::
.string "{STR_VAR_2}!\n"
.string "Kamu yang paling cantik!$"

ContestLiveUpdates_Text_VeryCute::
.string "{STR_VAR_2}!\n"
.string "Kamu yang paling imut!$"

ContestLiveUpdates_Text_VerySmart::
.string "{STR_VAR_2}!\n"
.string "Kamu yang terpintar di antara yang\n"
.string "pintar!$"

ContestLiveUpdates_Text_VeryTough::
.string "{STR_VAR_2}!\n"
.string "Kamu yang tertangguh di antara yang\n"
.string "tangguh!$"

ContestLiveUpdates_Text_TookBreak::
.string "Penonton: Bahkan saat {STR_VAR_2}\n"
.string "beristirahat dari membuat penampilan,\l"
.string "aku tidak bisa mengalihkan pandanganku\l"
.string "darinya.\p"
.string "Aku terpikat oleh {STR_VAR_2} itu.$"

ContestLiveUpdates_Text_GotStartled::
.string "Penonton: Saat {STR_VAR_2} dikejutkan\n"
.string "oleh penampilan POKéMON lain, aku\l"
.string "hampir menangis.\p"
.string "{STR_VAR_2}, kamu tangguh!\n"
.string "Bagus!$"

ContestLiveUpdates_Text_MoveWonderful::
.string "Penonton: Oh…\n"
.string "{STR_VAR_3} dari {STR_VAR_2} itu!\l"
.string "{STR_VAR_3} dari {STR_VAR_2}!\l"
.string "{STR_VAR_3} dari {STR_VAR_2}!\l"
.string "Bagaimana bisa begitu indah?$"

ContestLiveUpdates_Text_TalkAboutAnotherMon::
.string "MC: Nah, itu dia. Tempat ini penuh\n"
.string "dengan penggemar {STR_VAR_1}!\p"
.string "Aku juga harus menyebutkan bahwa\n"
.string "POKéMON lain, {STR_VAR_3} milik\l"
.string "{STR_VAR_2}, menarik perhatianku.\p"
.string "{STR_VAR_3} milik {STR_VAR_2}…$"

ContestLiveUpdates_Text_FailedToAppeal::
.string "Ia gagal membuat satu pun penampilan\n"
.string "selama penilaian kedua karena gugup.\p"
.string "Lain kali, aku ingin melihat {STR_VAR_1}\n"
.string "ini membuat setidaknya satu penampilan.$"

ContestLiveUpdates_Text_LastInBothRounds::
.string "Ia berada di posisi terakhir di kedua\n"
.string "penilaian pertama dan kedua.\p"
.string "Aku harap {STR_VAR_1} akan melatih\n"
.string "kembali {STR_VAR_2} ini dan menghapus\l"
.string "rasa malu dari finis terakhir yang tak\l"
.string "terbantahkan ini.$"

ContestLiveUpdates_Text_NotExcitingEnough::
.string "Ia gagal memanfaatkan kegembiraan\n"
.string "penonton dan membuat penampilan yang\l"
.string "sesuai.\p"
.string "Kami harap {STR_VAR_1} akan belajar\n"
.string "bagaimana merasakan suasana penonton\l"
.string "dan membangkitkan semangat mereka\l"
.string "lain kali.$"

ContestLiveUpdates_Text_LostAfterWinningRound1::
.string "Meskipun finis pertama di penilaian\n"
.string "pertama, penampilannya di penilaian\l"
.string "kedua gagal.\p"
.string "Ia menderita kekalahan telak yang\n"
.string "memalukan.\p"
.string "Aku yakin {STR_VAR_1} sedang mempelajari\n"
.string "cara membuat penampilan yang lebih\l"
.string "efektif sekarang.$"

ContestLiveUpdates_Text_NeverExciting::
.string "Penonton tidak pernah bersemangat dengan\n"
.string "penampilannya selama penilaian kedua.\p"
.string "Kami harap ia akan berhenti mengkhawatirkan\n"
.string "POKéMON lain dan belajar untuk lebih\l"
.string "memperhatikan penonton.$"

ContestLiveUpdates_Text_LostBySmallMargin::
.string "Ia kalah dari {STR_VAR_2} milik\n"
.string "{STR_VAR_1} dengan selisih tipis.\p"
.string "Pasti menyakitkan untuk begitu dekat\n"
.string "dengan kemenangan hanya untuk gagal.\p"
.string "Aku tidak akan terkejut jika {STR_VAR_3}\n"
.string "menangisi hasil ini.$"

ContestLiveUpdates_Text_RepeatedAppeals::
.string "Ia mengecewakan JURI dengan mengulangi\n"
.string "penampilan yang sama.\p"
.string "Itu adalah kesalahan yang tidak bisa\n"
.string "dimaafkan di CONTEST mana pun, dan\l"
.string "POKéMON itu menanggung akibatnya.\p"
.string "{STR_VAR_1} harus merasa bersalah atas\n"
.string "penampilan yang menyedihkan ini.$"

ContestLiveUpdates_Text_ValiantEffortButLost::
.string "{STR_VAR_1} berusaha keras, tapi…\p"
.string "Semuanya sia-sia, finis terakhir.\p"
.string "{STR_VAR_1} harus belajar dari kekalahan\n"
.string "ini dan memanfaatkannya dengan baik.$"

ContestLiveUpdates_Text_Outro::
.string "Aku ingin mengakhiri program ini dengan\n"
.string "ucapan selamat tinggal kami yang biasa\l"
.string "kepada para pemenang.\p"
.string "Kali ini, {STR_VAR_1} dan {STR_VAR_2}!\p"
.string "MC: Apakah semua orang siap?\n"
.string "Semua bersama-sama!\p"
.string "Penonton: {STR_VAR_1}! {STR_VAR_2}!\n"
.string "Selamat!\l"
.string "Kamu pemenang CONTEST!$"

gTVPokemonBattleUpdateText00::
.string "“UPDATE PERTARUNGAN POKéMON!”\p"
.string "Membawakanmu hasil pertarungan POKéMON\n"
.string "segera setelah tersedia!$"

gTVPokemonBattleUpdateText01::
.string "TRAINER {STR_VAR_1} dan {STR_VAR_2}\n"
.string "saling berhadapan dalam PERTARUNGAN\l"
.string "{STR_VAR_3}.\p"
.string "Pertandingan ini berakhir dengan\n"
.string "kemenangan untuk {STR_VAR_1}!$"

gTVPokemonBattleUpdateText02::
.string "Dalam pertarungan, {STR_VAR_2} milik\n"
.string "{STR_VAR_1} adalah kekuatan yang\l"
.string "tangguh menggunakan {STR_VAR_3}!$"

gTVPokemonBattleUpdateText03::
.string "{STR_VAR_2} milik {STR_VAR_1} menunjukkan\n"
.string "penampilan yang lemah yang sangat\l"
.string "merugikan.$"

gTVPokemonBattleUpdateText04::
.string "Selamat atas kemenanganmu, {STR_VAR_1}!\p"
.string "Dan untuk {STR_VAR_2} yang kalah,\n"
.string "kami berharap hasil yang lebih baik\l"
.string "lain kali!\p"
.string "Ini mengakhiri episode kali ini dari\n"
.string "“UPDATE PERTARUNGAN POKéMON!”$"

gTVPokemonBattleUpdateText05::
.string "Tim TRAINER {STR_VAR_1} dan {STR_VAR_2}\n"
.string "bertemu dalam PERTARUNGAN GANDA.\p"
.string "Pertandingan ini berakhir dengan\n"
.string "kemenangan untuk tim {STR_VAR_1}.$"

gTVPokemonBattleUpdateText06::
.string "Dalam pertarungan, {STR_VAR_2} di tim\n"
.string "{STR_VAR_1} adalah kekuatan yang\l"
.string "tangguh menggunakan {STR_VAR_3}.$"

gTVPokemonBattleUpdateText07::
.string "Penampilan lemah dari {STR_VAR_3} di tim\n"
.string "{STR_VAR_2} sangat merugikan.\p"
.string "Selamat atas kemenangan timmu,\n"
.string "{STR_VAR_1}!\p"
.string "Adapun tim {STR_VAR_2} yang kalah,\n"
.string "kami berharap hasil yang lebih baik\l"
.string "lain kali!\p"
.string "Ini mengakhiri episode kali ini dari\n"
.string "“UPDATE PERTARUNGAN POKéMON!”$"

GabbyAndTy_Text_GabbyPreFirstBattle::
.string "GABBY: Oh! Kami baru saja melihat\n"
.string "TRAINER yang tampak tangguh di sini!\p"
.string "Oke, putar kamera!\n"
.string "Mari kita dapatkan wawancara ini.$"

GabbyAndTy_Text_GabbyIntro::
.string "GABBY: Oh! Kamu {PLAYER}! Hai!\n"
.string "Apakah kamu ingat kami dari terakhir\n"
.string "kali?\p"
.string "Bisakah kamu menunjukkan seberapa kuat\n"
.string "dirimu sekarang? Oke, mulai wawancara!$"

GabbyAndTy_Text_GabbyDefeatFirstTime::
.string "GABBY: Mataku tidak berbohong!\n"
.string "Aku menemukan TRAINER yang luar biasa!$"

GabbyAndTy_Text_WhoAreYouInterview::
.string "GABBY: Luar biasa! Luar biasa!\n"
.string "Siapa kamu?!\p"
.string "Aku tahu kami menemukan sesuatu yang\n"
.string "liar saat kami melihatmu!\p"
.string "Oh, tolong biarkan aku menjelaskan.\n"
.string "Kami bepergian ke mana-mana\l"
.string "mewawancarai berbagai macam TRAINER.\p"
.string "Jadi, maukah kamu meluangkan sedikit\n"
.string "waktu untuk wawancara?$"

GabbyAndTy_Text_QuoteFromLastInterview::
.string "GABBY: “{STR_VAR_1}!”\p"
.string "Ingat? Itu kutipan yang kamu berikan\n"
.string "sebagai penentu kemenangan terakhir kali.\p"
.string "Aku tidak pernah melupakan hal seperti\n"
.string "itu!$"

GabbyAndTy_Text_YouStompedUsInterviewAgain::
.string "Terakhir kali kita bertarung, kamu\n"
.string "mengalahkan kami sebelum kami bisa\l"
.string "bersiap…\p"
.string "Ngomong-ngomong, bagaimana menurutmu?\n"
.string "Apakah kamu mau diwawancarai lagi?$"

GabbyAndTy_Text_YouThrewABallAtUsInterviewAgain::
.string "Terakhir kali kita bertarung, bukankah\n"
.string "kamu melempar POKé BALL ke kami?\p"
.string "Kami terkejut! Jadi kami memberitahu\n"
.string "semua orang, semua orang, tentang itu!\p"
.string "Ngomong-ngomong, bagaimana menurutmu?\n"
.string "Apakah kamu mau diwawancarai lagi?$"

GabbyAndTy_Text_CleverItemSkillsInterviewAgain::
.string "Terakhir kali kita bertarung, keahlian\n"
.string "item-mu dengan cerdik mengalahkan kami.\p"
.string "Ngomong-ngomong, bagaimana menurutmu?\n"
.string "Apakah kamu mau diwawancarai lagi?$"

GabbyAndTy_Text_WeLookedRespectableInterviewAgain::
.string "Terakhir kali kita bertarung, kami\n"
.string "berhasil terlihat terhormat.\p"
.string "Ngomong-ngomong, bagaimana menurutmu?\n"
.string "Apakah kamu mau diwawancarai lagi?$"

GabbyAndTy_Text_InterviewAgain::
.string "Ngomong-ngomong, bagaimana menurutmu?\n"
.string "Apakah kamu mau diwawancarai lagi?$"

GabbyAndTy_Text_DescribeYourFeelings::
.string "Kamu mau?\n"
.string "Terima kasih!\p"
.string "Oke, aku ingin kamu mendeskripsikan\n"
.string "perasaanmu tentang pertarungan kita,\l"
.string "tapi harus singkat dan manis. Mulai!$"

GabbyAndTy_Text_PerfectWellBeSeeingYou::
.string "GABBY: Mmm, ya!\n"
.string "Itu penutup yang sempurna!\p"
.string "Aku merasa ini akan menjadi acara TV\n"
.string "yang bagus.\p"
.string "Ada kemungkinan ini akan ditayangkan\n"
.string "di TV, jadi pastikan untuk mencari kami!\p"
.string "Oke!\n"
.string "Sampai jumpa!$"

GabbyAndTy_Text_DontGiveUpKeepingEyeOut::
.string "GABBY: Oh…\p"
.string "Oke, tapi jangan menyerah!\n"
.string "Kami akan mengawasimu!$"

GabbyAndTy_Text_KeepingAnEyeOutForYou::
.string "GABBY: Kami akan mengawasimu!$"

GabbyAndTy_Text_GabbyNotEnoughMons::
.string "GABBY: Apakah ada TRAINER kuat di mana\n"
.string "pun dengan banyak POKéMON?$"

GabbyAndTy_Text_GiveUsAnInterviewThisTime::
.string "GABBY: Wow, kamu luar biasa!\p"
.string "Kamu menjadi jauh lebih kuat--sangat--\n"
.string "sejak terakhir kali kita bertarung.\p"
.string "Kami benar tentangmu saat kami melihatmu\n"
.string "sebagai TRAINER yang hebat.\p"
.string "Jadi, ngomong-ngomong, bagaimana\n"
.string "menurutmu?\n"
.string "Apakah kamu bersedia memberi kami\n"
.string "wawancara kali ini?$"

GabbyAndTy_Text_GabbyDefeat::
.string "GABBY: Pertarungan yang intens!\n"
.string "Apakah kamu merekam semuanya di kamera?$"

GabbyAndTy_Text_TyPreFirstBattle::
.string "TY: Hei, lihat di sini! TRAINER yang\n"
.string "tampak tangguh di sini!\l"
.string "Kamera berputar!$"

GabbyAndTy_Text_TyIntro::
.string "TY: Hei, lihat di sini!\n"
.string "Aku ingat kamu!\p"
.string "Aku akan merekam semua pertarungan ini\n"
.string "di kamera ini!$"

GabbyAndTy_Text_TyPostBattle::
.string "TY: Kamu alami!\n"
.string "Dapat rekaman bagus di sini!$"

GabbyAndTy_Text_TyNotEnoughMons::
.string "TY: Apakah kamu hanya punya satu POKéMON\n"
.string "dan itu saja?\p"
.string "Jika kamu punya lebih banyak POKéMON,\n"
.string "itu akan menjadi rekaman yang lebih\l"
.string "baik, tapi…$"

GabbyAndTy_Text_TyDefeatFirstTime::
.string "TY: Ya, kami benar-benar menemukan\n"
.string "TRAINER yang hebat.\n"
.string "Ini adalah berita besar bagi kami!$"

GabbyAndTy_Text_TyDefeat::
.string "TY: Ya, aku merekam semuanya.\n"
.string "Seluruh pertarungan itu ada di kamera.$"

gTVInSearchOfTrainersText00::
.string "MENCARI TRAINER…\p"
.string "GABBY: Hai! Hari ini aku mengunjungi\n"
.string "daerah dekat {STR_VAR_1}.\p"
.string "Kami mencoba menemukan bakat baru yang\n"
.string "sedang naik daun di lapangan.\p"
.string "Hari ini, kami mengarahkan lensa kami\n"
.string "pada TRAINER {PLAYER}.\p"
.string "Ada sesuatu tentang TRAINER ini yang\n"
.string "menarik minat kami.$"

gTVInSearchOfTrainersText01::
.string "Kami pernah bertarung dengan {PLAYER}\n"
.string "sebelumnya, tapi kami bisa memastikan\l"
.string "bahwa TRAINER itu pasti telah meningkat\l"
.string "dari sebelumnya.\p"
.string "Aku tahu kami menemukan seseorang yang\n"
.string "istimewa saat kami melihat TRAINER ini!$"

gTVInSearchOfTrainersText02::
.string "Cara terbaik untuk menentukan seberapa\n"
.string "kuat seorang TRAINER…\p"
.string "Yah, cara tercepat adalah dengan\n"
.string "bertarung.\n"
.string "Dan begitulah kami memulai penyelidikan\n"
.string "kami!\p"
.string "… …\p"
.string "Begitulah akhirnya kami bertarung\n"
.string "dengan {PLAYER}.\p"
.string "Dalam penampilan yang mendominasi, kami\n"
.string "diratakan, digulung, dan dibuang!\p"
.string "{PLAYER} sangat kuat…\p"
.string "Inilah kesan kami setelah bertarung\n"
.string "dengan TRAINER pilihan kami.$"

gTVInSearchOfTrainersText03::
.string "Kombinasi {STR_VAR_1} dan {STR_VAR_3}\n"
.string "sangat luar biasa!\p"
.string "Pemandangan mereka--{STR_VAR_1} dan\n"
.string "{STR_VAR_3}--saling mendukung tanpa\l"
.string "pamrih di tengah pertempuran…\p"
.string "Itu adalah pemandangan yang luar biasa\n"
.string "untuk dilihat!\p"
.string "{STR_VAR_2} adalah jurus yang digunakan\n"
.string "TRAINER terakhir dalam pertarungan kami.\p"
.string "Jurus {STR_VAR_2} adalah tanda\n"
.string "persahabatan {STR_VAR_1} dan {STR_VAR_3}!$"

gTVInSearchOfTrainersText04::
.string "…Aku kehilangan kepercayaan diri sebagai\n"
.string "hasil dari pertemuan kami.\p"
.string "Kami dikalahkan sebelum kami bisa\n"
.string "melancarkan satu serangan pun.\l"
.string "Ohhh… Terisak…\p"
.string "Meskipun begitu, pertarungan {PLAYER}\n"
.string "layak untuk dilihat.\p"
.string "Aku merekomendasikan TRAINER yang percaya\n"
.string "diri untuk menantang {PLAYER}.$"

gTVInSearchOfTrainersText05::
.string "Hanya ada satu hal yang bisa dikatakan.\n"
.string "Jangan berani-beraninya melempar POKé\n"
.string "BALL selama pertarungan TRAINER!\p"
.string "{PLAYER} memang kuat, tapi tidak tahu\n"
.string "aturan dasar.\p"
.string "Kepada penonton TV kami, aku punya\n"
.string "permintaan.\p"
.string "Jika kamu melihat {PLAYER}, tolong\n"
.string "peringatkan TRAINER itu!$"

gTVInSearchOfTrainersText06::
.string "{PLAYER} mahir dalam membaca gerakan\n"
.string "lawan.\p"
.string "Waktu penggunaan item sangat efektif!$"

gTVInSearchOfTrainersText07::
.string "Jujur saja, aku pikir aku mungkin\n"
.string "cukup baik.\p"
.string "Meskipun kami akhirnya kalah, kami\n"
.string "memiliki pertarungan yang sengit.\p"
.string "Tapi jika kamu kesulitan melawanku,\n"
.string "kamu masih harus banyak belajar,\n"
.string "{PLAYER}!$"

gTVInSearchOfTrainersText08::
.string "Setelah pertarungan kami, kami meminta\n"
.string "ringkasan singkat dari {PLAYER}.\p"
.string "TRAINER itu menjawab, “{STR_VAR_1}.”\p"
.string "POKéMON {STR_VAR_2} dan {STR_VAR_3}\n"
.string "milik {PLAYER}…\l"
.string "Dan “{STR_VAR_1}”…\p"
.string "Mmm! Itu dalam! Ada makna mendalam\n"
.string "di balik kutipan itu!\p"
.string "Tidak mengherankan--TRAINER yang baik\n"
.string "memiliki hal-hal baik untuk dikatakan.\p"
.string "Itu saja untuk hari ini!\n"
.string "Sampai jumpa lagi di siaran kami\n"
.string "berikutnya!$"

ContestLadyShow_Text_Intro::
.string "“LAPORAN LANGSUNG POKéMON CONTEST!”\p"
.string "MC: Maaf mengganggu program reguler,\n"
.string "dan terima kasih telah bergabung dengan\l"
.string "kami!\p"
.string "Kami membawakan ini langsung dari lokasi\n"
.string "{STR_VAR_1} yang baru saja selesai!\p"
.string "Penonton: ?!!!!\p"
.string "MC: Oh! Sepertinya para peserta\n"
.string "CONTEST sedang menuju ke sini!\p"
.string "Aku akan mencoba mendapatkan wawancara\n"
.string "dadakan untuk kalian di rumah!\p"
.string "Penonton: ?!!!!\n"
.string "?!!!!$"

ContestLadyShow_Text_Won::
.string "MC: Permisi!\n"
.string "Terima kasih telah bergabung dengan\n"
.string "kami di siaran langsung TV!\p"
.string "Bolehkah aku mengucapkan selamat atas\n"
.string "kemenanganmu?\p"
.string "Apa faktor kunci dalam kemenangan\n"
.string "menakjubkan hari ini?\p"
.string "BEAUTY: Kami memberikan usaha terbaik\n"
.string "kami hari ini, {STR_VAR_2}-ku dan aku!\p"
.string "Tapi aku yakin kami tidak akan berhasil\n"
.string "jika bukan karena semua bantuan yang\l"
.string "kami terima menjelang CONTEST!\p"
.string "MC: Apakah kamu punya seseorang yang\n"
.string "istimewa dengan siapa kamu ingin\l"
.string "berbagi kegembiraanmu?\l"
.string "Mari kita dengar langsung!\p"
.string "BEAUTY: Hei, di luar sana!\p"
.string "{STR_VAR_3}! Apakah kamu menonton?\n"
.string "Kami berhasil!\l"
.string "Terima kasih!$"

ContestLadyShow_Text_Lost::
.string "MC: Permisi!\n"
.string "Terima kasih telah bergabung dengan\n"
.string "kami di siaran langsung TV!\p"
.string "Kamu pasti kecewa dengan kejadian itu.\n"
.string "Apakah kamu punya komentar?\p"
.string "BEAUTY: Ini menyakitkan…\n"
.string "{STR_VAR_2}-ku dan aku, kami melakukan\n"
.string "yang terbaik…\p"
.string "Tapi aku merasa telah mengecewakan semua\n"
.string "orang yang telah mendukung kami melalui\l"
.string "ini.\p"
.string "MC: Aku benci mengatakannya, tapi warna\n"
.string "POKéMON-nya sedikit kurang.\p"
.string "BEAUTY: {STR_VAR_3}, aku sangat menyesal…\n"
.string "Aku akan lebih baik lain kali, aku\n"
.string "bersumpah…\l"
.string "…Isak… Waaaaah!\p"
.string "Penonton: Lihat itu?\n"
.string "Gadis malang!\p"
.string "MC: Uh… Uh-oh…\p"
.string "Uh… Waktu kita habis hari ini!\n"
.string "Terima kasih telah menonton!$"

ContestLadyShow_Text_LostBadly::
.string "MC: Permisi!\n"
.string "Terima kasih telah bergabung dengan\n"
.string "kami di siaran langsung TV!\p"
.string "Bagaimana penampilan CONTEST-mu?\p"
.string "BEAUTY: Tidak ada yang berjalan lancar…\n"
.string "Entah kenapa, {STR_VAR_2}-ku tidak bisa\n"
.string "menarik popularitas sama sekali.\p"
.string "MC: Aku benci mengatakannya, tapi warna\n"
.string "POKéMON-nya sedikit kurang.\p"
.string "BEAUTY: … … … … … …\n"
.string "…Isak… Waaaaah!\p"
.string "Penonton: Lihat itu?\n"
.string "Gadis malang!\p"
.string "MC: Uh… Uh-oh…\p"
.string "Uh… Waktu kita habis hari ini!\n"
.string "Terima kasih telah menonton!$"