VerdanturfTown_House_MapScripts::
	.byte 0

VerdanturfTown_House_EventScript_Woman1::
	msgbox VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague, MSGBOX_NPC
	end

VerdanturfTown_House_EventScript_Woman2::
	msgbox VerdanturfTown_House_Text_DefeatEliteFourInARow, MSGBOX_NPC
	end

VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague:
	.string "Jauh di sana, jauh di dalam EVER GRANDE CITY,\n"
	.string "ada POKéMON LEAGUE.\p"
	.string "PARA TRAINER yang berkumpul di sana\n"
	.string "semuanya sangat terampil.$"

VerdanturfTown_House_Text_DefeatEliteFourInARow:
	.string "Di POKéMON LEAGUE, aku rasa aturannya\n"
	.string "mengatakan kamu harus melawan ELITE FOUR\l"
	.string "secara berurutan.\p"
	.string "Jika kamu kalah dari salah satu dari mereka,\n"
	.string "kamu harus memulai tantanganmu lagi dari\l"
	.string "yang pertama.$"

