SootopolisCity_House7_MapScripts::
	.byte 0

SootopolisCity_House7_EventScript_OldMan::
	msgbox SootopolisCity_House7_Text_CityFromEruptedVolcano, MSGBOX_NPC
	end

SootopolisCity_House7_EventScript_PokefanF::
	msgbox SootopolisCity_House7_Text_CaveMadeToKeepSomething, MSGBOX_NPC
	end

SootopolisCity_House7_Text_CityFromEruptedVolcano:
	.string "Gunung berapi bawah laut meletus dan\n"
	.string "memaksa dirinya muncul dari kedalaman.\p"
	.string "Kawahnya muncul dari laut dan\n"
	.string "terisi air hujan.\p"
	.string "Begitulah SOOTOPOLIS CITY tercipta.$"

SootopolisCity_House7_Text_CaveMadeToKeepSomething:
	.string "Gua yang menghubungkan SOOTOPOLIS dan\n"
	.string "dunia luar...\p"
	.string "Sepertinya gua ini dibuat untuk\n"
	.string "mencegah sesuatu keluar.\p"
	.string "Atau aku hanya membayangkan saja?$"

