SlateportCity_SternsShipyard_2F_MapScripts::
	.byte 0

SlateportCity_SternsShipyard_2F_EventScript_Scientist1::
	msgbox SlateportCity_SternsShipyard_2F_Text_ShipDesignMoreLikeBuilding, MSGBOX_NPC
	end

SlateportCity_SternsShipyard_2F_EventScript_Scientist2::
	msgbox SlateportCity_SternsShipyard_2F_Text_FloatsBecauseBuoyancy, MSGBOX_NPC
	end

SlateportCity_SternsShipyard_2F_Text_ShipDesignMoreLikeBuilding:
	.string "Merancang kapal besar lebih seperti\n"
	.string "membuat bangunan besar daripada merakit\l"
	.string "kendaraan transportasi.$"

SlateportCity_SternsShipyard_2F_Text_FloatsBecauseBuoyancy:
	.string "Tidakkah menurutmu aneh bahwa\n"
	.string "kapal yang terbuat dari besi berat bisa mengapung?\p"
	.string "Ia mengapung karena suatu prinsip\n"
	.string "yang disebut daya apung.$"

