SootopolisCity_Gym_B1F_MapScripts::
	.byte 0

SootopolisCity_Gym_B1F_EventScript_Andrea::
	trainerbattle_single TRAINER_ANDREA, SootopolisCity_Gym_B1F_Text_AndreaIntro, SootopolisCity_Gym_B1F_Text_AndreaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_AndreaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Crissy::
	trainerbattle_single TRAINER_CRISSY, SootopolisCity_Gym_B1F_Text_CrissyIntro, SootopolisCity_Gym_B1F_Text_CrissyDefeat
	msgbox SootopolisCity_Gym_B1F_Text_CrissyPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Brianna::
	trainerbattle_single TRAINER_BRIANNA, SootopolisCity_Gym_B1F_Text_BriannaIntro, SootopolisCity_Gym_B1F_Text_BriannaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_BriannaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Connie::
	trainerbattle_single TRAINER_CONNIE, SootopolisCity_Gym_B1F_Text_ConnieIntro, SootopolisCity_Gym_B1F_Text_ConnieDefeat
	msgbox SootopolisCity_Gym_B1F_Text_ConniePostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Bridget::
	trainerbattle_single TRAINER_BRIDGET, SootopolisCity_Gym_B1F_Text_BridgetIntro, SootopolisCity_Gym_B1F_Text_BridgetDefeat
	msgbox SootopolisCity_Gym_B1F_Text_BridgetPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Olivia::
	trainerbattle_single TRAINER_OLIVIA, SootopolisCity_Gym_B1F_Text_OliviaIntro, SootopolisCity_Gym_B1F_Text_OliviaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_OliviaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Tiffany::
	trainerbattle_single TRAINER_TIFFANY, SootopolisCity_Gym_B1F_Text_TiffanyIntro, SootopolisCity_Gym_B1F_Text_TiffanyDefeat
	msgbox SootopolisCity_Gym_B1F_Text_TiffanyPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Bethany::
	trainerbattle_single TRAINER_BETHANY, SootopolisCity_Gym_B1F_Text_BethanyIntro, SootopolisCity_Gym_B1F_Text_BethanyDefeat
	msgbox SootopolisCity_Gym_B1F_Text_BethanyPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Annika::
	trainerbattle_single TRAINER_ANNIKA, SootopolisCity_Gym_B1F_Text_AnnikaIntro, SootopolisCity_Gym_B1F_Text_AnnikaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_AnnikaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Daphne::
	trainerbattle_single TRAINER_DAPHNE, SootopolisCity_Gym_B1F_Text_DaphneIntro, SootopolisCity_Gym_B1F_Text_DaphneDefeat
	msgbox SootopolisCity_Gym_B1F_Text_DaphnePostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_Text_AndreaIntro:
	.string "Aku akan menunjukkan padamu teknik\n"
	.string "luar biasa yang kupelajari dari PEMIMPIN kami, JUAN!$"

SootopolisCity_Gym_B1F_Text_AndreaDefeat:
	.string "Tolong maafkan aku, JUAN…$"

SootopolisCity_Gym_B1F_Text_AndreaPostBattle:
	.string "Lihat apa yang terjadi jika kamu\n"
	.string "memecahkan semua ubin lantai.$"

SootopolisCity_Gym_B1F_Text_CrissyIntro:
	.string "Kamu datang jauh-jauh ke sini, tapi kamu\n"
	.string "tidak akan bisa melihat JUAN.\p"
	.string "Tidak jika kamu kalah dariku, kamu tidak akan bisa!$"

SootopolisCity_Gym_B1F_Text_CrissyDefeat:
	.string "Kamu kuat!\n"
	.string "Aku tertipu oleh penampilanmu yang imut!$"

SootopolisCity_Gym_B1F_Text_CrissyPostBattle:
	.string "Kamu mungkin cukup bagus untuk\n"
	.string "menghindari KO dalam satu serangan oleh JUAN.$"

SootopolisCity_Gym_B1F_Text_DaphneIntro:
	.string "Pemandangan JUAN memimpin\n"
	.string "pertarungan…\p"
	.string "Keindahannya mendorongku untuk\n"
	.string "menjadi seorang TRAINER.$"

SootopolisCity_Gym_B1F_Text_DaphneDefeat:
	.string "Kamu bertarung dengan lebih indah\n"
	.string "daripada yang bisa kulakukan…$"

SootopolisCity_Gym_B1F_Text_DaphnePostBattle:
	.string "Keanggunan yang kamu bawa ke medan\n"
	.string "pertempuran sangat luar biasa.\p"
	.string "Oh… Aku sangat beruntung telah\n"
	.string "menemukan POKéMON.$"

SootopolisCity_Gym_B1F_Text_ConnieIntro:
	.string "Aku harus mengajarimu betapa\n"
	.string "kerasnya pertarungan itu.$"

SootopolisCity_Gym_B1F_Text_ConnieDefeat:
	.string "Oh.\n"
	.string "Kamu kuat.$"

SootopolisCity_Gym_B1F_Text_ConniePostBattle:
	.string "Aku akan memberitahumu sesuatu yang bagus.\p"
	.string "Jika kamu ingin mencapai JUAN, kamu\n"
	.string "harus berjalan di setiap ubin lantai sekali.$"

SootopolisCity_Gym_B1F_Text_BridgetIntro:
	.string "POKéMON GYM tingkat tertinggi\n"
	.string "di wilayah HOENN…\p"
	.string "Itulah GYM SOOTOPOLIS.$"

SootopolisCity_Gym_B1F_Text_BridgetDefeat:
	.string "Betapa tingginya levelmu!$"

SootopolisCity_Gym_B1F_Text_BridgetPostBattle:
	.string "Daripada puas berada di GYM yang\n"
	.string "kuat, aku membayangkan berlatih di\l"
	.string "tempat lain akan membuatmu lebih kuat.\l"
	.string "Tapi di atas segalanya, itu terlihat lebih menyenangkan.$"

SootopolisCity_Gym_B1F_Text_OliviaIntro:
	.string "Aku melatih POKéMON-ku bersama\n"
	.string "JUAN.\p"
	.string "Jangan kira aku mudah dikalahkan.$"

SootopolisCity_Gym_B1F_Text_OliviaDefeat:
	.string "Aku kalah…$"

SootopolisCity_Gym_B1F_Text_OliviaPostBattle:
	.string "Aku rasa kamu punya potensi.\n"
	.string "Mengapa kamu tidak tinggal dan berlatih bersama kami?$"

SootopolisCity_Gym_B1F_Text_TiffanyIntro:
	.string "Meluncur dengan anggun di atas es tanpa\n"
	.string "melewati garis…\p"
	.string "Seorang TRAINER yang menampilkan\n"
	.string "pertunjukan itu akan menjadi sangat indah!$"

SootopolisCity_Gym_B1F_Text_TiffanyDefeat:
	.string "Maafkan aku?!$"

SootopolisCity_Gym_B1F_Text_TiffanyPostBattle:
	.string "Ini sangat jelas, tapi seberapa kuat\n"
	.string "kamu sebagai TRAINER tidak ada hubungannya\l"
	.string "dengan berapa usiamu.$"

SootopolisCity_Gym_B1F_Text_BethanyIntro:
	.string "Ketika aku bersama POKéMON-ku, waktu\n"
	.string "berlalu begitu cepat sebelum kamu bisa bilang, “Ups!”$"

SootopolisCity_Gym_B1F_Text_BethanyDefeat:
	.string "Ups!$"

SootopolisCity_Gym_B1F_Text_BethanyPostBattle:
	.string "Aku berharap bisa melupakan hal yang\n"
	.string "sia-sia sebelum aku bisa mengatakan “Ups!”$"

SootopolisCity_Gym_B1F_Text_AnnikaIntro:
	.string "Aku bisa bertarung dengan POKéMON yang\n"
	.string "sangat langka jika kamu mau.$"

SootopolisCity_Gym_B1F_Text_AnnikaDefeat:
	.string "Oh, sekarang! Apakah kamu melihat\n"
	.string "POKéMON-ku dengan baik?$"

SootopolisCity_Gym_B1F_Text_AnnikaPostBattle:
	.string "Aku datang ke GYM ini karena JUAN\n"
	.string "memujiku atas POKéMON kesayanganku.\p"
	.string "Oh, andai saja aku bertemu JUAN\n"
	.string "bertahun-tahun yang lalu saat aku masih muda…$"

SootopolisCity_Gym_B1F_Text_BriannaIntro:
	.string "Terkikik…\n"
	.string "Wajahmu yang muram sangat menawan.$"

SootopolisCity_Gym_B1F_Text_BriannaDefeat:
	.string "Oh, sayang.\n"
	.string "Aku terlalu mudah padamu.$"

SootopolisCity_Gym_B1F_Text_BriannaPostBattle:
	.string "Kamu tidak bisa menyentuh JUAN,\n"
	.string "aku yakin. Terkikik…$"

